import type { ModuleContent } from '../learning-types';

export const abap: Record<'ja' | 'en', ModuleContent> = {
  ja: {
    id: 'abap',
    title: 'ABAP開発',
    description: 'SAPの標準開発言語ABAPの基礎を学びます',
    sections: [
      {
        id: 'abap-overview',
        title: 'ABAPとは',
        content: [
          'ABAP（Advanced Business Application Programming）は、SAP社が開発した独自のプログラミング言語です。SAP ERPの大部分はABAPで構築されており、アドオン開発やカスタマイズにもABAPが使われます。COBOLに似た構文を持ち、ビジネスアプリケーション開発に特化した言語です。',
          'ABAPプログラムはSAPアプリケーションサーバー上で動作します。ソースコードはデータベースに格納され、実行時にABAPランタイム環境によって解釈・実行されます。ABAPには「レポート（Report）」「モジュールプール（Module Pool）」「ファンクションモジュール（Function Module）」「クラス（Class）」など複数のプログラムタイプがあります。',
        ],
        quizzes: [
          {
            type: 'ox',
            question: 'ABAPはSAP社が開発した独自のプログラミング言語であり、SAP ERPの大部分はABAPで構築されている。',
            correct: true,
            explanation: '正しいです。ABAPはAdvanced Business Application Programmingの略で、SAP ERPの標準開発言語です。',
          },
          {
            type: 'four-choice',
            question: 'ABAPの正式名称は何か。',
            choices: ['Advanced Business Application Programming', 'Advanced Business Analysis Program', 'Application Business ABAP Platform', 'Automated Business Application Processor'],
            correctIndex: 0,
            explanation: 'ABAPはAdvanced Business Application Programmingの略です。',
          },
          {
            type: 'ox',
            question: 'ABAPのソースコードはファイルシステム上のファイルとして保存される。',
            correct: false,
            explanation: '不正解です。ABAPのソースコードはデータベースに格納されます。これはSAPの特徴的な仕組みで、トランスポート管理と連携してコードを本番環境へ移送できます。',
          },
          {
            type: 'four-choice',
            question: 'ABAPの構文が似ているとされるプログラミング言語はどれか。',
            choices: ['Java', 'COBOL', 'Python', 'C++'],
            correctIndex: 1,
            explanation: 'ABAPはCOBOLに似た構文を持っています。英語の文章に近い記述スタイルで、ビジネスアプリケーション開発に特化しています。',
          },
          {
            type: 'four-choice',
            question: '画面を持たず、選択画面からデータを取得して一覧表示するABAPプログラムタイプはどれか。',
            choices: ['モジュールプール', 'レポート', 'インターフェース', 'ファンクショングループ'],
            correctIndex: 1,
            explanation: 'レポート（Report）は、選択画面でユーザーの入力条件を受け取り、データを取得して一覧表示するプログラムタイプです。最も基本的なABAPプログラムの形式です。',
          },
          {
            type: 'ox',
            question: 'ABAPプログラムはクライアントPC上で直接実行される。',
            correct: false,
            explanation: '不正解です。ABAPプログラムはSAPアプリケーションサーバー上で動作します。クライアントはSAP GUIなどのフロントエンドを通じてサーバーと通信します。',
          },
        ],
      },
      {
        id: 'abap-dev-environment',
        title: 'ABAP開発環境',
        content: [
          'ABAPの開発環境には、従来のSAP GUI上のABAPワークベンチ（トランザクションコードSE80）と、Eclipse上で動作するABAP Development Tools（ADT）があります。SE80ではプログラム・ファンクションモジュール・クラスなどを統合的に開発できます。ADTはS/4HANAの開発では推奨される開発環境です。',
          '個別の開発オブジェクトにはそれぞれ専用のトランザクションコードがあります。ABAPエディタ（SE38）ではレポートプログラムの作成・編集を行い、ファンクションビルダ（SE37）ではファンクションモジュールを、クラスビルダ（SE24）ではABAPクラスを開発します。データディクショナリ（SE11）ではテーブルやデータ型を定義します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'ABAPワークベンチのトランザクションコードはどれか。',
            choices: ['SE38', 'SE80', 'SE11', 'SE37'],
            correctIndex: 1,
            explanation: 'SE80はABAPワークベンチ（Object Navigator）のトランザクションコードです。SE38はABAPエディタ、SE11はデータディクショナリ、SE37はファンクションビルダです。',
          },
          {
            type: 'four-choice',
            question: 'ファンクションモジュールを開発するためのトランザクションコードはどれか。',
            choices: ['SE38', 'SE24', 'SE37', 'SE80'],
            correctIndex: 2,
            explanation: 'SE37はファンクションビルダで、ファンクションモジュールの作成・テスト・管理に使用します。SE24はクラスビルダ、SE38はABAPエディタです。',
          },
          {
            type: 'ox',
            question: 'ABAP Development Tools（ADT）はEclipse上で動作する開発環境である。',
            correct: true,
            explanation: '正しいです。ADTはEclipseベースのIDEで、S/4HANAの開発では推奨される開発環境です。コード補完やリファクタリングなどモダンな開発機能を提供します。',
          },
          {
            type: 'four-choice',
            question: 'ABAPクラスを開発するためのトランザクションコードはどれか。',
            choices: ['SE37', 'SE38', 'SE24', 'SE11'],
            correctIndex: 2,
            explanation: 'SE24はクラスビルダで、ABAPオブジェクト（クラスとインターフェース）の作成・編集に使用します。',
          },
          {
            type: 'ox',
            question: 'SE38はデータディクショナリのトランザクションコードである。',
            correct: false,
            explanation: '不正解です。SE38はABAPエディタのトランザクションコードです。データディクショナリのトランザクションコードはSE11です。',
          },
          {
            type: 'four-choice',
            question: 'S/4HANAの開発で推奨される開発環境はどれか。',
            choices: ['SE80（ABAPワークベンチ）', 'ABAP Development Tools（ADT）', 'SE38（ABAPエディタ）', 'Visual Studio Code'],
            correctIndex: 1,
            explanation: 'S/4HANAの開発ではABAP Development Tools（ADT）が推奨されています。ADTはEclipseベースのIDEで、CDS Viewなど新しい開発オブジェクトにも対応しています。',
          },
        ],
      },
      {
        id: 'abap-data-types',
        title: 'データ型と変数宣言',
        content: [
          'ABAPでは変数をDATA命令で宣言します。基本データ型として、C（文字列・固定長）、N（数字文字列）、I（整数）、P（パック10進数）、F（浮動小数点）、D（日付・YYYYMMDD形式）、T（時刻・HHMMSS形式）、STRING（可変長文字列）、XSTRING（可変長バイト列）などがあります。',
          '構造体はBEGIN OF〜END OFで定義し、複数の項目をまとめて扱えます。また、TYPESで独自の型を定義でき、DATA命令のTYPE句で参照します。データディクショナリ（SE11）で定義されたデータエレメントやテーブルの型も、TYPE句で直接参照できます。例えばDATA lv_bukrs TYPE bukrsと書けば、会社コードと同じ型の変数を宣言できます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'ABAPで整数を表す基本データ型はどれか。',
            choices: ['C', 'N', 'I', 'P'],
            correctIndex: 2,
            explanation: 'I（Integer）は整数型です。Cは固定長文字列、Nは数字文字列（数字のみの固定長文字列）、Pはパック10進数（小数点を含む計算に使用）です。',
          },
          {
            type: 'four-choice',
            question: 'ABAPの日付型Dの内部形式はどれか。',
            choices: ['DD/MM/YYYY', 'YYYYMMDD', 'YYYY-MM-DD', 'MM-DD-YYYY'],
            correctIndex: 1,
            explanation: '日付型DはYYYYMMDD形式の8桁文字列として内部的に保持されます。表示形式はユーザー設定により異なりますが、内部形式は常にYYYYMMDDです。',
          },
          {
            type: 'ox',
            question: 'ABAPでは変数をDATA命令で宣言する。',
            correct: true,
            explanation: '正しいです。DATA命令で変数を宣言し、TYPE句でデータ型を指定します。例：DATA lv_name TYPE string.',
          },
          {
            type: 'four-choice',
            question: '金額や数量など小数点を含む計算に適したデータ型はどれか。',
            choices: ['I（整数）', 'F（浮動小数点）', 'P（パック10進数）', 'N（数字文字列）'],
            correctIndex: 2,
            explanation: 'P（パック10進数）は小数点以下の桁数を指定でき、丸め誤差がないため、金額や数量の計算に最適です。F（浮動小数点）は丸め誤差が発生する可能性があるため、業務計算には推奨されません。',
          },
          {
            type: 'ox',
            question: 'データディクショナリで定義されたデータエレメントの型を、ABAPプログラム内でTYPE句により参照することができる。',
            correct: true,
            explanation: '正しいです。例えばDATA lv_bukrs TYPE bukrsと記述すれば、データディクショナリで定義された会社コード（bukrs）と同じ型の変数を宣言できます。',
          },
          {
            type: 'four-choice',
            question: 'ABAPの型Nの説明として正しいものはどれか。',
            choices: ['負の数を含む整数型', '数字のみで構成される固定長文字列型', '可変長の数値型', 'NULL値を格納できる特殊型'],
            correctIndex: 1,
            explanation: 'N（Numeric text）は数字（0-9）のみで構成される固定長文字列型です。伝票番号や取引先コードなど、先頭ゼロを保持する必要がある数字の格納に使用されます。算術計算には向きません。',
          },
        ],
      },
      {
        id: 'abap-control-flow',
        title: '制御構文',
        content: [
          'ABAPの条件分岐にはIF〜ELSEIF〜ELSE〜ENDIFとCASE〜WHEN〜ENDCASEがあります。IF文では比較演算子として=（EQ）、<>（NE）、>（GT）、<（LT）、>=（GE）、<=（LE）が使えます。IS INITIALで変数が初期値かどうかを判定できます。',
          'ループ処理にはDO〜ENDDO（回数指定）、WHILE〜ENDWHILE（条件指定）、LOOP AT〜ENDLOOP（内部テーブル走査）があります。LOOP AT itab INTO waのように書くことで内部テーブルの各行を作業領域に読み込んで処理できます。ループ内ではCONTINUE（次の繰り返しへ）やEXIT（ループ終了）が使えます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'ABAPで変数が初期値かどうかを判定する式はどれか。',
            choices: ['IS NULL', 'IS INITIAL', 'IS EMPTY', 'IS DEFAULT'],
            correctIndex: 1,
            explanation: 'IS INITIALは変数が型ごとの初期値（数値なら0、文字列なら空文字列）であるかを判定します。ABAPではIS NULLはOpen SQLのWHERE句で使用されるもので、ABAP変数の判定にはIS INITIALを使います。',
          },
          {
            type: 'ox',
            question: 'LOOP AT命令は内部テーブルの各行を順に処理するための制御構文である。',
            correct: true,
            explanation: '正しいです。LOOP AT itab INTO waのように書くことで、内部テーブルの各行を作業領域に読み込んで処理できます。',
          },
          {
            type: 'four-choice',
            question: 'ABAPのループ処理で、現在の繰り返しを中断して次の繰り返しに進む命令はどれか。',
            choices: ['EXIT', 'CONTINUE', 'STOP', 'RETURN'],
            correctIndex: 1,
            explanation: 'CONTINUEは現在の繰り返しを中断し、次の繰り返しに進みます。EXITはループ自体を終了します。STOPはイベントブロック内でプログラムの処理を終了する命令です。',
          },
          {
            type: 'four-choice',
            question: 'ABAPで「等しくない」ことを表す比較演算子はどれか。',
            choices: ['!=', '<>', 'NOT EQ', 'NE と <> の両方'],
            correctIndex: 3,
            explanation: 'ABAPでは<>とNEの両方が「等しくない」を表す比較演算子として使用できます。',
          },
          {
            type: 'ox',
            question: 'DO〜ENDDO命令は条件が真の間繰り返す制御構文である。',
            correct: false,
            explanation: '不正解です。DO〜ENDDOは回数を指定して繰り返す制御構文です（例：DO 10 TIMES）。条件が真の間繰り返すのはWHILE〜ENDWHILEです。',
          },
          {
            type: 'four-choice',
            question: '複数の固定値と比較して処理を分岐する場合に適した制御構文はどれか。',
            choices: ['IF〜ENDIF', 'CASE〜ENDCASE', 'DO〜ENDDO', 'WHILE〜ENDWHILE'],
            correctIndex: 1,
            explanation: 'CASE〜WHEN〜ENDCASEは、1つの変数を複数の固定値と比較して処理を分岐する場合に適しています。IF文でも同様の処理は可能ですが、CASE文の方が可読性が高くなります。',
          },
        ],
      },
      {
        id: 'abap-internal-tables',
        title: '内部テーブル',
        content: [
          '内部テーブルはABAPプログラム内でデータを一時的に格納するためのテーブル構造です。データベーステーブルから読み込んだデータの加工やレポート出力のために広く使われます。内部テーブルにはSTANDARD TABLE（標準テーブル）、SORTED TABLE（ソートテーブル）、HASHED TABLE（ハッシュテーブル）の3種類があります。',
          '標準テーブルはインデックスアクセスが可能で、最も汎用的です。ソートテーブルはキー順に自動ソートされ、バイナリサーチが可能です。ハッシュテーブルはキーによるダイレクトアクセスが高速ですが、インデックスアクセスはできません。内部テーブルの操作にはAPPEND（行追加）、INSERT（行挿入）、READ TABLE（行読み取り）、MODIFY（行変更）、DELETE（行削除）、SORT（ソート）などの命令があります。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'キーによるダイレクトアクセスが最も高速な内部テーブルの種類はどれか。',
            choices: ['STANDARD TABLE', 'SORTED TABLE', 'HASHED TABLE', 'INDEX TABLE'],
            correctIndex: 2,
            explanation: 'HASHED TABLEはハッシュアルゴリズムを使用するため、キーによるダイレクトアクセスが最も高速です（計算量O(1)）。ただし、インデックスアクセスはできません。',
          },
          {
            type: 'ox',
            question: 'SORTED TABLEはキー項目で自動的にソートされた状態を維持する。',
            correct: true,
            explanation: '正しいです。SORTED TABLEはデータ挿入時にキーの順序が自動的に維持されます。バイナリサーチによる高速な検索が可能です。',
          },
          {
            type: 'four-choice',
            question: '内部テーブルの末尾に行を追加する命令はどれか。',
            choices: ['INSERT', 'APPEND', 'ADD', 'PUSH'],
            correctIndex: 1,
            explanation: 'APPEND命令は内部テーブルの末尾に行を追加します。INSERT命令は指定した位置に行を挿入できます。なお、SORTED TABLEではAPPENDは使用できません（ソート順が崩れるため）。',
          },
          {
            type: 'four-choice',
            question: '内部テーブルから条件に一致する1行を読み取る命令はどれか。',
            choices: ['SELECT', 'GET', 'READ TABLE', 'FETCH'],
            correctIndex: 2,
            explanation: 'READ TABLE命令で内部テーブルから1行を読み取ります。WITH KEY句でキー条件を指定するか、INDEX句でインデックスを指定して読み取ります。SELECTはデータベーステーブルからの読み取りに使用します。',
          },
          {
            type: 'ox',
            question: 'HASHED TABLEはインデックスを使ったアクセスが可能である。',
            correct: false,
            explanation: '不正解です。HASHED TABLEはキーによるアクセスのみ可能で、インデックスアクセスはできません。インデックスアクセスが必要な場合はSTANDARD TABLEまたはSORTED TABLEを使用します。',
          },
          {
            type: 'ordering',
            question: '内部テーブルのデータ操作を一般的な処理順に並べてください。',
            items: ['テーブル型を宣言する', 'データを格納する', 'LOOP ATで処理する', '不要な行を削除する'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'まずテーブル型を宣言（DATA命令）し、データを格納（APPENDやSELECT）し、LOOP ATで各行を処理し、必要に応じて不要な行を削除するのが一般的な流れです。',
          },
        ],
      },
      {
        id: 'abap-open-sql',
        title: 'Open SQL',
        content: [
          'Open SQLはABAPプログラムからデータベースにアクセスするためのSQL方言です。標準SQLと似ていますが、SAP独自の拡張があります。SELECT文でデータを読み取り、INSERT・UPDATE・MODIFY・DELETEでデータを変更します。Open SQLはデータベースの種類（HANA、Oracle、SQL Serverなど）に依存しないため、SAPシステムのデータベースが変わってもABAPコードの変更は不要です。',
          'SELECT文では、取得する列をSELECT句に、対象テーブルをFROM句に、条件をWHERE句に指定します。複数行を内部テーブルに取得する場合はINTO TABLE句を使い、1行だけ取得する場合はINTO句とSINGLE修飾子を使います。取得後のシステム変数sy-subrcが0なら成功、4ならデータが見つからなかったことを示します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Open SQLのSELECT文で1行だけ取得する場合に使用する修飾子はどれか。',
            choices: ['FIRST', 'SINGLE', 'TOP 1', 'LIMIT 1'],
            correctIndex: 1,
            explanation: 'SINGLE修飾子を使うと、条件に一致する最初の1行だけを取得します。例：SELECT SINGLE * FROM mara INTO @DATA(ls_mara) WHERE matnr = @lv_matnr.',
          },
          {
            type: 'ox',
            question: 'Open SQLはデータベースの種類に依存しないため、HANAからOracle等へデータベースが変わってもABAPコードを変更する必要はない。',
            correct: true,
            explanation: '正しいです。Open SQLはSAPのデータベースインターフェース層で標準SQLに変換されるため、データベースの種類に依存しません。これがOpen SQLの大きな利点です。',
          },
          {
            type: 'four-choice',
            question: 'SELECT文の実行後、データが見つからなかった場合のsy-subrcの値はどれか。',
            choices: ['0', '2', '4', '8'],
            correctIndex: 2,
            explanation: 'sy-subrcが0の場合はデータが見つかった（成功）、4の場合はデータが見つからなかったことを示します。',
          },
          {
            type: 'four-choice',
            question: '複数行のデータをデータベーステーブルから内部テーブルに取得する際に使用する句はどれか。',
            choices: ['INTO', 'INTO TABLE', 'APPENDING', 'INTO TABLE と APPENDING の両方が使える'],
            correctIndex: 3,
            explanation: 'INTO TABLEは内部テーブルの中身を上書きしてデータを取得します。APPENDING TABLEは既存のデータを保持したまま追加します。どちらも複数行の取得に使用できます。',
          },
          {
            type: 'ox',
            question: 'ABAPのMODIFY命令は、キーが一致する行が存在すれば更新し、存在しなければ新規挿入する。',
            correct: true,
            explanation: '正しいです。MODIFYはUPSERT（Update or Insert）の動作をします。キーが一致する行があれば更新し、なければ挿入します。',
          },
          {
            type: 'four-choice',
            question: 'Open SQLで使用できないSQL機能はどれか。',
            choices: ['WHERE句による条件指定', 'ORDER BY句によるソート', 'GROUP BY句による集約', 'ストアドプロシージャの実行'],
            correctIndex: 3,
            explanation: 'Open SQLではストアドプロシージャの直接実行はできません。データベース固有の機能を使う場合はNative SQL（ADBC）やAMDP（ABAP Managed Database Procedures）を使用します。',
          },
        ],
      },
      {
        id: 'abap-modularization',
        title: 'モジュール化技法',
        content: [
          'ABAPではコードを再利用可能な単位に分割するモジュール化技法があります。代表的なものとして、サブルーチン（FORM〜ENDFORM）、ファンクションモジュール（FUNCTION〜ENDFUNCTION）、メソッド（METHOD〜ENDMETHOD）があります。サブルーチンは現在は非推奨であり、新規開発ではファンクションモジュールまたはクラスのメソッドを使用することが推奨されています。',
          'ファンクションモジュールはファンクショングループに属し、IMPORTING・EXPORTING・CHANGING・TABLESのパラメータインターフェースを持ちます。リモート呼び出し可能なRFC（Remote Function Call）対応のファンクションモジュールは、外部システムとの連携に広く使われます。BAPIもファンクションモジュールとして実装されており、SAPの標準ビジネスプロセスを外部から呼び出すためのインターフェースです。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '現在のABAP開発で新規開発時に非推奨とされているモジュール化技法はどれか。',
            choices: ['ファンクションモジュール', 'クラスのメソッド', 'サブルーチン（FORM）', 'BAPI'],
            correctIndex: 2,
            explanation: 'サブルーチン（FORM〜ENDFORM）は現在は非推奨です。新規開発ではクラスのメソッドまたはファンクションモジュールを使用することが推奨されています。',
          },
          {
            type: 'ox',
            question: 'BAPIはファンクションモジュールとして実装されている。',
            correct: true,
            explanation: '正しいです。BAPI（Business Application Programming Interface）はRFC対応のファンクションモジュールとして実装されており、SAPの標準ビジネスプロセスを外部から呼び出すためのインターフェースです。',
          },
          {
            type: 'four-choice',
            question: 'ファンクションモジュールのパラメータで、呼び出し側からデータを受け取るパラメータはどれか。',
            choices: ['EXPORTING', 'IMPORTING', 'CHANGING', 'RETURNING'],
            correctIndex: 1,
            explanation: 'ファンクションモジュールのIMPORTINGパラメータは呼び出し側からデータを受け取ります。EXPORTINGは呼び出し側にデータを返し、CHANGINGは受け取りと返却の両方を行います。なお、呼び出し側のCALL FUNCTIONではIMPORTING/EXPORTINGの意味が逆になる点に注意が必要です。',
          },
          {
            type: 'four-choice',
            question: '外部システムからSAPのファンクションモジュールを呼び出す仕組みは何か。',
            choices: ['BADI', 'RFC', 'User Exit', 'Enhancement Point'],
            correctIndex: 1,
            explanation: 'RFC（Remote Function Call）は外部システムからSAPのファンクションモジュールを呼び出す仕組みです。RFC対応のファンクションモジュールはリモート呼び出しが可能です。',
          },
          {
            type: 'ox',
            question: 'ファンクションモジュールは単独で存在し、ファンクショングループに属する必要はない。',
            correct: false,
            explanation: '不正解です。ファンクションモジュールは必ずファンクショングループに属します。ファンクショングループ内のファンクションモジュールはグローバルデータを共有できます。',
          },
          {
            type: 'ordering',
            question: 'ファンクションモジュール呼び出しの処理順序を並べてください。',
            items: ['CALL FUNCTIONを記述', 'IMPORTINGパラメータを渡す', '処理が実行される', 'EXPORTINGパラメータを受け取る'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'CALL FUNCTION文でファンクションモジュールを呼び出し、EXPORTINGで値を渡し（FM側ではIMPORTINGで受け取り）、処理が実行され、IMPORTINGで結果を受け取ります（FM側ではEXPORTINGで返却）。',
          },
        ],
      },
      {
        id: 'abap-oop',
        title: 'ABAPオブジェクト指向',
        content: [
          'ABAP Objects（ABAPオブジェクト指向プログラミング）は、ABAPにおけるオブジェクト指向のプログラミングモデルです。クラス（CLASS）を定義し、属性（ATTRIBUTES）とメソッド（METHODS）を持たせることができます。クラスにはPUBLIC・PROTECTED・PRIVATEの可視性セクションがあり、データのカプセル化を実現します。',
          'ABAPのクラスにはインスタンスメソッドとスタティックメソッド（CLASS-METHODS）があります。継承（INHERITING FROM）により既存クラスを拡張でき、インターフェース（INTERFACE）により共通のメソッドシグネチャを定義できます。また、イベント（EVENTS）を使ったオブジェクト間の疎結合な通信も可能です。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'ABAPクラスで、外部から直接アクセスできる可視性セクションはどれか。',
            choices: ['PRIVATE', 'PROTECTED', 'PUBLIC', 'すべてのセクション'],
            correctIndex: 2,
            explanation: 'PUBLICセクションに定義された属性とメソッドは外部から直接アクセスできます。PRIVATEは同一クラス内のみ、PROTECTEDは同一クラスとサブクラスからアクセス可能です。',
          },
          {
            type: 'ox',
            question: 'ABAPではクラスの継承（INHERITING FROM）がサポートされている。',
            correct: true,
            explanation: '正しいです。ABAPではCLASS cl_child DEFINITION INHERITING FROM cl_parentのように記述して継承を実現します。ABAPの継承は単一継承です。',
          },
          {
            type: 'four-choice',
            question: 'インスタンスを生成せずに呼び出せるメソッドの種類はどれか。',
            choices: ['インスタンスメソッド', 'スタティックメソッド', 'コンストラクタ', 'イベントハンドラ'],
            correctIndex: 1,
            explanation: 'スタティックメソッド（CLASS-METHODS）はクラス名で直接呼び出せます（cl_class=>method_name）。インスタンスメソッドはオブジェクトを生成してから呼び出す必要があります。',
          },
          {
            type: 'ox',
            question: 'ABAPのクラスは多重継承（複数の親クラスからの継承）をサポートしている。',
            correct: false,
            explanation: '不正解です。ABAPの継承は単一継承のみです。ただし、インターフェースを使うことで、複数のインターフェースを1つのクラスに実装することは可能です。',
          },
          {
            type: 'four-choice',
            question: 'ABAPでオブジェクト（インスタンス）を生成するための命令はどれか。',
            choices: ['NEW', 'CREATE OBJECT', 'NEW と CREATE OBJECT の両方', 'INSTANTIATE'],
            correctIndex: 2,
            explanation: 'CREATE OBJECTは従来からの記法で、NEWはABAP 7.40以降で使用できる新しい記法です。どちらもオブジェクトのインスタンスを生成します。',
          },
          {
            type: 'four-choice',
            question: 'ABAPのインターフェースの説明として正しいものはどれか。',
            choices: ['実装を持つクラスの一種', 'メソッドのシグネチャのみを定義する仕組み', 'グローバル変数を共有する仕組み', '画面レイアウトを定義する仕組み'],
            correctIndex: 1,
            explanation: 'インターフェース（INTERFACE）はメソッドのシグネチャ（名前・パラメータ）のみを定義し、実装はインターフェースを実装するクラスが行います。複数のクラスに共通の契約を定義するために使用します。',
          },
        ],
      },
      {
        id: 'abap-alv',
        title: 'ALVレポート',
        content: [
          'ALV（ABAP List Viewer）は、SAPの標準的なデータ表示機能です。内部テーブルのデータを表形式で表示し、ソート・フィルタ・小計・レイアウト保存などの機能を標準で提供します。ユーザーは表示列の並び替えやフィルタをALVの機能で自由にカスタマイズできます。',
          'ALVの実装方法には、ファンクションモジュールベースのREUSE_ALV_GRID_DISPLAYや、オブジェクト指向のCL_SALV_TABLEクラスなどがあります。CL_SALV_TABLEはALV出力をシンプルに実装でき、新規開発で推奨されます。ALVにはフィールドカタログ（表示列の定義）が必要で、データディクショナリの構造を参照すると自動生成できます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'ALVの正式名称は何か。',
            choices: ['Advanced List View', 'ABAP List Viewer', 'Application List View', 'ABAP Layout Viewer'],
            correctIndex: 1,
            explanation: 'ALVはABAP List Viewerの略です。SAPの標準的なデータ一覧表示機能で、ソートやフィルタなどの機能を標準で提供します。',
          },
          {
            type: 'ox',
            question: 'ALVでは、ユーザーが表示列の並び替えやフィルタを自由にカスタマイズできる。',
            correct: true,
            explanation: '正しいです。ALVはソート・フィルタ・列の表示/非表示・レイアウト保存などの機能を標準で提供しており、ユーザーは自由にカスタマイズできます。',
          },
          {
            type: 'four-choice',
            question: 'ALVの表示列を定義する仕組みを何と呼ぶか。',
            choices: ['スクリーンペインタ', 'フィールドカタログ', 'メニューペインタ', 'レイアウトマネージャ'],
            correctIndex: 1,
            explanation: 'フィールドカタログ（Field Catalog）はALVの表示列（列名・表示テキスト・データ型・表示幅など）を定義する仕組みです。データディクショナリの構造を参照すると自動生成できます。',
          },
          {
            type: 'four-choice',
            question: '新規開発でALV出力に推奨されるクラスはどれか。',
            choices: ['CL_GUI_ALV_GRID', 'CL_SALV_TABLE', 'REUSE_ALV_GRID_DISPLAY', 'CL_ALV_DISPLAY'],
            correctIndex: 1,
            explanation: 'CL_SALV_TABLEはシンプルなインターフェースでALV出力を実装できるクラスで、新規開発で推奨されます。REUSE_ALV_GRID_DISPLAYはファンクションモジュールベースの旧方式です。',
          },
          {
            type: 'ox',
            question: 'REUSE_ALV_GRID_DISPLAYはクラスベースのALV実装方法である。',
            correct: false,
            explanation: '不正解です。REUSE_ALV_GRID_DISPLAYはファンクションモジュールベースのALV実装方法です。クラスベースではCL_SALV_TABLEやCL_GUI_ALV_GRIDを使用します。',
          },
          {
            type: 'ordering',
            question: 'CL_SALV_TABLEを使ったALV表示の実装手順を並べてください。',
            items: ['内部テーブルにデータを取得', 'CL_SALV_TABLE=>FACTORYでインスタンス生成', '表示設定をカスタマイズ', 'DISPLAY メソッドを呼び出し'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'まずデータを内部テーブルに取得し、FACTORYメソッドでALVインスタンスを生成し、列の表示設定などをカスタマイズした後、DISPLAYメソッドで画面に表示します。',
          },
        ],
      },
      {
        id: 'abap-data-dictionary',
        title: 'データディクショナリ',
        content: [
          'データディクショナリ（DDIC / トランザクションコードSE11）はSAPのメタデータ管理ツールです。テーブル・ビュー・データ型・検索ヘルプ・ロックオブジェクトなどを定義・管理します。ABAPプログラムからはここで定義した型やテーブルを直接参照できます。',
          'データディクショナリで定義するテーブルには、透過テーブル（Transparent Table）・クラスタテーブル・プールテーブルがあります。透過テーブルはデータベース上に1対1で対応するテーブルが作成される最も一般的な形式です。また、データエレメント（Data Element）はフィールドの意味（ラベル・ヘルプテキスト）を定義し、ドメイン（Domain）は技術的な属性（データ型・桁数・値範囲）を定義します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'データディクショナリのトランザクションコードはどれか。',
            choices: ['SE38', 'SE37', 'SE11', 'SE80'],
            correctIndex: 2,
            explanation: 'SE11はデータディクショナリ（ABAP Dictionary）のトランザクションコードです。テーブル・データ型・検索ヘルプなどを定義・管理します。',
          },
          {
            type: 'four-choice',
            question: 'データベース上に1対1で対応するテーブルが作成されるテーブルタイプはどれか。',
            choices: ['クラスタテーブル', 'プールテーブル', '透過テーブル', '内部テーブル'],
            correctIndex: 2,
            explanation: '透過テーブル（Transparent Table）はデータベース上に同じ構造のテーブルが1対1で作成される最も一般的なテーブルタイプです。内部テーブルはABAPプログラム内の一時的なテーブルで、データベースには保存されません。',
          },
          {
            type: 'ox',
            question: 'ドメイン（Domain）はフィールドのラベルやヘルプテキストなどの意味的な情報を定義する。',
            correct: false,
            explanation: '不正解です。ドメインはデータ型・桁数・値範囲などの技術的な属性を定義します。フィールドのラベルやヘルプテキストなどの意味的な情報を定義するのはデータエレメント（Data Element）です。',
          },
          {
            type: 'four-choice',
            question: 'データエレメントとドメインの関係として正しいものはどれか。',
            choices: ['データエレメントがドメインに属する', 'ドメインがデータエレメントに属する', 'データエレメントはドメインを参照して技術的属性を継承する', '両者に関連はない'],
            correctIndex: 2,
            explanation: 'データエレメントはドメインを参照し、ドメインに定義された技術的属性（データ型・桁数など）を継承します。データエレメント自体はフィールドの意味（ラベル・ドキュメント）を定義します。',
          },
          {
            type: 'ox',
            question: '検索ヘルプ（Search Help）はデータディクショナリで定義される。',
            correct: true,
            explanation: '正しいです。検索ヘルプはSE11で定義され、入力フィールドでF4キーを押した際に表示される値一覧を提供します。',
          },
          {
            type: 'four-choice',
            question: '同時更新によるデータ不整合を防ぐためにデータディクショナリで定義するオブジェクトはどれか。',
            choices: ['検索ヘルプ', 'ビュー', 'ロックオブジェクト', 'テーブルタイプ'],
            correctIndex: 2,
            explanation: 'ロックオブジェクト（Lock Object）は、複数ユーザーによる同時更新を制御するための排他制御の仕組みです。SE11で定義し、自動生成されるENQUEUE/DEQUEUEファンクションモジュールで使用します。',
          },
        ],
      },
      {
        id: 'abap-debugging-error',
        title: 'デバッグとエラー処理',
        content: [
          'ABAPデバッガは、プログラムの実行をステップごとに追跡し、変数の値やプログラムの流れを確認するためのツールです。ABAPエディタや実行画面で /h を入力するか、ソースコードにBREAK-POINTを記述することでデバッガを起動できます。デバッガではステップイン（F5）・ステップオーバー（F6）・ステップアウト（F7）・続行（F8）でプログラムの実行を制御できます。',
          'ABAPのエラー処理にはTRY〜CATCH〜ENDTRYによる例外処理があります。クラスベースの例外はCX_で始まる例外クラスを使用し、RAISE EXCEPTIONで例外を発生させます。また、ABAPのショートダンプ（実行時エラー）はトランザクションST22で確認できます。MESSAGE命令を使用してユーザーにメッセージを表示することもできます。メッセージタイプにはE（エラー）、W（警告）、I（情報）、S（ステータス）、A（中断）があります。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'ABAPのショートダンプ（実行時エラー）を確認するトランザクションコードはどれか。',
            choices: ['SM21', 'ST22', 'SM37', 'SE38'],
            correctIndex: 1,
            explanation: 'ST22はABAPランタイムエラー（ショートダンプ）を確認するトランザクションコードです。エラーの詳細情報、発生箇所、変数の値などを確認できます。',
          },
          {
            type: 'four-choice',
            question: 'ABAPデバッガで、サブルーチンやメソッドの中に入らずに次の行に進む操作はどれか。',
            choices: ['F5（ステップイン）', 'F6（ステップオーバー）', 'F7（ステップアウト）', 'F8（続行）'],
            correctIndex: 1,
            explanation: 'F6（ステップオーバー）はサブルーチンやメソッドの内部に入らずに次の行に進みます。F5は内部に入り、F7は現在のルーチンから抜け、F8はブレークポイントまで実行を続行します。',
          },
          {
            type: 'ox',
            question: 'ABAPではTRY〜CATCH〜ENDTRYによる例外処理が使用できる。',
            correct: true,
            explanation: '正しいです。クラスベースの例外処理としてTRY〜CATCH〜ENDTRY構文が使用できます。CATCH句でCX_で始まる例外クラスを指定して例外を捕捉します。',
          },
          {
            type: 'four-choice',
            question: 'MESSAGE命令でエラーメッセージを表示する場合のメッセージタイプはどれか。',
            choices: ['TYPE W', 'TYPE I', 'TYPE E', 'TYPE S'],
            correctIndex: 2,
            explanation: 'TYPE Eはエラーメッセージで、処理を中断してユーザーに修正を求めます。Wは警告、Iは情報（ポップアップ表示）、Sはステータスバー表示です。',
          },
          {
            type: 'ox',
            question: '実行画面でコマンドフィールドに /h と入力するとデバッガが起動する。',
            correct: true,
            explanation: '正しいです。/h はデバッグモードを有効にするシステムコマンドです。次にアクションを実行するとデバッガが起動します。',
          },
          {
            type: 'four-choice',
            question: 'ABAPの例外クラスの命名規則として、クラス名はどのプレフィックスで始まるか。',
            choices: ['EX_', 'CX_', 'ZX_', 'CL_'],
            correctIndex: 1,
            explanation: 'ABAPの標準例外クラスはCX_で始まります（例：CX_SY_ZERO_DIVIDE）。カスタム例外クラスもCX_で始めるか、顧客名前空間のZCX_やYCX_で始めます。CL_は通常クラスのプレフィックスです。',
          },
        ],
      },
    ],
  },
  en: {
    id: 'abap',
    title: 'ABAP Development',
    description: 'Learn the fundamentals of ABAP, SAP\'s standard development language',
    sections: [
      {
        id: 'abap-overview',
        title: 'What is ABAP?',
        content: [
          'ABAP (Advanced Business Application Programming) is a proprietary programming language developed by SAP. Most of SAP ERP is built in ABAP, and it is also used for add-on development and customization. ABAP has a COBOL-like syntax and is specifically designed for business application development.',
          'ABAP programs run on the SAP Application Server. Source code is stored in the database and interpreted/executed by the ABAP runtime environment. ABAP has several program types including Reports, Module Pools, Function Modules, and Classes.',
        ],
        quizzes: [
          {
            type: 'ox',
            question: 'ABAP is a proprietary programming language developed by SAP, and most of SAP ERP is built in ABAP.',
            correct: true,
            explanation: 'Correct. ABAP stands for Advanced Business Application Programming and is the standard development language for SAP ERP.',
          },
          {
            type: 'four-choice',
            question: 'What does ABAP stand for?',
            choices: ['Advanced Business Application Programming', 'Advanced Business Analysis Program', 'Application Business ABAP Platform', 'Automated Business Application Processor'],
            correctIndex: 0,
            explanation: 'ABAP stands for Advanced Business Application Programming.',
          },
          {
            type: 'ox',
            question: 'ABAP source code is stored as files on the file system.',
            correct: false,
            explanation: 'Incorrect. ABAP source code is stored in the database. This is a distinctive feature of SAP, enabling transport management to move code between environments.',
          },
          {
            type: 'four-choice',
            question: 'Which programming language is ABAP\'s syntax most similar to?',
            choices: ['Java', 'COBOL', 'Python', 'C++'],
            correctIndex: 1,
            explanation: 'ABAP has a COBOL-like syntax with an English sentence-like coding style, specialized for business application development.',
          },
          {
            type: 'four-choice',
            question: 'Which ABAP program type is used for retrieving data via a selection screen and displaying it as a list?',
            choices: ['Module Pool', 'Report', 'Interface', 'Function Group'],
            correctIndex: 1,
            explanation: 'A Report receives user input via a selection screen, retrieves data, and displays it as a list. It is the most basic ABAP program type.',
          },
          {
            type: 'ox',
            question: 'ABAP programs are executed directly on the client PC.',
            correct: false,
            explanation: 'Incorrect. ABAP programs run on the SAP Application Server. Clients communicate with the server through front-end tools such as SAP GUI.',
          },
        ],
      },
      {
        id: 'abap-dev-environment',
        title: 'ABAP Development Environment',
        content: [
          'ABAP development environments include the traditional ABAP Workbench on SAP GUI (transaction code SE80) and Eclipse-based ABAP Development Tools (ADT). SE80 provides integrated development for programs, function modules, classes, and more. ADT is the recommended development environment for S/4HANA development.',
          'Individual development objects have dedicated transaction codes. The ABAP Editor (SE38) is used for creating and editing report programs, Function Builder (SE37) for function modules, Class Builder (SE24) for ABAP classes, and Data Dictionary (SE11) for defining tables and data types.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What is the transaction code for the ABAP Workbench?',
            choices: ['SE38', 'SE80', 'SE11', 'SE37'],
            correctIndex: 1,
            explanation: 'SE80 is the transaction code for the ABAP Workbench (Object Navigator). SE38 is the ABAP Editor, SE11 is the Data Dictionary, and SE37 is the Function Builder.',
          },
          {
            type: 'four-choice',
            question: 'What is the transaction code for developing Function Modules?',
            choices: ['SE38', 'SE24', 'SE37', 'SE80'],
            correctIndex: 2,
            explanation: 'SE37 is the Function Builder, used for creating, testing, and managing function modules. SE24 is the Class Builder, and SE38 is the ABAP Editor.',
          },
          {
            type: 'ox',
            question: 'ABAP Development Tools (ADT) is a development environment that runs on Eclipse.',
            correct: true,
            explanation: 'Correct. ADT is an Eclipse-based IDE and is the recommended development environment for S/4HANA development. It provides modern features such as code completion and refactoring.',
          },
          {
            type: 'four-choice',
            question: 'What is the transaction code for developing ABAP classes?',
            choices: ['SE37', 'SE38', 'SE24', 'SE11'],
            correctIndex: 2,
            explanation: 'SE24 is the Class Builder, used for creating and editing ABAP Objects (classes and interfaces).',
          },
          {
            type: 'ox',
            question: 'SE38 is the transaction code for the Data Dictionary.',
            correct: false,
            explanation: 'Incorrect. SE38 is the transaction code for the ABAP Editor. The Data Dictionary transaction code is SE11.',
          },
          {
            type: 'four-choice',
            question: 'Which development environment is recommended for S/4HANA development?',
            choices: ['SE80 (ABAP Workbench)', 'ABAP Development Tools (ADT)', 'SE38 (ABAP Editor)', 'Visual Studio Code'],
            correctIndex: 1,
            explanation: 'ABAP Development Tools (ADT) is recommended for S/4HANA development. It is an Eclipse-based IDE that supports new development objects such as CDS Views.',
          },
        ],
      },
      {
        id: 'abap-data-types',
        title: 'Data Types and Variable Declaration',
        content: [
          'In ABAP, variables are declared using the DATA statement. Basic data types include C (fixed-length character), N (numeric text), I (integer), P (packed decimal), F (floating point), D (date in YYYYMMDD format), T (time in HHMMSS format), STRING (variable-length string), and XSTRING (variable-length byte string).',
          'Structures are defined using BEGIN OF~END OF to group multiple fields. Custom types can be defined using TYPES and referenced with the TYPE clause in DATA statements. Data types defined in the Data Dictionary (SE11), such as data elements and table types, can also be directly referenced using the TYPE clause. For example, DATA lv_bukrs TYPE bukrs declares a variable with the same type as the company code.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which basic data type represents an integer in ABAP?',
            choices: ['C', 'N', 'I', 'P'],
            correctIndex: 2,
            explanation: 'I (Integer) is the integer type. C is fixed-length character, N is numeric text (fixed-length string of digits only), and P is packed decimal (used for calculations with decimal points).',
          },
          {
            type: 'four-choice',
            question: 'What is the internal format of ABAP date type D?',
            choices: ['DD/MM/YYYY', 'YYYYMMDD', 'YYYY-MM-DD', 'MM-DD-YYYY'],
            correctIndex: 1,
            explanation: 'Date type D is internally stored as an 8-character string in YYYYMMDD format. The display format varies by user settings, but the internal format is always YYYYMMDD.',
          },
          {
            type: 'ox',
            question: 'In ABAP, variables are declared using the DATA statement.',
            correct: true,
            explanation: 'Correct. The DATA statement declares variables, with the TYPE clause specifying the data type. Example: DATA lv_name TYPE string.',
          },
          {
            type: 'four-choice',
            question: 'Which data type is most suitable for calculations involving decimal points, such as amounts and quantities?',
            choices: ['I (Integer)', 'F (Floating Point)', 'P (Packed Decimal)', 'N (Numeric Text)'],
            correctIndex: 2,
            explanation: 'P (Packed Decimal) allows specifying decimal places and has no rounding errors, making it ideal for amount and quantity calculations. F (Floating Point) can have rounding errors and is not recommended for business calculations.',
          },
          {
            type: 'ox',
            question: 'Data element types defined in the Data Dictionary can be referenced using the TYPE clause in ABAP programs.',
            correct: true,
            explanation: 'Correct. For example, DATA lv_bukrs TYPE bukrs declares a variable with the same type as the company code (bukrs) defined in the Data Dictionary.',
          },
          {
            type: 'four-choice',
            question: 'Which statement correctly describes ABAP type N?',
            choices: ['An integer type that includes negative numbers', 'A fixed-length string type consisting only of digits', 'A variable-length numeric type', 'A special type that can store NULL values'],
            correctIndex: 1,
            explanation: 'N (Numeric text) is a fixed-length string type consisting only of digits (0-9). It is used for storing numbers that need to preserve leading zeros, such as document numbers and partner codes. It is not suitable for arithmetic calculations.',
          },
        ],
      },
      {
        id: 'abap-control-flow',
        title: 'Control Structures',
        content: [
          'ABAP conditional statements include IF~ELSEIF~ELSE~ENDIF and CASE~WHEN~ENDCASE. IF statements support comparison operators such as = (EQ), <> (NE), > (GT), < (LT), >= (GE), and <= (LE). IS INITIAL can be used to check whether a variable holds its initial value.',
          'Loop constructs include DO~ENDDO (count-based), WHILE~ENDWHILE (condition-based), and LOOP AT~ENDLOOP (internal table iteration). Writing LOOP AT itab INTO wa reads each row of the internal table into a work area for processing. Within loops, CONTINUE (skip to next iteration) and EXIT (terminate loop) can be used.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which expression checks whether a variable holds its initial value in ABAP?',
            choices: ['IS NULL', 'IS INITIAL', 'IS EMPTY', 'IS DEFAULT'],
            correctIndex: 1,
            explanation: 'IS INITIAL checks whether a variable holds the initial value for its type (0 for numbers, empty string for characters). In ABAP, IS NULL is used in Open SQL WHERE clauses, while IS INITIAL is used for ABAP variables.',
          },
          {
            type: 'ox',
            question: 'The LOOP AT statement is a control structure for processing each row of an internal table sequentially.',
            correct: true,
            explanation: 'Correct. Writing LOOP AT itab INTO wa reads each row of the internal table into a work area for processing.',
          },
          {
            type: 'four-choice',
            question: 'Which statement skips the current iteration and proceeds to the next iteration in an ABAP loop?',
            choices: ['EXIT', 'CONTINUE', 'STOP', 'RETURN'],
            correctIndex: 1,
            explanation: 'CONTINUE skips the current iteration and proceeds to the next one. EXIT terminates the loop entirely. STOP ends processing within an event block.',
          },
          {
            type: 'four-choice',
            question: 'Which comparison operator means "not equal" in ABAP?',
            choices: ['!=', '<>', 'NOT EQ', 'Both NE and <>'],
            correctIndex: 3,
            explanation: 'In ABAP, both <> and NE can be used as "not equal" comparison operators.',
          },
          {
            type: 'ox',
            question: 'The DO~ENDDO statement repeats execution while a condition is true.',
            correct: false,
            explanation: 'Incorrect. DO~ENDDO repeats execution a specified number of times (e.g., DO 10 TIMES). WHILE~ENDWHILE repeats while a condition is true.',
          },
          {
            type: 'four-choice',
            question: 'Which control structure is most appropriate for branching based on comparison with multiple fixed values?',
            choices: ['IF~ENDIF', 'CASE~ENDCASE', 'DO~ENDDO', 'WHILE~ENDWHILE'],
            correctIndex: 1,
            explanation: 'CASE~WHEN~ENDCASE is ideal for branching based on comparing one variable against multiple fixed values. While IF statements can achieve the same result, CASE statements offer better readability.',
          },
        ],
      },
      {
        id: 'abap-internal-tables',
        title: 'Internal Tables',
        content: [
          'Internal tables are table structures for temporarily storing data within ABAP programs. They are widely used for processing data read from database tables and for report output. There are three types of internal tables: STANDARD TABLE, SORTED TABLE, and HASHED TABLE.',
          'Standard tables allow index access and are the most versatile. Sorted tables are automatically sorted by key and support binary search. Hashed tables provide fast direct access by key but do not support index access. Operations on internal tables include APPEND (add row), INSERT (insert row), READ TABLE (read row), MODIFY (modify row), DELETE (delete row), and SORT.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which type of internal table provides the fastest direct access by key?',
            choices: ['STANDARD TABLE', 'SORTED TABLE', 'HASHED TABLE', 'INDEX TABLE'],
            correctIndex: 2,
            explanation: 'HASHED TABLE uses a hash algorithm for the fastest direct key access (O(1) complexity). However, it does not support index access.',
          },
          {
            type: 'ox',
            question: 'A SORTED TABLE automatically maintains its data sorted by key fields.',
            correct: true,
            explanation: 'Correct. A SORTED TABLE automatically maintains key order when data is inserted, enabling fast binary search.',
          },
          {
            type: 'four-choice',
            question: 'Which statement adds a row to the end of an internal table?',
            choices: ['INSERT', 'APPEND', 'ADD', 'PUSH'],
            correctIndex: 1,
            explanation: 'APPEND adds a row to the end of an internal table. INSERT can insert a row at a specified position. Note that APPEND cannot be used with SORTED TABLEs as it would break the sort order.',
          },
          {
            type: 'four-choice',
            question: 'Which statement reads a single row from an internal table that matches a condition?',
            choices: ['SELECT', 'GET', 'READ TABLE', 'FETCH'],
            correctIndex: 2,
            explanation: 'READ TABLE reads a single row from an internal table. Use WITH KEY for key conditions or INDEX for index-based access. SELECT is used for reading from database tables.',
          },
          {
            type: 'ox',
            question: 'HASHED TABLE supports index-based access.',
            correct: false,
            explanation: 'Incorrect. HASHED TABLE only supports key-based access and does not support index access. Use STANDARD TABLE or SORTED TABLE if index access is needed.',
          },
          {
            type: 'ordering',
            question: 'Arrange the internal table data operations in their typical processing order.',
            items: ['Declare the table type', 'Populate data', 'Process with LOOP AT', 'Delete unnecessary rows'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'First declare the table type (DATA statement), populate data (APPEND or SELECT), process each row with LOOP AT, and optionally delete unnecessary rows.',
          },
        ],
      },
      {
        id: 'abap-open-sql',
        title: 'Open SQL',
        content: [
          'Open SQL is a SQL dialect for accessing databases from ABAP programs. While similar to standard SQL, it includes SAP-specific extensions. SELECT reads data, while INSERT, UPDATE, MODIFY, and DELETE change data. Open SQL is database-independent (works with HANA, Oracle, SQL Server, etc.), so ABAP code does not need to change when the underlying database changes.',
          'In SELECT statements, columns are specified in the SELECT clause, the target table in the FROM clause, and conditions in the WHERE clause. Use INTO TABLE to retrieve multiple rows into an internal table, or INTO with the SINGLE modifier to retrieve a single row. After execution, the system variable sy-subrc being 0 indicates success, while 4 indicates no data was found.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which modifier is used in an Open SQL SELECT statement to retrieve only one row?',
            choices: ['FIRST', 'SINGLE', 'TOP 1', 'LIMIT 1'],
            correctIndex: 1,
            explanation: 'The SINGLE modifier retrieves only the first row matching the conditions. Example: SELECT SINGLE * FROM mara INTO @DATA(ls_mara) WHERE matnr = @lv_matnr.',
          },
          {
            type: 'ox',
            question: 'Open SQL is database-independent, so ABAP code does not need to change when switching from HANA to Oracle or other databases.',
            correct: true,
            explanation: 'Correct. Open SQL is translated to standard SQL by SAP\'s database interface layer, making it independent of the underlying database. This is a major advantage of Open SQL.',
          },
          {
            type: 'four-choice',
            question: 'What is the value of sy-subrc when no data is found after a SELECT statement?',
            choices: ['0', '2', '4', '8'],
            correctIndex: 2,
            explanation: 'sy-subrc = 0 indicates data was found (success), while sy-subrc = 4 indicates no data was found.',
          },
          {
            type: 'four-choice',
            question: 'Which clause is used to retrieve multiple rows from a database table into an internal table?',
            choices: ['INTO', 'INTO TABLE', 'APPENDING', 'Both INTO TABLE and APPENDING TABLE can be used'],
            correctIndex: 3,
            explanation: 'INTO TABLE overwrites the internal table contents when retrieving data. APPENDING TABLE preserves existing data and adds to it. Both can be used for retrieving multiple rows.',
          },
          {
            type: 'ox',
            question: 'The ABAP MODIFY statement updates a row if the key matches, or inserts a new row if no match is found.',
            correct: true,
            explanation: 'Correct. MODIFY performs an UPSERT (Update or Insert) operation. It updates the row if the key matches, or inserts a new row if no match exists.',
          },
          {
            type: 'four-choice',
            question: 'Which SQL feature is NOT available in Open SQL?',
            choices: ['WHERE clause for conditions', 'ORDER BY clause for sorting', 'GROUP BY clause for aggregation', 'Stored procedure execution'],
            correctIndex: 3,
            explanation: 'Open SQL does not support direct stored procedure execution. For database-specific features, use Native SQL (ADBC) or AMDP (ABAP Managed Database Procedures).',
          },
        ],
      },
      {
        id: 'abap-modularization',
        title: 'Modularization Techniques',
        content: [
          'ABAP provides modularization techniques to divide code into reusable units. Key techniques include subroutines (FORM~ENDFORM), function modules (FUNCTION~ENDFUNCTION), and methods (METHOD~ENDMETHOD). Subroutines are now deprecated, and new development should use function modules or class methods.',
          'Function modules belong to function groups and have an interface with IMPORTING, EXPORTING, CHANGING, and TABLES parameters. RFC (Remote Function Call)-enabled function modules are widely used for integration with external systems. BAPIs are also implemented as function modules, providing standardized interfaces for calling SAP business processes from external systems.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which modularization technique is deprecated for new ABAP development?',
            choices: ['Function Modules', 'Class Methods', 'Subroutines (FORM)', 'BAPIs'],
            correctIndex: 2,
            explanation: 'Subroutines (FORM~ENDFORM) are now deprecated. New development should use class methods or function modules.',
          },
          {
            type: 'ox',
            question: 'BAPIs are implemented as function modules.',
            correct: true,
            explanation: 'Correct. BAPIs (Business Application Programming Interfaces) are implemented as RFC-enabled function modules, providing standardized interfaces for calling SAP business processes from external systems.',
          },
          {
            type: 'four-choice',
            question: 'Which function module parameter receives data from the caller?',
            choices: ['EXPORTING', 'IMPORTING', 'CHANGING', 'RETURNING'],
            correctIndex: 1,
            explanation: 'The IMPORTING parameter of a function module receives data from the caller. EXPORTING returns data to the caller, and CHANGING handles both directions. Note that in the CALL FUNCTION statement, the IMPORTING/EXPORTING meanings are reversed from the caller\'s perspective.',
          },
          {
            type: 'four-choice',
            question: 'What mechanism allows external systems to call SAP function modules?',
            choices: ['BADI', 'RFC', 'User Exit', 'Enhancement Point'],
            correctIndex: 1,
            explanation: 'RFC (Remote Function Call) enables external systems to call SAP function modules. Function modules marked as RFC-enabled can be called remotely.',
          },
          {
            type: 'ox',
            question: 'Function modules can exist independently without belonging to a function group.',
            correct: false,
            explanation: 'Incorrect. Function modules must always belong to a function group. Function modules within the same function group can share global data.',
          },
          {
            type: 'ordering',
            question: 'Arrange the steps for calling a function module in order.',
            items: ['Write CALL FUNCTION', 'Pass IMPORTING parameters', 'Processing executes', 'Receive EXPORTING parameters'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'Write the CALL FUNCTION statement, pass values via EXPORTING (received as IMPORTING by the FM), the function module processes, and receive results via IMPORTING (sent as EXPORTING by the FM).',
          },
        ],
      },
      {
        id: 'abap-oop',
        title: 'ABAP Object-Oriented Programming',
        content: [
          'ABAP Objects is the object-oriented programming model in ABAP. Classes (CLASS) are defined with attributes and methods, organized into PUBLIC, PROTECTED, and PRIVATE visibility sections to achieve data encapsulation.',
          'ABAP classes support instance methods and static methods (CLASS-METHODS). Inheritance (INHERITING FROM) allows extending existing classes, and interfaces (INTERFACE) define common method signatures. Event-based (EVENTS) loosely coupled communication between objects is also supported.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which visibility section in an ABAP class allows direct external access?',
            choices: ['PRIVATE', 'PROTECTED', 'PUBLIC', 'All sections'],
            correctIndex: 2,
            explanation: 'Attributes and methods defined in the PUBLIC section can be accessed directly from outside the class. PRIVATE is accessible only within the same class, and PROTECTED is accessible from the same class and subclasses.',
          },
          {
            type: 'ox',
            question: 'ABAP supports class inheritance (INHERITING FROM).',
            correct: true,
            explanation: 'Correct. ABAP supports inheritance using CLASS cl_child DEFINITION INHERITING FROM cl_parent syntax. ABAP supports single inheritance only.',
          },
          {
            type: 'four-choice',
            question: 'Which type of method can be called without creating an instance?',
            choices: ['Instance method', 'Static method', 'Constructor', 'Event handler'],
            correctIndex: 1,
            explanation: 'Static methods (CLASS-METHODS) can be called directly using the class name (cl_class=>method_name). Instance methods require an object to be created first.',
          },
          {
            type: 'ox',
            question: 'ABAP classes support multiple inheritance (inheriting from multiple parent classes).',
            correct: false,
            explanation: 'Incorrect. ABAP supports single inheritance only. However, a class can implement multiple interfaces.',
          },
          {
            type: 'four-choice',
            question: 'Which statements are used to create an object (instance) in ABAP?',
            choices: ['NEW', 'CREATE OBJECT', 'Both NEW and CREATE OBJECT', 'INSTANTIATE'],
            correctIndex: 2,
            explanation: 'CREATE OBJECT is the traditional syntax, and NEW is the newer syntax available from ABAP 7.40. Both create object instances.',
          },
          {
            type: 'four-choice',
            question: 'Which statement correctly describes ABAP interfaces?',
            choices: ['A type of class with implementation', 'A mechanism that defines only method signatures', 'A mechanism for sharing global variables', 'A mechanism for defining screen layouts'],
            correctIndex: 1,
            explanation: 'An INTERFACE defines only method signatures (names and parameters), while the implementing class provides the actual implementation. Interfaces are used to define common contracts across multiple classes.',
          },
        ],
      },
      {
        id: 'abap-alv',
        title: 'ALV Reports',
        content: [
          'ALV (ABAP List Viewer) is SAP\'s standard data display feature. It displays internal table data in a tabular format with built-in features such as sorting, filtering, subtotals, and layout saving. Users can freely customize column order and filters using ALV functionality.',
          'ALV can be implemented using the function module-based REUSE_ALV_GRID_DISPLAY or the object-oriented CL_SALV_TABLE class. CL_SALV_TABLE provides a simpler implementation and is recommended for new development. ALV requires a field catalog (column definitions), which can be auto-generated by referencing a Data Dictionary structure.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What does ALV stand for?',
            choices: ['Advanced List View', 'ABAP List Viewer', 'Application List View', 'ABAP Layout Viewer'],
            correctIndex: 1,
            explanation: 'ALV stands for ABAP List Viewer. It is SAP\'s standard data list display feature, providing built-in sorting, filtering, and other features.',
          },
          {
            type: 'ox',
            question: 'ALV allows users to freely customize column order and filters.',
            correct: true,
            explanation: 'Correct. ALV provides built-in features for sorting, filtering, showing/hiding columns, and saving layouts, all customizable by users.',
          },
          {
            type: 'four-choice',
            question: 'What is the mechanism called that defines ALV display columns?',
            choices: ['Screen Painter', 'Field Catalog', 'Menu Painter', 'Layout Manager'],
            correctIndex: 1,
            explanation: 'The Field Catalog defines ALV display columns (column name, display text, data type, display width, etc.). It can be auto-generated by referencing a Data Dictionary structure.',
          },
          {
            type: 'four-choice',
            question: 'Which class is recommended for ALV output in new development?',
            choices: ['CL_GUI_ALV_GRID', 'CL_SALV_TABLE', 'REUSE_ALV_GRID_DISPLAY', 'CL_ALV_DISPLAY'],
            correctIndex: 1,
            explanation: 'CL_SALV_TABLE provides a simple interface for ALV output and is recommended for new development. REUSE_ALV_GRID_DISPLAY is the older function module-based approach.',
          },
          {
            type: 'ox',
            question: 'REUSE_ALV_GRID_DISPLAY is a class-based ALV implementation.',
            correct: false,
            explanation: 'Incorrect. REUSE_ALV_GRID_DISPLAY is a function module-based ALV implementation. Class-based options include CL_SALV_TABLE and CL_GUI_ALV_GRID.',
          },
          {
            type: 'ordering',
            question: 'Arrange the implementation steps for displaying ALV using CL_SALV_TABLE.',
            items: ['Retrieve data into internal table', 'Create instance with CL_SALV_TABLE=>FACTORY', 'Customize display settings', 'Call DISPLAY method'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'First retrieve data into an internal table, create an ALV instance with the FACTORY method, customize column display settings, then call the DISPLAY method to show it on screen.',
          },
        ],
      },
      {
        id: 'abap-data-dictionary',
        title: 'Data Dictionary',
        content: [
          'The Data Dictionary (DDIC / transaction code SE11) is SAP\'s metadata management tool. It defines and manages tables, views, data types, search helps, and lock objects. ABAP programs can directly reference types and tables defined here.',
          'Tables defined in the Data Dictionary include transparent tables, cluster tables, and pool tables. Transparent tables are the most common type, where a corresponding table is created 1:1 in the database. Data Elements define the semantic meaning of fields (labels, help text), while Domains define technical attributes (data type, length, value range).',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What is the transaction code for the Data Dictionary?',
            choices: ['SE38', 'SE37', 'SE11', 'SE80'],
            correctIndex: 2,
            explanation: 'SE11 is the transaction code for the Data Dictionary (ABAP Dictionary), used for defining and managing tables, data types, search helps, etc.',
          },
          {
            type: 'four-choice',
            question: 'Which table type creates a 1:1 corresponding table in the database?',
            choices: ['Cluster table', 'Pool table', 'Transparent table', 'Internal table'],
            correctIndex: 2,
            explanation: 'A Transparent Table creates a table with the same structure 1:1 in the database and is the most common table type. Internal tables are temporary tables within ABAP programs and are not stored in the database.',
          },
          {
            type: 'ox',
            question: 'A Domain defines the semantic information of fields such as labels and help text.',
            correct: false,
            explanation: 'Incorrect. A Domain defines technical attributes such as data type, length, and value range. Semantic information like labels and help text is defined by Data Elements.',
          },
          {
            type: 'four-choice',
            question: 'What is the correct relationship between Data Elements and Domains?',
            choices: ['Data Elements belong to Domains', 'Domains belong to Data Elements', 'Data Elements reference Domains to inherit technical attributes', 'They are unrelated'],
            correctIndex: 2,
            explanation: 'Data Elements reference Domains and inherit their technical attributes (data type, length, etc.). Data Elements themselves define the semantic meaning of fields (labels, documentation).',
          },
          {
            type: 'ox',
            question: 'Search Helps are defined in the Data Dictionary.',
            correct: true,
            explanation: 'Correct. Search Helps are defined in SE11 and provide a value list displayed when the user presses F4 on an input field.',
          },
          {
            type: 'four-choice',
            question: 'Which Data Dictionary object is used to prevent data inconsistencies from concurrent updates?',
            choices: ['Search Help', 'View', 'Lock Object', 'Table Type'],
            correctIndex: 2,
            explanation: 'Lock Objects control concurrent access by multiple users. They are defined in SE11 and used via automatically generated ENQUEUE/DEQUEUE function modules.',
          },
        ],
      },
      {
        id: 'abap-debugging-error',
        title: 'Debugging and Error Handling',
        content: [
          'The ABAP Debugger is a tool for tracing program execution step by step, examining variable values and program flow. It can be activated by entering /h in the ABAP Editor or execution screen, or by writing BREAK-POINT in the source code. The debugger supports Step Into (F5), Step Over (F6), Step Out (F7), and Continue (F8) for controlling execution.',
          'ABAP error handling includes TRY~CATCH~ENDTRY exception handling. Class-based exceptions use exception classes starting with CX_, and RAISE EXCEPTION triggers them. ABAP short dumps (runtime errors) can be viewed in transaction ST22. The MESSAGE statement displays messages to users with types: E (Error), W (Warning), I (Information), S (Status), and A (Abort).',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction code is used to view ABAP short dumps (runtime errors)?',
            choices: ['SM21', 'ST22', 'SM37', 'SE38'],
            correctIndex: 1,
            explanation: 'ST22 is the transaction code for viewing ABAP runtime errors (short dumps). It provides detailed error information, the error location, and variable values.',
          },
          {
            type: 'four-choice',
            question: 'Which debugger action advances to the next line without entering subroutines or methods?',
            choices: ['F5 (Step Into)', 'F6 (Step Over)', 'F7 (Step Out)', 'F8 (Continue)'],
            correctIndex: 1,
            explanation: 'F6 (Step Over) advances to the next line without entering subroutines or methods. F5 enters them, F7 exits the current routine, and F8 continues execution until the next breakpoint.',
          },
          {
            type: 'ox',
            question: 'ABAP supports TRY~CATCH~ENDTRY exception handling.',
            correct: true,
            explanation: 'Correct. Class-based exception handling using TRY~CATCH~ENDTRY syntax is supported. The CATCH clause specifies exception classes starting with CX_ to catch exceptions.',
          },
          {
            type: 'four-choice',
            question: 'Which message type displays an error message in the MESSAGE statement?',
            choices: ['TYPE W', 'TYPE I', 'TYPE E', 'TYPE S'],
            correctIndex: 2,
            explanation: 'TYPE E displays an error message, interrupting processing and requiring user correction. W is warning, I is information (popup), and S is status bar display.',
          },
          {
            type: 'ox',
            question: 'Entering /h in the command field activates the debugger.',
            correct: true,
            explanation: 'Correct. /h is a system command that enables debug mode. The debugger will activate the next time an action is executed.',
          },
          {
            type: 'four-choice',
            question: 'What prefix do ABAP exception class names start with?',
            choices: ['EX_', 'CX_', 'ZX_', 'CL_'],
            correctIndex: 1,
            explanation: 'Standard ABAP exception classes start with CX_ (e.g., CX_SY_ZERO_DIVIDE). Custom exception classes also start with CX_ or use customer namespaces like ZCX_ or YCX_. CL_ is the prefix for regular classes.',
          },
        ],
      },
    ],
  },
};
