import type { ModuleContent } from '../learning-types';

export const basis: Record<'ja' | 'en', ModuleContent> = {
  ja: {
    id: 'basis',
    title: 'Basis（システム管理）',
    description: 'SAPシステムの管理・運用の基礎を学びます',
    sections: [
      {
        id: 'basis-overview',
        title: 'SAP Basisとは',
        content: [
          'SAP Basis（ベーシス）はSAPシステムの技術基盤であり、システム管理・運用を担う領域です。Basisの担当者（Basisコンサルタント/管理者）は、SAPシステムのインストール・設定・監視・パフォーマンスチューニング・トランスポート管理・ユーザー管理など、システムの安定稼働に必要なすべての技術的業務を担当します。',
          'SAPシステムは3層アーキテクチャで構成されます。プレゼンテーション層（SAP GUIやブラウザ）、アプリケーション層（SAPアプリケーションサーバー）、データベース層（HANA、Oracle等）の3つです。Basisはこのアーキテクチャ全体を管理し、各層の連携を確保します。S/4HANAではデータベースがSAP HANAに統一されています。',
        ],
        quizzes: [
          {
            type: 'ox',
            question: 'SAP Basisはシステムの技術基盤であり、インストール・監視・パフォーマンスチューニングなどの技術的業務を担う。',
            correct: true,
            explanation: '正しいです。BasisはSAPシステムの安定稼働に必要な技術基盤全般を管理する領域です。',
          },
          {
            type: 'four-choice',
            question: 'SAPシステムの3層アーキテクチャに含まれないものはどれか。',
            choices: ['プレゼンテーション層', 'アプリケーション層', 'データベース層', 'ネットワーク層'],
            correctIndex: 3,
            explanation: 'SAPの3層アーキテクチャはプレゼンテーション層・アプリケーション層・データベース層で構成されます。ネットワークはインフラとして重要ですが、SAPの3層には含まれません。',
          },
          {
            type: 'four-choice',
            question: 'S/4HANAで使用されるデータベースはどれか。',
            choices: ['Oracle', 'SQL Server', 'SAP HANA', 'DB2'],
            correctIndex: 2,
            explanation: 'S/4HANAではデータベースがSAP HANAに統一されています。従来のSAP ECCでは複数のデータベースをサポートしていました。',
          },
          {
            type: 'ox',
            question: 'SAP GUIはSAPの3層アーキテクチャにおけるアプリケーション層に位置する。',
            correct: false,
            explanation: '不正解です。SAP GUIはプレゼンテーション層（クライアント層）に位置します。ユーザーインターフェースを提供し、アプリケーションサーバーと通信します。',
          },
          {
            type: 'four-choice',
            question: 'SAPアプリケーションサーバーの役割として正しいものはどれか。',
            choices: ['データの永続化のみ', '画面の表示のみ', 'ビジネスロジックの実行とデータベースとの通信', 'ネットワーク通信の管理のみ'],
            correctIndex: 2,
            explanation: 'アプリケーションサーバーはABAPプログラムの実行（ビジネスロジック）とデータベースとの通信を担当します。プレゼンテーション層からのリクエストを処理し、データベース層にアクセスします。',
          },
          {
            type: 'ordering',
            question: 'SAP 3層アーキテクチャをユーザーに近い順に並べてください。',
            items: ['プレゼンテーション層', 'アプリケーション層', 'データベース層'],
            correctOrder: [0, 1, 2],
            explanation: 'ユーザーはプレゼンテーション層（SAP GUI等）を操作し、リクエストがアプリケーション層で処理され、データベース層でデータが読み書きされます。',
          },
        ],
      },
      {
        id: 'basis-client-system-landscape',
        title: 'クライアントとシステムランドスケープ',
        content: [
          'SAPのクライアント（Client）は、同一システム内でデータを論理的に分離する単位です。クライアント番号（000〜999）で識別され、マスタデータやトランザクションデータはクライアント単位で管理されます。クライアント000はSAPの初期設定が格納されたリファレンスクライアントです。',
          'システムランドスケープとは、開発（DEV）・品質保証/テスト（QAS）・本番（PRD）の3環境構成が一般的です。開発環境で変更を行い、テスト環境で検証し、本番環境へリリースするという流れで品質を確保します。環境間の変更移送にはトランスポート管理システム（TMS）を使用します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'SAPの初期設定が格納されたリファレンスクライアントはどれか。',
            choices: ['000', '001', '100', '800'],
            correctIndex: 0,
            explanation: 'クライアント000はSAPの初期設定が格納されたリファレンスクライアントです。直接変更は推奨されず、カスタマイズ作業は別のクライアント（001や100など）で行います。',
          },
          {
            type: 'ox',
            question: 'SAPのクライアントは、同一システム内でデータを論理的に分離する単位である。',
            correct: true,
            explanation: '正しいです。各クライアントはマスタデータやトランザクションデータを独立して管理します。クライアント間でのデータ参照は基本的にできません。',
          },
          {
            type: 'four-choice',
            question: '一般的なSAPシステムランドスケープの3環境構成で含まれないものはどれか。',
            choices: ['開発環境（DEV）', 'ステージング環境（STG）', '品質保証環境（QAS）', '本番環境（PRD）'],
            correctIndex: 1,
            explanation: '一般的な3環境構成はDEV（開発）・QAS（品質保証/テスト）・PRD（本番）です。企業によってはサンドボックスやステージングを追加する場合もありますが、標準的な3環境には含まれません。',
          },
          {
            type: 'four-choice',
            question: '環境間の変更移送に使用するシステムは何か。',
            choices: ['SAP Solution Manager', 'トランスポート管理システム（TMS）', 'SAP Router', 'SAP HANA Studio'],
            correctIndex: 1,
            explanation: 'トランスポート管理システム（TMS / Transport Management System）は、開発環境からテスト環境、本番環境への変更移送を管理するシステムです。',
          },
          {
            type: 'ox',
            question: '本番環境（PRD）で直接カスタマイズ変更を行うことは推奨される。',
            correct: false,
            explanation: '不正解です。本番環境での直接変更は推奨されません。変更は必ず開発環境で行い、テスト環境で検証した上で、トランスポートにより本番環境へリリースします。',
          },
          {
            type: 'ordering',
            question: 'SAPの標準的な変更管理フローを正しい順序で並べてください。',
            items: ['開発環境で変更を作成', 'トランスポート依頼をリリース', 'テスト環境で検証', '本番環境へインポート'],
            correctOrder: [0, 1, 2, 3],
            explanation: '開発環境で変更を作成し、トランスポート依頼としてリリースし、テスト環境にインポートして検証した上で、本番環境にインポートする流れです。',
          },
        ],
      },
      {
        id: 'basis-user-auth',
        title: 'ユーザー管理と権限',
        content: [
          'SAPのユーザー管理はトランザクションSU01で行います。ユーザーマスタにはログインID・氏名・メールアドレス・有効期間・ユーザータイプなどが含まれます。ユーザータイプにはダイアログユーザー（対話型ログイン用）・システムユーザー（バックグラウンド処理やRFC通信用）・コミュニケーションユーザー・サービスユーザー・リファレンスユーザーがあります。',
          'SAP権限の仕組みは「権限オブジェクト」「権限プロファイル」「ロール」で構成されます。権限オブジェクトは特定の操作（トランザクション実行、データ参照など）のチェック項目を定義します。ロール（SU01ではなくPFCGで作成）に権限を割り当て、そのロールをユーザーに付与することでアクセス制御を行います。トランザクションPFCGはロールの作成・権限割り当てに使用されます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'SAPでユーザーの作成・変更を行うトランザクションコードはどれか。',
            choices: ['SU01', 'PFCG', 'SU10', 'SM04'],
            correctIndex: 0,
            explanation: 'SU01はユーザーマスタの作成・変更・照会を行うトランザクションコードです。PFCGはロール管理、SU10は一括ユーザー管理、SM04はログイン中ユーザーの確認に使用します。',
          },
          {
            type: 'four-choice',
            question: 'ロールの作成と権限割り当てに使用するトランザクションコードはどれか。',
            choices: ['SU01', 'PFCG', 'SU53', 'SM21'],
            correctIndex: 1,
            explanation: 'PFCG（Profile Generator）はロールの作成・権限割り当て・権限プロファイルの生成に使用します。SU53は権限エラーの確認に使用します。',
          },
          {
            type: 'ox',
            question: 'ダイアログユーザーはSAP GUIからの対話型ログインに使用されるユーザータイプである。',
            correct: true,
            explanation: '正しいです。ダイアログユーザーは対話型のログインに使用される最も一般的なユーザータイプです。パスワードの有効期限やログイン回数制限の対象となります。',
          },
          {
            type: 'four-choice',
            question: 'バックグラウンド処理やRFC通信に使用されるユーザータイプはどれか。',
            choices: ['ダイアログユーザー', 'システムユーザー', 'サービスユーザー', 'リファレンスユーザー'],
            correctIndex: 1,
            explanation: 'システムユーザーはバックグラウンドジョブの実行やRFC通信など、非対話型の処理に使用されます。ダイアログログインはできません。',
          },
          {
            type: 'four-choice',
            question: 'ユーザーが権限エラーになった際に、不足している権限を確認するトランザクションはどれか。',
            choices: ['SU01', 'PFCG', 'SU53', 'SM04'],
            correctIndex: 2,
            explanation: 'SU53は直近の権限チェックエラーの詳細（不足している権限オブジェクトと項目値）を表示します。権限エラーの調査に必須のトランザクションです。',
          },
          {
            type: 'ox',
            question: '権限はユーザーに直接割り当てるのではなく、ロールを通じて割り当てるのが推奨される。',
            correct: true,
            explanation: '正しいです。PFCGでロールを作成し、ロールに権限を割り当て、そのロールをユーザーに付与するのが標準的な権限管理方法です。これにより権限の一元管理が可能になります。',
          },
        ],
      },
      {
        id: 'basis-transport',
        title: 'トランスポート管理',
        content: [
          'トランスポート管理は、開発環境の変更を他の環境へ移送する仕組みです。開発者が変更を保存すると「トランスポート依頼（Transport Request）」に記録されます。トランスポート依頼には「ワークベンチ依頼」（リポジトリオブジェクト：ABAP、テーブル定義など）と「カスタマイジング依頼」（クライアント依存のカスタマイズ設定）の2種類があります。',
          'トランスポート依頼のライフサイクルは、作成→変更記録→リリース→インポートの順に進みます。リリース（SE09/SE10）すると変更がファイルとして書き出され、TMS（トランスポート管理システム / トランザクションSTMS）を通じてターゲット環境にインポートされます。インポートログを確認してエラーがないかチェックすることが重要です。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'ABAPプログラムやテーブル定義など、リポジトリオブジェクトの変更を記録するトランスポート依頼はどれか。',
            choices: ['カスタマイジング依頼', 'ワークベンチ依頼', 'ローカル変更依頼', 'コピー依頼'],
            correctIndex: 1,
            explanation: 'ワークベンチ依頼はABAPプログラム・テーブル定義・ファンクションモジュールなどのリポジトリオブジェクトの変更を記録します。カスタマイジング依頼はクライアント依存の設定変更を記録します。',
          },
          {
            type: 'four-choice',
            question: 'トランスポート依頼のリリースに使用するトランザクションコードはどれか。',
            choices: ['STMS', 'SE09', 'SM37', 'SE80'],
            correctIndex: 1,
            explanation: 'SE09（Transport Organizer）はトランスポート依頼の管理・リリースに使用します。SE10も同様の機能を持ちます。STMSはトランスポート管理システムで、環境間のインポートに使用します。',
          },
          {
            type: 'ox',
            question: 'トランスポート依頼をリリースすると、変更は自動的に本番環境にインポートされる。',
            correct: false,
            explanation: '不正解です。リリースすると変更がファイルとして書き出されますが、ターゲット環境へのインポートは別途STMSで行う必要があります。自動インポートを設定することは可能ですが、デフォルトでは手動です。',
          },
          {
            type: 'four-choice',
            question: 'トランスポート管理システム（TMS）のトランザクションコードはどれか。',
            choices: ['SE09', 'SE10', 'STMS', 'SCC1'],
            correctIndex: 2,
            explanation: 'STMSはトランスポート管理システムのトランザクションコードです。環境間のトランスポートルートの設定やインポートキューの管理を行います。',
          },
          {
            type: 'ox',
            question: 'カスタマイジング依頼はクライアント依存の設定変更を記録する。',
            correct: true,
            explanation: '正しいです。カスタマイジング依頼はIMGなどで行うクライアント依存の設定変更を記録します。ワークベンチ依頼はクライアント非依存のリポジトリオブジェクトの変更を記録します。',
          },
          {
            type: 'ordering',
            question: 'トランスポート依頼のライフサイクルを正しい順序で並べてください。',
            items: ['依頼を作成', '変更を記録', '依頼をリリース', 'ターゲット環境にインポート'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'まずトランスポート依頼を作成し、変更内容を記録し、リリースしてファイルに書き出し、STMSを通じてターゲット環境にインポートします。',
          },
        ],
      },
      {
        id: 'basis-background-jobs',
        title: 'バックグラウンドジョブ',
        content: [
          'バックグラウンドジョブは、ユーザーの操作なしに自動実行されるプログラムです。大量データの処理や定期的なバッチ処理に使用されます。ジョブはトランザクションSM36で定義（スケジュール）し、SM37で監視・管理します。ジョブの状態にはScheduled（予定）・Released（リリース済み）・Active（実行中）・Finished（完了）・Cancelled（異常終了）があります。',
          'ジョブの定義では、実行するプログラム（ABAPレポートやBAPIなど）のステップを指定し、開始条件（即時実行・日時指定・イベント連動・他ジョブ完了後など）を設定します。定期実行にはPeriodic Job（周期ジョブ）を設定します。ジョブクラスにはA（最優先）・B（優先）・C（通常）があり、リソース割り当てに影響します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'バックグラウンドジョブの定義（スケジュール）に使用するトランザクションコードはどれか。',
            choices: ['SM37', 'SM36', 'SM21', 'SM50'],
            correctIndex: 1,
            explanation: 'SM36はバックグラウンドジョブの定義（スケジュール設定）に使用します。SM37はジョブの監視・管理に使用します。',
          },
          {
            type: 'four-choice',
            question: 'バックグラウンドジョブの監視・管理に使用するトランザクションコードはどれか。',
            choices: ['SM36', 'SM37', 'SM50', 'SM04'],
            correctIndex: 1,
            explanation: 'SM37（Job Overview）はバックグラウンドジョブの一覧表示・ログ確認・キャンセルなどの管理に使用します。',
          },
          {
            type: 'four-choice',
            question: 'バックグラウンドジョブが異常終了した場合のステータスはどれか。',
            choices: ['Finished', 'Released', 'Cancelled', 'Active'],
            correctIndex: 2,
            explanation: 'Cancelled（異常終了）はジョブが正常に完了しなかった場合のステータスです。SM37でジョブログを確認してエラー原因を調査する必要があります。',
          },
          {
            type: 'ox',
            question: 'バックグラウンドジョブの開始条件として、別のジョブの完了後に実行する設定ができる。',
            correct: true,
            explanation: '正しいです。ジョブの開始条件には即時実行・日時指定のほか、別のジョブ完了後やイベント発生時に実行する設定が可能です。これによりジョブチェーン（連鎖実行）を構成できます。',
          },
          {
            type: 'four-choice',
            question: 'ジョブクラスで最も優先度が高いのはどれか。',
            choices: ['クラスA', 'クラスB', 'クラスC', 'クラスD'],
            correctIndex: 0,
            explanation: 'クラスAが最優先で、システムリソースが優先的に割り当てられます。クラスBは優先、クラスCは通常です。',
          },
          {
            type: 'ox',
            question: '周期ジョブ（Periodic Job）は1回実行した後に自動的に削除される。',
            correct: false,
            explanation: '不正解です。周期ジョブは設定した間隔（毎日・毎週・毎月など）で繰り返し自動実行されます。明示的に削除またはスケジュール解除しない限り継続します。',
          },
        ],
      },
      {
        id: 'basis-system-monitoring',
        title: 'システム監視',
        content: [
          'SAPシステムの安定稼働にはシステム監視が不可欠です。ワークプロセスの監視はトランザクションSM50（単一インスタンス）やSM66（全インスタンス）で行います。ワークプロセスにはダイアログ・バッチ・アップデート・エンキュー・スプールの種類があり、それぞれ異なる処理を担当します。',
          'システムログはトランザクションSM21で確認でき、システムイベントやエラーが記録されています。パフォーマンス監視にはトランザクションST02（バッファ統計）・ST03N（ワークロード統計）・ST04（データベース監視）・ST06（OS監視）などが使用されます。アラートやしきい値の設定によりシステムの異常を早期に検知できます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'ワークプロセスの状態を監視するトランザクションコードはどれか。',
            choices: ['SM04', 'SM21', 'SM50', 'SM37'],
            correctIndex: 2,
            explanation: 'SM50は単一インスタンスのワークプロセスの状態を監視するトランザクションコードです。全インスタンスを一覧で確認する場合はSM66を使用します。',
          },
          {
            type: 'four-choice',
            question: 'ダイアログ処理を担当するワークプロセスの種類はどれか。',
            choices: ['バッチワークプロセス', 'ダイアログワークプロセス', 'アップデートワークプロセス', 'エンキューワークプロセス'],
            correctIndex: 1,
            explanation: 'ダイアログワークプロセスはユーザーの対話型操作（画面表示・入力処理など）を担当します。バッチはバックグラウンドジョブ、アップデートは非同期更新、エンキューはロック管理を担当します。',
          },
          {
            type: 'four-choice',
            question: 'システムログを確認するトランザクションコードはどれか。',
            choices: ['SM50', 'SM21', 'SM37', 'ST22'],
            correctIndex: 1,
            explanation: 'SM21はシステムログ（Syslog）を確認するトランザクションコードです。システムイベント・エラー・警告などが時系列で記録されています。ST22はABAPショートダンプの確認に使用します。',
          },
          {
            type: 'ox',
            question: 'エンキューワークプロセスはデータベースのロック管理を担当する。',
            correct: true,
            explanation: '正しいです。エンキュー（Enqueue）ワークプロセスは、SAPの論理ロック（ロックオブジェクトによる排他制御）の管理を担当します。',
          },
          {
            type: 'four-choice',
            question: 'ワークロード統計の分析に使用するトランザクションコードはどれか。',
            choices: ['ST02', 'ST03N', 'ST04', 'ST06'],
            correctIndex: 1,
            explanation: 'ST03Nはワークロード統計を分析するトランザクションです。レスポンスタイム・トランザクション数・ユーザー数などの統計情報を確認できます。ST02はバッファ統計、ST04はDB監視、ST06はOS監視です。',
          },
          {
            type: 'ox',
            question: 'SM66はすべてのインスタンスのワークプロセスを一覧で確認できる。',
            correct: true,
            explanation: '正しいです。SM66はGlobal Work Process Overviewで、複数のアプリケーションサーバーインスタンスのワークプロセスを一画面で確認できます。SM50は単一インスタンスのみです。',
          },
        ],
      },
      {
        id: 'basis-spool-print',
        title: 'スプールと印刷管理',
        content: [
          'SAPのスプール（Spool）システムは、帳票やレポートの出力を管理する仕組みです。プログラムの出力はまずスプール依頼として保存され、その後プリンタへの出力依頼に変換されます。スプール管理はトランザクションSP01で行い、スプール依頼の確認・再出力・削除などが可能です。',
          'プリンタの設定はトランザクションSPADで行います。出力デバイス（論理プリンタ）を定義し、物理プリンタへのマッピングやアクセスサーバーの指定を行います。スプール管理で重要なのは、不要なスプール依頼の定期的なクリーンアップです。大量のスプール依頼が蓄積するとディスク容量を圧迫し、システムパフォーマンスに影響します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'スプール依頼の確認・管理を行うトランザクションコードはどれか。',
            choices: ['SPAD', 'SP01', 'SP02', 'SM50'],
            correctIndex: 1,
            explanation: 'SP01はスプール依頼の確認・再出力・削除を行うトランザクションコードです。SPADはプリンタ設定、SP02は自分のスプール依頼の確認に使用します。',
          },
          {
            type: 'four-choice',
            question: 'プリンタ（出力デバイス）の設定を行うトランザクションコードはどれか。',
            choices: ['SP01', 'SP02', 'SPAD', 'SM21'],
            correctIndex: 2,
            explanation: 'SPAD（Spool Administration）は出力デバイス（プリンタ）の定義・設定を行うトランザクションコードです。',
          },
          {
            type: 'ox',
            question: 'SAPの出力はまずスプール依頼として保存され、その後プリンタに出力される。',
            correct: true,
            explanation: '正しいです。プログラムの出力はまずスプール依頼（Spool Request）として保存され、その後出力依頼（Output Request）としてプリンタに送信されます。',
          },
          {
            type: 'ox',
            question: '不要なスプール依頼を放置してもシステムに影響はない。',
            correct: false,
            explanation: '不正解です。大量のスプール依頼が蓄積するとディスク容量を圧迫し、スプールテーブル（TSP01等）が肥大化してパフォーマンスに影響します。定期的なクリーンアップが重要です。',
          },
          {
            type: 'four-choice',
            question: 'SP02の用途として正しいものはどれか。',
            choices: ['プリンタの設定', '全ユーザーのスプール管理', '自分のスプール依頼の確認', 'スプールジョブのスケジュール'],
            correctIndex: 2,
            explanation: 'SP02は自分（ログインユーザー）のスプール依頼を確認・再出力するためのトランザクションです。SP01は管理者向けの全体管理に使用します。',
          },
          {
            type: 'ordering',
            question: 'SAP出力処理の流れを正しい順序で並べてください。',
            items: ['プログラムが出力を生成', 'スプール依頼として保存', '出力依頼が作成される', 'プリンタに送信'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'プログラムの出力がスプール依頼として保存され、出力依頼に変換された後、プリンタに送信されます。',
          },
        ],
      },
      {
        id: 'basis-system-update',
        title: 'システム更新とパッチ管理',
        content: [
          'SAPシステムの保守には、サポートパッケージ（Support Package）とSAPノート（SAP Note）の適用があります。サポートパッケージは複数の修正を含む定期的な更新パッケージで、トランザクションSPAM（Support Package Manager）で適用します。SAPノートは個別の問題修正や機能改善で、トランザクションSNOTE（Note Assistant）で適用します。',
          'カーネルはSAPシステムの実行エンジンであり、OSレベルで動作します。カーネルのアップデートはSAPシステムの安定性とセキュリティに重要で、SAPのサポートサイトからダウンロードしてOS上で差し替えます。システム更新はまずテスト環境で検証してから本番環境に適用するのが鉄則です。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'サポートパッケージの適用に使用するトランザクションコードはどれか。',
            choices: ['SNOTE', 'SPAM', 'STMS', 'SE38'],
            correctIndex: 1,
            explanation: 'SPAM（Support Package Manager）はサポートパッケージの適用に使用するトランザクションコードです。SNOTEは個別のSAPノートの適用に使用します。',
          },
          {
            type: 'four-choice',
            question: '個別のSAPノートの適用に使用するトランザクションコードはどれか。',
            choices: ['SPAM', 'SNOTE', 'STMS', 'SU01'],
            correctIndex: 1,
            explanation: 'SNOTE（Note Assistant）は個別のSAPノートの確認・適用・管理に使用するトランザクションコードです。',
          },
          {
            type: 'ox',
            question: 'SAPノートは複数の修正を含む定期的な更新パッケージである。',
            correct: false,
            explanation: '不正解です。複数の修正を含む定期的な更新パッケージはサポートパッケージです。SAPノートは個別の問題修正や機能改善を提供します。',
          },
          {
            type: 'ox',
            question: 'サポートパッケージは本番環境に直接適用する前に、テスト環境で検証すべきである。',
            correct: true,
            explanation: '正しいです。システム更新はまずテスト環境で検証し、問題がないことを確認してから本番環境に適用するのが鉄則です。',
          },
          {
            type: 'four-choice',
            question: 'SAPカーネルの説明として正しいものはどれか。',
            choices: ['ABAPプログラムの一種', 'SAPシステムのOSレベルの実行エンジン', 'データベースの管理ツール', 'ユーザーインターフェースのフレームワーク'],
            correctIndex: 1,
            explanation: 'カーネルはSAPシステムの実行エンジンで、OSレベルで動作します。ABAPプログラムの実行環境や通信処理などを担います。',
          },
          {
            type: 'four-choice',
            question: 'カーネルのアップデート方法として正しいものはどれか。',
            choices: ['SPAMで適用する', 'SNOTEで適用する', 'SAPサポートサイトからダウンロードしてOS上で差し替える', 'STMSでトランスポートする'],
            correctIndex: 2,
            explanation: 'カーネルはOSレベルのファイルであるため、SAPのサポートサイト（SAP for Me等）からダウンロードし、OS上で実行ファイルを差し替えます。SPAMやSTMSでは適用できません。',
          },
        ],
      },
      {
        id: 'basis-performance',
        title: 'パフォーマンス管理',
        content: [
          'SAPシステムのパフォーマンス問題の主な原因には、非効率なABAPプログラム・メモリ不足・データベースのボトルネック・ワークプロセス不足などがあります。パフォーマンス分析にはST03N（ワークロード統計）が入り口となり、応答時間の内訳（CPU時間・DB時間・ネットワーク時間など）を確認します。',
          'データベース関連のパフォーマンスにはST04（データベースモニタ）やST05（SQLトレース）を使用します。ST05では特定のプログラムやトランザクションが発行するSQL文を記録・分析でき、非効率なSQLの特定に役立ちます。メモリ管理にはST02（バッファ統計）でSAPバッファのヒット率やスワップ状況を確認し、必要に応じてパラメータを調整します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'SQLトレースの記録・分析に使用するトランザクションコードはどれか。',
            choices: ['ST02', 'ST03N', 'ST04', 'ST05'],
            correctIndex: 3,
            explanation: 'ST05（Performance Trace）はSQLトレース・バッファトレースなどの記録・分析に使用します。SQL文の実行時間や実行回数を確認でき、パフォーマンス改善に役立ちます。',
          },
          {
            type: 'four-choice',
            question: 'SAPバッファの統計情報を確認するトランザクションコードはどれか。',
            choices: ['ST02', 'ST03N', 'ST04', 'ST05'],
            correctIndex: 0,
            explanation: 'ST02はSAPバッファの統計情報（ヒット率・使用量・スワップ数など）を確認するトランザクションです。バッファのヒット率が低い場合はパラメータ調整が必要になることがあります。',
          },
          {
            type: 'ox',
            question: 'ST03Nではトランザクションごとの平均応答時間を確認できる。',
            correct: true,
            explanation: '正しいです。ST03N（Workload Analysis）ではトランザクションごとの応答時間・実行回数・DB時間・CPU時間などの統計を確認でき、パフォーマンス分析の入り口として使用されます。',
          },
          {
            type: 'four-choice',
            question: 'データベース監視に使用するトランザクションコードはどれか。',
            choices: ['ST02', 'ST03N', 'ST04', 'SM50'],
            correctIndex: 2,
            explanation: 'ST04はデータベースモニタで、データベースのパフォーマンス統計（キャッシュヒット率・SQLの実行状況など）を確認します。',
          },
          {
            type: 'ox',
            question: 'パフォーマンス問題の原因は常にデータベースにある。',
            correct: false,
            explanation: '不正解です。パフォーマンス問題の原因は多岐にわたります。非効率なABAPプログラム・メモリ不足・ワークプロセス不足・ネットワーク遅延など、様々な要因があります。ST03Nで応答時間の内訳を確認してボトルネックを特定します。',
          },
          {
            type: 'ordering',
            question: 'パフォーマンス問題の一般的な調査手順を並べてください。',
            items: ['ST03Nで応答時間の内訳を確認', 'ボトルネック箇所を特定', '詳細トレース（ST05等）で原因調査', '対策を実施・検証'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'まずST03Nで全体像を把握し、ボトルネックがDB・CPU・メモリのどこにあるか特定し、ST05等の詳細ツールで原因を調査し、対策を実施します。',
          },
        ],
      },
      {
        id: 'basis-security',
        title: 'セキュリティ管理',
        content: [
          'SAP Basisにおけるセキュリティ管理は、ユーザー認証・権限管理・通信セキュリティ・監査ログなど多岐にわたります。パスワードポリシーはプロファイルパラメータ（login/min_password_lengthなど）で設定し、パスワードの最小長・有効期限・複雑さなどを制御します。トランザクションRZ10でインスタンスプロファイルを管理します。',
          '監査ログ（セキュリティ監査ログ）はトランザクションSM19で設定し、SM20で表示します。ユーザーのログイン・ログアウト・トランザクション実行・権限チェック失敗などのイベントを記録できます。SNC（Secure Network Communications）やSSLにより通信の暗号化を設定でき、SAP GUIとサーバー間やRFC通信の安全性を確保します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '監査ログの設定に使用するトランザクションコードはどれか。',
            choices: ['SM20', 'SM19', 'SM21', 'SM04'],
            correctIndex: 1,
            explanation: 'SM19でセキュリティ監査ログの設定（記録するイベントの選択など）を行います。SM20は監査ログの表示に使用します。SM21はシステムログです。',
          },
          {
            type: 'four-choice',
            question: '監査ログの表示に使用するトランザクションコードはどれか。',
            choices: ['SM19', 'SM20', 'SM21', 'SM37'],
            correctIndex: 1,
            explanation: 'SM20は記録された監査ログの表示・分析に使用します。SM19は監査ログの設定に使用します。',
          },
          {
            type: 'four-choice',
            question: 'インスタンスプロファイルの管理に使用するトランザクションコードはどれか。',
            choices: ['SM50', 'SM21', 'RZ10', 'PFCG'],
            correctIndex: 2,
            explanation: 'RZ10はSAPインスタンスプロファイルパラメータの表示・編集に使用します。パスワードポリシーやメモリ設定などのシステムパラメータを管理します。',
          },
          {
            type: 'ox',
            question: 'SNCはSAP GUIとサーバー間の通信を暗号化する仕組みである。',
            correct: true,
            explanation: '正しいです。SNC（Secure Network Communications）はSAP GUIとアプリケーションサーバー間やサーバー間のRFC通信を暗号化し、認証の強化も提供します。',
          },
          {
            type: 'ox',
            question: 'パスワードポリシーはABAPプログラムでのみ設定できる。',
            correct: false,
            explanation: '不正解です。パスワードポリシーはプロファイルパラメータ（login/min_password_lengthなど）で設定します。RZ10でインスタンスプロファイルを編集するか、RZ11で個別パラメータを変更します。',
          },
          {
            type: 'four-choice',
            question: '監査ログで記録できるイベントとして適切でないものはどれか。',
            choices: ['ユーザーのログイン', 'トランザクションの実行', 'プログラムのソースコード変更履歴', '権限チェックの失敗'],
            correctIndex: 2,
            explanation: 'プログラムのソースコード変更履歴はバージョン管理（SE38のバージョン管理機能やトランスポート履歴）で管理されます。監査ログはログイン・トランザクション実行・権限チェック失敗などのランタイムイベントを記録します。',
          },
        ],
      },
    ],
  },
  en: {
    id: 'basis',
    title: 'Basis (System Administration)',
    description: 'Learn the fundamentals of SAP system administration and operations',
    sections: [
      {
        id: 'basis-overview',
        title: 'What is SAP Basis?',
        content: [
          'SAP Basis is the technical foundation of SAP systems, covering system administration and operations. Basis administrators handle all technical tasks required for stable system operation, including installation, configuration, monitoring, performance tuning, transport management, and user management.',
          'SAP systems use a three-tier architecture: Presentation layer (SAP GUI or browser), Application layer (SAP Application Server), and Database layer (HANA, Oracle, etc.). Basis manages this entire architecture and ensures coordination between layers. In S/4HANA, the database is standardized to SAP HANA.',
        ],
        quizzes: [
          {
            type: 'ox',
            question: 'SAP Basis is the technical foundation of SAP systems, covering installation, monitoring, and performance tuning.',
            correct: true,
            explanation: 'Correct. Basis manages all technical infrastructure required for stable SAP system operation.',
          },
          {
            type: 'four-choice',
            question: 'Which is NOT part of the SAP three-tier architecture?',
            choices: ['Presentation layer', 'Application layer', 'Database layer', 'Network layer'],
            correctIndex: 3,
            explanation: 'SAP\'s three-tier architecture consists of the Presentation, Application, and Database layers. While networking is important infrastructure, it is not part of the SAP three-tier model.',
          },
          {
            type: 'four-choice',
            question: 'Which database is used in S/4HANA?',
            choices: ['Oracle', 'SQL Server', 'SAP HANA', 'DB2'],
            correctIndex: 2,
            explanation: 'S/4HANA exclusively uses SAP HANA as its database. Traditional SAP ECC supported multiple databases.',
          },
          {
            type: 'ox',
            question: 'SAP GUI belongs to the Application layer in the three-tier architecture.',
            correct: false,
            explanation: 'Incorrect. SAP GUI belongs to the Presentation layer (client layer), providing the user interface and communicating with the Application Server.',
          },
          {
            type: 'four-choice',
            question: 'What is the role of the SAP Application Server?',
            choices: ['Data persistence only', 'Screen display only', 'Business logic execution and database communication', 'Network communication management only'],
            correctIndex: 2,
            explanation: 'The Application Server executes ABAP programs (business logic) and communicates with the database. It processes requests from the Presentation layer and accesses the Database layer.',
          },
          {
            type: 'ordering',
            question: 'Arrange the SAP three-tier architecture from closest to the user.',
            items: ['Presentation layer', 'Application layer', 'Database layer'],
            correctOrder: [0, 1, 2],
            explanation: 'Users interact with the Presentation layer (SAP GUI, etc.), requests are processed by the Application layer, and data is read/written in the Database layer.',
          },
        ],
      },
      {
        id: 'basis-client-system-landscape',
        title: 'Clients and System Landscape',
        content: [
          'A SAP Client is a logical unit for data separation within the same system. Identified by a client number (000-999), master data and transaction data are managed per client. Client 000 is the reference client containing SAP initial settings.',
          'A System Landscape typically consists of three environments: Development (DEV), Quality Assurance/Test (QAS), and Production (PRD). Changes are made in development, verified in test, and released to production to ensure quality. The Transport Management System (TMS) is used to move changes between environments.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which client number is the SAP reference client containing initial settings?',
            choices: ['000', '001', '100', '800'],
            correctIndex: 0,
            explanation: 'Client 000 is the reference client containing SAP initial settings. Direct modifications are not recommended; customization should be done in other clients (e.g., 001, 100).',
          },
          {
            type: 'ox',
            question: 'A SAP Client is a logical unit for data separation within the same system.',
            correct: true,
            explanation: 'Correct. Each client manages master data and transaction data independently. Cross-client data access is generally not possible.',
          },
          {
            type: 'four-choice',
            question: 'Which environment is NOT part of the standard three-environment SAP system landscape?',
            choices: ['Development (DEV)', 'Staging (STG)', 'Quality Assurance (QAS)', 'Production (PRD)'],
            correctIndex: 1,
            explanation: 'The standard three-environment landscape consists of DEV, QAS, and PRD. Some organizations add sandbox or staging environments, but they are not part of the standard three.',
          },
          {
            type: 'four-choice',
            question: 'Which system is used to move changes between environments?',
            choices: ['SAP Solution Manager', 'Transport Management System (TMS)', 'SAP Router', 'SAP HANA Studio'],
            correctIndex: 1,
            explanation: 'The Transport Management System (TMS) manages the transport of changes from development to test and production environments.',
          },
          {
            type: 'ox',
            question: 'Making customization changes directly in the production environment (PRD) is recommended.',
            correct: false,
            explanation: 'Incorrect. Direct changes in production are not recommended. Changes must be made in development, verified in test, and then released to production via transport.',
          },
          {
            type: 'ordering',
            question: 'Arrange the standard SAP change management flow in the correct order.',
            items: ['Create changes in development', 'Release transport request', 'Verify in test environment', 'Import to production'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'Create changes in development, release as a transport request, import to test for verification, then import to production.',
          },
        ],
      },
      {
        id: 'basis-user-auth',
        title: 'User Management and Authorization',
        content: [
          'SAP user management is performed via transaction SU01. User master records include login ID, name, email, validity period, and user type. User types include Dialog (interactive login), System (background processing and RFC), Communication, Service, and Reference users.',
          'SAP authorization is structured around authorization objects, authorization profiles, and roles. Authorization objects define check fields for specific operations (transaction execution, data access, etc.). Roles (created in PFCG) are assigned authorizations, then assigned to users for access control. Transaction PFCG is used for role creation and authorization assignment.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction code is used to create and modify SAP users?',
            choices: ['SU01', 'PFCG', 'SU10', 'SM04'],
            correctIndex: 0,
            explanation: 'SU01 is used for creating, modifying, and displaying user master records. PFCG is for role management, SU10 for mass user management, and SM04 for viewing logged-in users.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used for role creation and authorization assignment?',
            choices: ['SU01', 'PFCG', 'SU53', 'SM21'],
            correctIndex: 1,
            explanation: 'PFCG (Profile Generator) is used for creating roles, assigning authorizations, and generating authorization profiles. SU53 is used for checking authorization errors.',
          },
          {
            type: 'ox',
            question: 'A Dialog user is the user type used for interactive login via SAP GUI.',
            correct: true,
            explanation: 'Correct. Dialog users are the most common user type, used for interactive login. They are subject to password expiration and login attempt restrictions.',
          },
          {
            type: 'four-choice',
            question: 'Which user type is used for background processing and RFC communication?',
            choices: ['Dialog user', 'System user', 'Service user', 'Reference user'],
            correctIndex: 1,
            explanation: 'System users are used for non-interactive processing such as background jobs and RFC communication. They cannot perform dialog login.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction checks the details of a recent authorization failure?',
            choices: ['SU01', 'PFCG', 'SU53', 'SM04'],
            correctIndex: 2,
            explanation: 'SU53 displays details of the most recent authorization check failure (missing authorization objects and field values). It is essential for investigating authorization errors.',
          },
          {
            type: 'ox',
            question: 'It is recommended to assign authorizations to users through roles rather than directly.',
            correct: true,
            explanation: 'Correct. The standard approach is to create roles in PFCG, assign authorizations to roles, and then assign roles to users. This enables centralized authorization management.',
          },
        ],
      },
      {
        id: 'basis-transport',
        title: 'Transport Management',
        content: [
          'Transport management is the mechanism for moving development changes to other environments. When developers save changes, they are recorded in Transport Requests. There are two types: Workbench Requests (for repository objects like ABAP programs and table definitions) and Customizing Requests (for client-dependent customization settings).',
          'The transport request lifecycle follows: creation → change recording → release → import. Releasing (SE09/SE10) writes changes to files, which are then imported to target environments via TMS (Transport Management System / transaction STMS). Checking import logs for errors is critical.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which type of transport request records changes to repository objects like ABAP programs and table definitions?',
            choices: ['Customizing Request', 'Workbench Request', 'Local Change Request', 'Copy Request'],
            correctIndex: 1,
            explanation: 'Workbench Requests record changes to repository objects (ABAP programs, table definitions, function modules, etc.). Customizing Requests record client-dependent configuration changes.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used to release transport requests?',
            choices: ['STMS', 'SE09', 'SM37', 'SE80'],
            correctIndex: 1,
            explanation: 'SE09 (Transport Organizer) is used for managing and releasing transport requests. SE10 provides similar functionality. STMS is the Transport Management System for importing between environments.',
          },
          {
            type: 'ox',
            question: 'Releasing a transport request automatically imports changes to the production environment.',
            correct: false,
            explanation: 'Incorrect. Releasing writes changes to files, but importing to target environments must be done separately via STMS. Automatic import can be configured but is not the default.',
          },
          {
            type: 'four-choice',
            question: 'What is the transaction code for the Transport Management System (TMS)?',
            choices: ['SE09', 'SE10', 'STMS', 'SCC1'],
            correctIndex: 2,
            explanation: 'STMS is the transaction code for the Transport Management System, used for configuring transport routes and managing import queues.',
          },
          {
            type: 'ox',
            question: 'Customizing Requests record client-dependent configuration changes.',
            correct: true,
            explanation: 'Correct. Customizing Requests record client-dependent configuration changes made in IMG and similar tools. Workbench Requests record client-independent repository object changes.',
          },
          {
            type: 'ordering',
            question: 'Arrange the transport request lifecycle in the correct order.',
            items: ['Create request', 'Record changes', 'Release request', 'Import to target environment'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'First create a transport request, record changes, release to write to files, then import to the target environment via STMS.',
          },
        ],
      },
      {
        id: 'basis-background-jobs',
        title: 'Background Jobs',
        content: [
          'Background jobs are programs that run automatically without user interaction. They are used for large data processing and scheduled batch operations. Jobs are defined (scheduled) in transaction SM36 and monitored/managed in SM37. Job statuses include Scheduled, Released, Active, Finished, and Cancelled.',
          'Job definitions specify program steps to execute (ABAP reports, BAPIs, etc.) and start conditions (immediate, date/time, event-triggered, after another job completes). Periodic Jobs run on a recurring schedule. Job classes A (highest priority), B (priority), and C (normal) affect resource allocation.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction code is used to define (schedule) background jobs?',
            choices: ['SM37', 'SM36', 'SM21', 'SM50'],
            correctIndex: 1,
            explanation: 'SM36 is used for defining and scheduling background jobs. SM37 is used for monitoring and managing jobs.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used to monitor and manage background jobs?',
            choices: ['SM36', 'SM37', 'SM50', 'SM04'],
            correctIndex: 1,
            explanation: 'SM37 (Job Overview) is used for listing, viewing logs, and managing background jobs.',
          },
          {
            type: 'four-choice',
            question: 'What is the status when a background job terminates abnormally?',
            choices: ['Finished', 'Released', 'Cancelled', 'Active'],
            correctIndex: 2,
            explanation: 'Cancelled indicates a job did not complete successfully. The job log in SM37 should be checked to investigate the error cause.',
          },
          {
            type: 'ox',
            question: 'Background jobs can be configured to start after another job completes.',
            correct: true,
            explanation: 'Correct. Job start conditions include immediate, date/time-based, event-triggered, and after-job-completion options, enabling job chains.',
          },
          {
            type: 'four-choice',
            question: 'Which job class has the highest priority?',
            choices: ['Class A', 'Class B', 'Class C', 'Class D'],
            correctIndex: 0,
            explanation: 'Class A has the highest priority with preferential system resource allocation. Class B is priority, and Class C is normal.',
          },
          {
            type: 'ox',
            question: 'A Periodic Job is automatically deleted after running once.',
            correct: false,
            explanation: 'Incorrect. Periodic Jobs run repeatedly at configured intervals (daily, weekly, monthly, etc.) and continue until explicitly deleted or unscheduled.',
          },
        ],
      },
      {
        id: 'basis-system-monitoring',
        title: 'System Monitoring',
        content: [
          'System monitoring is essential for stable SAP operation. Work process monitoring is performed via transaction SM50 (single instance) or SM66 (all instances). Work process types include Dialog, Batch, Update, Enqueue, and Spool, each handling different processing.',
          'The System Log is viewed via transaction SM21, recording system events and errors. Performance monitoring uses ST02 (buffer statistics), ST03N (workload statistics), ST04 (database monitoring), and ST06 (OS monitoring). Alert configuration enables early detection of system anomalies.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction code monitors work process status?',
            choices: ['SM04', 'SM21', 'SM50', 'SM37'],
            correctIndex: 2,
            explanation: 'SM50 monitors work process status for a single instance. SM66 provides an overview across all instances.',
          },
          {
            type: 'four-choice',
            question: 'Which work process type handles interactive user operations?',
            choices: ['Batch work process', 'Dialog work process', 'Update work process', 'Enqueue work process'],
            correctIndex: 1,
            explanation: 'Dialog work processes handle interactive user operations (screen display, input processing). Batch handles background jobs, Update handles asynchronous updates, and Enqueue handles lock management.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used to view the System Log?',
            choices: ['SM50', 'SM21', 'SM37', 'ST22'],
            correctIndex: 1,
            explanation: 'SM21 displays the System Log (Syslog), which records system events, errors, and warnings chronologically. ST22 is used for ABAP short dump analysis.',
          },
          {
            type: 'ox',
            question: 'The Enqueue work process handles database lock management.',
            correct: true,
            explanation: 'Correct. The Enqueue work process manages SAP logical locks (exclusive control via lock objects).',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used for workload analysis?',
            choices: ['ST02', 'ST03N', 'ST04', 'ST06'],
            correctIndex: 1,
            explanation: 'ST03N analyzes workload statistics including response times, transaction counts, and user counts. ST02 is for buffer statistics, ST04 for DB monitoring, and ST06 for OS monitoring.',
          },
          {
            type: 'ox',
            question: 'SM66 can display work processes across all instances in a single view.',
            correct: true,
            explanation: 'Correct. SM66 (Global Work Process Overview) displays work processes from multiple application server instances in one screen. SM50 only shows a single instance.',
          },
        ],
      },
      {
        id: 'basis-spool-print',
        title: 'Spool and Print Management',
        content: [
          'The SAP Spool system manages report and form output. Program output is first saved as a spool request, then converted to an output request for printer delivery. Spool management is performed via transaction SP01 for viewing, reprinting, and deleting spool requests.',
          'Printer configuration uses transaction SPAD, where output devices (logical printers) are defined and mapped to physical printers. Regular cleanup of unnecessary spool requests is important, as accumulated requests consume disk space and impact system performance.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction code is used to view and manage spool requests?',
            choices: ['SPAD', 'SP01', 'SP02', 'SM50'],
            correctIndex: 1,
            explanation: 'SP01 is used for viewing, reprinting, and deleting spool requests. SPAD is for printer configuration, and SP02 is for viewing your own spool requests.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used for printer (output device) configuration?',
            choices: ['SP01', 'SP02', 'SPAD', 'SM21'],
            correctIndex: 2,
            explanation: 'SPAD (Spool Administration) is used for defining and configuring output devices (printers).',
          },
          {
            type: 'ox',
            question: 'SAP output is first saved as a spool request before being sent to a printer.',
            correct: true,
            explanation: 'Correct. Program output is first saved as a Spool Request, then converted to an Output Request for delivery to the printer.',
          },
          {
            type: 'ox',
            question: 'Leaving unnecessary spool requests has no impact on the system.',
            correct: false,
            explanation: 'Incorrect. Accumulated spool requests consume disk space and cause spool tables (TSP01, etc.) to grow, impacting performance. Regular cleanup is important.',
          },
          {
            type: 'four-choice',
            question: 'What is the purpose of SP02?',
            choices: ['Printer configuration', 'Managing all users\' spool requests', 'Viewing your own spool requests', 'Scheduling spool jobs'],
            correctIndex: 2,
            explanation: 'SP02 is for viewing and reprinting your own (logged-in user\'s) spool requests. SP01 is for administrator-level overall management.',
          },
          {
            type: 'ordering',
            question: 'Arrange the SAP output processing flow in the correct order.',
            items: ['Program generates output', 'Saved as spool request', 'Output request is created', 'Sent to printer'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'Program output is saved as a spool request, converted to an output request, then sent to the printer.',
          },
        ],
      },
      {
        id: 'basis-system-update',
        title: 'System Updates and Patch Management',
        content: [
          'SAP system maintenance involves applying Support Packages and SAP Notes. Support Packages are periodic update packages containing multiple fixes, applied via transaction SPAM (Support Package Manager). SAP Notes are individual problem fixes or enhancements, applied via transaction SNOTE (Note Assistant).',
          'The kernel is the SAP system execution engine that runs at the OS level. Kernel updates are important for system stability and security, downloaded from SAP support sites and replaced at the OS level. System updates should always be verified in a test environment before applying to production.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction code is used to apply Support Packages?',
            choices: ['SNOTE', 'SPAM', 'STMS', 'SE38'],
            correctIndex: 1,
            explanation: 'SPAM (Support Package Manager) is used for applying Support Packages. SNOTE is used for individual SAP Notes.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used to apply individual SAP Notes?',
            choices: ['SPAM', 'SNOTE', 'STMS', 'SU01'],
            correctIndex: 1,
            explanation: 'SNOTE (Note Assistant) is used for viewing, applying, and managing individual SAP Notes.',
          },
          {
            type: 'ox',
            question: 'SAP Notes are periodic update packages containing multiple fixes.',
            correct: false,
            explanation: 'Incorrect. Periodic update packages containing multiple fixes are Support Packages. SAP Notes provide individual problem fixes or enhancements.',
          },
          {
            type: 'ox',
            question: 'Support Packages should be verified in a test environment before applying to production.',
            correct: true,
            explanation: 'Correct. System updates should always be verified in a test environment first, and applied to production only after confirming no issues.',
          },
          {
            type: 'four-choice',
            question: 'Which statement correctly describes the SAP kernel?',
            choices: ['A type of ABAP program', 'The OS-level execution engine of the SAP system', 'A database management tool', 'A user interface framework'],
            correctIndex: 1,
            explanation: 'The kernel is the SAP system execution engine that runs at the OS level, providing the ABAP runtime and communication processing.',
          },
          {
            type: 'four-choice',
            question: 'How are kernel updates applied?',
            choices: ['Applied via SPAM', 'Applied via SNOTE', 'Downloaded from SAP support and replaced at the OS level', 'Transported via STMS'],
            correctIndex: 2,
            explanation: 'The kernel consists of OS-level files, downloaded from SAP support (SAP for Me, etc.) and replaced on the OS. SPAM and STMS cannot apply kernel updates.',
          },
        ],
      },
      {
        id: 'basis-performance',
        title: 'Performance Management',
        content: [
          'Common causes of SAP performance issues include inefficient ABAP programs, insufficient memory, database bottlenecks, and work process shortages. Performance analysis starts with ST03N (workload statistics), examining response time breakdown (CPU time, DB time, network time, etc.).',
          'Database performance analysis uses ST04 (Database Monitor) and ST05 (SQL Trace). ST05 records and analyzes SQL statements issued by specific programs or transactions, helping identify inefficient SQL. Memory management uses ST02 (buffer statistics) to check SAP buffer hit rates and swap situations, adjusting parameters as needed.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction code is used for SQL trace recording and analysis?',
            choices: ['ST02', 'ST03N', 'ST04', 'ST05'],
            correctIndex: 3,
            explanation: 'ST05 (Performance Trace) records and analyzes SQL traces and buffer traces, showing SQL execution times and counts for performance improvement.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code checks SAP buffer statistics?',
            choices: ['ST02', 'ST03N', 'ST04', 'ST05'],
            correctIndex: 0,
            explanation: 'ST02 displays SAP buffer statistics (hit rates, usage, swap counts). Low hit rates may require parameter adjustment.',
          },
          {
            type: 'ox',
            question: 'ST03N can show average response times per transaction.',
            correct: true,
            explanation: 'Correct. ST03N (Workload Analysis) shows statistics per transaction including response time, execution count, DB time, and CPU time, serving as the entry point for performance analysis.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used for database monitoring?',
            choices: ['ST02', 'ST03N', 'ST04', 'SM50'],
            correctIndex: 2,
            explanation: 'ST04 is the Database Monitor, showing database performance statistics (cache hit rates, SQL execution status, etc.).',
          },
          {
            type: 'ox',
            question: 'Performance problems are always caused by the database.',
            correct: false,
            explanation: 'Incorrect. Performance issues can have many causes: inefficient ABAP programs, insufficient memory, work process shortages, network latency, etc. ST03N response time breakdown helps identify the bottleneck.',
          },
          {
            type: 'ordering',
            question: 'Arrange the general performance investigation steps in order.',
            items: ['Check response time breakdown in ST03N', 'Identify bottleneck area', 'Investigate with detailed trace (ST05, etc.)', 'Implement and verify solution'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'Start with ST03N for the big picture, identify whether the bottleneck is DB/CPU/memory, use detailed tools like ST05 for root cause analysis, then implement and verify the solution.',
          },
        ],
      },
      {
        id: 'basis-security',
        title: 'Security Management',
        content: [
          'SAP Basis security management covers user authentication, authorization management, communication security, and audit logging. Password policies are configured via profile parameters (e.g., login/min_password_length), controlling minimum length, expiration, and complexity. Transaction RZ10 manages instance profiles.',
          'The Security Audit Log is configured via transaction SM19 and displayed via SM20. It records events such as user login/logout, transaction execution, and authorization check failures. SNC (Secure Network Communications) and SSL provide communication encryption between SAP GUI and servers and for RFC connections.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction code is used to configure the Security Audit Log?',
            choices: ['SM20', 'SM19', 'SM21', 'SM04'],
            correctIndex: 1,
            explanation: 'SM19 configures the Security Audit Log (selecting events to record). SM20 displays the audit log. SM21 is the System Log.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used to display the Security Audit Log?',
            choices: ['SM19', 'SM20', 'SM21', 'SM37'],
            correctIndex: 1,
            explanation: 'SM20 displays and analyzes recorded audit logs. SM19 is used for configuration.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code manages instance profiles?',
            choices: ['SM50', 'SM21', 'RZ10', 'PFCG'],
            correctIndex: 2,
            explanation: 'RZ10 is used for viewing and editing SAP instance profile parameters, managing system parameters for password policies, memory settings, and more.',
          },
          {
            type: 'ox',
            question: 'SNC encrypts communication between SAP GUI and the server.',
            correct: true,
            explanation: 'Correct. SNC (Secure Network Communications) encrypts communication between SAP GUI and the Application Server, as well as server-to-server RFC connections, and provides enhanced authentication.',
          },
          {
            type: 'ox',
            question: 'Password policies can only be configured through ABAP programs.',
            correct: false,
            explanation: 'Incorrect. Password policies are configured via profile parameters (e.g., login/min_password_length). Use RZ10 to edit instance profiles or RZ11 to change individual parameters.',
          },
          {
            type: 'four-choice',
            question: 'Which event is NOT typically recorded by the Security Audit Log?',
            choices: ['User login', 'Transaction execution', 'Program source code change history', 'Authorization check failures'],
            correctIndex: 2,
            explanation: 'Program source code change history is managed by version control (SE38 version management, transport history). The audit log records runtime events like login, transaction execution, and authorization failures.',
          },
        ],
      },
    ],
  },
};
