import type { Quiz } from '../learning-types';
import type { Language } from '../i18n';

/** Additional CO practice questions, appended after each section's originals. */
export const coQuizzes: Record<Language, Record<string, Quiz[]>> = {
  ja: {
    'co-overview': [
      {
        type: 'four-choice',
        question: 'FIで転記された費用や収益を、COでも同じ項目として扱えるように橋渡しする役割を持つものはどれか。',
        choices: ['原価要素', '評価クラス', '転記キー', '伝票タイプ'],
        correctIndex: 0,
        explanation: '原価要素です。FIの損益科目に対応する一次原価要素を通じて、費用がCOの原価センタや指図に引き渡されます。',
      },
      {
        type: 'four-choice',
        question: '1つの管理領域に複数の会社コードを割り当てるための条件として正しいものはどれか。',
        choices: ['同じ勘定科目表と会計年度バリアントを使用している', '同じ国に所在している', '同じ販売組織を持っている', '同じ事業領域を使用している'],
        correctIndex: 0,
        explanation: '管理領域をまたいで原価を扱うには、勘定科目と期間の区切りがそろっている必要があります。そのため、同じ勘定科目表と会計年度バリアントを使っていることが条件になります。',
      },
      {
        type: 'ox',
        question: 'S/4HANAではFIとCOの明細がユニバーサルジャーナル（ACDOCA）に統合されたため、FIとCOの間の照合作業は大幅に減った。',
        correct: true,
        explanation: '正しいです。ECCではFIとCOの明細が別テーブルにあり、両者を照合する必要がありました。S/4HANAでは同じ明細を共有します。',
      },
      {
        type: 'ox',
        question: 'COの数値は社内の意思決定のためのものなので、FIの財務諸表の数値と整合させる必要は一切ない。',
        correct: false,
        explanation: '誤りです。COは社内向けですが、元になる費用はFIと同じ取引です。両者の数値が説明できない形でずれていると管理数値の信頼性が損なわれるため、整合確認は重要な作業です。',
      },
    ],
    'co-cost-center': [
      {
        type: 'four-choice',
        question: '管理領域内のすべての原価センタが、必ずいずれかのノードに属する階層構造を何と呼ぶか。',
        choices: ['標準階層', '原価センタグループ', '利益センタグループ', '財務諸表バージョン'],
        correctIndex: 0,
        explanation: '標準階層です。すべての原価センタが属するため、組織全体の原価を漏れなく集計できます。別の切り口で集計したい場合は原価センタグループを使います。',
      },
      {
        type: 'four-choice',
        question: 'アセスメント（配賦）の説明として正しいものはどれか。',
        choices: [
          '配賦用の二次原価要素にまとめて振り替えるため、受け側では元の費目がわからなくなる',
          '元の一次原価要素のまま振り替えるため、受け側でも費目ごとの内訳がわかる',
          '原価センタから得意先へ費用を請求する処理である',
          '活動量に活動単価を掛けて製造指図に原価を計上する処理である',
        ],
        correctIndex: 0,
        explanation: 'アセスメントは配賦用の二次原価要素でまとめて振り替えます。元の一次原価要素のまま振り替えるのは分配（Distribution）です。',
      },
      {
        type: 'ox',
        question: '配賦の基準には、固定の比率のほか、従業員数や床面積などの統計キー数値を使うことができる。',
        correct: true,
        explanation: '正しいです。統計キー数値を原価センタごとに登録しておくと、その比率で費用を配賦できます。',
      },
      {
        type: 'ox',
        question: '原価センタは売上などの収益を管理する単位であり、売上も原価センタに集計するのが一般的である。',
        correct: false,
        explanation: '誤りです。原価センタは費用が発生する場所を表す単位です。収益と費用の両方を管理して利益を見るのは利益センタやCO-PAの役割です。',
      },
    ],
    'co-profit-center': [
      {
        type: 'four-choice',
        question: 'S/4HANAにおいて、利益センタ会計のデータはどこに記録されるか。',
        choices: ['総勘定元帳（ユニバーサルジャーナル）', '独立した利益センタ元帳（EC-PCA）', '原価基準型CO-PAのテーブル', '特別目的元帳'],
        correctIndex: 0,
        explanation: 'S/4HANAでは利益センタは総勘定元帳の項目として、ユニバーサルジャーナルに直接記録されます。従来の独立したEC-PCA元帳は使いません。',
      },
      {
        type: 'ox',
        question: '利益センタを品目マスタや原価センタ、内部指図などに割り当てておくと、転記時に利益センタが自動的に導出される。',
        correct: true,
        explanation: '正しいです。利用者が毎回入力しなくても、転記先のオブジェクトに割り当てられた利益センタが引き継がれます。割当漏れは利益センタ別の数値が狂う原因になります。',
      },
      {
        type: 'four-choice',
        question: '利益センタ間で製品やサービスを受け渡すときに使う、社内の取引価格を何と呼ぶか。',
        choices: ['内部振替価格', '標準価格', '移動平均価格', '政治価格'],
        correctIndex: 0,
        explanation: '内部振替価格です。これを設定すると、受け渡す側の利益センタにも利益が計上され、各利益センタの業績をより公平に評価できます。',
      },
      {
        type: 'ox',
        question: '利益センタは損益だけでなく、設定によっては貸借対照表の項目も利益センタ単位で管理できる。',
        correct: true,
        explanation: '正しいです。伝票分割を有効にすると、債権・債務などの貸借対照表項目も利益センタ単位で貸借が一致し、利益センタ別の貸借対照表を作成できます。',
      },
    ],
    'co-internal-order': [
      {
        type: 'four-choice',
        question: '費用を実際には原価センタに計上し、内部指図には情報として記録するだけの指図を何と呼ぶか。',
        choices: ['統計指図', '実指図', '製造指図', '保守指図'],
        correctIndex: 0,
        explanation: '統計指図です。原価センタ側に実際の費用が計上されるので、決済は不要です。費用を指図に実際に集計し、決済で振り替えるのは実指図です。',
      },
      {
        type: 'ox',
        question: '統計指図に記録された費用は、決済によって最終帰属先に振り替える必要がある。',
        correct: false,
        explanation: '誤りです。統計指図は情報として記録するだけで、費用はすでに原価センタなどの実際の帰属先に計上されています。決済が必要なのは実指図です。',
      },
      {
        type: 'four-choice',
        question: '内部指図の番号範囲や、決済・予算のプロファイルなどの既定値を決めるものはどれか。',
        choices: ['指図タイプ', '原価要素グループ', '活動タイプ', '統計キー数値'],
        correctIndex: 0,
        explanation: '指図タイプです。用途ごとに指図タイプを分けることで、番号帯や決済ルール、予算管理の有無などを使い分けられます。',
      },
      {
        type: 'four-choice',
        question: '内部指図の典型的な使いどころとして最も適切なものはどれか。',
        choices: ['展示会や社内イベントなど、期間限定の取組みの費用集計', '部門の恒常的な人件費の管理', '得意先ごとの売掛金の管理', '品目ごとの在庫評価'],
        correctIndex: 0,
        explanation: '内部指図は、原価センタでは追いにくい一時的な取組みの費用を集計するのに向いています。恒常的な部門費は原価センタで管理します。',
      },
    ],
    'co-activity-type': [
      {
        type: 'four-choice',
        question: '計画費用と計画活動量から計算せず、手入力で設定する活動単価を何と呼ぶか。',
        choices: ['政治価格', '実際活動単価', '移動平均価格', '内部振替価格'],
        correctIndex: 0,
        explanation: '政治価格（Political Price）です。原価計算の結果にかかわらず、経営判断で単価を決めたい場合に使います。',
      },
      {
        type: 'four-choice',
        question: '活動配賦で製造指図に計上される金額はどのように決まるか。',
        choices: ['活動量 × 活動単価', '原価センタの費用総額 ÷ 指図数', '品目の標準価格 × 生産数量', '計画費用 × 統計キー数値'],
        correctIndex: 0,
        explanation: '確認などで記録した活動量（機械時間など）に活動単価を掛けた金額が、指図の借方と原価センタの貸方に計上されます。',
      },
      {
        type: 'ox',
        question: '活動配賦を行っても、送り側の原価センタの費用は減らず、受け側の指図に費用が追加されるだけである。',
        correct: false,
        explanation: '誤りです。活動配賦では送り側の原価センタが貸方、受け側の指図が借方になります。原価センタの費用が指図へ移る処理です。',
      },
      {
        type: 'ox',
        question: '実際活動単価を算定すると、原価センタの実際費用と実際活動量から実際の単価が計算され、計画単価との差額で活動配賦を再評価できる。',
        correct: true,
        explanation: '正しいです。再評価によって原価センタに残った差額を指図側に配分でき、原価センタの残高をゼロに近づけられます。',
      },
    ],
    'co-product-costing': [
      {
        type: 'four-choice',
        question: '標準原価を材料費・加工費・間接費などの内訳に分けて保持・表示するための設定はどれか。',
        choices: ['原価コンポーネント構造', '原価計算バリアント', '勘定設定カテゴリ', '財務諸表バージョン'],
        correctIndex: 0,
        explanation: '原価コンポーネント構造です。原価要素をコンポーネントに割り当てて、製品原価の内訳を分析できるようにします。',
      },
      {
        type: 'four-choice',
        question: '原価見積で使う価格の取り方、日付、数量構造の決め方などを束ねる設定はどれか。',
        choices: ['原価計算バリアント', '原価コンポーネント構造', '指図タイプ', '評価クラス'],
        correctIndex: 0,
        explanation: '原価計算バリアントです。原価計算タイプや評価バリアントなどをまとめ、どの価格とどの日付で原価を計算するかを決めます。',
      },
      {
        type: 'ox',
        question: '製造指図の実際原価は、部品の出庫、確認による活動配賦、間接費計算などによって指図に積み上がっていく。',
        correct: true,
        explanation: '正しいです。これらの実績と、完成品の入庫で貸方に計上される標準原価との差が、差異計算の対象になります。',
      },
      {
        type: 'four-choice',
        question: '製品の標準原価の積み上げに通常含まれないものはどれか。',
        choices: ['部品表にもとづく材料費', '作業手順にもとづく活動費', '間接費', '得意先への販売手数料'],
        correctIndex: 3,
        explanation: '販売手数料は製造原価ではなく販売費です。標準原価は部品表の材料費、作業手順の活動費、それらにかかる間接費から積み上げます。',
      },
    ],
    'co-cost-element': [
      {
        type: 'four-choice',
        question: '決済（Settlement）で使用する二次原価要素のカテゴリはどれか。',
        choices: ['01', '11', '21', '43'],
        correctIndex: 2,
        explanation: 'カテゴリ21が内部決済です。01は一次原価、11は収益、43は内部活動配賦に使います。',
      },
      {
        type: 'four-choice',
        question: '複数の原価要素をまとめ、レポートや計画、配賦サイクルで一括して指定するために使うものはどれか。',
        choices: ['原価要素グループ', '勘定科目グループ', '原価センタグループ', '統計キー数値'],
        correctIndex: 0,
        explanation: '原価要素グループです。「人件費」「減価償却費」のように原価要素を束ねておくと、配賦の対象やレポートの行を簡単に指定できます。',
      },
      {
        type: 'ox',
        question: 'S/4HANAでは、二次原価要素もG/L勘定マスタとして、勘定タイプ「二次原価」で作成する。',
        correct: true,
        explanation: '正しいです。S/4HANAでは原価要素がG/L勘定に統合され、二次原価要素もFIの勘定コードとして管理されます。ただしFIの財務諸表には表示されません。',
      },
      {
        type: 'ox',
        question: '一次原価要素に費用を転記する場合、原価センタや指図などのCOの集計対象を指定する必要がある。',
        correct: true,
        explanation: '正しいです。原価要素になっている勘定に転記するとCOにもデータが渡るため、どこに原価を計上するかの指定が必要です。指定がないとエラーになります。',
      },
    ],
    'co-copa': [
      {
        type: 'four-choice',
        question: '勘定基準型CO-PAの特徴として正しいものはどれか。',
        choices: [
          'G/L勘定（原価要素）単位で記録するため、FIの数値と一致しやすい',
          '数値項目で記録し、出荷時点で標準原価による売上原価を認識する',
          '原価センタ単位でしか分析できない',
          'SDの請求伝票からはデータを受け取れない',
        ],
        correctIndex: 0,
        explanation: '勘定基準型はFIと同じ勘定単位で記録するため、FIとの照合がしやすいのが特徴です。数値項目で記録するのは原価基準型です。',
      },
      {
        type: 'four-choice',
        question: 'CO-PAにデータが流れる経路として通常存在しないものはどれか。',
        choices: ['SDの請求伝票の転記', 'FIからの直接転記', '原価センタからのアセスメント', '購買発注の登録'],
        correctIndex: 3,
        explanation: '購買発注の登録だけでは会計データが発生しないため、CO-PAには流れません。請求、FIの転記、原価センタからの配賦、指図の決済などが主な経路です。',
      },
      {
        type: 'ox',
        question: '請求伝票からCO-PAにデータを引き渡すとき、得意先・品目・販売組織などの特性値は伝票から自動的に引き継がれる。',
        correct: true,
        explanation: '正しいです。請求伝票にはすでに得意先や品目などの情報があるため、特性値として自動設定されます。',
      },
      {
        type: 'ox',
        question: '製造指図の差異を決済でCO-PAに振り替えると、製品別の収益性分析に製造差異を反映できる。',
        correct: true,
        explanation: '正しいです。標準原価で計上された売上原価に実際の製造差異を加えることで、製品ごとの実際の利益に近い数値を分析できます。',
      },
    ],
    'co-variance': [
      {
        type: 'four-choice',
        question: '製造指図の差異のうち、投入側の差異に含まれないものはどれか。',
        choices: ['価格差異', '数量差異', '資源使用差異', 'ロットサイズ差異'],
        correctIndex: 3,
        explanation: 'ロットサイズ差異は産出側の差異で、計画と異なるロットサイズで製造したことにより固定費の按分が変わるときに生じます。価格・数量・資源使用差異は投入側です。',
      },
      {
        type: 'four-choice',
        question: '差異計算で実際原価と比較される「目標原価」は、何をもとに計算されるか。',
        choices: ['実際に完成した数量に対する標準原価', '計画数量に対する計画原価', '前月の実際原価', '品目の移動平均価格'],
        correctIndex: 0,
        explanation: '目標原価は、実際に完成した数量で標準原価を計算し直したものです。計画数量のままでは、生産量の違いまで差異に含まれてしまいます。',
      },
      {
        type: 'ox',
        question: '部品表と異なる品目を代わりに使ったことで生じた差異は、資源使用差異に区分される。',
        correct: true,
        explanation: '正しいです。計画にない品目や活動を使った場合、あるいは計画した品目を使わなかった場合は資源使用差異になります。',
      },
      {
        type: 'ox',
        question: '差異計算は、まだ製造中の指図にも実行し、仕掛中の原価をすべて差異として計上するのが一般的である。',
        correct: false,
        explanation: '誤りです。製造中の指図の原価は差異ではなく仕掛品として扱います。差異計算の対象は、納入完了やTECOとなった指図です。',
      },
    ],
    'co-period-end': [
      {
        type: 'four-choice',
        question: 'COの期末処理で「未処理の検出」として確認すべきものはどれか。',
        choices: ['決済ルールが設定されていない実指図', '当月に作成された原価センタ', '有効期間内の原価要素', '承認済みの購買発注'],
        correctIndex: 0,
        explanation: '決済ルールがない実指図は決済できず、費用が指図に残ったままになります。期末処理の前に洗い出しておくべき代表的な項目です。',
      },
      {
        type: 'four-choice',
        question: 'COの取引ごとに、期間単位で転記をロックする設定を行うトランザクションコードはどれか。',
        choices: ['OKP1', 'OB52', 'MMPV', 'KSII'],
        correctIndex: 0,
        explanation: 'OKP1はCOの期間ロックです。配賦や決済などの取引ごとに期間を締められます。OB52はFIの転記期間、MMPVはMMの期間、KSIIは実際活動単価の算定です。',
      },
      {
        type: 'ox',
        question: '原価センタの締めでは、アセスメントなどの配賦を、実際活動単価の算定より前に実行する必要がある。',
        correct: true,
        explanation: '正しいです。実際活動単価は原価センタの費用総額から計算するため、配賦で受け取る費用が確定してから算定しないと単価が正しくなりません。',
      },
      {
        type: 'four-choice',
        question: '実際活動単価で活動配賦を再評価する効果として正しいものはどれか。',
        choices: [
          '原価センタに残った差額を指図などの受け側に配分し、原価センタの残高をゼロに近づける',
          '計画単価を翌期の単価として自動設定する',
          '原価センタの費用をCO-PAに直接振り替える',
          '指図の決済ルールを自動作成する',
        ],
        correctIndex: 0,
        explanation: '計画単価で配賦した金額と実際費用の差は原価センタに残ります。再評価でその差を受け側に配分することで、原価センタの残高を解消できます。',
      },
    ],
  },
  en: {
    'co-overview': [
      {
        type: 'four-choice',
        question: 'What links costs and revenues posted in FI to CO so that both treat them as the same item?',
        choices: ['Cost element', 'Valuation class', 'Posting key', 'Document type'],
        correctIndex: 0,
        explanation: 'The cost element. Primary cost elements correspond to FI P&L accounts, and through them costs flow to cost centres and orders in CO.',
      },
      {
        type: 'four-choice',
        question: 'What is required for several company codes to be assigned to one controlling area?',
        choices: ['They use the same chart of accounts and fiscal year variant', 'They are in the same country', 'They share a sales organisation', 'They use the same business area'],
        correctIndex: 0,
        explanation: 'Handling costs across company codes requires the same accounts and the same period structure, so they must share a chart of accounts and fiscal year variant.',
      },
      {
        type: 'ox',
        question: 'Because FI and CO line items are unified in the Universal Journal (ACDOCA) in S/4HANA, reconciliation between FI and CO has been greatly reduced.',
        correct: true,
        explanation: 'Correct. In ECC, FI and CO line items were stored separately and had to be reconciled; in S/4HANA they share the same line items.',
      },
      {
        type: 'ox',
        question: 'CO figures are for internal decisions, so there is no need for them to agree with the FI financial statements at all.',
        correct: false,
        explanation: 'Incorrect. CO serves internal purposes, but its costs come from the same transactions as FI. Unexplained differences undermine trust in management figures, so reconciliation matters.',
      },
    ],
    'co-cost-center': [
      {
        type: 'four-choice',
        question: 'What is the hierarchy in which every cost centre of a controlling area must sit under a node?',
        choices: ['Standard hierarchy', 'Cost centre group', 'Profit centre group', 'Financial statement version'],
        correctIndex: 0,
        explanation: 'The standard hierarchy. Because every cost centre belongs to it, costs roll up completely. Other views use cost centre groups.',
      },
      {
        type: 'four-choice',
        question: 'Which statement describes an assessment correctly?',
        choices: [
          'Costs are transferred under a secondary assessment cost element, so the receiver cannot see the original cost types',
          'Costs are transferred under their original primary cost elements, so the receiver sees the breakdown',
          'It charges costs from a cost centre to a customer',
          'It multiplies activity quantity by activity price to charge a production order',
        ],
        correctIndex: 0,
        explanation: 'An assessment transfers costs under a secondary cost element. Transferring under the original primary cost elements is a distribution.',
      },
      {
        type: 'ox',
        question: 'Allocations can be based on fixed percentages or on statistical key figures such as headcount or floor space.',
        correct: true,
        explanation: 'Correct. Once statistical key figures are recorded per cost centre, costs can be allocated in proportion to them.',
      },
      {
        type: 'ox',
        question: 'Cost centres manage revenue, and it is normal to collect sales revenue on cost centres.',
        correct: false,
        explanation: 'Incorrect. A cost centre represents where costs arise. Managing revenue and cost together to see profit is the job of profit centres and CO-PA.',
      },
    ],
    'co-profit-center': [
      {
        type: 'four-choice',
        question: 'Where is profit centre accounting data recorded in S/4HANA?',
        choices: ['In the general ledger (Universal Journal)', 'In a separate profit centre ledger (EC-PCA)', 'In costing-based CO-PA tables', 'In a special purpose ledger'],
        correctIndex: 0,
        explanation: 'In S/4HANA the profit centre is a field of the general ledger, recorded directly in the Universal Journal. The separate EC-PCA ledger is no longer used.',
      },
      {
        type: 'ox',
        question: 'Assigning profit centres to material masters, cost centres and internal orders lets the system derive the profit centre automatically at posting.',
        correct: true,
        explanation: 'Correct. The profit centre is inherited from the object posted to, so users need not enter it. Missing assignments distort profit centre figures.',
      },
      {
        type: 'four-choice',
        question: 'What is the internal price used when goods or services pass between profit centres?',
        choices: ['Transfer price', 'Standard price', 'Moving average price', 'Political price'],
        correctIndex: 0,
        explanation: 'A transfer price. It lets the supplying profit centre show a profit too, so each profit centre’s performance can be judged more fairly.',
      },
      {
        type: 'ox',
        question: 'Depending on configuration, profit centres can carry balance sheet items as well as profit and loss.',
        correct: true,
        explanation: 'Correct. With document splitting active, balance sheet items such as receivables and payables balance per profit centre, allowing a balance sheet by profit centre.',
      },
    ],
    'co-internal-order': [
      {
        type: 'four-choice',
        question: 'What is an order on which costs are only recorded for information, while the real posting goes to a cost centre?',
        choices: ['Statistical order', 'Real order', 'Production order', 'Maintenance order'],
        correctIndex: 0,
        explanation: 'A statistical order. The actual cost sits on the cost centre, so no settlement is needed. Real orders collect costs that are then settled.',
      },
      {
        type: 'ox',
        question: 'Costs recorded on a statistical order must be settled to their final receiver.',
        correct: false,
        explanation: 'Incorrect. A statistical order only records information; the costs already sit on the real receiver such as a cost centre. Only real orders are settled.',
      },
      {
        type: 'four-choice',
        question: 'What determines an internal order’s number range and default settlement and budget profiles?',
        choices: ['Order type', 'Cost element group', 'Activity type', 'Statistical key figure'],
        correctIndex: 0,
        explanation: 'The order type. Separate order types per purpose give different number ranges, settlement rules and budget control.',
      },
      {
        type: 'four-choice',
        question: 'Which is the most typical use of an internal order?',
        choices: ['Collecting the costs of a time-limited initiative such as a trade fair', 'Managing a department’s ongoing payroll costs', 'Managing receivables per customer', 'Valuing inventory per material'],
        correctIndex: 0,
        explanation: 'Internal orders suit temporary initiatives whose costs are hard to follow on cost centres. Ongoing departmental costs belong on cost centres.',
      },
    ],
    'co-activity-type': [
      {
        type: 'four-choice',
        question: 'What is an activity price entered by hand rather than calculated from planned cost and planned quantity?',
        choices: ['Political price', 'Actual activity price', 'Moving average price', 'Transfer price'],
        correctIndex: 0,
        explanation: 'A political price, used when management wants to set the rate regardless of the costing result.',
      },
      {
        type: 'four-choice',
        question: 'How is the amount charged to a production order by activity allocation determined?',
        choices: ['Activity quantity × activity price', 'Total cost centre cost ÷ number of orders', 'Material standard price × quantity produced', 'Planned cost × statistical key figure'],
        correctIndex: 0,
        explanation: 'The activity quantity recorded, for example machine hours from confirmations, is multiplied by the activity price, debiting the order and crediting the cost centre.',
      },
      {
        type: 'ox',
        question: 'Activity allocation adds cost to the receiving order without reducing the sending cost centre’s costs.',
        correct: false,
        explanation: 'Incorrect. The sending cost centre is credited and the receiving order debited; cost moves from the cost centre to the order.',
      },
      {
        type: 'ox',
        question: 'Calculating actual activity prices derives a price from actual cost and actual quantity, and allocations can then be revalued by the difference from plan.',
        correct: true,
        explanation: 'Correct. Revaluation passes the remaining difference on to receivers, bringing the cost centre balance close to zero.',
      },
    ],
    'co-product-costing': [
      {
        type: 'four-choice',
        question: 'Which setting holds and displays the standard cost broken down into material, production and overhead?',
        choices: ['Cost component structure', 'Costing variant', 'Account assignment category', 'Financial statement version'],
        correctIndex: 0,
        explanation: 'The cost component structure. Cost elements are assigned to components so that the product cost breakdown can be analysed.',
      },
      {
        type: 'four-choice',
        question: 'Which setting bundles how a cost estimate picks prices, dates and quantity structure?',
        choices: ['Costing variant', 'Cost component structure', 'Order type', 'Valuation class'],
        correctIndex: 0,
        explanation: 'The costing variant. It combines the costing type and valuation variant to decide which prices and dates the estimate uses.',
      },
      {
        type: 'ox',
        question: 'Actual costs build up on a production order through component issues, activity allocation from confirmations and overhead calculation.',
        correct: true,
        explanation: 'Correct. The difference between these actuals and the standard cost credited when finished goods are received is what variance calculation analyses.',
      },
      {
        type: 'four-choice',
        question: 'Which of these is not normally part of a product’s standard cost?',
        choices: ['Material cost from the BOM', 'Activity cost from the routing', 'Overhead', 'Sales commission paid on customer orders'],
        correctIndex: 3,
        explanation: 'Sales commission is a selling expense, not a production cost. Standard cost is built from BOM materials, routing activities and the overhead on them.',
      },
    ],
    'co-cost-element': [
      {
        type: 'four-choice',
        question: 'Which secondary cost element category is used for settlement?',
        choices: ['01', '11', '21', '43'],
        correctIndex: 2,
        explanation: 'Category 21 is internal settlement. 01 is primary costs, 11 is revenue and 43 is internal activity allocation.',
      },
      {
        type: 'four-choice',
        question: 'What groups cost elements so they can be specified together in reports, planning and allocation cycles?',
        choices: ['Cost element group', 'Account group', 'Cost centre group', 'Statistical key figure'],
        correctIndex: 0,
        explanation: 'A cost element group. Bundling elements such as personnel costs or depreciation makes allocation senders and report rows easy to specify.',
      },
      {
        type: 'ox',
        question: 'In S/4HANA, secondary cost elements are also created as G/L account masters, with the account type for secondary costs.',
        correct: true,
        explanation: 'Correct. Cost elements are merged into G/L accounts in S/4HANA, so secondary cost elements are managed as FI accounts, though they do not appear in financial statements.',
      },
      {
        type: 'ox',
        question: 'Posting a cost to a primary cost element requires a CO account assignment such as a cost centre or order.',
        correct: true,
        explanation: 'Correct. Posting to a cost element passes data to CO, so it must state where the cost belongs; without an assignment the posting fails.',
      },
    ],
    'co-copa': [
      {
        type: 'four-choice',
        question: 'Which statement describes account-based CO-PA correctly?',
        choices: [
          'It records by G/L account (cost element), so it reconciles easily with FI',
          'It records in value fields and recognises cost of sales at standard cost at delivery',
          'It can only analyse by cost centre',
          'It cannot receive data from SD billing documents',
        ],
        correctIndex: 0,
        explanation: 'Account-based CO-PA records by the same accounts as FI, which makes reconciliation straightforward. Recording in value fields is costing-based CO-PA.',
      },
      {
        type: 'four-choice',
        question: 'Which of these is not normally a route by which data reaches CO-PA?',
        choices: ['Posting an SD billing document', 'Direct postings from FI', 'Assessment from cost centres', 'Creating a purchase order'],
        correctIndex: 3,
        explanation: 'Creating a purchase order generates no accounting data, so nothing reaches CO-PA. Billing, FI postings, cost centre assessments and order settlement are the main routes.',
      },
      {
        type: 'ox',
        question: 'When billing data passes to CO-PA, characteristics such as customer, material and sales organisation are taken over from the document automatically.',
        correct: true,
        explanation: 'Correct. The billing document already carries this information, so the characteristic values are filled in automatically.',
      },
      {
        type: 'ox',
        question: 'Settling production order variances to CO-PA lets product profitability reflect production variances.',
        correct: true,
        explanation: 'Correct. Adding actual production variances to cost of sales posted at standard brings product profit closer to the actual figure.',
      },
    ],
    'co-variance': [
      {
        type: 'four-choice',
        question: 'Which of these is not an input-side variance on a production order?',
        choices: ['Price variance', 'Quantity variance', 'Resource-usage variance', 'Lot size variance'],
        correctIndex: 3,
        explanation: 'Lot size variance is output-side, arising when a lot differs from the costed lot size and fixed costs are spread differently. Price, quantity and resource-usage variances are input-side.',
      },
      {
        type: 'four-choice',
        question: 'What is the target cost, against which actual cost is compared in variance calculation, based on?',
        choices: ['Standard cost for the quantity actually completed', 'Planned cost for the planned quantity', 'Last month’s actual cost', 'The material’s moving average price'],
        correctIndex: 0,
        explanation: 'Target cost recalculates standard cost for the quantity actually completed. Using the planned quantity would count differences in output volume as variances.',
      },
      {
        type: 'ox',
        question: 'A variance caused by using a different material from the one in the BOM is classed as a resource-usage variance.',
        correct: true,
        explanation: 'Correct. Using an unplanned material or activity, or not using a planned one, gives a resource-usage variance.',
      },
      {
        type: 'ox',
        question: 'Variance calculation is normally run on orders still in production, treating all their costs so far as variances.',
        correct: false,
        explanation: 'Incorrect. Costs on orders in progress are work in process, not variances. Variances are calculated for orders that are delivered or technically complete.',
      },
    ],
    'co-period-end': [
      {
        type: 'four-choice',
        question: 'At CO period end, what should be checked for as unprocessed items?',
        choices: ['Real orders with no settlement rule', 'Cost centres created this month', 'Cost elements within their validity period', 'Approved purchase orders'],
        correctIndex: 0,
        explanation: 'A real order without a settlement rule cannot be settled, leaving costs stranded on it. It is one of the first things to find before closing.',
      },
      {
        type: 'four-choice',
        question: 'Which transaction locks CO periods for individual business transactions?',
        choices: ['OKP1', 'OB52', 'MMPV', 'KSII'],
        correctIndex: 0,
        explanation: 'OKP1 is the CO period lock, allowing periods to be closed per transaction such as allocation or settlement. OB52 is the FI posting period, MMPV the MM period and KSII actual activity price calculation.',
      },
      {
        type: 'ox',
        question: 'When closing cost centres, allocations such as assessments must run before actual activity prices are calculated.',
        correct: true,
        explanation: 'Correct. Actual activity prices are calculated from a cost centre’s total cost, so costs received through allocations must be final first.',
      },
      {
        type: 'four-choice',
        question: 'What does revaluing activity allocations at actual prices achieve?',
        choices: [
          'It passes the remaining difference on to receivers such as orders, bringing the cost centre balance close to zero',
          'It sets next period’s plan price automatically',
          'It transfers cost centre costs directly to CO-PA',
          'It creates settlement rules on orders automatically',
        ],
        correctIndex: 0,
        explanation: 'The gap between allocations at plan price and actual cost stays on the cost centre. Revaluation passes it on to receivers and clears the balance.',
      },
    ],
  },
};
