import type { ModuleContent } from '../learning-types';

export const co: Record<'ja' | 'en', ModuleContent> = {
  ja: {
    id: 'co',
    title: '管理会計（CO）',
    description: 'SAPにおける管理会計の基礎を学びます',
    sections: [
      {
        id: 'co-overview',
        title: 'COモジュール概要',
        content: [
          'CO（Controlling / 管理会計）は、企業内部の原価管理と収益分析を担うSAPモジュールです。FIが対外的な財務諸表作成を目的とするのに対し、COは経営判断のための内部情報を提供します。',
          'COはFIと密接に連携しており、FIで発生した財務データがCOに自動的に引き渡されます。そのため両モジュールを合わせて「FI/CO」と表記されることが多くあります。',
        ],
        quizzes: [
          {
            type: 'ox',
            question: 'COモジュールは対外的な財務諸表の作成を主な目的としている。',
            correct: false,
            explanation: 'FIが対外的な財務諸表作成を目的とするのに対し、COは企業内部の原価管理・収益分析のための内部情報提供を目的としています。',
          },
          {
            type: 'four-choice',
            question: 'COで主に管理されるものはどれか。',
            choices: ['売掛金・買掛金', '原価・収益の内部分析', '在庫数量', '人事データ'],
            correctIndex: 1,
            explanation: 'COは原価センタ・利益センタ・内部指図などを使い、企業内部の原価管理と収益分析を行います。売掛金・買掛金はFI、在庫数量はMMの管轄です。',
          },
          {
            type: 'four-choice',
            question: 'COの最上位の組織単位はどれか。',
            choices: ['会社コード', '管理領域（Controlling Area）', 'プラント', '購買組織'],
            correctIndex: 1,
            explanation: '管理領域（Controlling Area）はCOの最上位組織単位です。1つ以上の会社コードに対応し、原価センタ・利益センタ・内部指図などのCOオブジェクトはすべて管理領域に属します。',
          },
          {
            type: 'ox',
            question: 'COとFIは完全に独立したモジュールであり、FIで転記された費用はCOへ自動的に引き渡されない。',
            correct: false,
            explanation: 'FIで転記された費用（例：経費・減価償却など）はCOの原価センタや内部指図へ自動的に引き渡されます。この統合によりFI/COでリアルタイムの管理情報が得られます。',
          },
          {
            type: 'four-choice',
            question: 'COモジュールのサブコンポーネントに含まれないものはどれか。',
            choices: ['CO-CCA（原価センタ会計）', 'CO-PC（製品原価計算）', 'CO-PA（収益性分析）', 'CO-AP（買掛金管理）'],
            correctIndex: 3,
            explanation: 'CO-AP（買掛金管理）はCOのサブコンポーネントではありません。買掛金管理はFI-APです。COのサブコンポーネントにはCO-CCA・CO-PC・CO-PA・CO-OPA（内部指図）などがあります。',
          },
          {
            type: 'ox',
            question: '管理領域（Controlling Area）は複数の会社コードをまたいで設定することができる。',
            correct: true,
            explanation: 'その通りです。1つの管理領域に複数の会社コードを割り当てることができます。これによりグループ企業全体の管理会計を一元管理することが可能です。ただし各会社コードは1つの管理領域にしか属せません。',
          },
        ],
      },
      {
        id: 'co-cost-center',
        title: '原価センタ',
        content: [
          '原価センタ（Cost Center）は、企業内で発生するコストを集計・管理するための組織単位です。部門・機能・場所などに基づいて設定され、間接費の配賦先として機能します。',
          '原価センタは管理領域（Controlling Area）という上位組織に属します。1つの管理領域に複数の原価センタを設定でき、原価センタ間の費用配賦も可能です。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '原価センタが属する上位の組織単位として正しいものはどれか。',
            choices: ['会社コード', '事業領域', '管理領域', 'プラント'],
            correctIndex: 2,
            explanation: '原価センタは管理領域に属します。管理領域は1つ以上の会社コードに対応し、CO全体の管理単位となります。',
          },
          {
            type: 'ox',
            question: '1つの管理領域には1つの原価センタしか設定できない。',
            correct: false,
            explanation: '1つの管理領域には複数の原価センタを設定できます。部門・工場・チームなど、コスト管理の目的に応じて細かく設定されます。',
          },
          {
            type: 'four-choice',
            question: '原価センタの実績費用明細を照会するトランザクションコードはどれか。',
            choices: ['KSB1', 'KP06', 'KSU5', 'KSBL'],
            correctIndex: 0,
            explanation: 'KSB1は原価センタの実績明細（Cost Center Actual Line Items）の照会に使用します。KP06は費用計画入力、KSU5はアセスメントの一括実行、KSBLは原価センタ期間残高の照会です。',
          },
          {
            type: 'ox',
            question: '原価センタマスタには有効期間（開始日・終了日）を設定でき、有効期間外への費用転記はできない。',
            correct: true,
            explanation: 'その通りです。原価センタには有効期間が設定されており、有効期間外の日付で費用を転記しようとするとエラーになります。組織変更に合わせて有効期間を適切に管理することが重要です。',
          },
          {
            type: 'ordering',
            question: '原価センタを活用した費用管理の一般的な手順を正しい順番に並べなさい。',
            items: ['実績費用の確認・差異分析', '原価センタマスタの作成', '費用計画の入力（KP06）', '業務活動による費用の計上'],
            correctOrder: [1, 2, 3, 0],
            explanation: '正しい順序は ①原価センタマスタの作成 → ②費用計画の入力 → ③業務活動による費用計上 → ④実績確認・差異分析 です。マスタ整備と計画が先行することで、実績との比較が可能になります。',
          },
          {
            type: 'four-choice',
            question: '複数の原価センタをグループ化して階層的に管理するためのオブジェクトはどれか。',
            choices: ['原価センタグループ', '利益センタ', '管理領域', '事業領域'],
            correctIndex: 0,
            explanation: '原価センタグループ（Cost Center Group）は複数の原価センタをグループ化し、階層的に管理するためのオブジェクトです。レポートや配賦処理でグループ単位の集計・操作が可能になります。',
          },
        ],
      },
      {
        id: 'co-profit-center',
        title: '利益センタ',
        content: [
          '利益センタ（Profit Center）は、損益を管理するための内部組織単位です。製品ライン・地域・事業部門などに基づいて設定され、各利益センタの収益性を分析できます。',
          '原価センタが費用の集計に特化しているのに対し、利益センタは収益と費用の両方を管理します。SAP ERP 6.0以降では利益センタ会計は「新GL（New General Ledger）」に統合されています。',
        ],
        quizzes: [
          {
            type: 'ox',
            question: '利益センタは原価センタと異なり、収益と費用の両方を管理することができる。',
            correct: true,
            explanation: 'その通りです。原価センタが費用の集計に特化しているのに対し、利益センタは収益と費用の両方を対象とし、各セグメントの収益性を分析できます。',
          },
          {
            type: 'four-choice',
            question: '利益センタによるセグメント分析の切り口として通常使われないものはどれか。',
            choices: ['製品ライン別', '地域別', '事業部門別', '伝票タイプ別'],
            correctIndex: 3,
            explanation: '伝票タイプは会計的な分類であり、利益センタによる収益性分析の切り口としては通常使用されません。製品ライン・地域・事業部門が一般的な分析軸です。',
          },
          {
            type: 'four-choice',
            question: '利益センタが属する組織単位はどれか。',
            choices: ['会社コード', '管理領域（Controlling Area）', 'プラント', '販売組織'],
            correctIndex: 1,
            explanation: '利益センタは管理領域（Controlling Area）に属します。管理領域は原価センタ・利益センタなどCOオブジェクトの共通の上位組織です。',
          },
          {
            type: 'ox',
            question: '1つの管理領域に複数の利益センタを設定することができる。',
            correct: true,
            explanation: 'その通りです。1つの管理領域に多数の利益センタを設定できます。事業部門・製品ライン・地域など、収益性分析の目的に応じて階層的に設定するのが一般的です。',
          },
          {
            type: 'four-choice',
            question: 'SAP ERP 6.0（新GL）以降での利益センタ会計の説明として正しいものはどれか。',
            choices: ['利益センタ会計は廃止されFIに完全移行した', '利益センタ会計は新GL（New General Ledger）に統合された', '利益センタ会計はCO-PAに置き換えられた', '利益センタ会計はMMに移管された'],
            correctIndex: 1,
            explanation: 'SAP ERP 6.0以降では利益センタ会計は新GL（New General Ledger）に統合されました。新GLのドキュメント分割機能により、利益センタ別のB/S（貸借対照表）分析も可能になっています。',
          },
          {
            type: 'ordering',
            question: '利益センタを活用した収益性分析の設定・運用の流れを正しい順番に並べなさい。',
            items: ['利益センタレポートで収益性を確認する', '利益センタマスタを作成する', '品目や勘定科目に利益センタを割り当てる', '業務処理（販売・製造等）を実行する'],
            correctOrder: [1, 2, 3, 0],
            explanation: '正しい順序は ①利益センタマスタの作成 → ②品目・勘定科目への割り当て設定 → ③業務処理の実行 → ④レポートでの収益性確認 です。マスタと割り当て設定が前提となります。',
          },
        ],
      },
      {
        id: 'co-internal-order',
        title: '内部指図',
        content: [
          '内部指図（Internal Order）は、特定の活動やプロジェクトに関わる費用を一時的に集計・追跡するためのオブジェクトです。キャンペーン費用・設備修繕・社内プロジェクトなどの費用を個別に管理できます。',
          '内部指図への費用計上後は「決済（Settlement）」処理によって、集計した費用を原価センタや固定資産などの最終帰属先に振り替えます。これにより費用の正確な帰属管理が可能です。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '内部指図に集計した費用を原価センタ等の最終帰属先に振り替える処理を何と呼ぶか。',
            choices: ['配賦（Allocation）', '決済（Settlement）', '振替（Transfer Posting）', '承認（Release）'],
            correctIndex: 1,
            explanation: '内部指図の費用を最終帰属先に振り替える処理は「決済（Settlement）」と呼びます。決済ルールに基づき、原価センタ・G/L勘定・固定資産などに費用を振り替えます。',
          },
          {
            type: 'ox',
            question: '内部指図は費用の一時集計オブジェクトであり、決済処理によって最終帰属先に費用を振り替えることができる。',
            correct: true,
            explanation: 'その通りです。内部指図は費用の一時集計オブジェクトとして機能し、設定された決済ルールに基づいて期末などに原価センタや固定資産などへ費用を振り替えます。',
          },
          {
            type: 'four-choice',
            question: '内部指図を新規作成するトランザクションコードはどれか。',
            choices: ['KO01', 'KO02', 'KO03', 'KO88'],
            correctIndex: 0,
            explanation: 'KO01は内部指図の新規作成に使用します。KO02は変更、KO03は照会、KO88は内部指図の個別決済処理です。',
          },
          {
            type: 'ox',
            question: '内部指図にはステータス管理（作成・リリース・完了など）があり、ステータスによって実行できる業務処理が制御される。',
            correct: true,
            explanation: 'その通りです。内部指図のステータスが「作成（Created）」状態では費用計上ができず、「リリース（Released）」状態にして初めて費用の転記が可能になります。「完了（Technically Completed）」後は費用計上を制限できます。',
          },
          {
            type: 'four-choice',
            question: '内部指図に予算を設定し、費用が予算を超過した場合に警告またはエラーを発生させる機能を何と呼ぶか。',
            choices: ['承認管理', 'コミットメント管理', '可用性チェック（Budget Availability Control）', '与信管理'],
            correctIndex: 2,
            explanation: '可用性チェック（Budget Availability Control）は、費用転記や発注時に予算残高をチェックし、超過する場合に警告またはエラーを発生させる機能です。予算管理が必要な社内プロジェクト等の管理に有効です。',
          },
          {
            type: 'ordering',
            question: '内部指図を使った費用管理の一般的なライフサイクルを正しい順番に並べなさい。',
            items: ['決済処理（費用を最終帰属先へ振替）', '内部指図の作成（KO01）', '内部指図のリリース', '費用の計上（業務処理・直接転記）'],
            correctOrder: [1, 2, 3, 0],
            explanation: '正しい順序は ①KO01で指図作成 → ②リリース（費用計上を許可） → ③費用の計上 → ④決済処理（最終帰属先へ振替） です。リリース前は費用計上ができないため、作成後のリリースが必須です。',
          },
        ],
      },
      {
        id: 'co-activity-type',
        title: '活動タイプと原価センタ計画',
        content: [
          '活動タイプ（Activity Type）は、原価センタが提供する作業・サービスの種類を表すマスタデータです。製造部門では「機械稼働時間」「人件費時間」、IT部門では「サポート時間」などが活動タイプとして定義されます。活動タイプを通じて、原価センタのコストを受益部門（製造指図・別の原価センタなど）に配賦します。',
          '原価センタへの費用計画は通常、年度初めに行います。KP06で費用計画を入力し、KP26で活動タイプの計画単価（価格）を設定します。この計画単価が活動配賦時のコスト計算に使用され、実績との差異分析にも使われます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '活動タイプの計画単価（価格）を原価センタに設定するトランザクションコードはどれか。',
            choices: ['KP06', 'KP26', 'KB21N', 'KSS4'],
            correctIndex: 1,
            explanation: 'KP26は原価センタへの活動タイプ計画単価設定に使用します。KP06は費用計画の入力、KB21Nは活動実績の確認入力、KSS4は原価センタ分割処理です。',
          },
          {
            type: 'ox',
            question: '活動タイプは、原価センタが提供するサービス・作業の種類を表すマスタデータである。',
            correct: true,
            explanation: 'その通りです。活動タイプを定義することで、原価センタのコストをサービスの提供量（時間・個数など）に基づいて受益部門へ配賦することができます。',
          },
          {
            type: 'four-choice',
            question: '原価センタ間で費用を配賦する方法のうち、配賦元の費用が元の勘定科目（一次原価要素）のまま受け手に転記される方法を何と呼ぶか。',
            choices: ['アセスメント（Assessment）', 'ディストリビューション（Distribution）', '活動配賦（Activity Allocation）', '決済（Settlement）'],
            correctIndex: 1,
            explanation: 'ディストリビューション（Distribution）は、配賦元の一次原価要素をそのまま受け手の原価センタに転記します。アセスメント（Assessment）は二次原価要素を使って費用をまとめて配賦する方法です。',
          },
          {
            type: 'four-choice',
            question: '原価センタの費用計画（プライマリコスト計画）を入力するトランザクションコードはどれか。',
            choices: ['KP26', 'KP06', 'KB21N', 'KSU5'],
            correctIndex: 1,
            explanation: 'KP06は原価センタへの費用計画（Primary Cost Planning）入力に使用します。KP26は活動タイプの計画単価設定、KB21Nは活動実績入力、KSU5はアセスメント一括実行です。',
          },
          {
            type: 'ox',
            question: '活動タイプの計画単価（KP26で設定）は、製造指図への活動配賦時に使用される。',
            correct: true,
            explanation: 'その通りです。製造指図へ活動配賦（例：機械時間の計上）を行う際には、KP26で設定した計画単価が使用されます。実際の活動原価との差異は後から差異分析で把握します。',
          },
          {
            type: 'four-choice',
            question: '製造実績として実際の活動量（機械稼働時間など）を原価センタに入力するトランザクションはどれか。',
            choices: ['KP06', 'KP26', 'KB21N', 'KSS4'],
            correctIndex: 2,
            explanation: 'KB21Nは原価センタへの活動実績確認入力（Enter Actual Activity）に使用します。KP06は費用計画、KP26は活動単価計画、KSS4は原価センタ分割処理です。',
          },
        ],
      },
      {
        id: 'co-product-costing',
        title: '製品原価計算',
        content: [
          '製品原価計算（Product Cost Calculation）は、製品を製造するコストを事前に計算する機能です。BOM（部品表）から材料費を、作業手順（Routing）と活動タイプの計画単価から加工費を積み上げて、製品の標準原価（Standard Cost）を算出します。',
          '算出した標準原価はCK11Nで「標準原価見積」として保存し、CK24で品目マスタへ「原価リリース」します。リリースした標準原価が製造指図の計画原価や製品の在庫評価額として使用されます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '製品の標準原価見積を作成するトランザクションコードはどれか。',
            choices: ['CK11N', 'KP26', 'MD01', 'CO01'],
            correctIndex: 0,
            explanation: 'CK11Nは製品の標準原価見積（Standard Cost Estimate）の作成に使用します。KP26は活動単価計画、MD01はMRP実行、CO01は製造指図作成です。',
          },
          {
            type: 'ox',
            question: '製品原価計算では、BOM（部品表）と作業手順（Routing）の両方の情報が標準原価の計算に使用される。',
            correct: true,
            explanation: 'その通りです。BOMから材料費を、作業手順と活動タイプ単価から加工費を積み上げて標準原価を算出します。どちらか一方でも不正確だと原価計算の精度が下がります。',
          },
          {
            type: 'ordering',
            question: '標準原価計算の一般的な実施手順を正しい順番に並べなさい。',
            items: ['品目マスタへの原価リリース（CK24）', '標準原価見積の作成（CK11N）', 'BOM・作業手順のマスタデータ整備', '原価見積のマーキング'],
            correctOrder: [2, 1, 3, 0],
            explanation: '正しい順序は ①BOM・作業手順の整備 → ②標準原価見積の作成（CK11N） → ③マーキング → ④原価リリース（CK24） です。リリース後に標準原価が品目マスタに反映されます。',
          },
          {
            type: 'four-choice',
            question: '標準原価見積を品目マスタへリリースするトランザクションコードはどれか。',
            choices: ['CK11N', 'CK24', 'CK40N', 'CKME'],
            correctIndex: 1,
            explanation: 'CK24は標準原価見積のマーキングおよびリリースに使用します。CK11Nは単品の原価見積作成、CK40Nはコストランによる一括作成、CKMEは原価リリース状況の照会です。',
          },
          {
            type: 'ox',
            question: '標準原価がリリースされた後、同一原価計算期間中に新しい標準原価を再リリースして即時上書きすることは原則できない。',
            correct: true,
            explanation: 'その通りです。原価計算期間中に標準原価のリリースは原則1回のみです。期中に変更するためには特別な手続きが必要であり、在庫評価額への影響も考慮しなければなりません。',
          },
          {
            type: 'four-choice',
            question: '製造指図の「計画原価」の計算基礎として正しいものはどれか。',
            choices: ['前年度の実績原価', 'リリース済み標準原価', '予算原価', '市場価格'],
            correctIndex: 1,
            explanation: '製造指図の計画原価はリリース済みの標準原価（品目マスタの標準価格）を基に計算されます。標準原価のリリースが製造指図作成前に完了していることが重要です。',
          },
        ],
      },
      {
        id: 'co-cost-element',
        title: '原価要素',
        content: [
          '原価要素（Cost Element）はCOにおける費用・収益の分類単位です。「一次原価要素（Primary Cost Element）」はFIの費用・収益勘定に対応し、FIからCOへの費用引き渡しに使用されます。「二次原価要素（Secondary Cost Element）」はCO内部の配賦・活動配賦専用の要素で、FIには対応する勘定科目がありません。',
          '原価要素には「カテゴリ（Cost Element Category）」が設定されており、用途を制御します。主なカテゴリとして、一般費用（1）・製品コスト（41）・アセスメント（42）・内部活動配賦（43）があります。SAP S/4HANAでは一次原価要素とG/L勘定が統合され、単一のオブジェクトとして管理されます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '一次原価要素（Primary Cost Element）の説明として正しいものはどれか。',
            choices: ['CO内部の配賦専用の要素でFI勘定科目との対応はない', 'FIの費用・収益勘定に対応しFIからCOへの費用引き渡しに使用される', 'MMの材料費専用の原価要素である', 'HRの給与データと連携するための要素である'],
            correctIndex: 1,
            explanation: '一次原価要素はFIのG/L勘定と1対1で対応しています。FIで費用が転記された際に、この一次原価要素を通じてCOの原価センタや内部指図などへ費用が引き渡されます。',
          },
          {
            type: 'ox',
            question: '二次原価要素（Secondary Cost Element）はFIの総勘定元帳に対応する勘定科目が存在する。',
            correct: false,
            explanation: '二次原価要素はCO内部の配賦処理（アセスメント・活動配賦など）専用の要素であり、FIの勘定科目には対応していません。CO内部でのコストの流れを追跡するためにのみ使用されます。',
          },
          {
            type: 'four-choice',
            question: 'アセスメント（Assessment）で使用される原価要素のカテゴリはどれか。',
            choices: ['カテゴリ1（一般費用）', 'カテゴリ41（製品コスト）', 'カテゴリ42（アセスメント）', 'カテゴリ43（内部活動配賦）'],
            correctIndex: 2,
            explanation: 'アセスメントには二次原価要素のカテゴリ42が使用されます。カテゴリ43は内部活動配賦、カテゴリ41は製品原価計算、カテゴリ1は一次原価要素（一般費用）です。',
          },
          {
            type: 'ox',
            question: 'SAP S/4HANAでは、一次原価要素とG/L勘定（総勘定元帳勘定）が統合され、FIとCOで同一のオブジェクトとして管理される。',
            correct: true,
            explanation: 'その通りです。SAP S/4HANAでは一次原価要素がG/L勘定に統合されました。従来のSAP ECC（ERP 6.0）では別々に管理されていましたが、S/4HANAではG/L勘定マスタで原価要素カテゴリも設定する形になっています。',
          },
          {
            type: 'four-choice',
            question: '活動配賦（Activity Allocation）に使用される二次原価要素のカテゴリはどれか。',
            choices: ['カテゴリ1', 'カテゴリ41', 'カテゴリ42', 'カテゴリ43'],
            correctIndex: 3,
            explanation: '活動配賦（Activity Allocation）に使用される二次原価要素のカテゴリは43です。カテゴリ43の原価要素は活動タイプと結びついて、活動量に応じた費用配賦に使用されます。',
          },
          {
            type: 'ordering',
            question: '費用の発生からCO内での処理までの流れを正しい順番に並べなさい。',
            items: ['原価センタや内部指図への配賦処理', 'FIで費用伝票が転記される', '一次原価要素を通じてCOへ費用が引き渡される', 'COレポートで原価を分析する'],
            correctOrder: [1, 2, 0, 3],
            explanation: '正しい順序は ①FIでの費用転記 → ②一次原価要素経由でCOへ引き渡し → ③CO内での配賦処理 → ④COレポートでの分析 です。一次原価要素がFIとCOをつなぐ重要な役割を担います。',
          },
        ],
      },
      {
        id: 'co-copa',
        title: '収益性分析（CO-PA）',
        content: [
          '収益性分析（Profitability Analysis / CO-PA）は、製品・顧客・地域・販売チャネルなどの切り口（特性）ごとに損益を分析するCOのサブモジュールです。CO-PAには「原価ベースCO-PA（Costing-based）」と「勘定ベースCO-PA（Account-based）」の2種類があります。SAP S/4HANAでは勘定ベースCO-PAが推奨・必須となっています。',
          'CO-PAでは「特性（Characteristic）」と「数値項目（Value Field）」を設定します。特性は分析の切り口（製品・得意先・販売地域など）、数値項目は売上・原価・利益などの金額情報です。SDで売上請求書が転記されると、収益・原価データがCO-PAへ自動的に引き渡されます。',
        ],
        quizzes: [
          {
            type: 'ox',
            question: 'CO-PAは製品・顧客・地域などの切り口（特性）ごとに収益性を分析するCOのサブモジュールである。',
            correct: true,
            explanation: 'その通りです。CO-PAはセグメント別の損益分析を目的としており、製品ライン・得意先・地域・販売チャネルなどの多次元分析が可能です。',
          },
          {
            type: 'four-choice',
            question: 'SAP S/4HANAで推奨・必須とされているCO-PAのタイプはどれか。',
            choices: ['原価ベースCO-PA（Costing-based）', '勘定ベースCO-PA（Account-based）', '両方同等に推奨される', 'CO-PAはS/4HANAで廃止された'],
            correctIndex: 1,
            explanation: 'SAP S/4HANAでは勘定ベースCO-PA（Account-based CO-PA）が推奨・必須です。勘定ベースはFIとの整合性が高く、リアルタイムの損益分析が可能です。',
          },
          {
            type: 'four-choice',
            question: 'CO-PAにおける「特性（Characteristic）」の説明として正しいものはどれか。',
            choices: ['売上・原価・利益などの金額項目', '分析の切り口となる属性（製品・得意先・地域など）', '費用配賦のルールを定義するマスタ', '原価センタと利益センタをつなぐ連携項目'],
            correctIndex: 1,
            explanation: '特性（Characteristic）はCO-PAにおける分析の切り口（ディメンション）です。製品グループ・得意先・販売地域・流通チャネルなどが代表的な特性です。金額情報は「数値項目（Value Field）」と呼ばれます。',
          },
          {
            type: 'ox',
            question: 'SDで売上請求書が転記されると、売上データは自動的にCO-PAへ引き渡される。',
            correct: true,
            explanation: 'その通りです。SDの請求書転記と同時に、売上収益・原価・値引きなどのデータがCO-PAの特性と数値項目にマッピングされて自動転記されます。これにより手動入力不要でリアルタイムの収益性分析が可能です。',
          },
          {
            type: 'four-choice',
            question: 'CO-PAにおける「数値項目（Value Field）」の説明として正しいものはどれか。',
            choices: ['分析の切り口となる属性情報', '売上・売上原価・値引き等の金額情報を格納する項目', 'CO-PA特有のマスタデータオブジェクト', '配賦計算で使用するキー数値'],
            correctIndex: 1,
            explanation: '数値項目（Value Field）は売上高・売上原価・値引き・販売費用など、収益性分析で管理する金額情報を格納する項目です。特性（分析軸）と組み合わせることでセグメント別の損益分析が可能になります。',
          },
          {
            type: 'ordering',
            question: 'CO-PAを使った収益性分析の一般的な流れを正しい順番に並べなさい。',
            items: ['セグメント別の収益性レポートを分析する', 'CO-PAの特性と数値項目を設定する', 'SDの請求書転記によりデータがCO-PAへ自動転記される', '収益性分析（CO-PA）の有効化を行う'],
            correctOrder: [3, 1, 2, 0],
            explanation: '正しい順序は ①CO-PAの有効化 → ②特性・数値項目の設定 → ③SDの請求書転記でデータが自動転記 → ④レポートで収益性を分析 です。設定が整って初めて実際のデータが蓄積・分析できます。',
          },
        ],
      },
      {
        id: 'co-variance',
        title: '差異分析',
        content: [
          '差異分析（Variance Analysis）は、製造指図の計画原価と実績原価の差異を原因別に分析する機能です。差異は「数量差異（Quantity Variance）」「価格差異（Price Variance）」「投入差異（Input Variance）」などに分解され、製造効率の管理・改善に活用されます。',
          '製造指図の差異計算はKKS1（個別処理）またはKKS2（一括処理）で実行します。計算された差異は決済処理によりCO-PAや原価センタへ振り替えられ、最終的に収益性分析の情報として反映されます。差異を定期的に分析することで製造プロセスの問題点を早期に発見できます。',
        ],
        quizzes: [
          {
            type: 'ox',
            question: '差異分析では、計画原価と実績原価の差を数量差異・価格差異などの原因カテゴリに分解して分析することができる。',
            correct: true,
            explanation: 'その通りです。差異分析では単純に計画vs実績の差額を把握するだけでなく、差異の発生原因（数量の違い・価格の違いなど）を明確にすることで、問題の所在を特定できます。',
          },
          {
            type: 'four-choice',
            question: '製造指図の差異計算を個別（1指図ずつ）実行するトランザクションコードはどれか。',
            choices: ['KKS1', 'KKS2', 'CO88', 'KO88'],
            correctIndex: 0,
            explanation: 'KKS1は製造指図の差異計算を個別（Individual）に実行するトランザクションです。KKS2は一括（Collective）処理、CO88は製造指図の一括決済、KO88は内部指図の個別決済です。',
          },
          {
            type: 'four-choice',
            question: '材料の実際消費単価が標準原価の計画単価より高かったことで生じる差異はどれか。',
            choices: ['数量差異（Quantity Variance）', '価格差異（Price Variance）', '資源配分差異（Resource-usage Variance）', 'スクラップ差異（Scrap Variance）'],
            correctIndex: 1,
            explanation: '材料や活動の「単価（価格）」の計画値と実績値の差から生じる差異を「価格差異（Price Variance）」と呼びます。計画単価より実際購買単価が高ければ不利差異（コストオーバー）となります。',
          },
          {
            type: 'ox',
            question: '差異計算の結果は決済処理によってCO-PAや原価センタに振り替えることができる。',
            correct: true,
            explanation: 'その通りです。製造指図の差異は決済ルールに基づいてCO-PA（収益性分析）や原価センタへ振り替えられます。これにより差異の影響が損益分析に正確に反映されます。',
          },
          {
            type: 'four-choice',
            question: '製造指図において計画より多くの材料を消費した場合に発生する差異はどれか。',
            choices: ['価格差異（Price Variance）', '数量差異（Quantity Variance）', '資源差異（Resource Variance）', 'ロット規模差異（Lot Size Variance）'],
            correctIndex: 1,
            explanation: '計画数量より多い（または少ない）材料・活動を消費したことで生じる差異を「数量差異（Quantity Variance）」と呼びます。工程の効率改善や材料歩留まりの管理に活用されます。',
          },
          {
            type: 'ordering',
            question: '製造指図における原価処理の流れを正しい順番に並べなさい。',
            items: ['差異計算の実行（KKS1/KKS2）', '製造指図の作成（CO01）', '製造確認（実績入力）', '決済処理（CO88）'],
            correctOrder: [1, 2, 0, 3],
            explanation: '正しい順序は ①製造指図の作成 → ②製造確認（実績の入力） → ③差異計算 → ④決済処理 です。差異計算は実績入力後に行い、計算された差異を決済で最終帰属先へ振り替えます。',
          },
        ],
      },
      {
        id: 'co-period-end',
        title: 'CO期末処理',
        content: [
          'CO期末処理では、月次・年次で複数の処理を定められた順序で実行する必要があります。主な処理として、①原価センタのアセスメント/ディストリビューション実行、②実際活動価格の計算（KSII）、③製造指図の差異計算（KKS2）、④製造指図の決済（CO88）、⑤CO-PAへのデータ確認などがあります。',
          '処理の順序を誤ると正しい原価情報が得られず、財務諸表の精度にも影響します。特に配賦処理（アセスメント/ディストリビューション）は製造指図の差異計算より前に行う必要があります。年次処理としては標準原価の更新・リリース（CK11N/CK24）や原価センタ計画の更新（KP06/KP26）などがあります。',
        ],
        quizzes: [
          {
            type: 'ox',
            question: 'CO期末処理では、各処理を正しい順序で実行することが重要であり、順序を誤ると原価情報が正確にならない場合がある。',
            correct: true,
            explanation: 'その通りです。例えば配賦処理より先に差異計算を行うと、配賦されるべき費用が差異計算に反映されず不正確な差異情報が生成されます。正しい処理順序の把握が重要です。',
          },
          {
            type: 'four-choice',
            question: '複数の製造指図を一括決済するトランザクションコードはどれか。',
            choices: ['KO88', 'CO88', 'KKS1', 'KSU5'],
            correctIndex: 1,
            explanation: 'CO88は製造指図の一括決済（Collective Settlement）に使用します。KO88は内部指図の個別決済、KKS1は製造指図の差異計算（個別）、KSU5は原価センタのアセスメント一括実行です。',
          },
          {
            type: 'ordering',
            question: 'CO期末処理の主要手順を正しい順番に並べなさい。',
            items: ['製造指図の差異計算（KKS2）', '製造指図の決済（CO88）', '原価センタのアセスメント/ディストリビューション実行', '実際活動価格の計算（KSII）'],
            correctOrder: [2, 3, 0, 1],
            explanation: '正しい順序は ①アセスメント/ディストリビューション（配賦） → ②実際活動価格計算（KSII） → ③製造指図の差異計算（KKS2） → ④製造指図の決済（CO88） です。配賦後に差異計算し最後に決済することで正確な原価情報が得られます。',
          },
          {
            type: 'ox',
            question: 'CO期末処理はすべて月次で実施するものであり、年次専用の処理は存在しない。',
            correct: false,
            explanation: '不正解です。CO期末処理には月次処理と年次処理があります。年次処理としては標準原価の更新・リリース（CK11N/CK24）、原価センタ計画の更新（KP06/KP26）などがあります。',
          },
          {
            type: 'four-choice',
            question: '原価センタのアセスメントを一括実行するトランザクションコードはどれか。',
            choices: ['KSU1', 'KSU5', 'KSV1', 'KSV5'],
            correctIndex: 1,
            explanation: 'KSU5は原価センタのアセスメントを一括（Collective）実行するトランザクションです。KSU1はアセスメントの個別実行、KSV1はディストリビューションの個別実行、KSV5はディストリビューションの一括実行です。',
          },
          {
            type: 'four-choice',
            question: '原価センタの実際活動価格計算を実行するトランザクションコードはどれか。',
            choices: ['KSS4', 'KP26', 'KSII', 'KB21N'],
            correctIndex: 2,
            explanation: 'KSIIは原価センタの実際活動価格計算（Actual Activity Price Calculation）に使用します。計画単価との差異を調整するために使います。KSS4は原価センタ分割、KP26は計画単価設定、KB21Nは活動実績入力です。',
          },
        ],
      },
    ],
  },

  en: {
    id: 'co',
    title: 'Controlling (CO)',
    description: 'Learn the fundamentals of management accounting in SAP',
    sections: [
      {
        id: 'co-overview',
        title: 'CO Module Overview',
        content: [
          'CO (Controlling) is the SAP module responsible for internal cost management and profitability analysis. While FI focuses on external financial reporting, CO provides internal information to support management decisions.',
          'CO is closely integrated with FI — financial data generated in FI is automatically passed to CO. Because of this tight link, the two modules are often written together as "FI/CO".',
        ],
        quizzes: [
          {
            type: 'ox',
            question: 'The primary purpose of the CO module is to produce external financial statements.',
            correct: false,
            explanation: 'Incorrect. While FI is responsible for external financial reporting, CO focuses on internal cost management and profitability analysis to support management decision-making.',
          },
          {
            type: 'four-choice',
            question: 'What is primarily managed in the CO module?',
            choices: ['Accounts receivable & payable', 'Internal cost & profitability analysis', 'Inventory quantities', 'HR data'],
            correctIndex: 1,
            explanation: 'CO manages internal cost and profitability using cost centers, profit centers, and internal orders. Accounts receivable/payable belong to FI, and inventory quantities belong to MM.',
          },
          {
            type: 'four-choice',
            question: 'Which is the top-level organizational unit in CO?',
            choices: ['Company Code', 'Controlling Area', 'Plant', 'Purchasing Organization'],
            correctIndex: 1,
            explanation: 'The Controlling Area is the top-level organizational unit in CO. One or more company codes are assigned to a Controlling Area, and all CO objects (cost centers, profit centers, internal orders, etc.) belong to it.',
          },
          {
            type: 'ox',
            question: 'CO and FI are completely independent modules, and costs posted in FI are not automatically transferred to CO.',
            correct: false,
            explanation: 'Incorrect. Costs posted in FI (expenses, depreciation, etc.) are automatically transferred to CO cost centers or internal orders. This integration enables real-time management information across FI/CO.',
          },
          {
            type: 'four-choice',
            question: 'Which of the following is NOT a sub-component of the CO module?',
            choices: ['CO-CCA (Cost Center Accounting)', 'CO-PC (Product Costing)', 'CO-PA (Profitability Analysis)', 'CO-AP (Accounts Payable)'],
            correctIndex: 3,
            explanation: 'CO-AP (Accounts Payable) is not a CO sub-component — Accounts Payable is part of FI-AP. CO sub-components include CO-CCA, CO-PC, CO-PA, and CO-OPA (Internal Orders).',
          },
          {
            type: 'ox',
            question: 'A Controlling Area can span multiple company codes.',
            correct: true,
            explanation: 'Correct. Multiple company codes can be assigned to a single Controlling Area, enabling centralized management accounting for a corporate group. Each company code can only belong to one Controlling Area.',
          },
        ],
      },
      {
        id: 'co-cost-center',
        title: 'Cost Centers',
        content: [
          'A Cost Center is an organizational unit used to collect and manage costs incurred within the company. Cost centers are defined based on departments, functions, or locations, and serve as recipients for indirect cost allocations.',
          'Cost centers belong to a higher organizational unit called the Controlling Area. Multiple cost centers can be assigned to one Controlling Area, and costs can be allocated between cost centers.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which organizational unit does a Cost Center belong to?',
            choices: ['Company Code', 'Business Area', 'Controlling Area', 'Plant'],
            correctIndex: 2,
            explanation: 'Cost centers belong to a Controlling Area, which is the top-level organizational unit in CO. A Controlling Area can span one or more company codes.',
          },
          {
            type: 'ox',
            question: 'Only one cost center can be created per Controlling Area.',
            correct: false,
            explanation: 'Incorrect. Multiple cost centers can be set up under one Controlling Area, allowing fine-grained cost tracking by department, plant, or team.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used to display actual cost line items for a cost center?',
            choices: ['KSB1', 'KP06', 'KSU5', 'KSBL'],
            correctIndex: 0,
            explanation: 'KSB1 displays actual line items for cost centers. KP06 is for cost planning, KSU5 runs the assessment cycle collectively, and KSBL shows period-based cost center balances.',
          },
          {
            type: 'ox',
            question: 'A cost center master record has a validity period (from/to date), and costs cannot be posted outside that period.',
            correct: true,
            explanation: 'Correct. Cost centers have a defined validity period. Posting costs outside the valid date range results in an error. Managing validity periods in line with organizational changes is essential.',
          },
          {
            type: 'ordering',
            question: 'Arrange the general cost management steps using a cost center in the correct order.',
            items: ['Review actuals and perform variance analysis', 'Create the cost center master', 'Enter cost planning (KP06)', 'Post costs through business activities'],
            correctOrder: [1, 2, 3, 0],
            explanation: 'The correct order is: ①Create cost center master → ②Enter cost plan → ③Post actual costs → ④Review actuals and analyze variances. Master data and planning must be in place before actuals can be meaningfully compared.',
          },
          {
            type: 'four-choice',
            question: 'Which object is used to group cost centers hierarchically for reporting and allocation purposes?',
            choices: ['Cost Center Group', 'Profit Center', 'Controlling Area', 'Business Area'],
            correctIndex: 0,
            explanation: 'A Cost Center Group allows multiple cost centers to be organized into a hierarchy. This enables group-level aggregation for reporting and simplifies allocation cycles by targeting groups rather than individual cost centers.',
          },
        ],
      },
      {
        id: 'co-profit-center',
        title: 'Profit Centers',
        content: [
          'A Profit Center is an internal organizational unit used to manage profitability. It is defined based on product lines, regions, or business divisions, and allows analysis of revenues and expenses by segment.',
          'Unlike cost centers, which focus only on costs, profit centers manage both revenues and costs. Since SAP ERP 6.0, profit center accounting has been integrated into the New General Ledger (New GL).',
        ],
        quizzes: [
          {
            type: 'ox',
            question: 'Unlike cost centers, profit centers can manage both revenues and costs.',
            correct: true,
            explanation: 'Correct. While cost centers focus on collecting costs, profit centers manage both revenues and expenses, enabling profitability analysis by business segment.',
          },
          {
            type: 'four-choice',
            question: 'Which of the following is NOT a typical dimension for profit center segment analysis?',
            choices: ['Product line', 'Region', 'Business division', 'Document type'],
            correctIndex: 3,
            explanation: 'Document type is an accounting classification and is not typically used as a segment analysis dimension for profit centers. Product line, region, and business division are common analysis axes.',
          },
          {
            type: 'four-choice',
            question: 'Which organizational unit does a Profit Center belong to?',
            choices: ['Company Code', 'Controlling Area', 'Plant', 'Sales Organization'],
            correctIndex: 1,
            explanation: 'Profit centers belong to a Controlling Area, the same top-level CO organizational unit as cost centers. The Controlling Area serves as the common parent for all CO objects.',
          },
          {
            type: 'ox',
            question: 'Multiple profit centers can be created under a single Controlling Area.',
            correct: true,
            explanation: 'Correct. Many profit centers can be set up under one Controlling Area, organized hierarchically by product line, region, or business division depending on reporting needs.',
          },
          {
            type: 'four-choice',
            question: 'Which best describes profit center accounting in SAP ERP 6.0 and later (New GL)?',
            choices: ['Profit center accounting was eliminated and fully moved to FI', 'Profit center accounting was integrated into the New General Ledger (New GL)', 'Profit center accounting was replaced by CO-PA', 'Profit center accounting was transferred to MM'],
            correctIndex: 1,
            explanation: 'From SAP ERP 6.0 onward, profit center accounting was integrated into the New General Ledger (New GL). The document splitting feature in New GL also allows balance sheet analysis by profit center.',
          },
          {
            type: 'ordering',
            question: 'Arrange the general setup and operation steps for profit center-based profitability analysis in the correct order.',
            items: ['Review profitability by segment in profit center reports', 'Create profit center master records', 'Assign profit centers to materials and G/L accounts', 'Execute business transactions (sales, production, etc.)'],
            correctOrder: [1, 2, 3, 0],
            explanation: 'The correct order is: ①Create profit center masters → ②Assign profit centers to materials/accounts → ③Execute business transactions → ④Review reports. Assignments must be configured before transactions so data flows to the correct profit center.',
          },
        ],
      },
      {
        id: 'co-internal-order',
        title: 'Internal Orders',
        content: [
          'An Internal Order is an object used to temporarily collect and track costs related to a specific activity or project. It allows individual cost tracking for items such as marketing campaigns, equipment repairs, or internal projects.',
          'After costs are collected on an internal order, a "Settlement" process transfers those costs to their final cost objects, such as cost centers or fixed assets. This ensures accurate cost attribution.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What is the process of transferring costs from an internal order to a final cost object called?',
            choices: ['Allocation', 'Settlement', 'Transfer Posting', 'Release'],
            correctIndex: 1,
            explanation: 'The process of transferring costs from an internal order to its final cost object (cost center, G/L account, fixed asset, etc.) is called Settlement. It is executed based on predefined settlement rules.',
          },
          {
            type: 'ox',
            question: 'An internal order acts as a temporary cost collector, and costs can be transferred to the final cost object through a settlement process.',
            correct: true,
            explanation: 'Correct. Internal orders temporarily collect costs and, through the settlement process, transfer those costs to cost centers, fixed assets, or other final objects based on settlement rules.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used to create a new internal order?',
            choices: ['KO01', 'KO02', 'KO03', 'KO88'],
            correctIndex: 0,
            explanation: 'KO01 is used to create a new internal order. KO02 is for changes, KO03 for display, and KO88 for individual internal order settlement.',
          },
          {
            type: 'ox',
            question: 'Internal orders have status management (Created, Released, Closed, etc.), and the status controls which business transactions are permitted.',
            correct: true,
            explanation: 'Correct. An internal order in "Created" status does not allow cost postings. It must be "Released" before costs can be posted. After "Technical Completion," further cost postings can be restricted.',
          },
          {
            type: 'four-choice',
            question: 'What is the feature called that checks the internal order budget and issues a warning or error when costs would exceed the budget?',
            choices: ['Approval Management', 'Commitment Management', 'Budget Availability Control', 'Credit Management'],
            correctIndex: 2,
            explanation: 'Budget Availability Control monitors whether costs (including purchase order commitments) exceed the allocated budget for an internal order. It can be configured to issue a warning or block the posting entirely.',
          },
          {
            type: 'ordering',
            question: 'Arrange the typical internal order lifecycle steps in the correct order.',
            items: ['Settlement (transfer costs to final receiver)', 'Create internal order (KO01)', 'Release the internal order', 'Post costs (through business activities or direct postings)'],
            correctOrder: [1, 2, 3, 0],
            explanation: 'The correct order is: ①Create the order (KO01) → ②Release it → ③Post costs → ④Settle to the final receiver. Costs cannot be posted until the order is released, so the release step is mandatory.',
          },
        ],
      },
      {
        id: 'co-activity-type',
        title: 'Activity Types & Cost Center Planning',
        content: [
          'An Activity Type is master data that defines the type of work or service provided by a cost center. For example, a production cost center might have "Machine Hours" and "Labor Hours" as activity types, while an IT department might use "Support Hours." Activity types are used to allocate cost center costs to benefiting objects such as production orders or other cost centers.',
          'Cost center planning is typically performed at the start of the fiscal year. Costs are planned using KP06, and planned activity prices (rates) are set using KP26. These planned rates are used for activity allocation and later for variance analysis against actuals.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction code is used to set planned activity prices (rates) on a cost center?',
            choices: ['KP06', 'KP26', 'KB21N', 'KSS4'],
            correctIndex: 1,
            explanation: 'KP26 is used to set planned activity type prices on cost centers. KP06 is for cost planning, KB21N is for recording actual activity quantities, and KSS4 is for cost center splitting.',
          },
          {
            type: 'ox',
            question: 'An Activity Type is master data that represents the type of service or work performed by a cost center.',
            correct: true,
            explanation: 'Correct. Defining activity types allows cost center costs to be allocated to benefiting departments based on the quantity of services provided (hours, units, etc.).',
          },
          {
            type: 'four-choice',
            question: 'Which cost allocation method transfers costs between cost centers while keeping the original primary cost elements intact on the receiving cost center?',
            choices: ['Assessment', 'Distribution', 'Activity Allocation', 'Settlement'],
            correctIndex: 1,
            explanation: 'Distribution transfers costs to receiving cost centers using the original primary cost elements. Assessment uses a secondary cost element to transfer costs in summarized form, obscuring the original cost nature.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used to enter primary cost planning for a cost center?',
            choices: ['KP26', 'KP06', 'KB21N', 'KSU5'],
            correctIndex: 1,
            explanation: 'KP06 is used to enter primary cost planning for cost centers. KP26 sets planned activity prices, KB21N records actual activity quantities, and KSU5 runs the assessment cycle collectively.',
          },
          {
            type: 'ox',
            question: 'The planned activity price set in KP26 is used when activity is allocated to production orders.',
            correct: true,
            explanation: 'Correct. When activity (e.g., machine hours) is allocated to a production order, the planned price from KP26 is used to calculate the cost. Differences between planned and actual activity costs are captured as variances.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction is used to manually enter actual activity quantities (e.g., actual machine hours) performed by a cost center?',
            choices: ['KP06', 'KP26', 'KB21N', 'KSS4'],
            correctIndex: 2,
            explanation: 'KB21N is used to enter actual activity quantities for a cost center (Enter Actual Activity). KP06 is for cost planning, KP26 for planned price setting, and KSS4 for cost center splitting.',
          },
        ],
      },
      {
        id: 'co-product-costing',
        title: 'Product Cost Calculation',
        content: [
          'Product Cost Calculation computes the cost of manufacturing a product in advance. It rolls up material costs from the BOM and processing costs from the Routing (using activity type planned prices) to calculate the Standard Cost of a product.',
          'The calculated standard cost is saved as a Standard Cost Estimate using CK11N, then released to the material master using CK24. The released standard cost is used as the planned cost for production orders and as the inventory valuation price.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction code is used to create a product Standard Cost Estimate?',
            choices: ['CK11N', 'KP26', 'MD01', 'CO01'],
            correctIndex: 0,
            explanation: 'CK11N is used to create a Standard Cost Estimate. KP26 sets activity type prices, MD01 runs MRP, and CO01 creates a production order.',
          },
          {
            type: 'ox',
            question: 'Product cost calculation uses both the BOM (Bill of Materials) and the Routing to compute the standard cost.',
            correct: true,
            explanation: 'Correct. The BOM provides the material cost component, and the Routing (combined with activity type planned prices) provides the processing cost component. Inaccuracies in either will reduce the quality of cost calculation.',
          },
          {
            type: 'ordering',
            question: 'Arrange the standard cost calculation process steps in the correct order.',
            items: ['Release the cost estimate to the material master (CK24)', 'Create the standard cost estimate (CK11N)', 'Maintain BOM and Routing master data', 'Mark the cost estimate'],
            correctOrder: [2, 1, 3, 0],
            explanation: 'The correct order is: ①Maintain BOM & Routing → ②Create cost estimate (CK11N) → ③Mark the estimate → ④Release to material master (CK24). After release, the standard cost is reflected in the material master.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used to release a standard cost estimate to the material master?',
            choices: ['CK11N', 'CK24', 'CK40N', 'CKME'],
            correctIndex: 1,
            explanation: 'CK24 is used to mark and release a standard cost estimate to the material master. CK11N creates a single cost estimate, CK40N runs a costing run for multiple materials, and CKME reviews release status.',
          },
          {
            type: 'ox',
            question: 'Once a standard cost is released in a costing period, it generally cannot be immediately replaced by releasing another standard cost in the same period.',
            correct: true,
            explanation: 'Correct. Only one standard cost release is allowed per costing period. Changing the standard cost mid-period requires special procedures and must account for the impact on inventory valuation.',
          },
          {
            type: 'four-choice',
            question: 'What serves as the basis for the "planned cost" on a production order?',
            choices: ['Prior year actual cost', 'Released standard cost', 'Budgeted cost', 'Market price'],
            correctIndex: 1,
            explanation: 'The planned cost of a production order is calculated based on the released standard cost in the material master. Ensuring the standard cost is released before production order creation is a prerequisite for accurate planned cost calculation.',
          },
        ],
      },
      {
        id: 'co-cost-element',
        title: 'Cost Elements',
        content: [
          'A Cost Element is the classification unit for costs and revenues in CO. Primary Cost Elements correspond to FI expense and revenue accounts and are used to transfer financial data from FI to CO. Secondary Cost Elements are used exclusively for internal CO allocations (assessments, activity allocations) and have no corresponding G/L accounts in FI.',
          'Each cost element has a Cost Element Category that defines its permitted usage. Key categories include: General Costs (1), Product Costs (41), Assessment (42), and Internal Activity Allocation (43). In SAP S/4HANA, primary cost elements and G/L accounts are unified and maintained as a single object.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which statement correctly describes a Primary Cost Element?',
            choices: ['An internal CO allocation element with no corresponding FI account', 'Corresponds to a FI expense/revenue account and transfers costs from FI to CO', 'A material cost element used only in MM', 'An element that integrates with HR payroll data'],
            correctIndex: 1,
            explanation: 'Primary Cost Elements correspond 1:1 with G/L accounts in FI. When a cost is posted in FI, the primary cost element routes that cost to the appropriate CO object (cost center, internal order, etc.).',
          },
          {
            type: 'ox',
            question: 'Secondary Cost Elements have a corresponding G/L account in the General Ledger.',
            correct: false,
            explanation: 'Incorrect. Secondary Cost Elements are used exclusively for internal CO processes (assessment, activity allocation, etc.) and do not have a corresponding G/L account in FI. They exist only within the CO layer.',
          },
          {
            type: 'four-choice',
            question: 'Which cost element category is used for Assessment cycles?',
            choices: ['Category 1 (General Costs)', 'Category 41 (Product Costs)', 'Category 42 (Assessment)', 'Category 43 (Internal Activity Allocation)'],
            correctIndex: 2,
            explanation: 'Category 42 is designated for Assessment secondary cost elements. Category 43 is for Internal Activity Allocation, Category 41 for Product Costing, and Category 1 for primary cost elements (general costs).',
          },
          {
            type: 'ox',
            question: 'In SAP S/4HANA, primary cost elements and G/L accounts are unified and maintained as a single object.',
            correct: true,
            explanation: 'Correct. In S/4HANA, the separation between primary cost elements and G/L accounts has been removed. Cost element attributes are now maintained directly on the G/L account master, simplifying setup compared to SAP ECC.',
          },
          {
            type: 'four-choice',
            question: 'Which cost element category is used for Internal Activity Allocation?',
            choices: ['Category 1', 'Category 41', 'Category 42', 'Category 43'],
            correctIndex: 3,
            explanation: 'Category 43 is used for secondary cost elements that represent internal activity allocations. These elements link activity types to cost centers and are used to transfer costs when activities are confirmed on production orders.',
          },
          {
            type: 'ordering',
            question: 'Arrange the steps from cost incurrence to CO processing in the correct order.',
            items: ['Allocation processing within CO (e.g., assessment)', 'A cost document is posted in FI', 'Costs are transferred to CO via a primary cost element', 'Analyze costs using CO reports'],
            correctOrder: [1, 2, 0, 3],
            explanation: 'The correct order is: ①Post cost in FI → ②Transfer to CO via primary cost element → ③Allocate within CO → ④Analyze in CO reports. The primary cost element acts as the bridge connecting FI and CO.',
          },
        ],
      },
      {
        id: 'co-copa',
        title: 'Profitability Analysis (CO-PA)',
        content: [
          'Profitability Analysis (CO-PA) is a CO sub-module that analyzes profit and loss by segment — product, customer, region, sales channel, and more. There are two types: Costing-based CO-PA and Account-based CO-PA. SAP S/4HANA mandates and recommends Account-based CO-PA.',
          'CO-PA is configured with Characteristics (analysis dimensions such as product, customer, and region) and Value Fields (monetary amounts such as revenue, cost, and profit). When a billing document is posted in SD, revenue and cost data are automatically transferred to CO-PA.',
        ],
        quizzes: [
          {
            type: 'ox',
            question: 'CO-PA is a CO sub-module that analyzes profitability by segment (product, customer, region, etc.).',
            correct: true,
            explanation: 'Correct. CO-PA enables multi-dimensional profit and loss analysis by product group, customer, region, sales channel, and more — providing segment-level insight for management decisions.',
          },
          {
            type: 'four-choice',
            question: 'Which type of CO-PA is mandated and recommended in SAP S/4HANA?',
            choices: ['Costing-based CO-PA', 'Account-based CO-PA', 'Both are equally recommended', 'CO-PA was discontinued in S/4HANA'],
            correctIndex: 1,
            explanation: 'Account-based CO-PA is mandated in SAP S/4HANA. It aligns directly with FI/GL accounts, enabling real-time and reconciled P&L reporting. Costing-based CO-PA may be used in parallel but is no longer the primary approach.',
          },
          {
            type: 'four-choice',
            question: 'What is the correct description of a "Characteristic" in CO-PA?',
            choices: ['A monetary amount field for revenue, cost, or profit', 'An attribute used as an analysis dimension (product, customer, region, etc.)', 'A cost allocation rule master record', 'A linking field between cost centers and profit centers'],
            correctIndex: 1,
            explanation: 'A Characteristic is an analysis dimension in CO-PA — examples include product group, customer, sales region, and distribution channel. Monetary amount fields are called Value Fields.',
          },
          {
            type: 'ox',
            question: 'When a billing document is posted in SD, revenue data is automatically transferred to CO-PA.',
            correct: true,
            explanation: 'Correct. SD billing document posting triggers an automatic transfer of revenue, cost, and discount data into CO-PA, mapped to the appropriate characteristics and value fields — no manual entry required.',
          },
          {
            type: 'four-choice',
            question: 'What is the correct description of a "Value Field" in CO-PA?',
            choices: ['An attribute used as an analysis dimension', 'A field that stores monetary amounts such as revenue, COGS, and discounts', 'A CO-PA-specific master data object', 'A key figure used in allocation calculations'],
            correctIndex: 1,
            explanation: 'A Value Field stores the monetary amounts in CO-PA — revenue, cost of goods sold, discounts, selling expenses, etc. Combined with Characteristics (dimensions), Value Fields enable segment-level P&L analysis.',
          },
          {
            type: 'ordering',
            question: 'Arrange the general steps for using CO-PA for profitability analysis in the correct order.',
            items: ['Analyze segment-level profitability in CO-PA reports', 'Configure CO-PA characteristics and value fields', 'SD billing document posting automatically transfers data to CO-PA', 'Activate CO-PA in the operating concern'],
            correctOrder: [3, 1, 2, 0],
            explanation: 'The correct order is: ①Activate CO-PA → ②Configure characteristics & value fields → ③SD billing automatically transfers data → ④Analyze in reports. Configuration must be complete before actual data can flow and be analyzed.',
          },
        ],
      },
      {
        id: 'co-variance',
        title: 'Variance Analysis',
        content: [
          'Variance Analysis identifies and categorizes the difference between planned (standard) costs and actual costs on production orders. Variances are broken down into categories such as Quantity Variance, Price Variance, and Resource-Usage Variance, enabling targeted improvement of manufacturing efficiency.',
          'Variance calculation for production orders is run using KKS1 (individual) or KKS2 (collective). The calculated variances are then settled to CO-PA or cost centers through the settlement process, ensuring that the impact of manufacturing variances flows into profitability analysis.',
        ],
        quizzes: [
          {
            type: 'ox',
            question: 'In variance analysis, the difference between planned and actual costs can be broken down into cause categories such as quantity variances and price variances.',
            correct: true,
            explanation: 'Correct. Variance analysis does not simply report a total difference — it decomposes the variance into root causes (quantity consumed, price paid, etc.), enabling targeted corrective actions on specific inefficiencies.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used to calculate variances for individual production orders?',
            choices: ['KKS1', 'KKS2', 'CO88', 'KO88'],
            correctIndex: 0,
            explanation: 'KKS1 calculates variances for individual production orders. KKS2 performs collective variance calculation, CO88 runs collective settlement of production orders, and KO88 settles individual internal orders.',
          },
          {
            type: 'four-choice',
            question: 'A variance caused by the actual purchase price of a material being higher than the standard planned price is called what?',
            choices: ['Quantity Variance', 'Price Variance', 'Resource-Usage Variance', 'Scrap Variance'],
            correctIndex: 1,
            explanation: 'A Price Variance arises when the actual unit price (of material or activity) differs from the planned price. If the actual purchase price exceeds the standard, an unfavorable price variance is recorded.',
          },
          {
            type: 'ox',
            question: 'The results of variance calculation can be settled to CO-PA or cost centers through the settlement process.',
            correct: true,
            explanation: 'Correct. Production order variances are transferred to CO-PA or cost centers through the settlement process, ensuring that manufacturing inefficiencies are accurately reflected in segment-level profitability reports.',
          },
          {
            type: 'four-choice',
            question: 'If more material is consumed on a production order than the standard quantity in the BOM, which type of variance occurs?',
            choices: ['Price Variance', 'Quantity Variance', 'Resource Variance', 'Lot Size Variance'],
            correctIndex: 1,
            explanation: 'Consuming more (or fewer) materials or activity than the standard plan generates a Quantity Variance. Monitoring quantity variances helps identify process inefficiencies and material yield issues.',
          },
          {
            type: 'ordering',
            question: 'Arrange the cost processing steps for a production order in the correct order.',
            items: ['Run variance calculation (KKS1/KKS2)', 'Create the production order (CO01)', 'Confirm production (enter actual quantities)', 'Execute settlement (CO88)'],
            correctOrder: [1, 2, 0, 3],
            explanation: 'The correct order is: ①Create production order → ②Confirm production (enter actuals) → ③Calculate variances → ④Settle. Variance calculation requires actual postings to exist, and settlement comes last to transfer variances to receivers.',
          },
        ],
      },
      {
        id: 'co-period-end',
        title: 'CO Period-End Closing',
        content: [
          'CO period-end closing requires multiple processes to be executed in a defined sequence each month and year. Key steps include: ① Cost center assessment / distribution, ② Actual activity price calculation (KSII), ③ Production order variance calculation (KKS2), ④ Production order settlement (CO88), and ⑤ CO-PA data verification.',
          'Executing steps out of sequence can result in inaccurate cost information and affect financial statement quality. In particular, allocation cycles (assessment/distribution) must be completed before production order variance calculation. Annual tasks include standard cost updates (CK11N/CK24) and cost center plan updates (KP06/KP26).',
        ],
        quizzes: [
          {
            type: 'ox',
            question: 'CO period-end closing requires steps to be executed in the correct sequence; performing them out of order can lead to inaccurate cost information.',
            correct: true,
            explanation: 'Correct. For example, running variance calculation before completing assessment cycles means allocation costs are not yet reflected, producing incomplete variance results. Strict adherence to the processing sequence is essential.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used for collective settlement of production orders?',
            choices: ['KO88', 'CO88', 'KKS1', 'KSU5'],
            correctIndex: 1,
            explanation: 'CO88 runs collective (batch) settlement of production orders. KO88 settles individual internal orders, KKS1 calculates variances for individual production orders, and KSU5 collectively runs the assessment cycle for cost centers.',
          },
          {
            type: 'ordering',
            question: 'Arrange the main CO period-end closing steps in the correct order.',
            items: ['Production order variance calculation (KKS2)', 'Production order settlement (CO88)', 'Cost center assessment / distribution', 'Actual activity price calculation (KSII)'],
            correctOrder: [2, 3, 0, 1],
            explanation: 'The correct order is: ①Assessment/Distribution → ②Actual activity price calculation (KSII) → ③Production order variance calculation (KKS2) → ④Settlement (CO88). Allocations must be complete before variances are calculated, and settlement comes last.',
          },
          {
            type: 'ox',
            question: 'All CO period-end closing activities are monthly; there are no annual-only closing tasks in CO.',
            correct: false,
            explanation: 'Incorrect. CO has both monthly and annual closing activities. Annual tasks include updating and releasing standard costs (CK11N/CK24) and updating cost center plans (KP06/KP26) for the new fiscal year.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used to run the assessment cycle collectively for cost centers?',
            choices: ['KSU1', 'KSU5', 'KSV1', 'KSV5'],
            correctIndex: 1,
            explanation: 'KSU5 runs the assessment cycle collectively (processing all cost centers in the cycle at once). KSU1 runs it individually, KSV1 runs distribution individually, and KSV5 runs distribution collectively.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used to calculate actual activity prices for cost centers?',
            choices: ['KSS4', 'KP26', 'KSII', 'KB21N'],
            correctIndex: 2,
            explanation: 'KSII (Actual Activity Price Calculation) recalculates activity prices based on actual costs incurred during the period. The resulting price differences are used for variance adjustments. KSS4 is for cost center splitting, KP26 for planned price setting, and KB21N for actual activity entry.',
          },
        ],
      },
    ],
  },
};
