import type { Quiz } from '../learning-types';
import type { Language } from '../i18n';

/**
 * Additional FI practice questions, appended after each section's originals.
 * They follow the section articles in fi-content.ts, so each one can be
 * answered from what the page itself explains.
 */
export const fiQuizzes: Record<Language, Record<string, Quiz[]>> = {
  ja: {
    'fi-overview': [
      {
        type: 'four-choice',
        question: 'S/4HANAで、FI・CO・新総勘定元帳の明細を1つに統合したテーブル（ユニバーサルジャーナル）はどれか。',
        choices: ['BSEG', 'COEP', 'ACDOCA', 'FAGLFLEXA'],
        correctIndex: 2,
        explanation: 'ACDOCAがユニバーサルジャーナルの実体です。ECCではFIの明細はBSEG、COの明細はCOEP、新総勘定元帳の明細はFAGLFLEXAと別々に保持されていましたが、S/4HANAでACDOCAに統合されました。',
      },
      {
        type: 'ox',
        question: 'MMで入庫を転記した時点では請求書が届いていないため、貸方には買掛金ではなくGR/IR勘定（入庫請求仮勘定）が計上される。',
        correct: true,
        explanation: '正しいです。入庫時は（借）在庫／（貸）GR/IR、請求書照合時に（借）GR/IR／（貸）買掛金となり、両方がそろうとGR/IRの残高は消えます。',
      },
      {
        type: 'four-choice',
        question: 'FIを構成するサブモジュールに含まれないものはどれか。',
        choices: ['総勘定元帳（FI-GL）', '債務管理（FI-AP）', '固定資産管理（FI-AA）', '生産計画（PP）'],
        correctIndex: 3,
        explanation: 'PP（生産計画）はFIのサブモジュールではなく、独立したロジスティクス系のモジュールです。FIは総勘定元帳・債務管理・債権管理・固定資産管理などで構成されます。',
      },
      {
        type: 'ox',
        question: 'S/4HANAではFIとCOが同じ明細行を共有するため、FIとCOの数値がずれるという従来の問題が構造的に起きにくくなった。',
        correct: true,
        explanation: '正しいです。ECCではFIとCOの明細が別テーブルにあり、両者の照合が必要でした。ACDOCAで同じ明細を共有するようになり、ずれそのものが起きにくい構造になりました。',
      },
    ],
    'fi-company-coa': [
      {
        type: 'four-choice',
        question: '得意先や仕入先の補助元帳の合計を、総勘定元帳上で表す勘定を何と呼ぶか。',
        choices: ['照合勘定', '仮勘定', '統計勘定', '代替勘定'],
        correctIndex: 0,
        explanation: '照合勘定（Reconciliation Account）です。補助元帳に転記すると、得意先・仕入先マスタに設定された照合勘定にも自動で同額が計上され、補助元帳と総勘定元帳の一致が保たれます。',
      },
      {
        type: 'ox',
        question: '照合勘定には、FB50などのG/L伝票入力で直接転記することができる。',
        correct: false,
        explanation: '誤りです。照合勘定には直接転記できず、得意先・仕入先の補助元帳への転記を通じてのみ計上されます。直接転記を許すと補助元帳との一致が崩れてしまうためです。',
      },
      {
        type: 'four-choice',
        question: '勘定科目グループ（Account Group）が制御するものとして最も適切なものはどれか。',
        choices: ['勘定科目の番号範囲と、マスタ画面の項目の入力制御', '転記に使う為替レートタイプ', '転記期間の開閉', '支払条件の既定値'],
        correctIndex: 0,
        explanation: '勘定科目グループは、どの番号帯の勘定コードを使えるか（番号範囲）と、マスタ作成時にどの項目を必須・任意・非表示にするかを制御します。',
      },
      {
        type: 'ox',
        question: '勘定科目が貸借対照表科目か損益計算書科目かの区分は、勘定科目表レベルで指定する。',
        correct: true,
        explanation: '正しいです。B/S科目かP/L科目かは勘定科目表レベルで決まり、P/L科目には年度末の繰越処理で使う利益剰余金勘定を紐づけます。',
      },
    ],
    'fi-document-types': [
      {
        type: 'ox',
        question: 'FB50やFB60などの新しい入力画面では、利用者が転記キーを直接入力する必要はない。',
        correct: true,
        explanation: '正しいです。新しい入力画面では借方・貸方を選ぶだけで転記キーが自動的に決まります。ただしFB03で転記済み伝票を照会すると各明細に転記キーが表示されるため、読み方は知っておく必要があります。',
      },
      {
        type: 'four-choice',
        question: '得意先からの入金（Customer Payment）を表す標準伝票タイプはどれか。',
        choices: ['KR', 'KZ', 'DR', 'DZ'],
        correctIndex: 3,
        explanation: 'DZは得意先入金の標準伝票タイプです。DRは得意先請求書、KRは仕入先請求書、KZは仕入先支払を表します。',
      },
      {
        type: 'four-choice',
        question: '転記キーが、借方・貸方の区分と勘定タイプのほかに制御するものはどれか。',
        choices: ['明細行の項目ステータス（入力必須・任意・非表示）', '伝票に適用する為替レート', '会計年度バリアント', '支払条件の計算方法'],
        correctIndex: 0,
        explanation: '転記キーは明細行の項目ステータスも制御します。どの項目を入力必須にするか、非表示にするかを転記キーごとに決められます。',
      },
      {
        type: 'four-choice',
        question: '得意先勘定の借方（請求書の計上など）に使用する転記キーはどれか。',
        choices: ['01', '15', '31', '40'],
        correctIndex: 0,
        explanation: '01は得意先勘定の借方です。15は得意先の貸方（入金時など）、31は仕入先の貸方、40はG/L勘定の借方です。',
      },
    ],
    'fi-journal': [
      {
        type: 'four-choice',
        question: '会計伝票の「伝票日付」と「転記日付」の説明として正しいものはどれか。',
        choices: [
          '伝票日付は請求書などの原始証憑の日付で、転記日付は計上する期間を決める日付である',
          '伝票日付は計上する期間を決める日付で、転記日付は原始証憑の日付である',
          'どちらもシステムに入力した日付が自動設定され、変更できない',
          '伝票日付と転記日付は常に同じ日付でなければならない',
        ],
        correctIndex: 0,
        explanation: '伝票日付は請求書などの原始証憑に記載された日付、転記日付はどの会計期間に計上するかを決める日付です。月末に届いた請求書を翌月に入力するときなど、両者が異なることはよくあります。',
      },
      {
        type: 'four-choice',
        question: '転記せずに伝票番号を付けて保存し、別の担当者が内容を確認してから転記できる伝票はどれか。',
        choices: ['保留伝票（Parked Document）', '保持伝票（Held Document）', '定期伝票（Recurring Entry）', '逆転記伝票'],
        correctIndex: 0,
        explanation: '保留伝票です。保存時に伝票番号が採番され、他の担当者が照会・修正したうえで転記できるため、承認フローに使われます。保持伝票は入力途中の一時保存で、作成者本人が続きを入力するためのものです。',
      },
      {
        type: 'ox',
        question: '保持伝票（Held Document）は、保存した時点で正式な伝票番号が採番され、他のユーザーからも照会できる。',
        correct: false,
        explanation: '誤りです。保持伝票は入力途中の内容を一時的に保存するもので、正式な伝票番号は採番されません。承認のために他の担当者へ回すなら保留伝票を使います。',
      },
      {
        type: 'four-choice',
        question: '転記済みの会計伝票を照会するトランザクションコードはどれか。',
        choices: ['FB03', 'FB08', 'FB50', 'OB52'],
        correctIndex: 0,
        explanation: 'FB03は会計伝票の照会です。FB08は逆転記、FB50はG/L伝票の入力、OB52は転記期間の開閉を行うトランザクションです。',
      },
    ],
    'fi-payment-terms': [
      {
        type: 'ox',
        question: '分割支払条件を指定して請求書を転記すると、伝票の明細が複数の支払期日に自動で分割される。',
        correct: true,
        explanation: '正しいです。分割支払条件（Installment Payment Terms）では、1枚の請求書を「40%を30日後、60%を60日後」のように分け、それぞれの期日を持つ明細が自動作成されます。',
      },
      {
        type: 'four-choice',
        question: '請求書を全額で計上し、実際に受けた現金割引の額を支払時に収益として計上する処理方法はどれか。',
        choices: ['総額法', '純額法', '定額法', '定率法'],
        correctIndex: 0,
        explanation: '総額法です。純額法は割引後の金額で計上し、割引を取り逃した場合にその差額を費用とします。定額法・定率法は減価償却の計算方法です。',
      },
      {
        type: 'four-choice',
        question: '支払条件（Payment Terms）が定義する2つの要素の組み合わせとして正しいものはどれか。',
        choices: ['支払期日の計算方法と現金割引の条件', '支払方法と取引銀行', '為替レートタイプと通貨', '与信限度額と督促レベル'],
        correctIndex: 0,
        explanation: '支払条件は「いつまでに支払うか（期日の計算）」と「いつまでに支払えば何%割り引くか（現金割引）」の2つを定義します。支払方法や取引銀行は自動支払プログラムの設定です。',
      },
      {
        type: 'ox',
        question: '支払ブロックが設定された請求書でも、支払期日が到来していればF110の自動支払で支払われる。',
        correct: false,
        explanation: '誤りです。支払ブロックが付いた明細はF110の支払対象から除外されます。品質問題で検収待ちの請求書などを、ブロックを解除するまで支払わないようにするための機能です。',
      },
    ],
    'fi-ap': [
      {
        type: 'four-choice',
        question: '購買発注と入庫を参照して、仕入先請求書を計上するトランザクションコードはどれか。',
        choices: ['MIRO', 'FB60', 'F110', 'XK01'],
        correctIndex: 0,
        explanation: 'MIROはMMの請求書照合で、発注・入庫を参照して請求書を計上します。FB60は発注を伴わない請求書をFIで直接計上するトランザクションです。',
      },
      {
        type: 'ox',
        question: 'S/4HANAでは、仕入先マスタと得意先マスタがビジネスパートナ（BP）に一本化された。',
        correct: true,
        explanation: '正しいです。従来は同じ取引先が仕入先でも得意先でもある場合に別々のマスタが必要でしたが、S/4HANAではビジネスパートナとして1つにまとめて管理します。',
      },
      {
        type: 'four-choice',
        question: '3点照合（Three-Way Match）で照合される3つの情報の組み合わせはどれか。',
        choices: ['購買発注・入庫・請求書', '購買依頼・購買発注・支払', '見積・購買発注・請求書', '入庫・出庫・棚卸'],
        correctIndex: 0,
        explanation: '購買発注（何をいくらで頼んだか）、入庫（実際に何が届いたか）、請求書（いくら請求されたか）の3つを照合し、数量や価格の不一致がある請求書は支払をブロックします。',
      },
      {
        type: 'four-choice',
        question: '仕入先への前渡金を、通常の買掛金と区別して管理するための仕組みはどれか。',
        choices: ['特殊仕訳（Special G/L Transaction）', '定期伝票', '保留伝票', '分割支払条件'],
        correctIndex: 0,
        explanation: '特殊仕訳です。特殊仕訳表示を付けて転記すると、通常の照合勘定ではなく前渡金用の代替照合勘定に計上されます。前渡金は資産なので、負債である買掛金と相殺表示しないために必要です。',
      },
    ],
    'fi-ar': [
      {
        type: 'four-choice',
        question: 'SDで請求伝票を作成し、FIに売掛金を自動計上するトランザクションコードはどれか。',
        choices: ['VF01', 'FB70', 'F150', 'VKM1'],
        correctIndex: 0,
        explanation: 'VF01はSDの請求伝票の作成で、転記と同時にFIへ売掛金と売上が計上されます。FB70はFIで得意先請求書を直接入力するトランザクション、F150は督促、VKM1は与信ブロックの解除です。',
      },
      {
        type: 'four-choice',
        question: '請求額の一部だけが入金されたとき、元の明細を消し込み、未入金の差額を新しい未決済明細として作成する方式はどれか。',
        choices: ['残額処理（Residual Item）', '部分消込（Partial Clearing）', '督促処理', '逆転記'],
        correctIndex: 0,
        explanation: '残額処理です。部分消込は元の明細を未決済のまま残し、入金分を紐づけて管理します。残額処理では新しい明細が作られるため、支払基準日がリセットされて督促の起算日が変わることがあります。',
      },
      {
        type: 'ox',
        question: 'S/4HANAでは従来のFI-ARの与信管理は廃止され、FSCMのクレジットマネジメントに一本化された。',
        correct: true,
        explanation: '正しいです。S/4HANAの与信管理はFSCM（Financial Supply Chain Management）のクレジットマネジメントで行い、与信スコアの算出ルールなどをより柔軟に定義できます。',
      },
      {
        type: 'four-choice',
        question: '督促処理（Dunning）を実行するトランザクションコードはどれか。',
        choices: ['F150', 'F110', 'FBL5N', 'VKM1'],
        correctIndex: 0,
        explanation: 'F150が督促の実行です。F110は自動支払プログラム、FBL5Nは得意先明細の照会、VKM1は与信ブロックがかかった受注の解除に使います。',
      },
    ],
    'fi-asset': [
      {
        type: 'ox',
        question: '1つの固定資産について、会計基準用と税務用など目的の異なる複数の帳簿価額を並行して管理する仕組みを「評価領域」という。',
        correct: true,
        explanation: '正しいです。たとえば会計上は定額法10年、税務上は定率法8年というように、評価領域ごとに異なる償却方法と耐用年数で計算できます。',
      },
      {
        type: 'four-choice',
        question: '1つの資産について、評価領域ごとの取得価額・償却累計額・帳簿価額・今後の償却予定を1画面で確認できるトランザクションはどれか。',
        choices: ['AW01N', 'AS01', 'AFAB', 'ABAVN'],
        correctIndex: 0,
        explanation: 'AW01N（資産エクスプローラ）です。AS01は資産マスタの作成、AFABは減価償却の実行、ABAVNは廃棄による除却です。償却額の根拠を調べるときに最初に開く画面です。',
      },
      {
        type: 'ox',
        question: 'すべての評価領域の減価償却額は、必ず総勘定元帳に転記される。',
        correct: false,
        explanation: '誤りです。税務用の評価領域は計算だけを行い、総勘定元帳には転記せず申告資料の作成に使う運用が一般的です。どの領域を転記するかは評価領域ごとに設定します。',
      },
      {
        type: 'four-choice',
        question: '減価償却キーと組み合わせて、毎期の償却額を自動計算するために資産マスタに設定する項目はどれか。',
        choices: ['耐用年数', '資産番号', '伝票タイプ', '転記キー'],
        correctIndex: 0,
        explanation: '耐用年数です。減価償却キーが計算方法を、耐用年数が償却期間を決め、この組み合わせで毎期の償却額が計算されます。耐用年数は評価領域ごとに設定できます。',
      },
    ],
    'fi-closing': [
      {
        type: 'four-choice',
        question: '決算時にGR/IR勘定の残高を分析し、未着請求・未着品を適切な勘定に振り替えるトランザクションコードはどれか。',
        choices: ['F.19', 'F.07', 'FAGLGVTR', 'OB52'],
        correctIndex: 0,
        explanation: 'F.19です。振り替えた仕訳は翌月初に自動で戻し入れる（洗替）のが一般的です。F.07は補助元帳の残高繰越、FAGLGVTRは総勘定元帳の残高繰越、OB52は転記期間の開閉です。',
      },
      {
        type: 'four-choice',
        question: '年次決算で、総勘定元帳のB/S科目の残高を翌年度に繰り越し、P/L科目を利益剰余金に振り替えるトランザクションコードはどれか。',
        choices: ['FAGLGVTR', 'F.07', 'FAGL_FCV', 'AFAB'],
        correctIndex: 0,
        explanation: 'FAGLGVTRです。仕入先・得意先の補助元帳の残高繰越はF.07で別に行います。FAGL_FCVは外貨評価、AFABは減価償却の実行です。',
      },
      {
        type: 'ox',
        question: '残高繰越は一度しか実行できないため、繰越後に前年度へ追加転記した分は、手作業で翌年度の残高に反映する必要がある。',
        correct: false,
        explanation: '誤りです。残高繰越は何度でも実行でき、繰越後に前年度へ転記した差額も翌年度の繰越残高に反映されます。多くのリリースでは、繰越後の前年度転記は自動的に翌年度へ反映されます。',
      },
      {
        type: 'four-choice',
        question: '貸借対照表・損益計算書の科目の並び順と階層を定義し、財務諸表を出力するために使う設定はどれか。',
        choices: ['財務諸表バージョン（FSV）', '勘定科目グループ', '会計年度バリアント', '項目ステータスグループ'],
        correctIndex: 0,
        explanation: '財務諸表バージョンです。勘定科目を「流動資産」「売上高」などのノードに割り当てて階層を作ります。会社の報告様式や会計基準ごとに複数のバージョンを持てます。',
      },
    ],
    'fi-fx-valuation': [
      {
        type: 'four-choice',
        question: 'SAPの会計伝票で並行して保持される代表的な3つの通貨の組み合わせはどれか。',
        choices: ['伝票通貨・会社コード通貨・グループ通貨', '伝票通貨・支払通貨・請求通貨', '国内通貨・海外通貨・基軸通貨', '計画通貨・実績通貨・予算通貨'],
        correctIndex: 0,
        explanation: '取引が行われた伝票通貨、会社コードの帳簿の通貨である会社コード通貨、連結報告に使うグループ通貨の3つです。外貨取引では伝票通貨の金額を換算して会社コード通貨の金額を持ちます。',
      },
      {
        type: 'four-choice',
        question: 'S/4HANAで、外貨建の未決済明細を期末レートで評価替えする外貨評価のトランザクションコードはどれか。',
        choices: ['FAGL_FCV', 'OB08', 'F.19', 'FAGLGVTR'],
        correctIndex: 0,
        explanation: 'FAGL_FCVです。OB08は為替レートの登録、F.19はGR/IR勘定の分析、FAGLGVTRは総勘定元帳の残高繰越です。',
      },
      {
        type: 'ox',
        question: '外貨建の売掛金を入金で消し込んだときに発生する為替差損益は、未実現差損益に分類される。',
        correct: false,
        explanation: '誤りです。入金や支払で決済が完了した時点で確定する差損益は、実現差損益です。未実現差損益は、期末に未決済のまま残っている明細を評価替えしたときに発生します。',
      },
      {
        type: 'ox',
        question: '為替レートはレートタイプ・通貨ペア・有効開始日の組み合わせで管理され、転記時にはその日付以前で最新の有効なレートが自動で使われる。',
        correct: true,
        explanation: '正しいです。OB08で登録したレートのうち、転記日付時点で有効な最新のレートが適用されます。レートの登録が漏れていると、古いレートで換算されてしまう点に注意が必要です。',
      },
    ],
  },
  en: {
    'fi-overview': [
      {
        type: 'four-choice',
        question: 'In S/4HANA, which table combines FI, CO and New G/L line items into one (the Universal Journal)?',
        choices: ['BSEG', 'COEP', 'ACDOCA', 'FAGLFLEXA'],
        correctIndex: 2,
        explanation: 'ACDOCA is the Universal Journal. In ECC, FI line items sat in BSEG, CO line items in COEP and New G/L line items in FAGLFLEXA; S/4HANA brings them together in ACDOCA.',
      },
      {
        type: 'ox',
        question: 'When a goods receipt is posted in MM, no invoice has arrived yet, so the credit goes to the GR/IR clearing account rather than to accounts payable.',
        correct: true,
        explanation: 'Correct. The goods receipt posts debit inventory, credit GR/IR; invoice verification then posts debit GR/IR, credit payables. Once both are in, the GR/IR balance clears.',
      },
      {
        type: 'four-choice',
        question: 'Which of these is not a component of FI?',
        choices: ['General Ledger (FI-GL)', 'Accounts Payable (FI-AP)', 'Asset Accounting (FI-AA)', 'Production Planning (PP)'],
        correctIndex: 3,
        explanation: 'Production Planning is a separate logistics module, not part of FI. FI is made up of components such as the General Ledger, Accounts Payable, Accounts Receivable and Asset Accounting.',
      },
      {
        type: 'ox',
        question: 'Because FI and CO share the same line items in S/4HANA, the old problem of FI and CO figures drifting apart is structurally far less likely.',
        correct: true,
        explanation: 'Correct. In ECC, FI and CO line items lived in separate tables and had to be reconciled. Sharing one line item in ACDOCA removes most of the room for them to differ.',
      },
    ],
    'fi-company-coa': [
      {
        type: 'four-choice',
        question: 'What is the G/L account that represents the total of a customer or vendor subledger in the general ledger?',
        choices: ['Reconciliation account', 'Clearing account', 'Statistical account', 'Alternative account'],
        correctIndex: 0,
        explanation: 'A reconciliation account. Every subledger posting also updates the reconciliation account assigned in the customer or vendor master, which keeps the subledger and general ledger in agreement.',
      },
      {
        type: 'ox',
        question: 'A reconciliation account can be posted to directly through G/L entry transactions such as FB50.',
        correct: false,
        explanation: 'Incorrect. Reconciliation accounts cannot be posted to directly; they are updated only through postings to the customer or vendor subledger. Direct postings would break the agreement with the subledger.',
      },
      {
        type: 'four-choice',
        question: 'What does an account group mainly control?',
        choices: ['The account number range and field control on the master data screen', 'The exchange rate type used in postings', 'Opening and closing posting periods', 'Default payment terms'],
        correctIndex: 0,
        explanation: 'An account group determines which range of account numbers may be used and which fields are required, optional or hidden when the account master is created.',
      },
      {
        type: 'ox',
        question: 'Whether an account is a balance sheet account or a profit and loss account is specified at chart of accounts level.',
        correct: true,
        explanation: 'Correct. The balance sheet or P&L indicator is set at chart of accounts level, and P&L accounts are linked to the retained earnings account used in year-end carryforward.',
      },
    ],
    'fi-document-types': [
      {
        type: 'ox',
        question: 'On newer entry screens such as FB50 and FB60, users do not need to enter posting keys directly.',
        correct: true,
        explanation: 'Correct. Choosing debit or credit is enough and the posting key is derived automatically. Posted documents displayed in FB03 still show a posting key on every line, so you need to know how to read them.',
      },
      {
        type: 'four-choice',
        question: 'Which standard document type is used for a customer payment?',
        choices: ['KR', 'KZ', 'DR', 'DZ'],
        correctIndex: 3,
        explanation: 'DZ is the standard document type for customer payments. DR is a customer invoice, KR a vendor invoice and KZ a vendor payment.',
      },
      {
        type: 'four-choice',
        question: 'Besides debit or credit and the account type, what else does a posting key control?',
        choices: ['The field status of the line item (required, optional or hidden)', 'The exchange rate applied to the document', 'The fiscal year variant', 'How payment terms are calculated'],
        correctIndex: 0,
        explanation: 'A posting key also controls line item field status, so each key can determine which fields must be entered and which are hidden.',
      },
      {
        type: 'four-choice',
        question: 'Which posting key debits a customer account, for example when posting an invoice?',
        choices: ['01', '15', '31', '40'],
        correctIndex: 0,
        explanation: '01 debits a customer account. 15 credits a customer (for example on payment), 31 credits a vendor and 40 debits a G/L account.',
      },
    ],
    'fi-journal': [
      {
        type: 'four-choice',
        question: 'Which statement correctly describes the document date and the posting date?',
        choices: [
          'The document date is the date on the source document such as an invoice; the posting date determines the period the entry falls into',
          'The document date determines the period; the posting date is the date on the source document',
          'Both are set automatically to the entry date and cannot be changed',
          'The document date and posting date must always be the same',
        ],
        correctIndex: 0,
        explanation: 'The document date is the date shown on the source document, while the posting date decides which accounting period receives the entry. They often differ, for instance when an invoice dated at month end is entered the following month.',
      },
      {
        type: 'four-choice',
        question: 'Which kind of document is saved with a document number but not posted, so that someone else can review it before posting?',
        choices: ['Parked document', 'Held document', 'Recurring entry', 'Reversal document'],
        correctIndex: 0,
        explanation: 'A parked document. It receives a document number when saved and can be displayed, changed and posted by another user, which makes it the basis for approval workflows. A held document is a personal work-in-progress save.',
      },
      {
        type: 'ox',
        question: 'A held document receives an official document number when saved and can be displayed by other users.',
        correct: false,
        explanation: 'Incorrect. A held document temporarily stores an incomplete entry and receives no official document number. To pass a document to someone else for approval, park it instead.',
      },
      {
        type: 'four-choice',
        question: 'Which transaction displays a posted accounting document?',
        choices: ['FB03', 'FB08', 'FB50', 'OB52'],
        correctIndex: 0,
        explanation: 'FB03 displays accounting documents. FB08 reverses a document, FB50 enters a G/L document and OB52 opens and closes posting periods.',
      },
    ],
    'fi-payment-terms': [
      {
        type: 'ox',
        question: 'Posting an invoice with installment payment terms automatically splits it into line items with separate due dates.',
        correct: true,
        explanation: 'Correct. Installment terms divide one invoice, for example 40% due in 30 days and 60% in 60 days, and a line item with its own due date is created for each part.',
      },
      {
        type: 'four-choice',
        question: 'Which method records an invoice at its full amount and books any cash discount taken as income at payment?',
        choices: ['Gross method', 'Net method', 'Straight-line method', 'Declining balance method'],
        correctIndex: 0,
        explanation: 'The gross method. The net method records the discounted amount and expenses any discount that is missed. Straight-line and declining balance are depreciation methods.',
      },
      {
        type: 'four-choice',
        question: 'Which pair of things do payment terms define?',
        choices: ['How the due date is calculated, and the cash discount conditions', 'The payment method and house bank', 'The exchange rate type and currency', 'The credit limit and dunning levels'],
        correctIndex: 0,
        explanation: 'Payment terms define when payment is due and what discount applies for paying early. Payment methods and house banks belong to the payment program configuration.',
      },
      {
        type: 'ox',
        question: 'An invoice with a payment block is still paid by F110 once its due date has arrived.',
        correct: false,
        explanation: 'Incorrect. Items carrying a payment block are excluded from the payment run. The block exists precisely to hold payment, for example while a quality issue is resolved, until it is removed.',
      },
    ],
    'fi-ap': [
      {
        type: 'four-choice',
        question: 'Which transaction posts a vendor invoice with reference to a purchase order and goods receipt?',
        choices: ['MIRO', 'FB60', 'F110', 'XK01'],
        correctIndex: 0,
        explanation: 'MIRO is MM invoice verification, which posts the invoice against the purchase order and goods receipt. FB60 posts invoices without a purchase order directly in FI.',
      },
      {
        type: 'ox',
        question: 'In S/4HANA, the vendor master and customer master are unified in the Business Partner.',
        correct: true,
        explanation: 'Correct. A trading partner that was both vendor and customer once needed two separate masters; in S/4HANA it is managed as a single Business Partner.',
      },
      {
        type: 'four-choice',
        question: 'Which three things are compared in a three-way match?',
        choices: ['Purchase order, goods receipt and invoice', 'Purchase requisition, purchase order and payment', 'Quotation, purchase order and invoice', 'Goods receipt, goods issue and physical inventory'],
        correctIndex: 0,
        explanation: 'The purchase order (what was ordered at what price), the goods receipt (what actually arrived) and the invoice (what was charged). Invoices with quantity or price differences are blocked for payment.',
      },
      {
        type: 'four-choice',
        question: 'Which mechanism keeps down payments to vendors separate from ordinary payables?',
        choices: ['Special G/L transaction', 'Recurring entry', 'Parked document', 'Installment payment terms'],
        correctIndex: 0,
        explanation: 'A special G/L transaction. Posting with a special G/L indicator routes the amount to an alternative reconciliation account for down payments. A down payment is an asset and should not be netted against payables, which are liabilities.',
      },
    ],
    'fi-ar': [
      {
        type: 'four-choice',
        question: 'Which transaction creates an SD billing document that automatically posts a receivable in FI?',
        choices: ['VF01', 'FB70', 'F150', 'VKM1'],
        correctIndex: 0,
        explanation: 'VF01 creates a billing document in SD, and releasing it to accounting posts the receivable and revenue in FI. FB70 enters a customer invoice directly in FI, F150 runs dunning and VKM1 releases credit-blocked orders.',
      },
      {
        type: 'four-choice',
        question: 'When only part of an invoice is paid, which method clears the original item and creates a new open item for the unpaid difference?',
        choices: ['Residual item', 'Partial payment', 'Dunning', 'Reversal'],
        correctIndex: 0,
        explanation: 'The residual item method. A partial payment leaves the original item open with the payment linked to it. Because a residual item is a new item, its baseline date can reset, changing when dunning starts.',
      },
      {
        type: 'ox',
        question: 'In S/4HANA, the classic FI-AR credit management has been retired in favour of FSCM Credit Management.',
        correct: true,
        explanation: 'Correct. Credit management in S/4HANA runs in FSCM (Financial Supply Chain Management) Credit Management, which allows more flexible rules such as credit scoring.',
      },
      {
        type: 'four-choice',
        question: 'Which transaction runs dunning?',
        choices: ['F150', 'F110', 'FBL5N', 'VKM1'],
        correctIndex: 0,
        explanation: 'F150 runs dunning. F110 is the payment program, FBL5N displays customer line items and VKM1 releases sales orders held by a credit block.',
      },
    ],
    'fi-asset': [
      {
        type: 'ox',
        question: 'The mechanism that keeps several book values for one asset in parallel, for example for financial reporting and for tax, is called a depreciation area.',
        correct: true,
        explanation: 'Correct. For example, one area can depreciate straight-line over ten years for accounting while another uses declining balance over eight years for tax.',
      },
      {
        type: 'four-choice',
        question: 'Which transaction shows, on one screen, an asset’s acquisition value, accumulated depreciation, book value and planned depreciation for each depreciation area?',
        choices: ['AW01N', 'AS01', 'AFAB', 'ABAVN'],
        correctIndex: 0,
        explanation: 'AW01N, the Asset Explorer. AS01 creates an asset master, AFAB runs depreciation and ABAVN retires an asset by scrapping. AW01N is the first place to look when asking why depreciation came out as it did.',
      },
      {
        type: 'ox',
        question: 'Depreciation from every depreciation area is always posted to the general ledger.',
        correct: false,
        explanation: 'Incorrect. Tax areas are commonly calculated but not posted, and used only to prepare tax returns. Whether an area posts to the general ledger is set per area.',
      },
      {
        type: 'four-choice',
        question: 'Together with the depreciation key, which asset master field lets the system calculate depreciation for each period?',
        choices: ['Useful life', 'Asset number', 'Document type', 'Posting key'],
        correctIndex: 0,
        explanation: 'Useful life. The depreciation key sets the method and the useful life sets the period, and together they determine each period’s depreciation. Useful life can differ by depreciation area.',
      },
    ],
    'fi-closing': [
      {
        type: 'four-choice',
        question: 'At period end, which transaction analyses the GR/IR balance and reclassifies goods received not invoiced and invoices received not delivered?',
        choices: ['F.19', 'F.07', 'FAGLGVTR', 'OB52'],
        correctIndex: 0,
        explanation: 'F.19. The reclassification is normally reversed automatically at the start of the next month. F.07 carries forward subledger balances, FAGLGVTR carries forward G/L balances and OB52 opens and closes periods.',
      },
      {
        type: 'four-choice',
        question: 'At year end, which transaction carries forward balance sheet balances in the general ledger and transfers P&L accounts to retained earnings?',
        choices: ['FAGLGVTR', 'F.07', 'FAGL_FCV', 'AFAB'],
        correctIndex: 0,
        explanation: 'FAGLGVTR. Vendor and customer subledger balances are carried forward separately with F.07. FAGL_FCV is foreign currency valuation and AFAB runs depreciation.',
      },
      {
        type: 'ox',
        question: 'Balance carryforward can only be run once, so anything posted to the prior year afterwards must be added to the new year’s balances by hand.',
        correct: false,
        explanation: 'Incorrect. Balance carryforward can be run as often as needed, and postings made to the prior year after carryforward are reflected in the new year’s opening balances.',
      },
      {
        type: 'four-choice',
        question: 'Which setting defines the order and hierarchy of balance sheet and P&L items for producing financial statements?',
        choices: ['Financial statement version (FSV)', 'Account group', 'Fiscal year variant', 'Field status group'],
        correctIndex: 0,
        explanation: 'The financial statement version. Accounts are assigned to nodes such as current assets or revenue to build the hierarchy, and several versions can exist for different reporting formats or accounting standards.',
      },
    ],
    'fi-fx-valuation': [
      {
        type: 'four-choice',
        question: 'Which three currencies are typically held in parallel on an SAP accounting document?',
        choices: ['Document currency, company code currency and group currency', 'Document currency, payment currency and invoice currency', 'Domestic, foreign and reserve currency', 'Plan, actual and budget currency'],
        correctIndex: 0,
        explanation: 'The document currency the transaction was in, the company code currency the books are kept in, and the group currency used for consolidated reporting. For foreign currency transactions the document currency amount is translated into company code currency.',
      },
      {
        type: 'four-choice',
        question: 'In S/4HANA, which transaction revalues open foreign currency items at the period-end rate?',
        choices: ['FAGL_FCV', 'OB08', 'F.19', 'FAGLGVTR'],
        correctIndex: 0,
        explanation: 'FAGL_FCV. OB08 maintains exchange rates, F.19 analyses the GR/IR account and FAGLGVTR carries forward G/L balances.',
      },
      {
        type: 'ox',
        question: 'An exchange difference arising when a foreign currency receivable is cleared by a payment is an unrealised gain or loss.',
        correct: false,
        explanation: 'Incorrect. A difference fixed by settlement through payment or receipt is realised. Unrealised differences arise when items still open at period end are revalued.',
      },
      {
        type: 'ox',
        question: 'Exchange rates are held by rate type, currency pair and valid-from date, and a posting automatically uses the latest rate valid on or before its date.',
        correct: true,
        explanation: 'Correct. Of the rates maintained in OB08, the latest one valid at the posting date is applied. If a rate has not been entered, an older rate will be used without warning, so maintenance must be kept up to date.',
      },
    ],
  },
};
