import type { ModuleContent } from '../learning-types';

export const fi: Record<'ja' | 'en', ModuleContent> = {
  ja: {
    id: 'fi',
    title: '財務会計（FI）',
    description: 'SAPにおける財務会計の基礎を学びます',
    sections: [
      {
        id: 'fi-overview',
        title: 'FIモジュール概要',
        content: [
          'FI（Financial Accounting / 財務会計）は、SAPにおける財務会計を担うコアモジュールです。企業の財務取引をリアルタイムで記録し、貸借対照表（B/S）や損益計算書（P/L）などの財務諸表を自動生成します。',
          'FIはCO（管理会計）・MM（購買・在庫管理）・SD（販売管理）など他のモジュールと密接に連携しており、各モジュールでの業務処理がFIに自動転記される仕組みになっています。FIとCOは特に一体的に使われることが多く、「FI/CO」と並べて表記されることもあります。',
        ],
        quizzes: [
          {
            type: 'ox',
            question: 'FIモジュールは財務会計を担当し、貸借対照表や損益計算書などの財務諸表の作成をサポートする。',
            correct: true,
            explanation: '正しいです。FIはFinancial Accountingの略で、財務諸表の自動生成はFIの主要機能のひとつです。',
          },
          {
            type: 'four-choice',
            question: 'FIが特に密接に連携しているモジュールはどれか。',
            choices: ['HR（人事管理）', 'CO（管理会計）', 'PS（プロジェクト管理）', 'QM（品質管理）'],
            correctIndex: 1,
            explanation: 'FIとCOは財務管理という観点で一体的に扱われることが多く、「FI/CO」と表記されることもあります。MMやSDもFIと連携しますが、最も密接なのはCOです。',
          },
          {
            type: 'ox',
            question: 'FIモジュールは財務取引をリアルタイムで記録し、転記と同時に財務諸表の数値が更新される。',
            correct: true,
            explanation: 'その通りです。SAPは仕訳転記と同時に財務諸表へ反映されるリアルタイム処理が特徴です。バッチ処理で後から集計するのではなく、転記の瞬間に残高が更新されます。',
          },
          {
            type: 'four-choice',
            question: 'MMモジュールで商品の入庫処理が行われた際、FIに自動転記される勘定の組み合わせはどれか。',
            choices: ['売上高と未払費用', '在庫勘定と買掛金（照合）勘定', '現金勘定と前払費用', '売掛金と売上収益'],
            correctIndex: 1,
            explanation: 'MM入庫時には「在庫勘定（借方）と買掛金照合勘定（貸方）」がFIに自動転記されます。このようにMMの業務処理がFIへリアルタイムで反映される仕組みがSAPの特徴です。',
          },
          {
            type: 'four-choice',
            question: 'SAPのFIモジュールが採用している記帳方式はどれか。',
            choices: ['単式簿記', '複式簿記', '三式簿記', 'キャッシュベース会計'],
            correctIndex: 1,
            explanation: 'SAPのFIは複式簿記を採用しており、すべての取引は借方と貸方の両面から記録されます。借方合計と貸方合計は常に一致しなければなりません。',
          },
          {
            type: 'ox',
            question: '一度転記された会計伝票は、直接上書きして修正することができる。',
            correct: false,
            explanation: '不正解です。転記済みの会計伝票は直接修正できません。誤りがあった場合は逆転記（反対仕訳）を入力するか、個別の修正処理を行う必要があります。これは監査証跡を守るための重要な原則です。',
          },
        ],
      },
      {
        id: 'fi-company-coa',
        title: '会社コードと勘定科目',
        content: [
          '会社コード（Company Code）はSAPにおける独立した会計単位です。1つの会社コードに対して1セットの財務諸表が作成されます。グループ企業では複数の会社コードを持つことが一般的です。',
          '勘定科目マスタは「勘定科目表（Chart of Accounts）レベル」と「会社コードレベル」の2層構造になっています。勘定科目表は複数の会社コードで共有できるため、グループ全体で統一した科目体系を使うことが可能です。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '1つの会社コードに対して作成される財務諸表は何セットか。',
            choices: ['0セット', '1セット', '2セット', '会社コード数に依存する'],
            correctIndex: 1,
            explanation: '会社コードはSAPの独立した会計単位であり、1会社コードに対して1セットの財務諸表が作成されます。',
          },
          {
            type: 'ox',
            question: '勘定科目表（Chart of Accounts）は、1つの会社コードにしか割り当てられない。',
            correct: false,
            explanation: '不正解です。勘定科目表は複数の会社コードで共有できます。これにより、グループ企業で統一した科目体系を使うことができます。',
          },
          {
            type: 'ox',
            question: '1つの会社コードに割り当てられる勘定科目表（Chart of Accounts）は1つのみである。',
            correct: true,
            explanation: 'その通りです。1つの会社コードに割り当てられる勘定科目表は1つだけです。ただし、同一の勘定科目表を複数の会社コードで共有することは可能です。',
          },
          {
            type: 'four-choice',
            question: '勘定科目マスタの「会社コードレベル」で管理される情報はどれか。',
            choices: ['勘定科目番号', '勘定科目名称（短テキスト）', '税区分や照合勘定タイプ', '勘定科目グループ'],
            correctIndex: 2,
            explanation: '会社コードレベルでは税区分・照合勘定タイプ（仕入先/得意先用かどうか）・通貨・残高照合コードなど、各会社固有の設定を管理します。勘定科目番号・名称・グループは勘定科目表レベルで管理されます。',
          },
          {
            type: 'four-choice',
            question: 'グループ企業全体の連結財務諸表作成に使用する統一の勘定科目体系を何と呼ぶか。',
            choices: ['業務用勘定科目表', '国別勘定科目表', '連結勘定科目表', '代替勘定科目表'],
            correctIndex: 2,
            explanation: '連結勘定科目表（Group Chart of Accounts）は、グループ全社で統一して使用する科目体系です。各会社コードの業務用勘定科目表の科目を連結勘定科目表の科目にマッピングすることで、連結財務諸表の作成を効率化します。',
          },
          {
            type: 'four-choice',
            question: 'SAPにおける「事業領域（Business Area）」の説明として最も適切なものはどれか。',
            choices: ['法的に独立した会計単位', '物理的な工場や倉庫の単位', '複数の会社コードにまたがって損益分析ができる内部区分', '仕入先を分類するための組織単位'],
            correctIndex: 2,
            explanation: '事業領域（Business Area）は、事業部門や製品ラインごとの損益分析を目的とした内部区分です。複数の会社コードにまたがって損益分析が可能な点が特徴です。法的な会計単位は会社コードです。',
          },
        ],
      },
      {
        id: 'fi-document-types',
        title: '伝票タイプと転記キー',
        content: [
          '伝票タイプ（Document Type）は会計伝票を業務区分ごとに分類するためのキーです。主な標準伝票タイプとして、KR（仕入先請求書）・KZ（仕入先支払）・DR（得意先請求書）・DZ（得意先入金）・SA（G/L転記）などがあります。伝票タイプは伝票番号の番号範囲も制御します。',
          '転記キー（Posting Key）は各行明細の「借方・貸方の区分」と「使用できる勘定タイプ（G/L・仕入先・得意先・資産）」を制御する2桁のコードです。主な転記キーとして、G/L勘定には40（借方）と50（貸方）、仕入先勘定には31（貸方）と25（借方）、得意先勘定には01（借方）と15（貸方）があります。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '仕入先への支払（Vendor Payment）を表す標準伝票タイプはどれか。',
            choices: ['KR', 'KZ', 'DZ', 'SA'],
            correctIndex: 1,
            explanation: 'KZは仕入先支払（Vendor Payment）の標準伝票タイプです。KRは仕入先請求書（Vendor Invoice）、DZは得意先入金（Customer Payment）、SAはG/L転記です。',
          },
          {
            type: 'ox',
            question: '転記キーは借方・貸方の区分だけでなく、使用できる勘定タイプ（G/L・仕入先・得意先など）も制御する。',
            correct: true,
            explanation: 'その通りです。たとえば転記キー31は仕入先勘定の貸方にのみ使用でき、G/L勘定には使えません。転記キーの設定によって入力ミスを防ぐ効果があります。',
          },
          {
            type: 'four-choice',
            question: 'G/L勘定への借方転記に使用する転記キーはどれか。',
            choices: ['25', '31', '40', '50'],
            correctIndex: 2,
            explanation: '転記キー40はG/L勘定の借方転記に使用します。50はG/L貸方、31は仕入先貸方（仕入先請求書計上時）、25は仕入先借方（支払時など）です。',
          },
          {
            type: 'four-choice',
            question: '得意先（Customer）への請求書を表す標準伝票タイプはどれか。',
            choices: ['KR', 'SA', 'DR', 'DZ'],
            correctIndex: 2,
            explanation: 'DRは得意先請求書（Customer Invoice）の標準伝票タイプです。KRは仕入先請求書、SAはG/L転記、DZは得意先入金（Customer Payment）です。',
          },
          {
            type: 'ox',
            question: '伝票タイプ（Document Type）は、会計伝票の業務区分の分類だけでなく、伝票番号の番号範囲も制御する。',
            correct: true,
            explanation: 'その通りです。伝票タイプには番号範囲（Number Range）が割り当てられており、転記時の伝票番号採番を制御します。伝票タイプごとに異なる番号体系を使うことが可能です。',
          },
          {
            type: 'four-choice',
            question: '仕入先請求書（FB60）を転記する際、仕入先勘定の貸方に使用する転記キーはどれか。',
            choices: ['25', '31', '40', '50'],
            correctIndex: 1,
            explanation: '転記キー31は仕入先勘定の貸方転記に使用します。仕入先への請求書計上では仕入先勘定を貸方（31）に、費用勘定を借方（40）に転記します。25は仕入先借方、40はG/L借方、50はG/L貸方です。',
          },
        ],
      },
      {
        id: 'fi-journal',
        title: '仕訳伝票の入力',
        content: [
          'SAPでは全ての会計処理は「仕訳伝票」として記録されます。伝票には借方（Debit）と貸方（Credit）があり、複式簿記の原則に従い両者の合計金額は必ず一致します。',
          '仕訳伝票の入力には主にFB50（一般転記）などのトランザクションを使用します。入力後に「保存」すると伝票番号が採番され、会計への転記が完了します。',
        ],
        quizzes: [
          {
            type: 'ox',
            question: '仕訳伝票において、借方合計と貸方合計は必ず一致しなければならない。',
            correct: true,
            explanation: 'これは複式簿記の基本原則です。SAPでは借方・貸方の合計が一致しない場合、伝票の保存ができない仕組みになっています。',
          },
          {
            type: 'ordering',
            question: 'FB50を使った仕訳伝票入力の手順を正しい順番に並べなさい。',
            items: [
              '伝票の保存',
              'FB50を起動する',
              '借方・貸方の勘定科目を入力する',
              '伝票日付・会社コードを入力する',
              '各行の金額を入力する',
            ],
            correctOrder: [1, 3, 2, 4, 0],
            explanation: '正しい手順は①FB50起動 → ②伝票日付・会社コード入力 → ③勘定科目入力 → ④金額入力 → ⑤保存です。日付と会社コードはヘッダ情報として最初に入力します。',
          },
          {
            type: 'four-choice',
            question: '仕訳伝票の「ヘッダデータ」に含まれる情報はどれか。',
            choices: ['勘定科目番号', '伝票日付・転記日付・会社コード', '各行明細の金額', '仕入先コード'],
            correctIndex: 1,
            explanation: '伝票ヘッダには伝票日付・転記日付・会社コード・通貨・参照番号などが含まれます。勘定科目番号・金額・仕入先/得意先コードは行明細（Line Item）レベルの情報です。',
          },
          {
            type: 'ox',
            question: '転記済みの会計伝票を修正する場合、逆転記（Reversal）を入力して元の伝票の効果を打ち消す方法が標準的な手順である。',
            correct: true,
            explanation: 'その通りです。転記済み伝票は直接修正できないため、逆転記（元の仕訳の反対仕訳）を入力してキャンセルし、必要に応じて正しい内容で再転記するのが標準手順です。',
          },
          {
            type: 'four-choice',
            question: '会計伝票の「計上期間（Posting Period）」を決定するのは何か。',
            choices: ['伝票日付', '転記日付', '入力日付', '請求書日付'],
            correctIndex: 1,
            explanation: '計上期間は転記日付によって決まります。たとえば転記日付が2025年3月31日なら第3期（3月）に計上されます。伝票日付は取引の実際の発生日で、計上期間の決定には使われません。',
          },
          {
            type: 'four-choice',
            question: '転記済み伝票を逆転記（Reverse Posting）する際に使用するトランザクションコードはどれか。',
            choices: ['FB50', 'FB60', 'FB08', 'FBL3N'],
            correctIndex: 2,
            explanation: 'FB08は転記済み伝票の逆転記（Reverse Document Posting）に使用します。FB50は一般転記、FB60は仕入先請求書の転記、FBL3Nは総勘定元帳明細の照会です。',
          },
        ],
      },
      {
        id: 'fi-payment-terms',
        title: '支払条件と支払基準日',
        content: [
          '支払条件（Payment Terms）は、請求書の支払期限と現金割引（Cash Discount）条件を定義します。「30日以内に全額払い」や「10日以内なら2%割引、30日以内に全額払い」のように設定します。支払条件コードは仕入先マスタ・得意先マスタに登録でき、伝票転記時に自動提案されます。',
          '支払条件の期限計算の基準となる日付を「支払基準日（Baseline Date）」と呼びます。支払基準日は伝票日付・転記日付・請求書日付・入力日付のいずれかを採用でき、この日付から現金割引期限・正味支払期日が算出されます。特定の請求書を自動支払の対象から除外したい場合は「支払ブロック（Payment Block）」を設定します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '支払条件の期限計算の基準となる日付を何と呼ぶか。',
            choices: ['転記日付', '支払基準日（Baseline Date）', '決済確定日', '請求確認日'],
            correctIndex: 1,
            explanation: '支払基準日（Baseline Date）は支払期限・現金割引期限の起算日です。伝票日付・転記日付・請求書日付などから選択して設定でき、誤った基準日は支払期限の計算誤りに直結します。',
          },
          {
            type: 'ox',
            question: '現金割引（Cash Discount）は、定められた割引期限内に支払った場合に適用される値引きである。',
            correct: true,
            explanation: 'その通りです。たとえば「10日以内2%割引・30日以内全額」の条件では、10日以内に支払うと請求額から2%が割り引かれます。仕入先側では現金割引費用、得意先側では現金割引収益として処理されます。',
          },
          {
            type: 'four-choice',
            question: '特定の仕入先請求書を自動支払（F110）の対象から除外するために設定する機能はどれか。',
            choices: ['現金割引率の変更', '支払ブロック（Payment Block）の設定', '伝票タイプの変更', '支払基準日の延長'],
            correctIndex: 1,
            explanation: '支払ブロック（Payment Block）を請求書に設定することで、その請求書を自動支払プログラム（F110）の対象から除外できます。支払に関する異議申立や確認待ちの際に使用します。',
          },
          {
            type: 'ox',
            question: '支払条件（Payment Terms）は仕入先マスタだけでなく、得意先マスタにも設定することができる。',
            correct: true,
            explanation: 'その通りです。支払条件は仕入先マスタと得意先マスタの両方に設定できます。得意先マスタの支払条件は売上請求書の支払期限計算に使用されます。',
          },
          {
            type: 'four-choice',
            question: '支払条件「14日以内2%現金割引・30日以内全額支払」の場合、請求金額10,000円を5日目に支払うといくらか。',
            choices: ['10,000円', '10,200円', '9,800円', '8,000円'],
            correctIndex: 2,
            explanation: '5日目は14日以内なので2%の現金割引が適用されます。10,000円 × (1 − 0.02) = 9,800円となります。現金割引期限内に支払うと割引分が差し引かれます。',
          },
          {
            type: 'four-choice',
            question: '自動支払プログラム（F110）の実行時、支払期日がまだ到来していない請求書はどのように扱われるか。',
            choices: ['エラーとして除外され警告が表示される', '強制的に支払対象に含まれる', '次回の支払実行まで選択されない', '自動的に支払ブロックが設定される'],
            correctIndex: 2,
            explanation: '支払期日未到来の請求書は支払提案に含まれず、次回の支払実行時（支払期日が到来した後）に初めて選択対象となります。これにより早払いを防止できます。',
          },
        ],
      },
      {
        id: 'fi-ap',
        title: '買掛金管理（FI-AP）',
        content: [
          '買掛金管理（Accounts Payable / FI-AP）では仕入先への支払業務を管理します。仕入先請求書はFB60トランザクション（直接FI転記）で登録します。転記と同時に仕入先サブ元帳と照合勘定（Reconciliation Account）に自動反映されます。照合勘定への直接転記はできず、常にサブ元帳経由で総勘定元帳に集計されます。',
          '仕入先への支払は「自動支払プログラム（F110）」で効率的に処理できます。F110ではまず支払パラメータ（会社コード・支払日・対象勘定など）を設定し、「支払提案（Payment Proposal）」を実行します。提案内容を確認・修正したうえで「支払実行（Payment Run）」を行い、最後に振込ファイルや支払媒体が出力されます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '直接FIで仕入先請求書を転記するトランザクションコードはどれか。',
            choices: ['MIRO', 'FB60', 'F-28', 'FBL1N'],
            correctIndex: 1,
            explanation: 'FB60は仕入先請求書の直接FI転記に使用します。MIROはMM連携（3点照合）での請求照合、F-28は得意先からの入金処理、FBL1Nは仕入先元帳照会です。',
          },
          {
            type: 'ordering',
            question: 'F110自動支払プログラムの実行手順を正しい順番に並べなさい。',
            items: [
              '支払実行（Payment Run）',
              'F110起動・パラメータ設定',
              '支払提案の確認・修正',
              '支払提案の実行（Proposal Run）',
            ],
            correctOrder: [1, 3, 2, 0],
            explanation: '正しい順序は ①F110起動・パラメータ設定 → ②支払提案の実行 → ③支払提案の確認・修正 → ④支払実行 です。提案で対象請求書を確認・除外できるため、実行前に必ず内容を確認します。',
          },
          {
            type: 'ox',
            question: '仕入先ごとの買掛金明細を照会するトランザクションFBL1Nでは、未決済・決済済みそれぞれの明細を絞り込んで照会できる。',
            correct: true,
            explanation: 'その通りです。FBL1Nでは未決済明細（Open Items）・決済済み明細（Cleared Items）・全明細を選択して照会できます。個別の支払状況の確認や残高確認に使用します。',
          },
          {
            type: 'ox',
            question: 'FB60で仕入先請求書を転記すると、仕入先サブ元帳と照合勘定（Reconciliation Account / 総勘定元帳）が同時に更新される。',
            correct: true,
            explanation: 'その通りです。仕入先サブ元帳への転記と同時に、仕入先マスタに設定された照合勘定（G/L勘定）が自動更新されます。照合勘定への直接転記はできないため、常にサブ元帳経由で集計されます。',
          },
          {
            type: 'four-choice',
            question: 'F110の支払提案に請求書が含まれない理由として考えられないものはどれか。',
            choices: ['支払ブロックが設定されている', '支払期日が未到来', '支払方法マスタが未設定', '仕入先の住所が未登録'],
            correctIndex: 3,
            explanation: '支払提案から除外される主な理由は①支払ブロック設定②支払期日未到来③支払方法（銀行振込など）マスタ未設定④与信限度額超過などです。仕入先住所の未登録は支払提案の除外理由にはなりません。',
          },
          {
            type: 'four-choice',
            question: 'F110の支払実行後に出力される「支払媒体（Payment Medium）」の主な用途はどれか。',
            choices: ['仕入先への請求書の送付', '銀行への振込指示ファイルや小切手の出力', '得意先への督促状の送付', '固定資産の減価償却計算'],
            correctIndex: 1,
            explanation: '支払媒体は銀行への振込指示ファイル（DME）や小切手などの出力物です。これを銀行に提出することで実際の送金が行われます。得意先への督促はF150、固定資産の償却はAFABです。',
          },
        ],
      },
      {
        id: 'fi-ar',
        title: '売掛金管理（FI-AR）',
        content: [
          '売掛金管理（Accounts Receivable / FI-AR）では得意先からの入金と債権管理を担います。得意先からの入金はF-28などのトランザクションで処理し、入金額に対応するオープン明細（未決済項目）と照合する「消込（Clearing）」を行います。消込が完了すると未決済明細がクローズされ、売掛金残高が減少します。',
          '与信管理（Credit Management）では得意先ごとに与信限度額を設定し、受注時に自動チェックします。与信限度額を超えた受注は自動ブロックされます。支払期限を過ぎても入金のない得意先には「督促処理（Dunning）」を実行し、督促状を段階的に送付します。督促レベルを複数設定することで、滞留期間に応じたエスカレーション対応が可能です。',
        ],
        quizzes: [
          {
            type: 'ox',
            question: '得意先から入金を受け取り、対応する未払い請求書（オープン明細）と照合・クローズする処理を「消込（Clearing）」と呼ぶ。',
            correct: true,
            explanation: 'その通りです。消込処理によって未決済項目がクローズされ、売掛金残高が減少します。入金額と請求金額が一致しない場合は差額（端数・割引など）の処理が必要です。',
          },
          {
            type: 'four-choice',
            question: '得意先の与信限度額を設定・管理するトランザクションコードはどれか。',
            choices: ['FBL5N', 'FD32', 'F150', 'F-28'],
            correctIndex: 1,
            explanation: 'FD32は得意先の与信限度額設定に使用します。FBL5Nは得意先元帳明細照会、F150は督促処理の実行、F-28は入金処理です。',
          },
          {
            type: 'four-choice',
            question: '督促処理（Dunning）の目的として最も適切なものはどれか。',
            choices: [
              '仕入先への支払を自動的に実行する',
              '支払期限を過ぎた得意先に督促状を送付し、未収金の回収を促す',
              '固定資産の減価償却を自動的に計上する',
              '外貨建残高を期末レートで再評価する',
            ],
            correctIndex: 1,
            explanation: '督促処理（Dunning）は、支払期限を過ぎた売掛金の回収を促すために得意先に督促状を送付するプロセスです。督促レベルに応じて督促文面・督促費用・督促利息を段階的に設定できます。',
          },
          {
            type: 'four-choice',
            question: '得意先から請求金額を超える過入金があった場合の処理として適切なものはどれか。',
            choices: ['差額を即座に雑収入として計上する', '入金全額を売上として計上する', '過入金分を貸方残高として残し、次回請求時に充当するか得意先に返金する', '入金伝票を取り消して再入力する'],
            correctIndex: 2,
            explanation: '過入金の場合、超過分は得意先勘定の貸方残高として残ります。次回の請求書と相殺（充当）するか、得意先に返金するかを決定します。単純に雑収入計上したり取消再入力したりするのは適切ではありません。',
          },
          {
            type: 'ox',
            question: '督促処理（Dunning）では複数の督促レベルを設定でき、レベルごとに異なる督促費用や督促利息を設定することができる。',
            correct: true,
            explanation: 'その通りです。督促レベル1（初回督促）から最大レベル（法的手続等）まで段階的に設定でき、各レベルで督促状のテキスト・督促費用・督促利息を個別に設定できます。',
          },
          {
            type: 'four-choice',
            question: '得意先元帳照会トランザクション FBL5N で確認できないものはどれか。',
            choices: ['未決済（未払い）の請求書一覧', '決済済みの入金明細', '督促レベルの状況', '得意先との売買契約書の内容'],
            correctIndex: 3,
            explanation: 'FBL5Nでは未決済・決済済み・督促レベルなどの売掛金明細を照会できます。ただし、売買契約書の内容はSAPのFI機能では管理されず、FBL5Nでは確認できません。',
          },
        ],
      },
      {
        id: 'fi-asset',
        title: '固定資産会計（FI-AA）',
        content: [
          '固定資産会計（Asset Accounting / FI-AA）は固定資産の取得から除却までのライフサイクルを管理するFIのサブモジュールです。固定資産マスタはAS01で作成します。資産クラス（Asset Class）は固定資産をグループ化する区分で、デフォルトの減価償却キー・耐用年数・総勘定元帳への転記先を定義します。',
          '減価償却キー（Depreciation Key）は減価償却の計算方法（定額法・定率法など）を定義するマスタデータです。耐用年数（Useful Life）と組み合わせて毎月の償却額が自動計算されます。固定資産の取得時はF-90（仕入先からの購入）などで転記し、除却（Retirement）はABAVNなどで処理します。減価償却の月次自動転記にはAFABを使用します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '固定資産マスタを新規作成するトランザクションコードはどれか。',
            choices: ['F-90', 'ABAVN', 'AS01', 'AFAB'],
            correctIndex: 2,
            explanation: 'AS01は固定資産マスタの新規作成に使用します。F-90は仕入先からの資産取得の転記、ABAVNは廃棄による除却処理、AFABは減価償却の自動転記です。',
          },
          {
            type: 'ox',
            question: '資産クラス（Asset Class）はデフォルトの減価償却キーや耐用年数を定義し、同じ資産クラスの固定資産は同じ減価償却条件が適用される。',
            correct: true,
            explanation: 'その通りです。資産クラスには減価償却キー・耐用年数・転記先G/L勘定などのデフォルト値が設定されており、同じ資産クラスの資産は同じ条件で減価償却が行われます。',
          },
          {
            type: 'four-choice',
            question: '固定資産の減価償却の計算方法（定額法・定率法など）を定義するマスタデータはどれか。',
            choices: ['資産クラス', '耐用年数', '減価償却キー（Depreciation Key）', '償却領域'],
            correctIndex: 2,
            explanation: '減価償却キー（Depreciation Key）が減価償却の計算方法を定義します。耐用年数は資産クラスに設定される「何年で償却するか」の年数で、減価償却キーと組み合わせて毎月の償却額が計算されます。',
          },
          {
            type: 'four-choice',
            question: '仕入先から固定資産を購入した際の取得転記に使用するトランザクションコードはどれか。',
            choices: ['AS01', 'ABAVN', 'AFAB', 'F-90'],
            correctIndex: 3,
            explanation: 'F-90は仕入先から固定資産を購入した際の取得転記（Asset Acquisition from Vendor）に使用します。AS01は資産マスタ作成、ABAVNは廃棄除却、AFABは減価償却の自動転記です。',
          },
          {
            type: 'ox',
            question: 'AFABで減価償却の自動転記を実行すると、固定資産の帳簿価額（Book Value）が減少する。',
            correct: true,
            explanation: 'その通りです。AFABによる減価償却転記では「減価償却費（費用）の借方」と「減価償却累計額（資産の控除項目）の貸方」が計上され、資産の帳簿価額（取得原価−減価償却累計額）が減少します。',
          },
          {
            type: 'four-choice',
            question: '固定資産を廃棄（スクラップ）により除却する際に使用するトランザクションコードはどれか。',
            choices: ['AS01', 'F-90', 'ABAVN', 'AFAB'],
            correctIndex: 2,
            explanation: 'ABAVNは廃棄（Retirement by Scrapping）による固定資産の除却処理に使用します。AS01は資産マスタ作成、F-90は仕入先からの資産取得、AFABは月次減価償却の自動転記です。',
          },
        ],
      },
      {
        id: 'fi-closing',
        title: '期末決算処理',
        content: [
          '期末決算（月次・年次）ではFIで様々な処理が行われます。代表的なものとして、固定資産の減価償却自動計上・外貨評価・引当金計上などがあります。これらの処理は通常、決算担当者が定められた手順で実行します。',
          'SAPでは決算処理のための専用トランザクションが用意されています。処理の順序を誤ると財務諸表の数値が正しくならないため、決算手順の把握が重要です。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '固定資産の減価償却を自動計上する際に使用するトランザクションコードはどれか。',
            choices: ['FB50', 'AFAB', 'F-02', 'FBL3N'],
            correctIndex: 1,
            explanation: 'AFABは減価償却の自動転記（Automatic Posting of Depreciation）に使用するトランザクションです。FB50は一般転記、F-02は一般仕訳入力、FBL3Nは総勘定元帳の照会です。',
          },
          {
            type: 'ordering',
            question: '月次決算の主要処理を正しい順番に並べなさい。',
            items: [
              '会計期間をクローズする',
              '財務諸表で結果を確認する',
              '外貨評価・減価償却を実行する',
            ],
            correctOrder: [2, 1, 0],
            explanation: '正しい順序は①外貨評価・減価償却などの自動処理実行 → ②財務諸表で結果確認 → ③会計期間のクローズです。期間をクローズすると追加入力ができなくなるため、確認後に実施します。',
          },
          {
            type: 'ox',
            question: 'SAPでは複数の会計期間を同時にオープン状態にしておくことができる。',
            correct: true,
            explanation: 'その通りです。SAPでは通常、当月と前月の2期間を同時にオープンにして、前月分の遅延転記に対応することが多いです。会計期間の管理はOB52で行います。',
          },
          {
            type: 'four-choice',
            question: '経過勘定（Accruals/Deferrals）を自動逆転記オプション付きで入力する際に使用するトランザクションはどれか。',
            choices: ['FB50', 'FB60', 'FBS1', 'FB08'],
            correctIndex: 2,
            explanation: 'FBS1は経過勘定伝票（Accrual/Deferral Document）の入力に使用します。翌月に自動逆転記する日付を指定できます。FB50は一般転記、FB60は仕入先請求書転記、FB08は逆転記処理です。',
          },
          {
            type: 'ox',
            question: '会計期間がクローズされた後でも、「特別期間（Special Period）」への転記は行うことができる。',
            correct: true,
            explanation: 'その通りです。通常期間（1〜12月）とは別に特別期間（13〜16期）を設定することで、決算調整仕訳など年次決算時の追加転記を通常期間のクローズ後に実施できます。',
          },
          {
            type: 'four-choice',
            question: '月次決算ではなく、年次決算でのみ実施が必要な処理はどれか。',
            choices: ['減価償却の自動転記', '外貨評価', '経過勘定の計上', '利益繰越処理（年次繰越）'],
            correctIndex: 3,
            explanation: '利益繰越処理（Carry Forward）は前期の損益（P/L）を利益剰余金（B/S）に振り替える年次処理です。減価償却・外貨評価・経過勘定は月次決算でも実施されます。',
          },
        ],
      },
      {
        id: 'fi-fx-valuation',
        title: '外貨管理と為替評価',
        content: [
          '外貨建取引では、取引時の為替レートで換算して転記されます。SAPでは複数の為替レートタイプを管理でき、用途に応じて月平均レートやスポットレートを使い分けることが可能です。',
          '期末には外貨建の残高（売掛金・買掛金など）を期末レートで再評価する「外貨評価（Foreign Currency Valuation）」を行います。この処理で生じる評価差額が「為替差損益」としてP/L科目に自動転記されます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '外貨建の売掛金・買掛金を期末レートで再評価する処理を何と呼ぶか。',
            choices: ['原価評価', '外貨評価（Foreign Currency Valuation）', '在庫評価', '標準原価更新'],
            correctIndex: 1,
            explanation: '外貨建残高を期末の為替レートで再評価する処理を「外貨評価（Foreign Currency Valuation）」と呼びます。評価差額は為替差損益としてP/L科目に自動転記されます。',
          },
          {
            type: 'ox',
            question: '外貨評価で発生した為替差損益は、FIの損益（P/L）科目に自動的に転記される。',
            correct: true,
            explanation: 'その通りです。外貨評価の実行により、評価差額が為替差損（費用）または為替差益（収益）としてP/L科目に自動転記されます。',
          },
          {
            type: 'ordering',
            question: '外貨建取引の期末処理の流れを正しい順番に並べなさい。',
            items: [
              '外貨評価を実行して為替差損益を計上する',
              '外貨建伝票を取引時の為替レートで転記する',
              '期末の為替レートを為替レートテーブルに登録する',
              '財務諸表で為替差損益を確認する',
            ],
            correctOrder: [1, 2, 0, 3],
            explanation: '正しい順序は ①外貨建伝票の転記（取引時レート） → ②期末レートの登録 → ③外貨評価の実行 → ④財務諸表での確認 です。期末レートの登録が外貨評価実行の前提条件です。',
          },
          {
            type: 'ox',
            question: 'SAPでは複数の為替レートタイプを管理でき、目的（会計・管理会計・グループ報告など）に応じて使い分けることができる。',
            correct: true,
            explanation: 'その通りです。SAPでは為替レートタイプ（例：M=平均レート、B=買いレート、G=グループレートなど）を複数管理でき、用途に応じて適切なタイプを選択して使用します。',
          },
          {
            type: 'four-choice',
            question: 'SAPで為替レートをメンテナンス（登録・変更）するトランザクションコードはどれか。',
            choices: ['OB08', 'FB50', 'F-02', 'OB09'],
            correctIndex: 0,
            explanation: 'OB08は為替レートテーブルのメンテナンスに使用します。期末の外貨評価前に期末レートをOB08で登録する必要があります。FB50は一般転記、F-02は一般仕訳、OB09は为替レートタイプの設定です。',
          },
          {
            type: 'ox',
            question: '外貨評価で計上した為替差損益を、翌月初に自動的に逆転記するように設定することができる。',
            correct: true,
            explanation: 'その通りです。外貨評価実行時に「逆転記日付（Reverse Posting Date）」を指定することで、翌月初に評価仕訳が自動逆転記されます。これにより月次での再評価が毎月正確に実施できます。',
          },
        ],
      },
    ],
  },

  en: {
    id: 'fi',
    title: 'Financial Accounting (FI)',
    description: 'Learn the fundamentals of financial accounting in SAP',
    sections: [
      {
        id: 'fi-overview',
        title: 'FI Module Overview',
        content: [
          'FI (Financial Accounting) is the core SAP module responsible for financial accounting. It records financial transactions in real time and automatically generates financial statements such as the Balance Sheet (B/S) and Profit & Loss (P/L) statement.',
          'FI integrates closely with CO (Controlling), MM (Materials Management), and SD (Sales & Distribution). Business transactions in those modules are automatically posted to FI. FI and CO are so closely linked that they are often referred to together as "FI/CO".',
        ],
        quizzes: [
          {
            type: 'ox',
            question: 'The FI module is responsible for financial accounting and supports the creation of financial statements such as the Balance Sheet and P&L.',
            correct: true,
            explanation: 'Correct. FI stands for Financial Accounting. Automatic generation of financial statements is one of its core functions.',
          },
          {
            type: 'four-choice',
            question: 'Which module has the closest integration with FI?',
            choices: ['HR (Human Resources)', 'CO (Controlling)', 'PS (Project System)', 'QM (Quality Management)'],
            correctIndex: 1,
            explanation: 'FI and CO are treated together from a financial management perspective, often written as "FI/CO". While MM and SD also integrate with FI, CO has the closest relationship.',
          },
          {
            type: 'ox',
            question: 'The FI module records financial transactions in real time, and the financial statement figures are updated immediately upon posting.',
            correct: true,
            explanation: 'Correct. Real-time processing is a key feature of SAP: balances are updated the moment a document is posted rather than being aggregated in a batch job later.',
          },
          {
            type: 'four-choice',
            question: 'When a goods receipt is posted in the MM module, which combination of accounts is automatically posted to FI?',
            choices: ['Revenue and accrued liabilities', 'Inventory account and accounts payable (reconciliation) account', 'Cash account and prepaid expenses', 'Accounts receivable and sales revenue'],
            correctIndex: 1,
            explanation: 'A goods receipt in MM automatically generates an FI posting of Debit Inventory / Credit Accounts Payable (reconciliation account). This real-time integration between MM and FI is one of SAP\'s core features.',
          },
          {
            type: 'four-choice',
            question: 'Which bookkeeping method does the SAP FI module use?',
            choices: ['Single-entry bookkeeping', 'Double-entry bookkeeping', 'Triple-entry bookkeeping', 'Cash-basis accounting'],
            correctIndex: 1,
            explanation: 'SAP FI uses double-entry bookkeeping, where every transaction is recorded on both a debit and a credit side. The total debits must always equal total credits.',
          },
          {
            type: 'ox',
            question: 'A posted accounting document can be directly overwritten and modified.',
            correct: false,
            explanation: 'Incorrect. Posted documents cannot be changed directly. Any correction requires posting a reversal document (reverse entry) to cancel the original, followed by a new correct posting. This preserves the audit trail.',
          },
        ],
      },
      {
        id: 'fi-company-coa',
        title: 'Company Code & Chart of Accounts',
        content: [
          'A Company Code is the independent accounting unit in SAP. One complete set of financial statements is created per company code. Large corporations typically have multiple company codes.',
          'The Chart of Accounts (COA) master data has a two-level structure: the COA level and the Company Code level. A single Chart of Accounts can be shared across multiple company codes, allowing a group of companies to use a unified account structure.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'How many sets of financial statements are created for one company code?',
            choices: ['0 sets', '1 set', '2 sets', 'Depends on the number of company codes'],
            correctIndex: 1,
            explanation: 'A company code is an independent accounting unit in SAP, and exactly one set of financial statements is produced per company code.',
          },
          {
            type: 'ox',
            question: 'A Chart of Accounts can only be assigned to one company code.',
            correct: false,
            explanation: 'Incorrect. A Chart of Accounts can be shared across multiple company codes, which allows group companies to use a unified account structure.',
          },
          {
            type: 'ox',
            question: 'Only one Chart of Accounts can be assigned to a single company code.',
            correct: true,
            explanation: 'Correct. Each company code is assigned exactly one Chart of Accounts. However, the same Chart of Accounts can be shared across multiple company codes within a group.',
          },
          {
            type: 'four-choice',
            question: 'Which of the following is managed at the "Company Code level" of a G/L account master?',
            choices: ['Account number', 'Account short description', 'Tax category and reconciliation account type', 'Account group'],
            correctIndex: 2,
            explanation: 'The company code level stores company-specific settings such as tax category, reconciliation account type, account currency, and sort key. Account number, description, and account group are managed at the Chart of Accounts level.',
          },
          {
            type: 'four-choice',
            question: 'What is the unified account structure used for group-level consolidated financial statements called?',
            choices: ['Operating Chart of Accounts', 'Country Chart of Accounts', 'Group Chart of Accounts', 'Alternative Chart of Accounts'],
            correctIndex: 2,
            explanation: 'The Group Chart of Accounts is a unified account structure used for group-wide consolidation. Operating accounts from each company code are mapped to group accounts to facilitate consolidated reporting.',
          },
          {
            type: 'four-choice',
            question: 'Which best describes a "Business Area" in SAP?',
            choices: ['A legally independent accounting unit', 'A physical plant or warehouse unit', 'An internal segment that allows P&L analysis across multiple company codes', 'An organizational unit for classifying vendors'],
            correctIndex: 2,
            explanation: 'A Business Area is an internal organizational unit used to analyze profit and loss by business segment or product line, and it can span multiple company codes. The legally independent accounting unit is the Company Code.',
          },
        ],
      },
      {
        id: 'fi-document-types',
        title: 'Document Types & Posting Keys',
        content: [
          'A Document Type classifies accounting documents by business transaction. Standard document types include KR (Vendor Invoice), KZ (Vendor Payment), DR (Customer Invoice), DZ (Customer Payment), and SA (G/L Account Posting). Document types also control the number range for document numbering.',
          'A Posting Key is a two-digit code that controls the debit/credit indicator and the account type (G/L, vendor, customer, asset) for each line item. Key posting keys include: 40 (G/L debit), 50 (G/L credit), 31 (vendor credit), 25 (vendor debit), 01 (customer debit), and 15 (customer credit).',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which standard document type represents a Vendor Payment?',
            choices: ['KR', 'KZ', 'DZ', 'SA'],
            correctIndex: 1,
            explanation: 'KZ is the standard document type for Vendor Payments. KR is for Vendor Invoices, DZ is for Customer Payments (incoming), and SA is for general G/L postings.',
          },
          {
            type: 'ox',
            question: 'A posting key controls not only the debit/credit indicator but also which account type (G/L, vendor, customer, etc.) can be used on that line item.',
            correct: true,
            explanation: 'Correct. For example, posting key 31 can only be used with a vendor account (credit side). This restriction prevents posting errors by limiting which account types can be entered per line.',
          },
          {
            type: 'four-choice',
            question: 'Which posting key is used for a debit posting to a G/L account?',
            choices: ['25', '31', '40', '50'],
            correctIndex: 2,
            explanation: 'Posting key 40 is used for G/L account debit postings. 50 is for G/L credit, 31 is for vendor credit (when recording an invoice), and 25 is for vendor debit (e.g., when clearing a payment).',
          },
          {
            type: 'four-choice',
            question: 'Which standard document type represents a Customer Invoice?',
            choices: ['KR', 'SA', 'DR', 'DZ'],
            correctIndex: 2,
            explanation: 'DR is the standard document type for Customer Invoices. KR is for Vendor Invoices, SA is for general G/L postings, and DZ is for Customer Payments (incoming).',
          },
          {
            type: 'ox',
            question: 'A Document Type controls not only the business transaction category but also the number range used for document numbering.',
            correct: true,
            explanation: 'Correct. Each document type is assigned a number range that controls how document numbers are issued when a document is posted. Different document types can use separate numbering sequences.',
          },
          {
            type: 'four-choice',
            question: 'Which posting key is used for a vendor account credit posting when recording a vendor invoice (FB60)?',
            choices: ['25', '31', '40', '50'],
            correctIndex: 1,
            explanation: 'Posting key 31 is used for vendor account credit postings. When posting a vendor invoice, the vendor account is credited (31) and the expense account is debited (40). Key 25 is for vendor debit, 40 is G/L debit, and 50 is G/L credit.',
          },
        ],
      },
      {
        id: 'fi-journal',
        title: 'Journal Entry Posting',
        content: [
          'In SAP, all accounting transactions are recorded as "journal entry documents." Each document has Debit and Credit lines, and following the double-entry bookkeeping principle, both sides must always be equal in total.',
          'Journal entries are typically posted using transaction FB50 (General Posting) or similar. Once saved, a document number is assigned and the posting is complete.',
        ],
        quizzes: [
          {
            type: 'ox',
            question: 'In a journal entry document, the total debits and total credits must always be equal.',
            correct: true,
            explanation: 'This is the fundamental principle of double-entry bookkeeping. In SAP, a document cannot be saved if the debit and credit totals do not match.',
          },
          {
            type: 'ordering',
            question: 'Arrange the steps for posting a journal entry in FB50 in the correct order.',
            items: [
              'Save the document',
              'Launch transaction FB50',
              'Enter debit/credit account lines',
              'Enter document date and company code',
              'Enter amounts for each line',
            ],
            correctOrder: [1, 3, 2, 4, 0],
            explanation: 'The correct order is: ①Launch FB50 → ②Enter document date & company code → ③Enter account lines → ④Enter amounts → ⑤Save. Date and company code are header data entered first.',
          },
          {
            type: 'four-choice',
            question: 'Which of the following is part of the "header data" of a journal entry document?',
            choices: ['G/L account number', 'Document date, posting date, and company code', 'Amount on each line item', 'Vendor code'],
            correctIndex: 1,
            explanation: 'Document header data includes the document date, posting date, company code, currency, and reference number. G/L account numbers, amounts, and vendor/customer codes are line item (detail) data.',
          },
          {
            type: 'ox',
            question: 'The standard way to correct a posted accounting document is to post a reversal entry that cancels the original document\'s effect.',
            correct: true,
            explanation: 'Correct. Since posted documents cannot be edited directly, the standard correction procedure is to post a reversal (counter-entry) to nullify the original, then re-enter the correct posting if needed.',
          },
          {
            type: 'four-choice',
            question: 'What determines the "Posting Period" of an accounting document?',
            choices: ['Document date', 'Posting date', 'Entry date', 'Invoice date'],
            correctIndex: 1,
            explanation: 'The posting period is determined by the posting date. For example, a posting date of March 31 places the document in period 3 (March). The document date records when the business transaction occurred but does not drive the period.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used to reverse a posted accounting document?',
            choices: ['FB50', 'FB60', 'FB08', 'FBL3N'],
            correctIndex: 2,
            explanation: 'FB08 is used to reverse (cancel) a previously posted accounting document. FB50 is for general postings, FB60 is for vendor invoice postings, and FBL3N is for G/L account line item display.',
          },
        ],
      },
      {
        id: 'fi-payment-terms',
        title: 'Payment Terms & Baseline Date',
        content: [
          'Payment Terms define payment due dates and cash discount conditions. For example: "Full payment within 30 days" or "2% discount if paid within 10 days, full amount due within 30 days." Payment terms codes are stored in the vendor or customer master and are automatically proposed when posting documents.',
          'The date used as the starting point for due date calculations is called the Baseline Date. It can be set to the document date, posting date, invoice date, or entry date — and both the cash discount deadline and the net due date are calculated from this baseline. To exclude a specific invoice from automatic payment, a Payment Block can be set on the document.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What is the date used as the starting point for calculating payment due dates called?',
            choices: ['Posting date', 'Baseline Date', 'Settlement date', 'Confirmation date'],
            correctIndex: 1,
            explanation: 'The Baseline Date is the reference point from which both the cash discount deadline and the net payment due date are calculated. Using an incorrect baseline date directly leads to wrong due date calculations.',
          },
          {
            type: 'ox',
            question: 'A Cash Discount applies when payment is made within the specified discount period.',
            correct: true,
            explanation: 'Correct. For example, with terms of "2% discount within 10 days, net 30," paying within 10 days entitles the payer to a 2% reduction. On the vendor side this is a cash discount expense; on the customer side it is cash discount income.',
          },
          {
            type: 'four-choice',
            question: 'Which feature is used to exclude a specific vendor invoice from an automatic payment run (F110)?',
            choices: ['Changing the cash discount rate', 'Setting a Payment Block', 'Changing the document type', 'Extending the baseline date'],
            correctIndex: 1,
            explanation: 'Setting a Payment Block on a document prevents it from being selected by the automatic payment program (F110). It is used when a payment is disputed or pending confirmation.',
          },
          {
            type: 'ox',
            question: 'Payment Terms can be stored in both the vendor master and the customer master.',
            correct: true,
            explanation: 'Correct. Payment Terms are maintained in both vendor and customer master records. For vendors, they define payment due dates for A/P invoices; for customers, they determine due dates on sales invoices.',
          },
          {
            type: 'four-choice',
            question: 'With payment terms of "2% discount within 14 days, net 30," how much is paid on day 5 for an invoice of ¥10,000?',
            choices: ['¥10,000', '¥10,200', '¥9,800', '¥8,000'],
            correctIndex: 2,
            explanation: 'Day 5 is within the 14-day discount period, so the 2% cash discount applies. ¥10,000 × (1 − 0.02) = ¥9,800.',
          },
          {
            type: 'four-choice',
            question: 'How does the Automatic Payment Program (F110) handle an invoice whose due date has not yet been reached?',
            choices: ['It is excluded as an error and a warning is displayed', 'It is forcibly included in the payment run', 'It is not selected until the next payment run after the due date arrives', 'A payment block is automatically set on the invoice'],
            correctIndex: 2,
            explanation: 'Invoices that are not yet due are excluded from the payment proposal and will only be picked up by a future payment run once the due date has passed. This prevents premature payments.',
          },
        ],
      },
      {
        id: 'fi-ap',
        title: 'Accounts Payable (FI-AP)',
        content: [
          'Accounts Payable (FI-AP) manages payments to vendors. Vendor invoices are posted directly in FI using transaction FB60, which simultaneously updates the vendor sub-ledger and the Reconciliation Account in the general ledger. The reconciliation account cannot be posted to directly — it is always updated through the sub-ledger.',
          'Vendor payments can be processed efficiently using the Automatic Payment Program (F110). The process starts with setting parameters (company code, payment date, accounts), then running a Payment Proposal to generate a list of due invoices. After reviewing and adjusting the proposal, the Payment Run is executed, after which payment media (bank transfer files, checks) are produced.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction code is used to post a vendor invoice directly in FI (without MM integration)?',
            choices: ['MIRO', 'FB60', 'F-28', 'FBL1N'],
            correctIndex: 1,
            explanation: 'FB60 is used to post vendor invoices directly in FI. MIRO is for MM-integrated invoice verification (3-way matching), F-28 is for posting incoming customer payments, and FBL1N is for displaying vendor line items.',
          },
          {
            type: 'ordering',
            question: 'Arrange the Automatic Payment Program (F110) execution steps in the correct order.',
            items: [
              'Execute the Payment Run',
              'Launch F110 and set parameters',
              'Review and adjust the payment proposal',
              'Run the Payment Proposal',
            ],
            correctOrder: [1, 3, 2, 0],
            explanation: 'The correct order is: ①Launch F110 & set parameters → ②Run Payment Proposal → ③Review/adjust the proposal → ④Execute Payment Run. Always review the proposal before executing payment to catch errors or exclusions.',
          },
          {
            type: 'ox',
            question: 'Transaction FBL1N allows you to display vendor line items filtered by open items, cleared items, or all items.',
            correct: true,
            explanation: 'Correct. FBL1N lets you view a vendor\'s sub-ledger with the option to filter for open (unpaid), cleared (paid), or all items. It is essential for reconciling A/P balances and monitoring payment status.',
          },
          {
            type: 'ox',
            question: 'When a vendor invoice is posted in FB60, both the vendor sub-ledger and the reconciliation account (G/L) are updated simultaneously.',
            correct: true,
            explanation: 'Correct. Posting to the vendor sub-ledger automatically updates the reconciliation account assigned in the vendor master. The reconciliation account cannot be posted to directly — it is always updated via sub-ledger entries.',
          },
          {
            type: 'four-choice',
            question: 'Which of the following is NOT a reason why an invoice might be excluded from an F110 payment proposal?',
            choices: ['A payment block is set on the invoice', 'The invoice due date has not yet been reached', 'Payment method master data is not configured', 'The vendor\'s address is not maintained'],
            correctIndex: 3,
            explanation: 'Common reasons for exclusion from an F110 proposal include: payment block set, due date not yet reached, and missing payment method configuration. A missing vendor address does not cause exclusion from the payment proposal.',
          },
          {
            type: 'four-choice',
            question: 'What is the main purpose of the "payment medium" output generated after an F110 payment run?',
            choices: ['Sending an invoice to the vendor', 'Generating a bank transfer instruction file or check for actual payment', 'Sending a dunning notice to a customer', 'Calculating asset depreciation'],
            correctIndex: 1,
            explanation: 'The payment medium (e.g., a DME bank transfer file or printed check) is the output submitted to the bank to initiate actual fund transfers. Customer dunning is handled by F150; asset depreciation is run via AFAB.',
          },
        ],
      },
      {
        id: 'fi-ar',
        title: 'Accounts Receivable (FI-AR)',
        content: [
          'Accounts Receivable (FI-AR) manages incoming payments and customer debt collection. Customer payments are posted using transaction F-28, which then "clears" (closes) the matching open items (outstanding invoices) on the customer account. Once cleared, the receivable balance is reduced.',
          'Credit Management allows setting a credit limit per customer, which is automatically checked during sales order entry. Orders that exceed the limit are automatically blocked. For customers who have not paid past the due date, the Dunning process (transaction F150) sends dunning notices in escalating levels based on the number of days overdue.',
        ],
        quizzes: [
          {
            type: 'ox',
            question: 'The process of matching an incoming customer payment against the corresponding outstanding invoice and closing it is called "Clearing."',
            correct: true,
            explanation: 'Correct. The Clearing process closes open (unpaid) items against the received payment, reducing the A/R balance. When payment and invoice amounts differ (partial payment, cash discount), the difference must be handled explicitly.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used to set and manage a customer\'s credit limit?',
            choices: ['FBL5N', 'FD32', 'F150', 'F-28'],
            correctIndex: 1,
            explanation: 'FD32 is used to set and display the credit limit for a customer. FBL5N displays customer line items, F150 runs the dunning program, and F-28 posts incoming customer payments.',
          },
          {
            type: 'four-choice',
            question: 'What is the primary purpose of the Dunning process?',
            choices: [
              'Automate payments to vendors',
              'Send payment reminder notices to overdue customers to collect outstanding receivables',
              'Automatically post asset depreciation',
              'Revalue foreign currency balances at the period-end rate',
            ],
            correctIndex: 1,
            explanation: 'Dunning sends payment reminders to customers with overdue receivables. Dunning levels can be configured with escalating notice text, dunning fees, and interest charges based on how long the payment is overdue.',
          },
          {
            type: 'four-choice',
            question: 'A customer pays more than the invoiced amount (overpayment). What is the appropriate treatment?',
            choices: ['Immediately post the difference as miscellaneous income', 'Post the entire payment as sales revenue', 'Leave the excess as a credit balance and apply it to the next invoice or refund it to the customer', 'Cancel the payment document and re-enter it'],
            correctIndex: 2,
            explanation: 'An overpayment creates a credit balance on the customer account. The standard approach is to keep the excess as a credit and offset it against the customer\'s next invoice, or process a refund. Posting it immediately as income or cancelling the document is not appropriate.',
          },
          {
            type: 'ox',
            question: 'The Dunning process supports multiple dunning levels, and each level can be configured with different dunning fees and interest charges.',
            correct: true,
            explanation: 'Correct. Each dunning level can have its own notice text, dunning fee, and interest rate. This allows escalating pressure from a polite first reminder up to a formal legal notice, with costs increasing at each level.',
          },
          {
            type: 'four-choice',
            question: 'Which of the following CANNOT be viewed in transaction FBL5N (Customer Line Item Display)?',
            choices: ['List of open (unpaid) invoices', 'Cleared payment details', 'Dunning level status', 'Contents of a sales contract with the customer'],
            correctIndex: 3,
            explanation: 'FBL5N displays customer sub-ledger line items including open items, cleared items, and dunning levels. Sales contract content is not stored in FI and cannot be viewed in FBL5N.',
          },
        ],
      },
      {
        id: 'fi-asset',
        title: 'Asset Accounting (FI-AA)',
        content: [
          'Asset Accounting (FI-AA) is the FI sub-module that manages the full lifecycle of fixed assets — from acquisition through retirement. Asset master records are created using AS01. An Asset Class groups fixed assets of a similar type and defines the default depreciation key, useful life, and the G/L accounts for automatic posting.',
          'The Depreciation Key defines the depreciation calculation method (straight-line, declining balance, etc.). Combined with the Useful Life, it drives the automatic monthly depreciation calculation. Asset acquisitions from vendors are posted using F-90, retirements (scrapping) are handled with ABAVN, and monthly depreciation is run using AFAB.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction code is used to create a new fixed asset master record?',
            choices: ['F-90', 'ABAVN', 'AS01', 'AFAB'],
            correctIndex: 2,
            explanation: 'AS01 creates a new asset master record. F-90 posts an asset acquisition from a vendor, ABAVN processes an asset retirement by scrapping, and AFAB runs the periodic depreciation posting.',
          },
          {
            type: 'ox',
            question: 'An Asset Class defines default depreciation key and useful life values; all assets in the same class share the same depreciation settings.',
            correct: true,
            explanation: 'Correct. The Asset Class sets default values including depreciation key, useful life, and account determination. Assets in the same class automatically inherit these defaults, ensuring consistent treatment within each asset category.',
          },
          {
            type: 'four-choice',
            question: 'Which master data defines the depreciation calculation method (e.g., straight-line or declining balance) for a fixed asset?',
            choices: ['Asset Class', 'Useful Life', 'Depreciation Key', 'Depreciation Area'],
            correctIndex: 2,
            explanation: 'The Depreciation Key defines the calculation method for depreciation. The Useful Life specifies the number of years over which the asset is depreciated, and together with the Depreciation Key, determines the monthly depreciation amount.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used to post an asset acquisition from a vendor?',
            choices: ['AS01', 'ABAVN', 'AFAB', 'F-90'],
            correctIndex: 3,
            explanation: 'F-90 is used to post a fixed asset acquisition from a vendor (Asset Acquisition with Vendor). AS01 creates the asset master, ABAVN retires an asset by scrapping, and AFAB runs the periodic depreciation posting.',
          },
          {
            type: 'ox',
            question: 'Running the depreciation posting in AFAB reduces the book value (net book value) of a fixed asset.',
            correct: true,
            explanation: 'Correct. AFAB posts depreciation expense (debit) against accumulated depreciation (credit). Since book value = acquisition cost − accumulated depreciation, the book value decreases with each depreciation posting.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used to retire a fixed asset by scrapping (disposal with no proceeds)?',
            choices: ['AS01', 'F-90', 'ABAVN', 'AFAB'],
            correctIndex: 2,
            explanation: 'ABAVN is used for asset retirement by scrapping — when an asset is disposed of without receiving sale proceeds. AS01 creates an asset master, F-90 posts an acquisition from a vendor, and AFAB posts periodic depreciation.',
          },
        ],
      },
      {
        id: 'fi-closing',
        title: 'Period-End Closing',
        content: [
          'Period-end closing (monthly/annual) involves various FI processes such as automatic depreciation posting, foreign currency revaluation, and accruals. These are typically performed by the accounting team in a prescribed sequence.',
          'SAP provides dedicated transactions for closing activities. Performing steps in the wrong order can result in incorrect financial statement figures, so understanding the closing procedure is essential.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction code is used to automatically post asset depreciation?',
            choices: ['FB50', 'AFAB', 'F-02', 'FBL3N'],
            correctIndex: 1,
            explanation: 'AFAB is used for Automatic Posting of Depreciation. FB50 is for general posting, F-02 is for general journal entry, and FBL3N is for G/L account line item display.',
          },
          {
            type: 'ordering',
            question: 'Arrange the main month-end closing steps in the correct order.',
            items: [
              'Close the accounting period',
              'Review financial statements',
              'Run foreign currency revaluation and depreciation',
            ],
            correctOrder: [2, 1, 0],
            explanation: 'The correct order is: ①Run automated processes (FX revaluation, depreciation) → ②Review financial statements → ③Close the period. Closing the period prevents further postings, so always confirm results first.',
          },
          {
            type: 'ox',
            question: 'In SAP, multiple accounting periods can be open at the same time.',
            correct: true,
            explanation: 'Correct. It is common practice to keep the current and previous month both open simultaneously to allow late postings from the prior period. Accounting period management is configured in transaction OB52.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction is used to post an accrual/deferral document with an automatic reversal option?',
            choices: ['FB50', 'FB60', 'FBS1', 'FB08'],
            correctIndex: 2,
            explanation: 'FBS1 (Accrual/Deferral Document) allows you to specify a reversal date so the entry is automatically reversed at the start of the following period. FB50 is for general postings, FB60 for vendor invoices, and FB08 for manual reversals.',
          },
          {
            type: 'ox',
            question: 'Even after a regular accounting period is closed, postings can still be made to a "Special Period."',
            correct: true,
            explanation: 'Correct. Special Periods (periods 13–16) allow year-end adjustments to be posted after the regular periods (1–12) have been closed. This is essential for year-end audit adjustments.',
          },
          {
            type: 'four-choice',
            question: 'Which of the following is performed only at year-end closing, not during monthly closing?',
            choices: ['Automatic depreciation posting', 'Foreign currency revaluation', 'Accrual/deferral posting', 'Profit and loss carry-forward'],
            correctIndex: 3,
            explanation: 'The P&L carry-forward transfers the net income/loss from P&L accounts to retained earnings on the balance sheet, and is an annual-only process. Depreciation, FX revaluation, and accruals are performed monthly.',
          },
        ],
      },
      {
        id: 'fi-fx-valuation',
        title: 'Foreign Currency Management & Valuation',
        content: [
          'Foreign currency transactions are translated using the exchange rate at the time of posting. SAP supports multiple exchange rate types (e.g., monthly average rate, spot rate) that can be used for different business purposes.',
          'At period-end, foreign currency balances (A/R, A/P, etc.) must be revalued at the closing rate — this process is called Foreign Currency Valuation. The resulting difference is automatically posted to FI as an exchange gain or loss (P/L account).',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What is the process of revaluing foreign currency A/R and A/P balances at the period-end exchange rate called?',
            choices: ['Cost valuation', 'Foreign Currency Valuation', 'Inventory valuation', 'Standard cost update'],
            correctIndex: 1,
            explanation: 'Revaluing foreign currency open items at the period-end rate is called Foreign Currency Valuation. The resulting difference is automatically posted to FI as an exchange gain or loss (P/L).',
          },
          {
            type: 'ox',
            question: 'Exchange gains and losses from foreign currency valuation are automatically posted to P/L accounts in FI.',
            correct: true,
            explanation: 'Correct. Running the foreign currency valuation posts the revaluation difference as either an exchange loss (expense) or exchange gain (revenue) to the appropriate P/L accounts in FI.',
          },
          {
            type: 'ordering',
            question: 'Arrange the period-end foreign currency processing steps in the correct order.',
            items: [
              'Run foreign currency valuation to post exchange gains/losses',
              'Post foreign currency transactions at transaction-date rates',
              'Enter the period-end exchange rate in the exchange rate table',
              'Review exchange gains/losses in financial statements',
            ],
            correctOrder: [1, 2, 0, 3],
            explanation: 'The correct order is: ①Post foreign currency documents at the transaction rate → ②Enter period-end rates → ③Run foreign currency valuation → ④Review financial statements. Period-end rates must be registered before running the valuation.',
          },
          {
            type: 'ox',
            question: 'SAP supports multiple exchange rate types, which can be used for different purposes such as accounting, controlling, and group reporting.',
            correct: true,
            explanation: 'Correct. SAP manages multiple exchange rate types (e.g., M = average rate, B = buying rate, G = group rate) that can be applied for different purposes. The appropriate type is selected based on the business requirement.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used to maintain (enter or update) exchange rates in SAP?',
            choices: ['OB08', 'FB50', 'F-02', 'OB09'],
            correctIndex: 0,
            explanation: 'OB08 is used to maintain the exchange rate table in SAP. Period-end exchange rates must be entered in OB08 before running the foreign currency valuation. FB50 is for general postings, F-02 for manual journal entries, and OB09 for exchange rate type configuration.',
          },
          {
            type: 'ox',
            question: 'It is possible to configure the foreign currency valuation so that the resulting exchange gain/loss posting is automatically reversed at the start of the next period.',
            correct: true,
            explanation: 'Correct. When running foreign currency valuation, you can specify a reversal date so the valuation entries are automatically reversed at the beginning of the next period. This ensures the revaluation is freshly recalculated each period.',
          },
        ],
      },
    ],
  },
};
