import type { Quiz } from '../learning-types';
import type { Language } from '../i18n';

/** Additional MM practice questions, appended after each section's originals. */
export const mmQuizzes: Record<Language, Record<string, Quiz[]>> = {
  ja: {
    'mm-overview': [
      {
        type: 'four-choice',
        question: 'MMを構成する領域に含まれないものはどれか。',
        choices: ['購買', '在庫管理', '請求書照合', '督促処理'],
        correctIndex: 3,
        explanation: '督促処理はFI-AR（債権管理）の機能です。MMは購買、在庫管理、請求書照合などで構成されます。',
      },
      {
        type: 'ox',
        question: '購買発注を登録しただけでは、FIに会計仕訳は計上されない。',
        correct: true,
        explanation: '正しいです。発注は約束の段階なので仕訳は発生しません。入庫で在庫とGR/IR、請求書照合でGR/IRと買掛金の仕訳が計上されます。',
      },
      {
        type: 'four-choice',
        question: 'MMとPPの接点として最も適切なものはどれか。',
        choices: ['製造指図への部品の出庫', '請求伝票の作成', '得意先の与信チェック', '固定資産の減価償却'],
        correctIndex: 0,
        explanation: '製造指図が必要とする部品は、MMの在庫から出庫されます。MRPが作成した購買依頼を購買が発注するのも両者の接点です。',
      },
      {
        type: 'four-choice',
        question: 'GR/IR勘定に残高が残っている状態は何を意味するか。',
        choices: ['入庫と請求書のどちらかが未処理である', '支払が完了している', '在庫がゼロである', '発注が承認されていない'],
        correctIndex: 0,
        explanation: '入庫と請求書照合がそろうとGR/IRの残高は消えます。残っている場合は、入庫済みで請求書未着、または請求書だけ届いて入庫未済の状態です。',
      },
    ],
    'material-master': [
      {
        type: 'four-choice',
        question: '品目マスタの購買ビューのデータは、どの組織レベルで保持されるか。',
        choices: ['クライアント', 'プラント', '保管場所', '販売組織'],
        correctIndex: 1,
        explanation: '購買ビューはプラントレベルです。同じ品目でもプラントごとに購買グループや発注単位を変えられます。',
      },
      {
        type: 'four-choice',
        question: '品目タイプが制御しないものはどれか。',
        choices: ['使用できるビュー', '番号範囲', '数量・金額の在庫更新の有無', '得意先の与信限度額'],
        correctIndex: 3,
        explanation: '与信限度額は得意先側の与信管理の設定です。品目タイプは、使えるビューや番号範囲、在庫の数量・金額を更新するかどうかを制御します。',
      },
      {
        type: 'ox',
        question: '品目テキストや基本数量単位などの基本データはクライアントレベルで保持され、すべてのプラントで共通である。',
        correct: true,
        explanation: '正しいです。基本データは品目そのものを表す情報なので全社共通です。プラントや販売組織ごとに変えたい情報は、それぞれのレベルのビューで持ちます。',
      },
      {
        type: 'ox',
        question: '標準原価（価格管理S）の品目では、入庫価格が標準原価と異なっても在庫は標準原価で評価され、差額は価格差異として計上される。',
        correct: true,
        explanation: '正しいです。在庫単価は変わらず、発注価格との差額は価格差異勘定に計上されます。移動平均価格（V）では差額が在庫単価に反映されます。',
      },
    ],
    'purchase-order': [
      {
        type: 'four-choice',
        question: '発注明細の費用を原価センタに直接計上するために指定する勘定設定カテゴリはどれか。',
        choices: ['K', 'P', 'F', 'A'],
        correctIndex: 0,
        explanation: 'Kは原価センタです。Pはプロジェクト（WBS要素）、Fは指図、Aは固定資産への計上に使います。',
      },
      {
        type: 'four-choice',
        question: 'サービスの調達に使う発注の明細カテゴリはどれか。',
        choices: ['D', 'K', 'L', 'U'],
        correctIndex: 0,
        explanation: 'Dはサービスです。Kはコンサインメント、Lは外注加工、Uは在庫転送に使います。',
      },
      {
        type: 'ox',
        question: '勘定設定カテゴリを指定した発注では、入庫しても在庫は増えず、原価センタなどの費用として計上される。',
        correct: true,
        explanation: '正しいです。消費目的の購買なので、入庫の時点で指定した原価センタや指図に費用が計上されます。',
      },
      {
        type: 'four-choice',
        question: '発注書を仕入先に印刷・メール・EDIなどで送るための仕組みはどれか。',
        choices: ['出力管理（メッセージ）', 'リリース戦略', 'クォータ取決め', 'ソースリスト'],
        correctIndex: 0,
        explanation: '出力管理（メッセージ）です。発注を保存したときに、条件に応じて印刷・メール・EDIなどの出力が自動で作成されます。',
      },
    ],
    'goods-receipt-invoice': [
      {
        type: 'four-choice',
        question: '入庫時に、品物を品質検査中や保留として受け入れるために指定するものはどれか。',
        choices: ['在庫タイプ', '勘定設定カテゴリ', '伝票タイプ', '購買グループ'],
        correctIndex: 0,
        explanation: '在庫タイプです。非制限使用・品質検査中・保留から選べ、検査が必要な品物を誤って使わないようにできます。',
      },
      {
        type: 'ox',
        question: 'GR基準請求書照合を使うと、請求書は入庫ごとに照合され、入庫前の請求書は計上できない。',
        correct: true,
        explanation: '正しいです。入庫と請求書を1対1で照合するため、分割納入の品目などで照合の精度が上がります。',
      },
      {
        type: 'four-choice',
        question: '照合ブロックで保留された請求書を、確認後に解除するトランザクションコードはどれか。',
        choices: ['MRBR', 'MIRO', 'MIGO', 'ME23N'],
        correctIndex: 0,
        explanation: 'MRBRは保留された請求書の解除です。MIROは請求書照合、MIGOは入庫などの在庫移動、ME23Nは発注の照会です。',
      },
      {
        type: 'four-choice',
        question: '請求書を転記せずに保存（パーク）し、後で確認してから転記するためのトランザクションコードはどれか。',
        choices: ['MIR7', 'MIRO', 'MRBR', 'MIGO'],
        correctIndex: 0,
        explanation: 'MIR7は請求書の保留（パーク）です。保存した請求書は、担当者が内容を確認したうえで転記できます。',
      },
    ],
    'inventory-valuation': [
      {
        type: 'four-choice',
        question: '在庫移動の転記先G/L勘定を決める勘定決定を設定するトランザクションコードはどれか。',
        choices: ['OBYC', 'OB52', 'MMPV', 'OMSY'],
        correctIndex: 0,
        explanation: 'OBYCです。取引キー（BSXなど）と評価クラスの組み合わせで、在庫勘定や価格差異勘定などを決めます。',
      },
      {
        type: 'ox',
        question: 'S/4HANAでは品目元帳が必須となり、在庫の評価額を複数の通貨で保持できる。',
        correct: true,
        explanation: '正しいです。S/4HANAでは品目元帳が常に有効で、会社コード通貨に加えてグループ通貨などでも在庫を評価できます。',
      },
      {
        type: 'four-choice',
        question: '在庫を廃棄として出庫するときに使う移動タイプはどれか。',
        choices: ['551', '561', '601', '311'],
        correctIndex: 0,
        explanation: '551が廃棄です。561は初期在庫の登録、601は出荷による出庫、311は保管場所間の在庫転送です。',
      },
      {
        type: 'four-choice',
        question: '移動タイプが決定しないものはどれか。',
        choices: ['在庫数量の増減', '転記先勘定を決める取引キー', '入力画面で使う項目', '仕入先の支払条件'],
        correctIndex: 3,
        explanation: '支払条件は仕入先マスタや発注で決まります。移動タイプは在庫の増減、勘定決定の取引キー、入力項目などを決めます。',
      },
    ],
    'vendor-master': [
      {
        type: 'four-choice',
        question: '仕入先勘定グループが制御するものとして正しいものはどれか。',
        choices: ['仕入先番号の番号範囲と、マスタ画面の項目の入力制御', '発注価格', '支払の実行日', '入庫の許容範囲'],
        correctIndex: 0,
        explanation: '仕入先勘定グループは、番号範囲や、どの項目を必須・任意・非表示にするかを制御します。一時仕入先用などの用途で分けます。',
      },
      {
        type: 'ox',
        question: '仕入先評価では、価格・品質・納期・サービスなどの基準で仕入先を点数化できる。',
        correct: true,
        explanation: '正しいです。基準ごとの点数と重み付けで総合点を算出し、仕入先の選定や改善要請の根拠に使います。',
      },
      {
        type: 'four-choice',
        question: 'S/4HANAで仕入先マスタを登録・変更するときに使うトランザクションコードはどれか。',
        choices: ['BP', 'XK01', 'MK01', 'FK01'],
        correctIndex: 0,
        explanation: 'S/4HANAではビジネスパートナ（BP）で登録します。XK01・MK01・FK01はECCで使われていた仕入先マスタのトランザクションです。',
      },
      {
        type: 'ox',
        question: '発注通貨や支払条件、インコタームズなどの購買組織データは、購買組織ごとに異なる値を持つことができる。',
        correct: true,
        explanation: '正しいです。同じ仕入先でも、国内の購買組織と海外の購買組織で通貨や取引条件を変えられます。',
      },
    ],
    'purchasing-info-contracts': [
      {
        type: 'four-choice',
        question: '同じ品目を複数の仕入先から、あらかじめ決めた割合で調達するための設定はどれか。',
        choices: ['クォータ取決め', 'ソースリスト', '購買情報レコード', 'リリース戦略'],
        correctIndex: 0,
        explanation: 'クォータ取決めです。「A社60%、B社40%」のように割合を設定すると、MRPや購買依頼の割当で自動的に振り分けられます。',
      },
      {
        type: 'four-choice',
        question: '品目とプラントごとに、調達してよい仕入先と期間を定義するマスタはどれか。',
        choices: ['ソースリスト', 'クォータ取決め', '条件レコード', '得意先・品目情報レコード'],
        correctIndex: 0,
        explanation: 'ソースリストです。承認された仕入先以外からの発注を防いだり、MRPで仕入先を自動で割り当てたりするのに使います。',
      },
      {
        type: 'ox',
        question: '期間発注契約では、納入のたびに個別の発注を作らず、納入日程行で日付と数量を指示する。',
        correct: true,
        explanation: '正しいです。継続的に同じ品目を納入してもらう場合に、発注の作成を省いて納入の指示だけを出せます。',
      },
      {
        type: 'four-choice',
        question: '契約（数量契約・金額契約）を参照して発行する個々の発注を何と呼ぶか。',
        choices: ['契約に対する呼出（リリースオーダ）', '購買依頼', '見積依頼', '在庫転送オーダー'],
        correctIndex: 0,
        explanation: '契約を参照して作成する発注は契約に対する呼出（リリースオーダ）と呼ばれ、契約の残数量や残金額が消し込まれていきます。',
      },
    ],
    'special-procurement': [
      {
        type: 'four-choice',
        question: '外注加工で、仕入先に部品を支給するときに使う移動タイプはどれか。',
        choices: ['541', '101', '261', '411'],
        correctIndex: 0,
        explanation: '541で外注先への支給在庫に移します。101は入庫、261は製造指図への出庫、411は特殊在庫から自社在庫への振替です。',
      },
      {
        type: 'ox',
        question: '外注加工で仕入先に支給した部品は、特殊在庫Oとして自社の在庫のまま管理される。',
        correct: true,
        explanation: '正しいです。所有権は自社にあるため評価額を持ったまま管理され、加工品の入庫時に消費として転記されます。',
      },
      {
        type: 'four-choice',
        question: '仕入先から預かっているコンサインメント在庫を表す特殊在庫区分はどれか。',
        choices: ['K', 'O', 'E', 'W'],
        correctIndex: 0,
        explanation: 'Kが仕入先のコンサインメント在庫です。Oは外注先への支給在庫、Eは受注在庫、Wは得意先のコンサインメント在庫を表します。',
      },
      {
        type: 'ox',
        question: '2ステップの在庫転送では、送り元で出庫してから受け入れ先で入庫するまでの間、在庫は輸送中在庫として管理される。',
        correct: true,
        explanation: '正しいです。輸送中の在庫はどちらの保管場所でも使えませんが、在庫としては計上されたまま管理されます。',
      },
    ],
    'inventory-count': [
      {
        type: 'four-choice',
        question: '実地棚卸の棚卸伝票を作成するトランザクションコードはどれか。',
        choices: ['MI01', 'MI04', 'MI07', 'MMBE'],
        correctIndex: 0,
        explanation: 'MI01が棚卸伝票の作成です。MI04は実際数量の入力、MI07は差異の転記、MMBEは在庫の照会です。',
      },
      {
        type: 'ox',
        question: '棚卸伝票を作成するときに転記ブロックを設定すると、棚卸中の品目の在庫移動を防ぐことができる。',
        correct: true,
        explanation: '正しいです。数えている最中に入出庫があると帳簿在庫と実際在庫の比較ができなくなるため、転記ブロックで移動を止めます。',
      },
      {
        type: 'four-choice',
        question: '棚卸差異を転記したときに計上される勘定の組み合わせとして正しいものはどれか。',
        choices: ['在庫勘定と棚卸差異（損益）勘定', '在庫勘定とGR/IR勘定', '買掛金と価格差異勘定', '売上原価と売掛金'],
        correctIndex: 0,
        explanation: '差異の数量に評価単価を掛けた金額が、在庫勘定と棚卸差異の損益勘定に計上されます。',
      },
      {
        type: 'four-choice',
        question: '仕入先のコンサインメント在庫を棚卸する場合の扱いとして正しいものはどれか。',
        choices: ['特殊在庫区分Kを指定して棚卸伝票を作成する', '自社在庫と同じ棚卸伝票に自動で含まれる', '棚卸の対象にできない', '仕入先マスタで直接数量を修正する'],
        correctIndex: 0,
        explanation: '特殊在庫は通常の在庫と別に管理されているため、特殊在庫区分を指定して棚卸伝票を作成します。',
      },
    ],
    'mm-period-end': [
      {
        type: 'four-choice',
        question: '在庫の低価法評価の目的として正しいものはどれか。',
        choices: ['在庫の評価額を、時価などの低い価額まで引き下げる', '在庫数量を実際の数量に合わせる', '仕入先への支払額を減らす', '標準原価を翌期に繰り越す'],
        correctIndex: 0,
        explanation: '低価法は、帳簿上の単価より市場価格や正味売却価額が下がった在庫の評価額を引き下げ、損失を計上する処理です。',
      },
      {
        type: 'ox',
        question: 'MMPVで期間を次に進めた後も、標準の設定では直前の期間に在庫を転記することができる。',
        correct: true,
        explanation: '正しいです。MMでは当期間と前期間の2つに転記できるのが標準です。月初に前月分の入庫を転記するような場合に対応できます。',
      },
      {
        type: 'four-choice',
        question: '在庫の評価額と、在庫勘定のG/L残高を比較して整合を確認するレポートはどれか。',
        choices: ['MB5L', 'MMBE', 'ME2M', 'MB52'],
        correctIndex: 0,
        explanation: 'MB5Lは在庫評価額とG/L残高の一覧で、MMとFIの整合確認に使います。MMBEやMB52は在庫数量の照会、ME2Mは品目別の発注一覧です。',
      },
      {
        type: 'ox',
        question: 'GR/IR勘定に長期間残り続けている明細は、発注の締め忘れや二重計上などの問題を示している可能性がある。',
        correct: true,
        explanation: '正しいです。通常は入庫と請求書が近い時期にそろうため、長期の残高は原因を調べて整理すべき対象です。',
      },
    ],
  },
  en: {
    'mm-overview': [
      {
        type: 'four-choice',
        question: 'Which of these is not an area of MM?',
        choices: ['Purchasing', 'Inventory management', 'Invoice verification', 'Dunning'],
        correctIndex: 3,
        explanation: 'Dunning belongs to FI-AR. MM covers purchasing, inventory management and invoice verification, among others.',
      },
      {
        type: 'ox',
        question: 'Creating a purchase order on its own posts no accounting entry in FI.',
        correct: true,
        explanation: 'Correct. A purchase order is only a commitment. Goods receipt posts inventory against GR/IR, and invoice verification posts GR/IR against payables.',
      },
      {
        type: 'four-choice',
        question: 'Which is the clearest link between MM and PP?',
        choices: ['Issuing components to a production order', 'Creating billing documents', 'Checking customer credit', 'Depreciating fixed assets'],
        correctIndex: 0,
        explanation: 'Components needed by production orders are issued from MM stock. Purchasing converting requisitions created by MRP is another link.',
      },
      {
        type: 'four-choice',
        question: 'What does a remaining balance on the GR/IR account mean?',
        choices: ['Either the goods receipt or the invoice is still outstanding', 'Payment has been made', 'Stock is zero', 'The purchase order has not been approved'],
        correctIndex: 0,
        explanation: 'Once both receipt and invoice are posted, the GR/IR balance clears. A balance means goods received without an invoice, or an invoice without the goods.',
      },
    ],
    'material-master': [
      {
        type: 'four-choice',
        question: 'At which organisational level is purchasing view data on the material master held?',
        choices: ['Client', 'Plant', 'Storage location', 'Sales organisation'],
        correctIndex: 1,
        explanation: 'The purchasing view is plant level, so purchasing group and order unit can differ by plant for the same material.',
      },
      {
        type: 'four-choice',
        question: 'Which of these is not controlled by the material type?',
        choices: ['Which views can be used', 'Number range', 'Whether quantity and value are updated in inventory', 'The customer’s credit limit'],
        correctIndex: 3,
        explanation: 'Credit limits belong to customer credit management. The material type controls available views, number range and whether quantity and value are updated.',
      },
      {
        type: 'ox',
        question: 'Basic data such as material description and base unit of measure is held at client level and shared by every plant.',
        correct: true,
        explanation: 'Correct. Basic data describes the material itself, so it is company-wide. Anything that varies by plant or sales organisation lives in views at those levels.',
      },
      {
        type: 'ox',
        question: 'For a material at standard price (price control S), stock stays valued at standard even when the receipt price differs, and the difference is posted as a price variance.',
        correct: true,
        explanation: 'Correct. The stock price is unchanged and the difference from the purchase price goes to a price difference account. With moving average price (V) the difference flows into the stock price.',
      },
    ],
    'purchase-order': [
      {
        type: 'four-choice',
        question: 'Which account assignment category charges a purchase order item directly to a cost centre?',
        choices: ['K', 'P', 'F', 'A'],
        correctIndex: 0,
        explanation: 'K is cost centre. P is project (WBS element), F is order and A is asset.',
      },
      {
        type: 'four-choice',
        question: 'Which item category is used to procure services?',
        choices: ['D', 'K', 'L', 'U'],
        correctIndex: 0,
        explanation: 'D is services. K is consignment, L is subcontracting and U is stock transfer.',
      },
      {
        type: 'ox',
        question: 'On a purchase order with an account assignment category, the goods receipt does not increase stock but posts the cost to the cost centre or other object.',
        correct: true,
        explanation: 'Correct. The purchase is for consumption, so cost is charged to the specified cost centre or order at goods receipt.',
      },
      {
        type: 'four-choice',
        question: 'What sends a purchase order to the vendor by print, email or EDI?',
        choices: ['Output control (messages)', 'Release strategy', 'Quota arrangement', 'Source list'],
        correctIndex: 0,
        explanation: 'Output control. When the order is saved, print, email or EDI output is created automatically according to conditions.',
      },
    ],
    'goods-receipt-invoice': [
      {
        type: 'four-choice',
        question: 'What is specified at goods receipt to receive goods into quality inspection or blocked stock?',
        choices: ['Stock type', 'Account assignment category', 'Document type', 'Purchasing group'],
        correctIndex: 0,
        explanation: 'The stock type: unrestricted use, quality inspection or blocked, which prevents goods needing inspection from being used by mistake.',
      },
      {
        type: 'ox',
        question: 'With GR-based invoice verification, invoices are matched per goods receipt and cannot be posted before the receipt.',
        correct: true,
        explanation: 'Correct. Matching each receipt with its invoice improves accuracy, especially for materials delivered in several shipments.',
      },
      {
        type: 'four-choice',
        question: 'Which transaction releases invoices blocked by invoice verification once they have been checked?',
        choices: ['MRBR', 'MIRO', 'MIGO', 'ME23N'],
        correctIndex: 0,
        explanation: 'MRBR releases blocked invoices. MIRO enters invoices, MIGO posts goods movements and ME23N displays purchase orders.',
      },
      {
        type: 'four-choice',
        question: 'Which transaction parks an invoice so it can be checked and posted later?',
        choices: ['MIR7', 'MIRO', 'MRBR', 'MIGO'],
        correctIndex: 0,
        explanation: 'MIR7 parks invoices. A parked invoice can be reviewed and then posted.',
      },
    ],
    'inventory-valuation': [
      {
        type: 'four-choice',
        question: 'Which transaction configures the account determination that decides G/L accounts for goods movements?',
        choices: ['OBYC', 'OB52', 'MMPV', 'OMSY'],
        correctIndex: 0,
        explanation: 'OBYC. Transaction keys such as BSX combined with valuation classes determine accounts like inventory and price differences.',
      },
      {
        type: 'ox',
        question: 'In S/4HANA the material ledger is mandatory, allowing inventory to be valued in several currencies.',
        correct: true,
        explanation: 'Correct. The material ledger is always active in S/4HANA, valuing stock in group currency and others as well as company code currency.',
      },
      {
        type: 'four-choice',
        question: 'Which movement type issues stock for scrapping?',
        choices: ['551', '561', '601', '311'],
        correctIndex: 0,
        explanation: '551 is scrapping. 561 enters initial stock, 601 is goods issue for delivery and 311 is transfer between storage locations.',
      },
      {
        type: 'four-choice',
        question: 'Which of these is not determined by the movement type?',
        choices: ['Whether stock quantity increases or decreases', 'The transaction key used for account determination', 'The fields used on the entry screen', 'The vendor’s payment terms'],
        correctIndex: 3,
        explanation: 'Payment terms come from the vendor master or purchase order. The movement type decides stock direction, the account determination key and entry fields.',
      },
    ],
    'vendor-master': [
      {
        type: 'four-choice',
        question: 'What does a vendor account group control?',
        choices: ['The vendor number range and field control on the master screen', 'Purchase prices', 'Payment run dates', 'Goods receipt tolerances'],
        correctIndex: 0,
        explanation: 'The account group controls the number range and which fields are required, optional or hidden, often split by use such as one-time vendors.',
      },
      {
        type: 'ox',
        question: 'Vendor evaluation can score vendors on criteria such as price, quality, delivery and service.',
        correct: true,
        explanation: 'Correct. Weighted scores per criterion give an overall score used for sourcing decisions and improvement requests.',
      },
      {
        type: 'four-choice',
        question: 'Which transaction creates and changes vendor master data in S/4HANA?',
        choices: ['BP', 'XK01', 'MK01', 'FK01'],
        correctIndex: 0,
        explanation: 'S/4HANA uses the Business Partner transaction BP. XK01, MK01 and FK01 were the ECC vendor master transactions.',
      },
      {
        type: 'ox',
        question: 'Purchasing organisation data such as order currency, payment terms and Incoterms can differ from one purchasing organisation to another.',
        correct: true,
        explanation: 'Correct. The same vendor can have different currencies and terms for a domestic and an overseas purchasing organisation.',
      },
    ],
    'purchasing-info-contracts': [
      {
        type: 'four-choice',
        question: 'Which setting sources the same material from several vendors in fixed proportions?',
        choices: ['Quota arrangement', 'Source list', 'Purchasing info record', 'Release strategy'],
        correctIndex: 0,
        explanation: 'A quota arrangement. With shares such as 60% and 40%, MRP and requisition assignment split requirements automatically.',
      },
      {
        type: 'four-choice',
        question: 'Which master data defines, per material and plant, which vendors may be used and for which period?',
        choices: ['Source list', 'Quota arrangement', 'Condition record', 'Customer-material info record'],
        correctIndex: 0,
        explanation: 'The source list. It can block ordering from unapproved vendors and lets MRP assign vendors automatically.',
      },
      {
        type: 'ox',
        question: 'Under a scheduling agreement, no individual purchase order is created per delivery; delivery dates and quantities are given in schedule lines.',
        correct: true,
        explanation: 'Correct. For ongoing supply of the same material, only delivery instructions are issued instead of new purchase orders.',
      },
      {
        type: 'four-choice',
        question: 'What is a purchase order issued with reference to a quantity or value contract called?',
        choices: ['Release order', 'Purchase requisition', 'Request for quotation', 'Stock transport order'],
        correctIndex: 0,
        explanation: 'A release order, which consumes the contract’s remaining quantity or value.',
      },
    ],
    'special-procurement': [
      {
        type: 'four-choice',
        question: 'Which movement type provides components to a subcontractor?',
        choices: ['541', '101', '261', '411'],
        correctIndex: 0,
        explanation: '541 moves stock to material provided to the vendor. 101 is goods receipt, 261 issue to a production order and 411 transfer from special stock to own stock.',
      },
      {
        type: 'ox',
        question: 'Components provided to a subcontractor remain the company’s own stock, managed as special stock O.',
        correct: true,
        explanation: 'Correct. The company still owns them, so they keep their value until consumption is posted when the finished item is received.',
      },
      {
        type: 'four-choice',
        question: 'Which special stock indicator represents consignment stock held on behalf of a vendor?',
        choices: ['K', 'O', 'E', 'W'],
        correctIndex: 0,
        explanation: 'K is vendor consignment. O is material provided to a subcontractor, E sales order stock and W consignment at the customer.',
      },
      {
        type: 'ox',
        question: 'In a two-step stock transfer, stock between issue at the supplying location and receipt at the destination is held as stock in transit.',
        correct: true,
        explanation: 'Correct. Stock in transit cannot be used at either location but remains on the books until received.',
      },
    ],
    'inventory-count': [
      {
        type: 'four-choice',
        question: 'Which transaction creates physical inventory documents?',
        choices: ['MI01', 'MI04', 'MI07', 'MMBE'],
        correctIndex: 0,
        explanation: 'MI01 creates inventory documents. MI04 enters counts, MI07 posts differences and MMBE displays stock.',
      },
      {
        type: 'ox',
        question: 'Setting a posting block when creating an inventory document stops goods movements for the materials being counted.',
        correct: true,
        explanation: 'Correct. Movements during counting would make book and counted quantities impossible to compare, so the block halts them.',
      },
      {
        type: 'four-choice',
        question: 'Which accounts are posted when an inventory difference is posted?',
        choices: ['Inventory and an inventory difference (P&L) account', 'Inventory and GR/IR', 'Payables and price differences', 'Cost of goods sold and receivables'],
        correctIndex: 0,
        explanation: 'The difference quantity times the valuation price is posted to the inventory account and an inventory difference P&L account.',
      },
      {
        type: 'four-choice',
        question: 'How is vendor consignment stock counted?',
        choices: ['By creating an inventory document with special stock indicator K', 'It is included automatically in the own-stock document', 'It cannot be counted', 'By changing the quantity on the vendor master'],
        correctIndex: 0,
        explanation: 'Special stock is managed separately from normal stock, so the inventory document is created with the special stock indicator.',
      },
    ],
    'mm-period-end': [
      {
        type: 'four-choice',
        question: 'What is lowest value valuation of inventory for?',
        choices: ['Writing inventory down to a lower value such as market price', 'Adjusting stock quantity to the counted quantity', 'Reducing payments to vendors', 'Carrying standard cost into the next period'],
        correctIndex: 0,
        explanation: 'Lowest value valuation writes down stock whose market price or net realisable value has fallen below book value, recognising the loss.',
      },
      {
        type: 'ox',
        question: 'After MMPV moves to the next period, the standard setting still allows stock postings to the previous period.',
        correct: true,
        explanation: 'Correct. MM normally allows postings to the current and previous periods, covering cases such as last month’s receipts posted early in the new month.',
      },
      {
        type: 'four-choice',
        question: 'Which report compares inventory value with the G/L balance of inventory accounts?',
        choices: ['MB5L', 'MMBE', 'ME2M', 'MB52'],
        correctIndex: 0,
        explanation: 'MB5L lists stock values against G/L balances for MM–FI reconciliation. MMBE and MB52 show stock quantities and ME2M lists purchase orders by material.',
      },
      {
        type: 'ox',
        question: 'Items sitting on the GR/IR account for a long time may point to problems such as purchase orders never closed or duplicate postings.',
        correct: true,
        explanation: 'Correct. Receipt and invoice normally arrive close together, so long-standing items should be investigated and cleaned up.',
      },
    ],
  },
};
