import type { ModuleContent } from '../learning-types';

export const mm: Record<'ja' | 'en', ModuleContent> = {
  ja: {
    id: 'mm',
    title: 'MM（資材管理）',
    description: '購買から在庫管理までの資材管理プロセスを学習します。',
    sections: [
      {
        id: 'mm-overview',
        title: 'MMモジュール概要',
        content: [
          'MM（Materials Management）は購買・在庫管理・請求照合を担うモジュールです。',
          '主要プロセスはPTP（Purchase to Pay）：購買依頼→発注→入庫→請求照合→支払の流れです。',
          'MMはFI（買掛金）・SD（出荷）・PP（所要量計画）・WM（倉庫管理）と連携します。',
          '組織構造として購買組織・購買グループ・プラント・保管場所が使用されます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'PTP（Purchase to Pay）プロセスの正しい順序はどれですか？',
            choices: [
              '発注→購買依頼→入庫→請求照合→支払',
              '購買依頼→発注→入庫→請求照合→支払',
              '入庫→発注→購買依頼→請求照合→支払',
              '購買依頼→入庫→発注→支払→請求照合',
            ],
            correctIndex: 1,
            explanation: 'PTPプロセスは購買依頼→発注→入庫→請求照合→支払の順です。',
          },
          {
            type: 'ox',
            question: 'MMモジュールはFI（財務会計）の買掛金と連携する。',
            correct: true,
            explanation: 'MM入庫・請求照合はFIの買掛金（AP）に自動転記されます。',
          },
          {
            type: 'four-choice',
            question: 'MMの購買組織の説明として正しいものはどれですか？',
            choices: [
              '在庫の保管場所を管理する',
              '購買交渉・契約の責任を持つ組織単位',
              '製品の製造を管理する',
              '販売エリアを構成する要素',
            ],
            correctIndex: 1,
            explanation: '購買組織は仕入先との交渉・契約に責任を持つ組織単位です。',
          },
          {
            type: 'ox',
            question: '一つのプラントは複数の購買組織に割り当てることができる。',
            correct: true,
            explanation: 'プラントは複数の購買組織に割り当て可能です。',
          },
          {
            type: 'four-choice',
            question: '在庫の実地場所を表すMMの組織単位はどれですか？',
            choices: ['購買グループ', '購買組織', '保管場所', 'プラント'],
            correctIndex: 2,
            explanation: '保管場所（Storage Location）がプラント内の物理的な在庫保管場所を表します。',
          },
          {
            type: 'ordering',
            question: 'MMのPTPプロセスを正しい順序に並べてください。',
            items: ['請求照合（MIRO）', '発注（ME21N）', '支払（F110）', '購買依頼（ME51N）', '入庫（MIGO）'],
            correctOrder: [3, 1, 4, 0, 2],
            explanation: '購買依頼→発注→入庫→請求照合→支払の順です。',
          },
        ],
      },
      {
        id: 'material-master',
        title: '品目マスタ',
        content: [
          '品目マスタはMM01で作成し、基本データ・購買データ・MRPデータ・在庫管理データ等の画面で構成されます。',
          '品目タイプ（ROH：原材料、FERT：製品、HALB：半製品等）が在庫管理や評価方法を決定します。',
          '評価クラス（Valuation Class）は品目タイプと連動し、在庫のGL勘定決定に使用されます。',
          '在庫管理単位（基本単位）と発注単位が異なる場合、変換係数を設定します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '品目マスタの作成トランザクションはどれですか？',
            choices: ['ME11', 'MM01', 'MB01', 'MK01'],
            correctIndex: 1,
            explanation: 'MM01が品目マスタの作成トランザクションです。',
          },
          {
            type: 'ox',
            question: '評価クラス（Valuation Class）は在庫のGL勘定決定に使用される。',
            correct: true,
            explanation: '評価クラスはAuto Account Determinationを通じて在庫・消費等のGL勘定を決定します。',
          },
          {
            type: 'four-choice',
            question: '製品（完成品）の品目タイプはどれですか？',
            choices: ['ROH', 'HALB', 'FERT', 'NLAG'],
            correctIndex: 2,
            explanation: 'FERTが完成品（Finished Product）の品目タイプです。ROHは原材料、HALBは半製品です。',
          },
          {
            type: 'ox',
            question: '品目マスタのMRPデータ画面はプラントレベルで管理される。',
            correct: true,
            explanation: 'MRPデータはプラント固有の画面で、プラントごとに異なる計画パラメータを設定できます。',
          },
          {
            type: 'four-choice',
            question: '品目マスタで在庫評価方法として「移動平均価格」を使用する場合、価格管理コードはどれですか？',
            choices: ['S（標準価格）', 'V（移動平均価格）', 'M（市場価格）', 'F（固定価格）'],
            correctIndex: 1,
            explanation: 'V（Moving Average Price）が移動平均価格を示す価格管理コードです。Sは標準価格です。',
          },
          {
            type: 'ordering',
            question: '品目マスタの主要画面を一般的な作成順序に並べてください。',
            items: ['MRPデータ', '購買データ', '在庫管理データ', '基本データ1', '評価データ'],
            correctOrder: [3, 1, 0, 4, 2],
            explanation: '基本データ1→購買データ→MRPデータ→評価データ→在庫管理データの順が一般的です。',
          },
        ],
      },
      {
        id: 'purchase-order',
        title: '購買発注処理',
        content: [
          '購買依頼（PR）はME51Nで作成し、内部部門からの購買要求を表します。',
          '購買発注（PO）はME21Nで作成し、仕入先への正式な発注書です。',
          'リリース戦略（承認ワークフロー）は金額・品目グループ等の条件に基づき承認ルートを決定します。',
          '確認管理（Confirmation Control Key）は発注確認・出荷通知等の受領制御に使用します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '購買発注の作成トランザクションはどれですか？',
            choices: ['ME51N', 'ME21N', 'MIGO', 'ME11'],
            correctIndex: 1,
            explanation: 'ME21NがPO（Purchase Order）の作成トランザクションです。ME51Nは購買依頼です。',
          },
          {
            type: 'ox',
            question: 'リリース戦略はPOの承認プロセスを自動化するために使用される。',
            correct: true,
            explanation: 'リリース戦略により金額・品目・組織条件に基づく承認ワークフローが自動的に適用されます。',
          },
          {
            type: 'four-choice',
            question: '購買依頼（PR）から購買発注（PO）への変換トランザクションはどれですか？',
            choices: ['ME57', 'ME21N', 'ME59N', 'ME11'],
            correctIndex: 2,
            explanation: 'ME59NはPRからPOへの自動変換（自動発注）トランザクションです。ME57は手動割り付けです。',
          },
          {
            type: 'ox',
            question: 'PO（発注）の変更はME22Nで行う。',
            correct: true,
            explanation: 'ME22NはPOの変更、ME21Nは作成、ME23Nは照会です。',
          },
          {
            type: 'four-choice',
            question: '発注タイプ（NB：標準発注）に加え、外注加工に使用される発注タイプはどれですか？',
            choices: ['UB', 'FO', 'ZB', 'RFQ'],
            correctIndex: 1,
            explanation: 'FO（フレームワーク発注/枠契約参照発注）も使用されますが、外注加工はサービス発注（タイプNB+アイテムカテゴリD）が一般的です。なお標準的には発注タイプNBで品目カテゴリDを使用します。',
          },
          {
            type: 'ordering',
            question: '購買プロセスを正しい順序に並べてください。',
            items: ['購買発注（ME21N）', '入庫（MIGO）', '購買依頼（ME51N）', '請求照合（MIRO）', 'リリース（承認）'],
            correctOrder: [2, 0, 4, 1, 3],
            explanation: '購買依頼→購買発注→リリース→入庫→請求照合の順です。',
          },
        ],
      },
      {
        id: 'goods-receipt-invoice',
        title: '入庫・請求照合',
        content: [
          '入庫（GR）はMIGOで処理し、移動タイプ101（標準入庫）が在庫を増加させます。',
          '3ウェイマッチングはPO・入庫・仕入先請求書の3者を照合してから支払を実行する仕組みです。',
          '請求照合はMIROで行い、PO価格との差異が許容範囲内であれば自動的に承認されます。',
          'GR/IR照合勘定は入庫から請求照合完了まで未処理残高を一時的に保持します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '標準入庫の移動タイプはどれですか？',
            choices: ['201', '101', '261', '311'],
            correctIndex: 1,
            explanation: '101が購買発注に対する標準入庫（Goods Receipt against PO）の移動タイプです。',
          },
          {
            type: 'ox',
            question: '3ウェイマッチングはPO・入庫・仕入先請求書の照合を意味する。',
            correct: true,
            explanation: '3ウェイマッチングにより発注金額・受領数量・請求金額の整合性を確認します。',
          },
          {
            type: 'four-choice',
            question: 'MIROは何のトランザクションですか？',
            choices: ['入庫処理', '在庫移動', '請求書照合（仕入先請求処理）', '在庫評価'],
            correctIndex: 2,
            explanation: 'MIROは仕入先からの請求書をPOと照合して登録するトランザクションです。',
          },
          {
            type: 'ox',
            question: 'GR/IR照合勘定は入庫と請求照合の間の差額を永続的に記録する。',
            correct: false,
            explanation: 'GR/IR照合勘定は一時的な負債計上口座です。MIROで請求照合が完了すると残高がゼロになります。',
          },
          {
            type: 'four-choice',
            question: '請求照合で価格差異が許容範囲を超えた場合、どうなりますか？',
            choices: [
              '自動的に承認される',
              '請求書がブロックされ手動承認が必要になる',
              '自動的に拒否される',
              'POが自動修正される',
            ],
            correctIndex: 1,
            explanation: '許容範囲超過時は請求書がブロックされ、MRBR等で手動解除が必要です。',
          },
          {
            type: 'ordering',
            question: '入庫から支払までの流れを正しい順序に並べてください。',
            items: ['支払実行（F110）', '仕入先請求書受領', '入庫（MIGO/101）', '請求照合（MIRO）', 'GR/IR残高クリア'],
            correctOrder: [2, 1, 3, 4, 0],
            explanation: '入庫→仕入先請求書受領→請求照合→GR/IR残高クリア→支払実行の順です。',
          },
        ],
      },
      {
        id: 'inventory-valuation',
        title: '在庫評価と移動タイプ',
        content: [
          '在庫評価方法には標準価格（S）と移動平均価格（V）があり、品目マスタで設定します。',
          '移動タイプは在庫移動の種類（入庫・出庫・転送等）を定義し、GL転記ロジックを制御します。',
          '代表的な移動タイプ：101（PO入庫）・201（原価センタへの出庫）・261（製造指図への出庫）・311（プラント内移送）。',
          '在庫特殊在庫（コンサインメント・プロジェクト在庫等）は通常在庫とは別に管理されます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '標準価格評価法の価格管理コードはどれですか？',
            choices: ['V', 'S', 'M', 'A'],
            correctIndex: 1,
            explanation: 'S（Standard Price）が標準価格評価法のコードです。Vは移動平均価格です。',
          },
          {
            type: 'ox',
            question: '移動平均価格（V）では入庫のたびに平均単価が再計算される。',
            correct: true,
            explanation: '移動平均価格は各入庫後に在庫総額÷在庫数量で単価が更新されます。',
          },
          {
            type: 'four-choice',
            question: '製造指図への材料出庫に使用する移動タイプはどれですか？',
            choices: ['101', '201', '261', '501'],
            correctIndex: 2,
            explanation: '261が製造指図（Production Order）への出庫の移動タイプです。',
          },
          {
            type: 'ox',
            question: '移動タイプ201は購買発注に対する標準入庫を表す。',
            correct: false,
            explanation: '201は原価センタへの出庫（Goods Issue to Cost Center）です。101が標準入庫です。',
          },
          {
            type: 'four-choice',
            question: '在庫移動（Transfer Posting）でプラント内の保管場所間移動に使用する移動タイプはどれですか？',
            choices: ['101', '311', '201', '551'],
            correctIndex: 1,
            explanation: '311が同一プラント内の保管場所間移送（Transfer Posting within Plant）の移動タイプです。',
          },
          {
            type: 'ordering',
            question: '在庫評価法の選択から会計転記までの流れを正しい順序に並べてください。',
            items: ['GL転記実行', '移動タイプ確認', '品目マスタで評価方法設定', 'MIGO入力', '在庫金額計算'],
            correctOrder: [2, 3, 1, 4, 0],
            explanation: '品目マスタで評価方法設定→MIGO入力→移動タイプ確認→在庫金額計算→GL転記実行の順です。',
          },
        ],
      },
      {
        id: 'vendor-master',
        title: '仕入先マスタと購買組織',
        content: [
          '仕入先マスタはMK01（購買データのみ）またはXK01（全データ）で作成します。',
          '仕入先マスタは一般データ・会社コードデータ・購買組織データの3階層で構成されます。',
          '購買組織は購買条件（価格・支払条件等）の交渉単位であり、プラントに割り当てられます。',
          '購買グループは購買担当者のグループを表し、購買依頼・発注の担当者管理に使用します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '仕入先マスタを全データで作成するトランザクションはどれですか？',
            choices: ['MK01', 'XK01', 'ME11', 'FK01'],
            correctIndex: 1,
            explanation: 'XK01は全レベル（一般・会社コード・購買組織）のデータを一括作成します。',
          },
          {
            type: 'ox',
            question: '仕入先マスタの一般データは複数の会社コードと購買組織で共有される。',
            correct: true,
            explanation: '一般データ（名称・住所等）は会社コードや購買組織をまたいで共有されます。',
          },
          {
            type: 'four-choice',
            question: '仕入先マスタの購買組織データに含まれる典型的な項目はどれですか？',
            choices: [
              '銀行口座',
              '照合勘定',
              '購買条件（発注通貨・支払条件）',
              '仕入先名称',
            ],
            correctIndex: 2,
            explanation: '購買条件（発注通貨・最小発注金額・支払条件等）は購買組織データに含まれます。',
          },
          {
            type: 'ox',
            question: '購買グループは購買組織と同一の概念である。',
            correct: false,
            explanation: '購買組織は交渉・契約の責任単位、購買グループは担当者グループです。異なる概念です。',
          },
          {
            type: 'four-choice',
            question: '仕入先マスタの照合勘定（Reconciliation Account）はどのレベルのデータですか？',
            choices: ['一般データ', '購買組織データ', '会社コードデータ', 'プラントデータ'],
            correctIndex: 2,
            explanation: '照合勘定（買掛金勘定）は会社コードデータに含まれます。',
          },
          {
            type: 'ordering',
            question: '仕入先マスタの階層を上位から正しい順序に並べてください。',
            items: ['購買組織データ', '会社コードデータ', '一般データ'],
            correctOrder: [2, 1, 0],
            explanation: '一般データ→会社コードデータ→購買組織データの階層構造です。',
          },
        ],
      },
      {
        id: 'purchasing-info-contracts',
        title: '購買情報レコードと枠契約',
        content: [
          '購買情報レコード（PIR）はME11で作成し、品目・仕入先の組み合わせごとの購買条件（価格・リードタイム等）を保持します。',
          '枠契約には数量契約（Contract）と期間発注契約（Scheduling Agreement）の2種類があります。',
          '数量契約はME31Kで作成し、特定数量を特定仕入先から購入する合意を記録します。',
          '期間発注契約（SA）はME31Lで作成し、納入スケジュールを詳細に管理します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '購買情報レコード（PIR）の作成トランザクションはどれですか？',
            choices: ['MM01', 'ME11', 'ME31K', 'MK01'],
            correctIndex: 1,
            explanation: 'ME11がPIR（Purchasing Info Record）の作成トランザクションです。',
          },
          {
            type: 'ox',
            question: '数量契約（Contract）では品目ごとの特定数量の購入合意を管理する。',
            correct: true,
            explanation: '数量契約は合意数量と価格を記録し、都度発注（ME21N/ME57）時に参照されます。',
          },
          {
            type: 'four-choice',
            question: '期間発注契約（Scheduling Agreement）の作成トランザクションはどれですか？',
            choices: ['ME31K', 'ME31L', 'ME21N', 'ME11'],
            correctIndex: 1,
            explanation: 'ME31LがScheduling Agreement（期間発注契約）の作成トランザクションです。',
          },
          {
            type: 'ox',
            question: '購買情報レコードは発注時に自動的に価格を提案する。',
            correct: true,
            explanation: 'PIRに登録された価格・条件はME21N発注時に自動提案されます。',
          },
          {
            type: 'four-choice',
            question: '枠契約の2種類として正しい組み合わせはどれですか？',
            choices: [
              '購買依頼と購買発注',
              '数量契約と期間発注契約',
              '購買情報レコードと数量契約',
              '標準発注と消費委託発注',
            ],
            correctIndex: 1,
            explanation: '枠契約（Outline Agreement）は数量契約（Contract）と期間発注契約（Scheduling Agreement）の2種類です。',
          },
          {
            type: 'ordering',
            question: '購買情報レコードを使った発注プロセスを正しい順序に並べてください。',
            items: ['発注書作成（ME21N）', '購買依頼作成', 'PIR自動参照', '入庫処理', '購買情報レコード登録（ME11）'],
            correctOrder: [4, 1, 0, 2, 3],
            explanation: 'PIR登録→購買依頼→発注書作成（PIR自動参照）→入庫処理の順です。',
          },
        ],
      },
      {
        id: 'special-procurement',
        title: '特殊調達（コンサインメント・STO）',
        content: [
          'コンサインメント在庫は仕入先所有の在庫をプラントに保管し、使用時点で支払が発生します。',
          'コンサインメントは発注タイプNB＋品目カテゴリKで処理し、移動タイプ411Kで使用引当します。',
          'STO（Stock Transfer Order）はプラント間在庫移送を発注伝票で管理します。',
          'STOはUBタイプの発注で処理し、送り元プラントでPGI・受け入れプラントで入庫が発生します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'コンサインメント在庫の在庫払い出し（使用）に使用する移動タイプはどれですか？',
            choices: ['101', '261', '411K', '201'],
            correctIndex: 2,
            explanation: '411Kがコンサインメント在庫を自社在庫に転換（使用）する移動タイプです。',
          },
          {
            type: 'ox',
            question: 'コンサインメント在庫は使用した時点で仕入先への支払が発生する。',
            correct: true,
            explanation: 'コンサインメントは保管中は仕入先所有のため費用不発生。引き出した（411K）時点で買掛金が計上されます。',
          },
          {
            type: 'four-choice',
            question: 'STO（Stock Transfer Order）の発注タイプはどれですか？',
            choices: ['NB', 'UB', 'FO', 'ZB'],
            correctIndex: 1,
            explanation: 'UBがSTO（Plant-to-Plant Stock Transfer）の発注タイプです。',
          },
          {
            type: 'ox',
            question: 'STOでは送り元プラントと受け入れプラントの両方で在庫動作が発生する。',
            correct: true,
            explanation: '送り元でPGI（在庫減少）、受け入れ先でGR（入庫/在庫増加）が発生します。',
          },
          {
            type: 'four-choice',
            question: 'コンサインメント発注の品目カテゴリはどれですか？',
            choices: ['D（サービス）', 'K（コンサインメント）', 'B（限度額）', 'L（下請）'],
            correctIndex: 1,
            explanation: 'K（Consignment）がコンサインメント発注の品目カテゴリです。',
          },
          {
            type: 'ordering',
            question: 'STOプロセスを正しい順序に並べてください。',
            items: ['受け入れプラントで入庫', 'STO発注作成（UB）', '送り元プラントでPGI', '入庫検査', '在庫移送依頼'],
            correctOrder: [4, 1, 2, 0, 3],
            explanation: '在庫移送依頼→STO発注→送り元PGI→受け入れ入庫→入庫検査の順です。',
          },
        ],
      },
      {
        id: 'inventory-count',
        title: '棚卸処理',
        content: [
          '棚卸（Physical Inventory）はMI01で棚卸伝票を作成し、MI04で実際数量を入力、MI07で差異を転記します。',
          '循環棚卸（Cycle Counting）はABC分類に基づき頻繁に使用される品目を定期的に数える方法です。',
          '棚卸差異（差異転記）は帳簿在庫と実際数量の差分をGL転記します。',
          '棚卸凍結（Freeze Book Inventory）は棚卸期間中の在庫変動を防止するオプション機能です。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '棚卸の実際数量入力に使用するトランザクションはどれですか？',
            choices: ['MI01', 'MI04', 'MI07', 'MIGO'],
            correctIndex: 1,
            explanation: 'MI04で棚卸実際数量を入力します。MI01は伝票作成、MI07は差異転記です。',
          },
          {
            type: 'ox',
            question: '循環棚卸（Cycle Counting）ではすべての品目を同じ頻度で数える。',
            correct: false,
            explanation: '循環棚卸はABC分類に基づき、価値の高い品目（A）は高頻度、低価値品目（C）は低頻度で数えます。',
          },
          {
            type: 'four-choice',
            question: '棚卸差異転記のトランザクションはどれですか？',
            choices: ['MI01', 'MI04', 'MI07', 'MI08'],
            correctIndex: 2,
            explanation: 'MI07（Post Differences）が棚卸差異をGL勘定に転記するトランザクションです。',
          },
          {
            type: 'ox',
            question: '棚卸差異転記（MI07）後は帳簿在庫が実際在庫と一致する。',
            correct: true,
            explanation: 'MI07による差異転記で帳簿残高が調整され、実際数量と一致します。',
          },
          {
            type: 'four-choice',
            question: '棚卸ABC分析でA品目の説明として正しいものはどれですか？',
            choices: [
              '在庫金額が低く、棚卸頻度が低い',
              '在庫金額が高く、棚卸頻度が高い',
              '移動が少なく、棚卸不要',
              '新規品目で分類未定',
            ],
            correctIndex: 1,
            explanation: 'A品目は在庫金額が高い最重要品目であり、最も頻繁に棚卸されます。',
          },
          {
            type: 'ordering',
            question: '棚卸プロセスを正しい順序に並べてください。',
            items: ['差異転記（MI07）', '棚卸伝票作成（MI01）', '差異確認', '実数入力（MI04）', '在庫凍結（オプション）'],
            correctOrder: [1, 4, 3, 2, 0],
            explanation: '棚卸伝票作成→在庫凍結→実数入力→差異確認→差異転記の順です。',
          },
        ],
      },
      {
        id: 'mm-period-end',
        title: 'MM月次処理',
        content: [
          'MM月次処理ではGR/IR照合勘定の残高クリア、在庫評価の再評価、期間クローズを行います。',
          'GR/IRクリアはF.13またはMR11で未照合の入庫・請求書を整理します。',
          'MMBE（在庫状況照会）は品目別・プラント別の在庫水準を確認するトランザクションです。',
          '月次処理後はMM60等のレポートで購買実績・在庫回転率等を確認します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'GR/IR照合勘定残高の整理に使用するトランザクションはどれですか？',
            choices: ['MIGO', 'MR11', 'MI07', 'F110'],
            correctIndex: 1,
            explanation: 'MR11（Maintain GR/IR Clearing Account）でGR/IR残高の調整・クリアを行います。',
          },
          {
            type: 'ox',
            question: 'MMBEは品目別・プラント別の在庫水準を照会するトランザクションである。',
            correct: true,
            explanation: 'MMBE（Stock Overview）は在庫状況を複数レベルで照会できます。',
          },
          {
            type: 'four-choice',
            question: 'MM月次クローズで最初に確認すべき事項はどれですか？',
            choices: [
              '在庫評価レポートの印刷',
              '未処理の入庫・請求書の確認',
              '翌月の購買計画の策定',
              '仕入先への支払実行',
            ],
            correctIndex: 1,
            explanation: '月次クローズ前に未処理の入庫・MIROを完了させることが最優先です。',
          },
          {
            type: 'ox',
            question: 'GR/IR照合勘定は借方（入庫側）と貸方（請求側）が完全一致するまで残高が残る。',
            correct: true,
            explanation: '入庫のみ（請求未着）または請求のみ（入庫未着）の場合、GR/IR勘定に残高が発生します。',
          },
          {
            type: 'four-choice',
            question: 'MMの期間クローズ（会計期間変更）に使用するトランザクションはどれですか？',
            choices: ['MMPV', 'MB52', 'MMBE', 'MR11'],
            correctIndex: 0,
            explanation: 'MMPV（Close Period for Material Master）でMMの会計期間を切り替えます。',
          },
          {
            type: 'ordering',
            question: 'MM月次クローズの主要手順を正しい順序に並べてください。',
            items: ['期間クローズ（MMPV）', '未処理入庫の完了', 'GR/IRクリア（MR11）', '未処理MIRO完了', '在庫レポート確認'],
            correctOrder: [1, 3, 2, 4, 0],
            explanation: '未処理入庫→未処理MIRO→GR/IRクリア→在庫レポート確認→期間クローズの順です。',
          },
        ],
      },
    ],
  },
  en: {
    id: 'mm',
    title: 'MM (Materials Management)',
    description: 'Learn the materials management process from purchasing to inventory management.',
    sections: [
      {
        id: 'mm-overview',
        title: 'MM Module Overview',
        content: [
          'MM (Materials Management) handles purchasing, inventory management, and invoice verification.',
          'The core process is PTP (Purchase to Pay): Purchase Requisition → Purchase Order → Goods Receipt → Invoice Verification → Payment.',
          'MM integrates with FI (accounts payable), SD (shipping), PP (requirements planning), and WM (warehouse management).',
          'The organizational structure uses Purchasing Organization, Purchasing Group, Plant, and Storage Location.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What is the correct order of the PTP (Purchase to Pay) process?',
            choices: [
              'PO → PR → GR → Invoice Verification → Payment',
              'PR → PO → GR → Invoice Verification → Payment',
              'GR → PO → PR → Invoice Verification → Payment',
              'PR → GR → PO → Payment → Invoice Verification',
            ],
            correctIndex: 1,
            explanation: 'PTP: Purchase Requisition → Purchase Order → Goods Receipt → Invoice Verification → Payment.',
          },
          {
            type: 'ox',
            question: 'The MM module integrates with FI Accounts Payable.',
            correct: true,
            explanation: 'MM goods receipts and invoice verification automatically post to FI accounts payable.',
          },
          {
            type: 'four-choice',
            question: 'Which best describes the Purchasing Organization in MM?',
            choices: [
              'Manages physical stock storage locations',
              'Organizational unit responsible for purchasing negotiations and contracts',
              'Manages product manufacturing',
              'A component of the Sales Area',
            ],
            correctIndex: 1,
            explanation: 'The Purchasing Organization is the unit responsible for vendor negotiations and contracts.',
          },
          {
            type: 'ox',
            question: 'A single Plant can be assigned to multiple Purchasing Organizations.',
            correct: true,
            explanation: 'A plant can be assigned to multiple purchasing organizations.',
          },
          {
            type: 'four-choice',
            question: 'Which MM organizational unit represents the physical inventory storage location?',
            choices: ['Purchasing Group', 'Purchasing Organization', 'Storage Location', 'Plant'],
            correctIndex: 2,
            explanation: 'Storage Location represents the physical location where inventory is kept within a plant.',
          },
          {
            type: 'ordering',
            question: 'Arrange the MM PTP process steps in the correct order.',
            items: ['Invoice Verification (MIRO)', 'Purchase Order (ME21N)', 'Payment (F110)', 'Purchase Requisition (ME51N)', 'Goods Receipt (MIGO)'],
            correctOrder: [3, 1, 4, 0, 2],
            explanation: 'Purchase Requisition → Purchase Order → Goods Receipt → Invoice Verification → Payment.',
          },
        ],
      },
      {
        id: 'material-master',
        title: 'Material Master',
        content: [
          'The Material Master is created with MM01 and contains views such as Basic Data, Purchasing, MRP, and Inventory Management.',
          'Material Type (ROH: raw material, FERT: finished product, HALB: semi-finished) determines inventory and valuation behavior.',
          'The Valuation Class links the material to GL account determination for inventory postings.',
          'When the Base Unit of Measure differs from the Order Unit, a conversion factor must be configured.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction is used to create a Material Master record?',
            choices: ['ME11', 'MM01', 'MB01', 'MK01'],
            correctIndex: 1,
            explanation: 'MM01 is the transaction for creating a Material Master.',
          },
          {
            type: 'ox',
            question: 'The Valuation Class is used for GL account determination for inventory postings.',
            correct: true,
            explanation: 'The Valuation Class drives Automatic Account Determination to assign inventory, consumption, and other GL accounts.',
          },
          {
            type: 'four-choice',
            question: 'What is the Material Type for a finished product?',
            choices: ['ROH', 'HALB', 'FERT', 'NLAG'],
            correctIndex: 2,
            explanation: 'FERT is the Material Type for Finished Products. ROH is raw material, HALB is semi-finished.',
          },
          {
            type: 'ox',
            question: 'MRP data in the Material Master is managed at the Plant level.',
            correct: true,
            explanation: 'MRP views are plant-specific, allowing different planning parameters per plant.',
          },
          {
            type: 'four-choice',
            question: 'Which Price Control code represents Moving Average Price?',
            choices: ['S (Standard Price)', 'V (Moving Average Price)', 'M (Market Price)', 'F (Fixed Price)'],
            correctIndex: 1,
            explanation: 'V (Moving Average Price) is the price control code. S is Standard Price.',
          },
          {
            type: 'ordering',
            question: 'Arrange the Material Master views in a typical creation sequence.',
            items: ['MRP Data', 'Purchasing Data', 'Inventory Management Data', 'Basic Data 1', 'Accounting Data'],
            correctOrder: [3, 1, 0, 4, 2],
            explanation: 'Basic Data 1 → Purchasing → MRP → Accounting → Inventory Management is a typical sequence.',
          },
        ],
      },
      {
        id: 'purchase-order',
        title: 'Purchase Order Processing',
        content: [
          'Purchase Requisitions (PR) are created with ME51N and represent internal purchase requests.',
          'Purchase Orders (PO) are created with ME21N and are the formal order documents sent to vendors.',
          'Release Strategy (approval workflow) determines the approval route based on amount, material group, etc.',
          'Confirmation Control Key controls receipt of order acknowledgments and shipping notifications from vendors.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction is used to create a Purchase Order?',
            choices: ['ME51N', 'ME21N', 'MIGO', 'ME11'],
            correctIndex: 1,
            explanation: 'ME21N creates Purchase Orders. ME51N creates Purchase Requisitions.',
          },
          {
            type: 'ox',
            question: 'Release Strategy is used to automate the PO approval process.',
            correct: true,
            explanation: 'Release Strategy applies an approval workflow automatically based on amount, material, and organizational conditions.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction automatically converts Purchase Requisitions into Purchase Orders?',
            choices: ['ME57', 'ME21N', 'ME59N', 'ME11'],
            correctIndex: 2,
            explanation: 'ME59N performs automatic PO creation from PRs. ME57 is for manual assignment.',
          },
          {
            type: 'ox',
            question: 'ME22N is used to change an existing Purchase Order.',
            correct: true,
            explanation: 'ME22N changes a PO. ME21N creates, ME23N displays.',
          },
          {
            type: 'four-choice',
            question: 'Which Item Category is used for consignment purchasing?',
            choices: ['D (Service)', 'K (Consignment)', 'B (Limit)', 'L (Subcontracting)'],
            correctIndex: 1,
            explanation: 'K is the Item Category for Consignment purchasing.',
          },
          {
            type: 'ordering',
            question: 'Arrange the purchasing process in the correct order.',
            items: ['Purchase Order (ME21N)', 'Goods Receipt (MIGO)', 'Purchase Requisition (ME51N)', 'Invoice Verification (MIRO)', 'Release (Approval)'],
            correctOrder: [2, 0, 4, 1, 3],
            explanation: 'Purchase Requisition → Purchase Order → Release → Goods Receipt → Invoice Verification.',
          },
        ],
      },
      {
        id: 'goods-receipt-invoice',
        title: 'Goods Receipt and Invoice Verification',
        content: [
          'Goods Receipts (GR) are processed in MIGO with movement type 101 (standard GR against PO) to increase inventory.',
          'Three-way matching compares PO, GR, and vendor invoice before authorizing payment.',
          'Invoice verification is done in MIRO; if the PO price variance is within tolerance, it is automatically approved.',
          'The GR/IR clearing account holds the interim balance between goods receipt and invoice verification.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What is the movement type for a standard Goods Receipt against a Purchase Order?',
            choices: ['201', '101', '261', '311'],
            correctIndex: 1,
            explanation: '101 is the movement type for Goods Receipt against a Purchase Order.',
          },
          {
            type: 'ox',
            question: 'Three-way matching means reconciling the PO, Goods Receipt, and vendor invoice.',
            correct: true,
            explanation: 'Three-way matching verifies alignment of ordered, received, and invoiced quantities and amounts.',
          },
          {
            type: 'four-choice',
            question: 'What does transaction MIRO do?',
            choices: ['Goods Receipt processing', 'Inventory transfer', 'Vendor invoice verification', 'Inventory valuation'],
            correctIndex: 2,
            explanation: 'MIRO is the vendor invoice verification transaction that matches invoices against POs.',
          },
          {
            type: 'ox',
            question: 'The GR/IR clearing account permanently records the difference between GR and invoice.',
            correct: false,
            explanation: 'The GR/IR account is a temporary account. Its balance clears to zero when invoice verification (MIRO) is complete.',
          },
          {
            type: 'four-choice',
            question: 'What happens when an invoice price variance exceeds the tolerance in MIRO?',
            choices: [
              'It is automatically approved',
              'The invoice is blocked and requires manual release',
              'It is automatically rejected',
              'The PO is automatically corrected',
            ],
            correctIndex: 1,
            explanation: 'Invoices exceeding tolerance are blocked and must be manually released using MRBR or similar.',
          },
          {
            type: 'ordering',
            question: 'Arrange the steps from Goods Receipt to Payment in the correct order.',
            items: ['Payment Run (F110)', 'Vendor Invoice Received', 'Goods Receipt (MIGO/101)', 'Invoice Verification (MIRO)', 'GR/IR Balance Cleared'],
            correctOrder: [2, 1, 3, 4, 0],
            explanation: 'Goods Receipt → Invoice Received → Invoice Verification → GR/IR Cleared → Payment.',
          },
        ],
      },
      {
        id: 'inventory-valuation',
        title: 'Inventory Valuation and Movement Types',
        content: [
          'Inventory valuation uses either Standard Price (S) or Moving Average Price (V), set in the Material Master.',
          'Movement Types define the type of inventory movement (receipt, issue, transfer) and control the GL posting logic.',
          'Key movement types: 101 (GR vs PO), 201 (GI to Cost Center), 261 (GI to Production Order), 311 (Transfer within Plant).',
          'Special stocks (consignment, project stock, etc.) are managed separately from unrestricted stock.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which Price Control code represents Standard Price?',
            choices: ['V', 'S', 'M', 'A'],
            correctIndex: 1,
            explanation: 'S (Standard Price) is the price control code. V is Moving Average Price.',
          },
          {
            type: 'ox',
            question: 'With Moving Average Price (V), the unit price is recalculated after every goods receipt.',
            correct: true,
            explanation: 'Moving Average Price = Total Stock Value ÷ Total Stock Quantity, recalculated on each receipt.',
          },
          {
            type: 'four-choice',
            question: 'Which movement type is used for a Goods Issue to a Production Order?',
            choices: ['101', '201', '261', '501'],
            correctIndex: 2,
            explanation: '261 is the movement type for Goods Issue to a Production Order.',
          },
          {
            type: 'ox',
            question: 'Movement type 201 represents a standard Goods Receipt against a Purchase Order.',
            correct: false,
            explanation: '201 is Goods Issue to a Cost Center. 101 is the standard Goods Receipt against PO.',
          },
          {
            type: 'four-choice',
            question: 'Which movement type is used for a transfer between storage locations within the same plant?',
            choices: ['101', '311', '201', '551'],
            correctIndex: 1,
            explanation: '311 is Transfer Posting within a Plant (between storage locations).',
          },
          {
            type: 'ordering',
            question: 'Arrange the inventory valuation posting flow in the correct order.',
            items: ['GL Posting Executed', 'Movement Type Checked', 'Set Valuation Method in Material Master', 'Enter MIGO', 'Calculate Stock Value'],
            correctOrder: [2, 3, 1, 4, 0],
            explanation: 'Set Valuation Method → Enter MIGO → Check Movement Type → Calculate Stock Value → GL Posting.',
          },
        ],
      },
      {
        id: 'vendor-master',
        title: 'Vendor Master and Purchasing Organization',
        content: [
          'Vendor Master records are created with MK01 (purchasing data only) or XK01 (all data).',
          'The Vendor Master has three levels: General Data, Company Code Data, and Purchasing Organization Data.',
          'The Purchasing Organization is the negotiation unit for purchasing terms (price, payment terms, etc.).',
          'The Purchasing Group represents a buyer or group of buyers for managing PR and PO responsibility.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction creates a Vendor Master with all data levels?',
            choices: ['MK01', 'XK01', 'ME11', 'FK01'],
            correctIndex: 1,
            explanation: 'XK01 creates all levels (General, Company Code, Purchasing Org) at once.',
          },
          {
            type: 'ox',
            question: 'General Data in the Vendor Master is shared across multiple Company Codes and Purchasing Organizations.',
            correct: true,
            explanation: 'General Data (name, address, etc.) is shared across all Company Codes and Purchasing Organizations.',
          },
          {
            type: 'four-choice',
            question: 'Which item is typically found in the Vendor Master Purchasing Organization data?',
            choices: [
              'Bank Account',
              'Reconciliation Account',
              'Purchasing Conditions (order currency, payment terms)',
              'Vendor Name',
            ],
            correctIndex: 2,
            explanation: 'Purchasing conditions (order currency, minimum order value, payment terms) belong to Purchasing Organization data.',
          },
          {
            type: 'ox',
            question: 'Purchasing Group and Purchasing Organization are the same concept.',
            correct: false,
            explanation: 'Purchasing Organization is the negotiation/contract unit; Purchasing Group is a group of buyers. They are different.',
          },
          {
            type: 'four-choice',
            question: 'The Reconciliation Account in the Vendor Master belongs to which data level?',
            choices: ['General Data', 'Purchasing Organization Data', 'Company Code Data', 'Plant Data'],
            correctIndex: 2,
            explanation: 'The reconciliation account (accounts payable GL account) is part of Company Code Data.',
          },
          {
            type: 'ordering',
            question: 'Arrange the Vendor Master hierarchy from top to bottom.',
            items: ['Purchasing Organization Data', 'Company Code Data', 'General Data'],
            correctOrder: [2, 1, 0],
            explanation: 'General Data → Company Code Data → Purchasing Organization Data (top to bottom).',
          },
        ],
      },
      {
        id: 'purchasing-info-contracts',
        title: 'Purchasing Info Records and Outline Agreements',
        content: [
          'Purchasing Info Records (PIR) are created in ME11 and store purchasing conditions (price, lead time) per material-vendor combination.',
          'Outline Agreements have two types: Contracts (quantity-based) and Scheduling Agreements (time-based).',
          'Contracts are created with ME31K and record agreements to purchase a specific quantity from a specific vendor.',
          'Scheduling Agreements are created with ME31L and manage detailed delivery schedules.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction creates a Purchasing Info Record (PIR)?',
            choices: ['MM01', 'ME11', 'ME31K', 'MK01'],
            correctIndex: 1,
            explanation: 'ME11 creates Purchasing Info Records.',
          },
          {
            type: 'ox',
            question: 'A Contract (outline agreement) records the agreement to purchase a specific quantity from a vendor.',
            correct: true,
            explanation: 'Contracts store agreed quantities and prices, referenced during subsequent purchase orders.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction creates a Scheduling Agreement?',
            choices: ['ME31K', 'ME31L', 'ME21N', 'ME11'],
            correctIndex: 1,
            explanation: 'ME31L creates Scheduling Agreements.',
          },
          {
            type: 'ox',
            question: 'Purchasing Info Records automatically propose prices when creating Purchase Orders.',
            correct: true,
            explanation: 'Prices and conditions stored in PIRs are automatically proposed in ME21N.',
          },
          {
            type: 'four-choice',
            question: 'Which two types form the Outline Agreements in MM?',
            choices: [
              'Purchase Requisition and Purchase Order',
              'Contract and Scheduling Agreement',
              'Info Record and Contract',
              'Standard PO and Consignment PO',
            ],
            correctIndex: 1,
            explanation: 'Outline Agreements consist of Contracts (quantity-based) and Scheduling Agreements (time-based).',
          },
          {
            type: 'ordering',
            question: 'Arrange the PIR-based ordering process in the correct order.',
            items: ['Create PO (ME21N)', 'Create Purchase Requisition', 'PIR Auto-Referenced', 'Goods Receipt', 'Register PIR (ME11)'],
            correctOrder: [4, 1, 0, 2, 3],
            explanation: 'Register PIR → Create PR → Create PO (PIR auto-referenced) → Goods Receipt.',
          },
        ],
      },
      {
        id: 'special-procurement',
        title: 'Special Procurement (Consignment and STO)',
        content: [
          'Consignment stock is vendor-owned inventory stored at the plant; payment only occurs when the stock is consumed.',
          'Consignment is ordered with document type NB + Item Category K, and movement type 411K transfers it to own stock.',
          'STO (Stock Transfer Order) manages plant-to-plant inventory transfers using purchase order documents.',
          'STOs use document type UB; the sending plant executes PGI and the receiving plant executes a goods receipt.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which movement type is used to consume (transfer to own stock) consignment inventory?',
            choices: ['101', '261', '411K', '201'],
            correctIndex: 2,
            explanation: '411K converts consignment stock to own unrestricted stock (consumption/withdrawal).',
          },
          {
            type: 'ox',
            question: 'Payment for consignment stock is triggered at the time of consumption.',
            correct: true,
            explanation: 'Consignment stock remains vendor-owned while in storage. The 411K movement triggers accounts payable posting.',
          },
          {
            type: 'four-choice',
            question: 'What is the document type for a Stock Transfer Order (STO)?',
            choices: ['NB', 'UB', 'FO', 'ZB'],
            correctIndex: 1,
            explanation: 'UB is the document type for plant-to-plant Stock Transfer Orders.',
          },
          {
            type: 'ox',
            question: 'An STO triggers inventory movements at both the sending and receiving plants.',
            correct: true,
            explanation: 'The sending plant executes PGI (stock decrease) and the receiving plant executes a GR (stock increase).',
          },
          {
            type: 'four-choice',
            question: 'Which Item Category is used for consignment purchase orders?',
            choices: ['D (Service)', 'K (Consignment)', 'B (Limit)', 'L (Subcontracting)'],
            correctIndex: 1,
            explanation: 'K is the Item Category for Consignment orders.',
          },
          {
            type: 'ordering',
            question: 'Arrange the STO process in the correct order.',
            items: ['Receiving Plant GR', 'Create STO (UB)', 'Sending Plant PGI', 'Quality Inspection', 'Stock Transfer Request'],
            correctOrder: [4, 1, 2, 0, 3],
            explanation: 'Stock Transfer Request → Create STO → Sending Plant PGI → Receiving Plant GR → Quality Inspection.',
          },
        ],
      },
      {
        id: 'inventory-count',
        title: 'Physical Inventory',
        content: [
          'Physical Inventory uses MI01 to create inventory documents, MI04 to enter actual counts, and MI07 to post differences.',
          'Cycle Counting counts high-value items (A-class) more frequently based on ABC classification.',
          'Inventory differences post the variance between book inventory and actual count to GL accounts.',
          'Freeze Book Inventory is an optional feature that prevents stock movements during the count period.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction is used to enter actual inventory counts?',
            choices: ['MI01', 'MI04', 'MI07', 'MIGO'],
            correctIndex: 1,
            explanation: 'MI04 enters the actual count. MI01 creates the document, MI07 posts differences.',
          },
          {
            type: 'ox',
            question: 'Cycle Counting counts all materials at the same frequency.',
            correct: false,
            explanation: 'Cycle Counting uses ABC classification: A-class (high value) is counted most frequently, C-class least frequently.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction posts inventory count differences?',
            choices: ['MI01', 'MI04', 'MI07', 'MI08'],
            correctIndex: 2,
            explanation: 'MI07 (Post Differences) posts inventory variances to GL accounts.',
          },
          {
            type: 'ox',
            question: 'After MI07, the book inventory matches the actual physical count.',
            correct: true,
            explanation: 'MI07 adjusts the book inventory to match the actual count, eliminating the difference.',
          },
          {
            type: 'four-choice',
            question: 'Which describes an A-class item in inventory ABC analysis?',
            choices: [
              'Low value; low counting frequency',
              'High value; high counting frequency',
              'Rarely moved; no counting needed',
              'New material; classification pending',
            ],
            correctIndex: 1,
            explanation: 'A-class items are high-value, most critical materials and are counted most frequently.',
          },
          {
            type: 'ordering',
            question: 'Arrange the physical inventory process in the correct order.',
            items: ['Post Differences (MI07)', 'Create Inventory Document (MI01)', 'Review Differences', 'Enter Actual Count (MI04)', 'Freeze Stock (optional)'],
            correctOrder: [1, 4, 3, 2, 0],
            explanation: 'Create Document → Freeze Stock → Enter Count → Review Differences → Post Differences.',
          },
        ],
      },
      {
        id: 'mm-period-end',
        title: 'MM Period-End Processing',
        content: [
          'MM period-end closing includes clearing the GR/IR account, revaluation of inventory, and period close.',
          'GR/IR clearing uses F.13 or MR11 to reconcile unmatched receipts and invoices.',
          'MMBE (Stock Overview) displays inventory levels by material, plant, and storage location.',
          'After period-end, reports such as MM60 are used to review purchasing performance and inventory turnover.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction is used to clear GR/IR account balances?',
            choices: ['MIGO', 'MR11', 'MI07', 'F110'],
            correctIndex: 1,
            explanation: 'MR11 (Maintain GR/IR Clearing Account) adjusts and clears outstanding GR/IR balances.',
          },
          {
            type: 'ox',
            question: 'MMBE is a transaction for viewing inventory levels by material and plant.',
            correct: true,
            explanation: 'MMBE (Stock Overview) provides a multi-level view of inventory status.',
          },
          {
            type: 'four-choice',
            question: 'What should be verified first before MM period-end close?',
            choices: [
              'Print inventory valuation reports',
              'Verify all open GRs and pending invoices are processed',
              'Prepare next month\'s purchasing plan',
              'Execute vendor payment run',
            ],
            correctIndex: 1,
            explanation: 'Completing all open GRs and MIROs before month-end close is the top priority.',
          },
          {
            type: 'ox',
            question: 'The GR/IR clearing account retains a balance until both the GR side and invoice side are fully matched.',
            correct: true,
            explanation: 'GR-only or invoice-only entries leave a balance on the GR/IR account until the counterpart is posted.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction is used to close the MM posting period (period change)?',
            choices: ['MMPV', 'MB52', 'MMBE', 'MR11'],
            correctIndex: 0,
            explanation: 'MMPV (Close Period for Material Master) switches the MM accounting period.',
          },
          {
            type: 'ordering',
            question: 'Arrange the MM period-end closing steps in the correct order.',
            items: ['Period Close (MMPV)', 'Complete Open GRs', 'GR/IR Clearing (MR11)', 'Complete Open MIROs', 'Review Inventory Reports'],
            correctOrder: [1, 3, 2, 4, 0],
            explanation: 'Complete Open GRs → Complete Open MIROs → GR/IR Clearing → Review Inventory Reports → Period Close.',
          },
        ],
      },
    ],
  },
};
