import type { Quiz } from '../learning-types';
import type { Language } from '../i18n';

/** Additional PP practice questions, appended after each section's originals. */
export const ppQuizzes: Record<Language, Record<string, Quiz[]>> = {
  ja: {
    'pp-overview': [
      {
        type: 'four-choice',
        question: '化学・食品・医薬品などのプロセス産業で、製造指図の代わりに使う指図はどれか。',
        choices: ['プロセス指図', '内部指図', '保守指図', '計画手配'],
        correctIndex: 0,
        explanation: 'プロセス指図です。作業手順の代わりにマスタレシピ、作業場所の代わりに資源を使います。',
      },
      {
        type: 'ox',
        question: '組立受注生産（ATO）では、部品までを見込みで準備しておき、受注を受けてから最終組立を行う。',
        correct: true,
        explanation: '正しいです。見込生産と受注生産の中間で、部品の調達リードタイムを短縮しながら、受注に合わせた組立ができます。',
      },
      {
        type: 'ox',
        question: 'MRPは自社で製造する品目の計画だけでなく、外部から調達する品目の購買依頼も作成する。',
        correct: true,
        explanation: '正しいです。調達タイプが外部調達の品目には購買依頼（または外部調達用の計画手配）が作成され、MMの購買に引き継がれます。',
      },
      {
        type: 'four-choice',
        question: 'PPとSDの接点として最も適切なものはどれか。',
        choices: ['受注が受注生産の所要量としてMRPに引き渡される', '請求伝票が製造指図を作成する', '出荷ポイントが作業場所を決める', '条件レコードが部品表を決める'],
        correctIndex: 0,
        explanation: '受注の数量と納期はMRPの所要量になります。受注生産では受注ごとに計画され、見込生産では計画独立所要量を消費します。',
      },
    ],
    'bom-routing': [
      {
        type: 'four-choice',
        question: '部品表用途「1」が表す用途はどれか。',
        choices: ['製造', '設計', '汎用', '原価計算'],
        correctIndex: 0,
        explanation: '1は製造用です。2は設計、3は汎用、5は販売、6は原価計算に使われます。用途を分けることで、同じ品目に目的別の部品表を持てます。',
      },
      {
        type: 'four-choice',
        question: '低位コードの目的として正しいものはどれか。',
        choices: [
          '複数の階層で使われる品目を、最も下の階層でまとめて計画できるようにする',
          '部品表の有効期間を管理する',
          '作業手順の工程番号を自動採番する',
          '品目の在庫評価方法を決める',
        ],
        correctIndex: 0,
        explanation: '同じ部品が複数の階層で使われる場合、MRPは低位コードの順に計画します。すべての所要量が出そろってから計画することで、計算の重複を防ぎます。',
      },
      {
        type: 'ox',
        question: '作業手順の標準値（段取時間や加工時間など）は、作業場所の活動タイプと組み合わせて原価計算にも使われる。',
        correct: true,
        explanation: '正しいです。標準値に活動単価を掛けることで、工程ごとの加工費が標準原価に積み上がります。',
      },
      {
        type: 'four-choice',
        question: '部品表を照会するトランザクションコードはどれか。',
        choices: ['CS03', 'CS01', 'CA03', 'CR03'],
        correctIndex: 0,
        explanation: 'CS03が部品表の照会です。CS01は部品表の作成、CA03は作業手順の照会、CR03は作業場所の照会です。',
      },
    ],
    'mrp-production-order': [
      {
        type: 'four-choice',
        question: '在庫が発注点を下回ったときに補充を計画するMRPタイプはどれか。',
        choices: ['PD', 'VB', 'ND', 'X0'],
        correctIndex: 1,
        explanation: 'VBは手動発注点計画です。PDは通常のMRP、NDは計画なしを表します。',
      },
      {
        type: 'four-choice',
        question: 'ロットサイズ「EX」の説明として正しいものはどれか。',
        choices: ['不足した数量をちょうど補う数量で計画する', '常に固定の数量で計画する', '1週間分の所要量をまとめて計画する', '最大在庫レベルまで補充する'],
        correctIndex: 0,
        explanation: 'EXはロット対ロット（Lot-for-Lot）で、不足数量ぴったりを計画します。在庫が残りにくい一方、調達や段取の回数は増えます。',
      },
      {
        type: 'ox',
        question: 'MRPの正味所要量計算では、所要量から利用可能な在庫と入庫予定を差し引いて、不足する数量を求める。',
        correct: true,
        explanation: '正しいです。この不足数量に対して、ロットサイズを考慮した計画手配や購買依頼が作成されます。',
      },
      {
        type: 'four-choice',
        question: 'MRPが作成した計画手配のうち、購買依頼に変換するのはどのような品目か。',
        choices: ['外部から調達する品目', '自社で製造する品目', '計画対象外の品目', 'バッチ管理対象の品目'],
        correctIndex: 0,
        explanation: '外部調達品目の計画手配は購買依頼に変換され、購買発注につながります。自社製造品目の計画手配は製造指図に変換します。',
      },
    ],
    'production-confirmation': [
      {
        type: 'four-choice',
        question: 'バックフラッシュの説明として正しいものはどれか。',
        choices: [
          '確認を入力したときに、部品の出庫が自動で転記される',
          '確認を取り消すと、製造指図が削除される',
          '部品の出庫を確認より先に手動で行う',
          '完成品の入庫を翌月にまとめて行う',
        ],
        correctIndex: 0,
        explanation: 'バックフラッシュでは、確認した数量に応じて部品表の数量分の出庫が自動で転記されます。細かい部品の出庫入力を省けます。',
      },
      {
        type: 'ox',
        question: '確認は最終工程だけでなく、工程ごとに入力することもできる。',
        correct: true,
        explanation: '正しいです。工程ごとに確認すると進捗をきめ細かく把握できます。どの工程で確認が必須かは管理キーで設定します。',
      },
      {
        type: 'four-choice',
        question: '入力した確認を取り消すトランザクションコードはどれか。',
        choices: ['CO13', 'CO11N', 'CO02', 'CO03'],
        correctIndex: 0,
        explanation: 'CO13が確認の取消です。取り消すと、確認で転記された活動配賦やバックフラッシュの出庫も戻されます。',
      },
      {
        type: 'ox',
        question: '確認で記録した作業時間は、活動単価を掛けた金額が製造指図に実際原価として計上される。',
        correct: true,
        explanation: '正しいです。作業時間などの活動量に活動単価を掛けた金額が、原価センタから製造指図に配賦されます。',
      },
    ],
    'capacity-planning': [
      {
        type: 'four-choice',
        question: '作業場所の負荷をグラフで確認しながら、作業を別の日や別の作業場所に移して平準化するトランザクションコードはどれか。',
        choices: ['CM25', 'CM01', 'CO11N', 'MD04'],
        correctIndex: 0,
        explanation: 'CM25は計画ボードによる能力平準化です。CM01は能力負荷の照会、CO11Nは確認、MD04は在庫/所要量一覧です。',
      },
      {
        type: 'four-choice',
        question: '作業場所の利用可能能力を計算するときに使う情報として適切でないものはどれか。',
        choices: ['稼働の開始時間と終了時間', '休憩時間', '稼働率', '得意先の与信限度額'],
        correctIndex: 3,
        explanation: '利用可能能力は、稼働時間から休憩を引き、稼働率と能力の数（機械の台数など）を掛けて計算します。与信限度額は関係ありません。',
      },
      {
        type: 'four-choice',
        question: 'ボトルネック工程に着目して能力計画を行う理由として最も適切なものはどれか。',
        choices: ['最も能力が不足する工程が、全体の産出量を決めるため', 'すべての工程の能力が同じであるため', 'ボトルネック工程は原価計算の対象外であるため', 'MRPがボトルネック工程だけを計画するため'],
        correctIndex: 0,
        explanation: 'ほかの工程に余力があっても、ボトルネック工程を通れる量以上は完成しません。その工程の負荷を優先して調整するのが効果的です。',
      },
      {
        type: 'ox',
        question: '前方スケジューリングは開始日から後ろへ、後方スケジューリングは終了日から前へ日程を計算する。',
        correct: true,
        explanation: '正しいです。MRPでは所要日から逆算する後方スケジューリングが基本で、開始日が過去になる場合は前方スケジューリングに切り替えることもあります。',
      },
    ],
    'batch-management': [
      {
        type: 'four-choice',
        question: 'あるバッチの原材料がどの製品に使われ、どの得意先に出荷されたかをたどるための機能はどれか。',
        choices: ['バッチ使用照会（トレーサビリティ）', 'バッチ決定', '分類システム', '低位コード'],
        correctIndex: 0,
        explanation: 'バッチの使用照会で、入庫から製造・出荷までのバッチのつながりをたどれます。品質問題の回収範囲を特定するのに欠かせません。',
      },
      {
        type: 'ox',
        question: '含有率や色などのバッチの特性は分類システムで保持し、バッチ決定の検索条件として使うことができる。',
        correct: true,
        explanation: '正しいです。「含有率が一定以上のバッチだけを出荷する」といった条件で、バッチ決定の対象を絞り込めます。',
      },
      {
        type: 'four-choice',
        question: 'バッチ決定が行われる場面として通常ないものはどれか。',
        choices: ['製造指図の部品出庫', '出荷伝票の作成', '在庫の出庫', '購買発注の登録'],
        correctIndex: 3,
        explanation: 'バッチ決定は、どのバッチを使うか・出すかを決める場面で行われます。発注の時点ではまだバッチが存在しないため対象外です。',
      },
      {
        type: 'ox',
        question: 'バッチ管理対象の品目では、入庫時にバッチ番号を指定するか自動採番しないと、在庫を転記できない。',
        correct: true,
        explanation: '正しいです。バッチ管理品目の在庫は必ずいずれかのバッチに属するため、入庫時にバッチの指定が必要です。',
      },
    ],
    'work-center': [
      {
        type: 'four-choice',
        question: '作業場所が担う役割に含まれないものはどれか。',
        choices: ['スケジューリング', '能力計画', '原価計算', '販売価格の決定'],
        correctIndex: 3,
        explanation: '作業場所は、日程計算（スケジューリング）、能力計画、原価計算の3つの役割を担います。販売価格はSDの価格決定で決まります。',
      },
      {
        type: 'four-choice',
        question: '作業場所に設定する標準値キーの役割として正しいものはどれか。',
        choices: ['作業手順で入力する標準値（段取時間、加工時間など）の種類を決める', '作業場所の番号範囲を決める', '作業場所を会社コードに割り当てる', '作業場所の稼働カレンダーを決める'],
        correctIndex: 0,
        explanation: '標準値キーは、作業手順の工程でどの標準値を入力できるかを決めます。作業場所ごとに段取・加工・人員時間などの項目を定義します。',
      },
      {
        type: 'ox',
        question: '作業場所を階層にまとめると、上位の階層で能力を集計して評価することができる。',
        correct: true,
        explanation: '正しいです。個々の機械だけでなく、工場やライン単位で負荷をまとめて確認できます。',
      },
      {
        type: 'four-choice',
        question: '作業場所に設定する計算式の用途として正しいものはどれか。',
        choices: ['標準値と数量から、所要時間・能力所要量・原価を計算する', '得意先ごとの価格を計算する', '減価償却費を計算する', '為替差損益を計算する'],
        correctIndex: 0,
        explanation: '計算式は、工程の標準値と製造数量から、日程計算の所要時間、能力所要量、原価計算の活動量をそれぞれ求めるために使います。',
      },
    ],
    'demand-management': [
      {
        type: 'four-choice',
        question: '計画戦略40（最終組立を含む計画）の説明として正しいものはどれか。',
        choices: [
          '計画独立所要量で部品まで生産を進め、受注がその所要量を消費する',
          '受注が入るまで一切生産しない',
          '計画独立所要量と受注を両方とも別々に生産する',
          '需要予測を使わずに発注点で補充する',
        ],
        correctIndex: 0,
        explanation: '戦略40では、予測にもとづいて生産を進め、受注が入るとその分だけ計画独立所要量を消費します。受注の変動に素早く対応できます。',
      },
      {
        type: 'four-choice',
        question: '消費モードが「後方消費」の場合の動作として正しいものはどれか。',
        choices: ['受注の所要日より前にある計画独立所要量を消費する', '受注の所要日より後にある計画独立所要量を消費する', '計画独立所要量を消費しない', 'すべての計画独立所要量を一度に消費する'],
        correctIndex: 0,
        explanation: '後方消費では、受注の所要日から過去方向にある計画独立所要量を探して消費します。前方消費はその逆で、将来方向を探します。',
      },
      {
        type: 'ox',
        question: '消費期間が短すぎると、受注と計画独立所要量の日付が少しずれただけで消費されず、所要量が二重に計上されることがある。',
        correct: true,
        explanation: '正しいです。MD04で受注と計画独立所要量が並んで残っていたら、消費期間の設定を疑うべきです。',
      },
      {
        type: 'four-choice',
        question: '品目にどの計画戦略を適用するかは、どこで設定するか。',
        choices: ['品目マスタの戦略グループ', '得意先マスタ', '作業場所', '購買情報レコード'],
        correctIndex: 0,
        explanation: '品目マスタのMRPビューに戦略グループを設定し、そこに計画戦略が割り当てられています。',
      },
    ],
    'production-order-lifecycle': [
      {
        type: 'four-choice',
        question: '製造指図の作成時やリリース時に、部品の在庫が足りるかを確認する機能はどれか。',
        choices: ['可用性チェック', '与信チェック', '差異計算', '仕掛品計算'],
        correctIndex: 0,
        explanation: '可用性チェックです。部品の不足がある状態で指図をリリースすると、現場で作業が止まる原因になります。',
      },
      {
        type: 'four-choice',
        question: 'リリース前（CRTD）の製造指図で、まだ実行できない処理はどれか。',
        choices: ['確認と部品の出庫', '指図の変更', '可用性チェック', '日程計算'],
        correctIndex: 0,
        explanation: 'CRTDは作成済みの段階で、現場での実行はまだ許可されていません。確認や出庫はリリース（REL）後に行えるようになります。',
      },
      {
        type: 'ox',
        question: 'リリース時の可用性チェックで部品が不足していても、設定によっては指図をリリースできる。',
        correct: true,
        explanation: '正しいです。不足があればリリースを止めるか、警告だけにするかを設定できます。',
      },
      {
        type: 'ox',
        question: '製造指図は削除フラグを設定したうえで、アーカイブ処理によってデータベースから物理的に削除される。',
        correct: true,
        explanation: '正しいです。削除フラグだけでは画面から消えず、アーカイブ処理を経て初めて物理的に削除されます。',
      },
    ],
    'pp-period-end': [
      {
        type: 'four-choice',
        question: '複数の製造指図の仕掛品（WIP）を一括で計算するトランザクションコードはどれか。',
        choices: ['KKAO', 'KKS1', 'CO88', 'CO11N'],
        correctIndex: 0,
        explanation: 'KKAOが仕掛品の一括計算です。KKS1は差異の一括計算、CO88は一括決済、CO11Nは確認の入力です。',
      },
      {
        type: 'ox',
        question: '仕掛品として計上された金額は、指図が納入完了やTECOになった期間に取り消され、その後は差異計算の対象になる。',
        correct: true,
        explanation: '正しいです。未完了の間は仕掛品として資産に計上し、完了すると仕掛品を取り消して、実際原価と目標原価の差を差異として計算します。',
      },
      {
        type: 'four-choice',
        question: '期末に滞留データとして確認すべきものとして最も適切なものはどれか。',
        choices: ['製造が終わっているのに長期間TECOされていない製造指図', '今月作成された作業場所', '有効期間内の部品表', '承認済みの購買発注'],
        correctIndex: 0,
        explanation: '製造が終わった指図がTECOされないまま残ると、仕掛品として計上され続け、差異も計算されません。期末に洗い出して整理します。',
      },
      {
        type: 'ox',
        question: '標準原価の製品は、製造指図の実際原価にかかわらず標準原価で入庫され、実際原価との差額は差異として処理される。',
        correct: true,
        explanation: '正しいです。完成品の在庫は標準原価で評価され、指図に集計された実際原価との差額が差異計算と決済で処理されます。',
      },
    ],
  },
  en: {
    'pp-overview': [
      {
        type: 'four-choice',
        question: 'In process industries such as chemicals, food and pharmaceuticals, which order is used instead of a production order?',
        choices: ['Process order', 'Internal order', 'Maintenance order', 'Planned order'],
        correctIndex: 0,
        explanation: 'The process order, which uses master recipes instead of routings and resources instead of work centres.',
      },
      {
        type: 'ox',
        question: 'In assemble-to-order, components are prepared in advance and final assembly happens once the sales order arrives.',
        correct: true,
        explanation: 'Correct. It sits between make-to-stock and make-to-order, shortening component lead time while assembling to the order.',
      },
      {
        type: 'ox',
        question: 'MRP plans not only in-house produced materials but also creates purchase requisitions for externally procured materials.',
        correct: true,
        explanation: 'Correct. For externally procured materials MRP creates purchase requisitions, or planned orders for external procurement, which pass on to purchasing.',
      },
      {
        type: 'four-choice',
        question: 'Which is the clearest link between PP and SD?',
        choices: ['Sales orders pass to MRP as requirements', 'Billing documents create production orders', 'Shipping points determine work centres', 'Condition records determine BOMs'],
        correctIndex: 0,
        explanation: 'Order quantities and dates become MRP requirements. Make-to-order plans per order, while make-to-stock consumes planned independent requirements.',
      },
    ],
    'bom-routing': [
      {
        type: 'four-choice',
        question: 'What does BOM usage 1 represent?',
        choices: ['Production', 'Engineering', 'Universal', 'Costing'],
        correctIndex: 0,
        explanation: 'Usage 1 is production. 2 is engineering, 3 universal, 5 sales and 6 costing. Usages let one material have BOMs for different purposes.',
      },
      {
        type: 'four-choice',
        question: 'What is the low-level code for?',
        choices: [
          'Planning a material used on several BOM levels once, at its lowest level',
          'Managing BOM validity periods',
          'Numbering routing operations automatically',
          'Setting the material’s valuation method',
        ],
        correctIndex: 0,
        explanation: 'When a component appears on several levels, MRP plans in low-level code order, waiting until all requirements are known and avoiding repeated calculation.',
      },
      {
        type: 'ox',
        question: 'Routing standard values such as setup and processing time are combined with work centre activity types for costing as well.',
        correct: true,
        explanation: 'Correct. Standard values multiplied by activity prices build production cost per operation into the standard cost.',
      },
      {
        type: 'four-choice',
        question: 'Which transaction displays a bill of materials?',
        choices: ['CS03', 'CS01', 'CA03', 'CR03'],
        correctIndex: 0,
        explanation: 'CS03 displays a BOM. CS01 creates one, CA03 displays a routing and CR03 displays a work centre.',
      },
    ],
    'mrp-production-order': [
      {
        type: 'four-choice',
        question: 'Which MRP type plans replenishment when stock falls below the reorder point?',
        choices: ['PD', 'VB', 'ND', 'X0'],
        correctIndex: 1,
        explanation: 'VB is manual reorder point planning. PD is standard MRP and ND means no planning.',
      },
      {
        type: 'four-choice',
        question: 'What does lot size EX mean?',
        choices: ['Plan exactly the shortage quantity', 'Always plan a fixed quantity', 'Group a week’s requirements', 'Replenish up to maximum stock'],
        correctIndex: 0,
        explanation: 'EX is lot-for-lot, planning exactly the shortage. Little stock is left over, but procurement and setups happen more often.',
      },
      {
        type: 'ox',
        question: 'MRP net requirements calculation subtracts available stock and scheduled receipts from requirements to find the shortage.',
        correct: true,
        explanation: 'Correct. Planned orders or purchase requisitions are then created for the shortage, taking the lot size into account.',
      },
      {
        type: 'four-choice',
        question: 'Planned orders for which materials are converted into purchase requisitions?',
        choices: ['Externally procured materials', 'In-house produced materials', 'Materials excluded from planning', 'Batch-managed materials'],
        correctIndex: 0,
        explanation: 'Planned orders for external procurement become purchase requisitions and then purchase orders; those for in-house production become production orders.',
      },
    ],
    'production-confirmation': [
      {
        type: 'four-choice',
        question: 'What is backflushing?',
        choices: [
          'Component issues are posted automatically when a confirmation is entered',
          'Cancelling a confirmation deletes the production order',
          'Components are issued manually before confirmation',
          'Finished goods receipts are grouped into the following month',
        ],
        correctIndex: 0,
        explanation: 'With backflushing, confirming a quantity posts issues of the BOM quantities automatically, saving manual entry for small components.',
      },
      {
        type: 'ox',
        question: 'Confirmations can be entered per operation, not only for the final operation.',
        correct: true,
        explanation: 'Correct. Confirming per operation gives finer visibility of progress; the control key decides where confirmation is required.',
      },
      {
        type: 'four-choice',
        question: 'Which transaction cancels a confirmation?',
        choices: ['CO13', 'CO11N', 'CO02', 'CO03'],
        correctIndex: 0,
        explanation: 'CO13 cancels confirmations, reversing the activity allocations and backflushed issues they posted.',
      },
      {
        type: 'ox',
        question: 'Labour time recorded in a confirmation is multiplied by the activity price and charged to the production order as actual cost.',
        correct: true,
        explanation: 'Correct. Activity quantity times activity price is allocated from the cost centre to the production order.',
      },
    ],
    'capacity-planning': [
      {
        type: 'four-choice',
        question: 'Which transaction levels capacity by moving operations to other dates or work centres on a graphical board?',
        choices: ['CM25', 'CM01', 'CO11N', 'MD04'],
        correctIndex: 0,
        explanation: 'CM25 is capacity levelling on the planning table. CM01 displays load, CO11N enters confirmations and MD04 is the stock/requirements list.',
      },
      {
        type: 'four-choice',
        question: 'Which of these is not used to calculate a work centre’s available capacity?',
        choices: ['Shift start and finish times', 'Break times', 'Utilisation rate', 'Customer credit limit'],
        correctIndex: 3,
        explanation: 'Available capacity takes operating time less breaks, times utilisation and the number of individual capacities such as machines. Credit limits play no part.',
      },
      {
        type: 'four-choice',
        question: 'Why focus capacity planning on the bottleneck operation?',
        choices: ['The most constrained operation determines overall output', 'All operations have the same capacity', 'Bottlenecks are excluded from costing', 'MRP only plans bottleneck operations'],
        correctIndex: 0,
        explanation: 'However much spare capacity elsewhere, output cannot exceed what passes through the bottleneck, so adjusting its load pays off most.',
      },
      {
        type: 'ox',
        question: 'Forward scheduling calculates dates from the start date onwards; backward scheduling works back from the finish date.',
        correct: true,
        explanation: 'Correct. MRP schedules backwards from the requirement date by default and can switch to forward scheduling when the start date would fall in the past.',
      },
    ],
    'batch-management': [
      {
        type: 'four-choice',
        question: 'Which function traces which products a raw material batch went into and which customers received them?',
        choices: ['Batch where-used (traceability)', 'Batch determination', 'Classification system', 'Low-level code'],
        correctIndex: 0,
        explanation: 'The batch where-used list follows batches from receipt through production to shipment, essential for defining the scope of a recall.',
      },
      {
        type: 'ox',
        question: 'Batch characteristics such as concentration or colour are held in the classification system and can be used as selection criteria in batch determination.',
        correct: true,
        explanation: 'Correct. Conditions such as shipping only batches above a certain concentration narrow batch determination.',
      },
      {
        type: 'four-choice',
        question: 'In which situation does batch determination not normally take place?',
        choices: ['Component issue to a production order', 'Creating a delivery', 'Issuing stock', 'Creating a purchase order'],
        correctIndex: 3,
        explanation: 'Batch determination decides which batch to use or ship. No batch exists yet when a purchase order is created.',
      },
      {
        type: 'ox',
        question: 'For a batch-managed material, stock cannot be received unless a batch number is entered or assigned automatically.',
        correct: true,
        explanation: 'Correct. Stock of a batch-managed material always belongs to a batch, so one must be specified at receipt.',
      },
    ],
    'work-center': [
      {
        type: 'four-choice',
        question: 'Which of these is not one of a work centre’s roles?',
        choices: ['Scheduling', 'Capacity planning', 'Costing', 'Setting sales prices'],
        correctIndex: 3,
        explanation: 'A work centre supports scheduling, capacity planning and costing. Sales prices come from SD pricing.',
      },
      {
        type: 'four-choice',
        question: 'What does the standard value key on a work centre do?',
        choices: ['Defines which standard values, such as setup and processing time, operations can carry', 'Sets the work centre number range', 'Assigns the work centre to a company code', 'Sets the factory calendar'],
        correctIndex: 0,
        explanation: 'The standard value key determines which standard values can be entered on routing operations for that work centre.',
      },
      {
        type: 'ox',
        question: 'Grouping work centres into a hierarchy lets capacity be aggregated and evaluated at higher levels.',
        correct: true,
        explanation: 'Correct. Load can be reviewed by plant or line, not just by individual machine.',
      },
      {
        type: 'four-choice',
        question: 'What are the formulas on a work centre used for?',
        choices: ['Calculating duration, capacity requirements and cost from standard values and quantity', 'Calculating customer prices', 'Calculating depreciation', 'Calculating exchange differences'],
        correctIndex: 0,
        explanation: 'Formulas turn operation standard values and order quantity into scheduling durations, capacity requirements and activity quantities for costing.',
      },
    ],
    'demand-management': [
      {
        type: 'four-choice',
        question: 'Which statement describes planning strategy 40 (planning with final assembly) correctly?',
        choices: [
          'Production proceeds against planned independent requirements, and sales orders consume them',
          'Nothing is produced until a sales order arrives',
          'Forecast and sales orders are both produced separately',
          'Replenishment uses reorder points without a forecast',
        ],
        correctIndex: 0,
        explanation: 'Under strategy 40, production runs to forecast and incoming orders consume the planned independent requirements, allowing quick response to demand.',
      },
      {
        type: 'four-choice',
        question: 'What happens with backward consumption?',
        choices: ['Planned independent requirements dated before the order’s requirement date are consumed', 'Those dated after it are consumed', 'No planned independent requirements are consumed', 'All of them are consumed at once'],
        correctIndex: 0,
        explanation: 'Backward consumption searches back from the order’s requirement date. Forward consumption searches ahead.',
      },
      {
        type: 'ox',
        question: 'If the consumption period is too short, a small date difference can stop consumption and requirements end up counted twice.',
        correct: true,
        explanation: 'Correct. Orders and forecast sitting side by side in MD04 are a sign to check the consumption period.',
      },
      {
        type: 'four-choice',
        question: 'Where is the planning strategy for a material set?',
        choices: ['The strategy group on the material master', 'The customer master', 'The work centre', 'The purchasing info record'],
        correctIndex: 0,
        explanation: 'The strategy group is set in the MRP view of the material master, and planning strategies are assigned to it.',
      },
    ],
    'production-order-lifecycle': [
      {
        type: 'four-choice',
        question: 'Which function checks whether enough components are available when a production order is created or released?',
        choices: ['Availability check', 'Credit check', 'Variance calculation', 'WIP calculation'],
        correctIndex: 0,
        explanation: 'The availability check. Releasing an order with missing components is a common reason work stops on the shop floor.',
      },
      {
        type: 'four-choice',
        question: 'What cannot yet be done on a production order that is created but not released (CRTD)?',
        choices: ['Confirmations and component issues', 'Changing the order', 'Running an availability check', 'Scheduling'],
        correctIndex: 0,
        explanation: 'CRTD means execution is not yet authorised. Confirmations and goods issues become possible after release (REL).',
      },
      {
        type: 'ox',
        question: 'Depending on configuration, an order can still be released even if the availability check finds missing components.',
        correct: true,
        explanation: 'Correct. Configuration decides whether a shortage blocks release or only issues a warning.',
      },
      {
        type: 'ox',
        question: 'Production orders are physically removed from the database by archiving after a deletion flag is set.',
        correct: true,
        explanation: 'Correct. A deletion flag alone does not remove the order; it is physically deleted only through archiving.',
      },
    ],
    'pp-period-end': [
      {
        type: 'four-choice',
        question: 'Which transaction calculates work in process for many production orders at once?',
        choices: ['KKAO', 'KKS1', 'CO88', 'CO11N'],
        correctIndex: 0,
        explanation: 'KKAO is collective WIP calculation. KKS1 is collective variance calculation, CO88 collective settlement and CO11N confirmation entry.',
      },
      {
        type: 'ox',
        question: 'WIP is cancelled in the period an order is delivered or technically completed, after which the order is included in variance calculation.',
        correct: true,
        explanation: 'Correct. While incomplete, costs are capitalised as WIP; on completion WIP is cancelled and the difference between actual and target cost is calculated as variance.',
      },
      {
        type: 'four-choice',
        question: 'At period end, which of these is most important to check as stale data?',
        choices: ['Production orders finished long ago but never technically completed', 'Work centres created this month', 'BOMs within their validity period', 'Approved purchase orders'],
        correctIndex: 0,
        explanation: 'Finished orders never set to TECO keep being carried as WIP and get no variance calculation, so they should be found and cleaned up.',
      },
      {
        type: 'ox',
        question: 'A product at standard price is received at standard cost regardless of the order’s actual cost, and the difference is handled as a variance.',
        correct: true,
        explanation: 'Correct. Finished stock is valued at standard, and the difference from actual cost collected on the order is dealt with through variance calculation and settlement.',
      },
    ],
  },
};
