import type { ModuleContent } from '../learning-types';

export const pp: Record<'ja' | 'en', ModuleContent> = {
  ja: {
    id: 'pp',
    title: 'PP（生産管理）',
    description: '生産計画から製造確認までの生産管理プロセスを学習します。',
    sections: [
      {
        id: 'pp-overview',
        title: 'PPモジュール概要',
        content: [
          'PP（Production Planning）は生産計画・製造指図・実績管理を担うモジュールです。',
          '主要プロセスは需要計画→MRP実行→計画指図→製造指図→製造確認→原価計算の流れです。',
          'PPはMM（部品調達）・CO（実績原価）・SD（需要引き）・PM（設備保全）と連携します。',
          '生産タイプとして個別生産（MTO）・見込生産（MTS）・繰り返し製造がサポートされます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'PPの主要プロセスで「MRP実行」の後に続く工程はどれですか？',
            choices: ['製造確認', '需要計画', '計画指図（Planned Order）の生成', '原価計算'],
            correctIndex: 2,
            explanation: 'MRP実行後に計画指図（Planned Order）が生成され、その後製造指図に変換されます。',
          },
          {
            type: 'ox',
            question: 'PPモジュールはMMの部品調達と連携する。',
            correct: true,
            explanation: 'PPのMRP実行により購買依頼が生成され、MMの購買プロセスに引き継がれます。',
          },
          {
            type: 'four-choice',
            question: '見込生産（MTS：Make to Stock）の説明として正しいものはどれですか？',
            choices: [
              '受注後に製造を開始する',
              '在庫補充を目的として事前に製造する',
              '顧客ごとにカスタマイズした製品を製造する',
              '外注先に製造を委託する',
            ],
            correctIndex: 1,
            explanation: 'MTSは需要予測に基づき事前に製造し在庫を確保する方式です。',
          },
          {
            type: 'ox',
            question: 'PPモジュールはCO（管理会計）と連携して製造原価を計算する。',
            correct: true,
            explanation: '製造指図の実績原価はCOの内部指図・製品原価計算と連携して計算されます。',
          },
          {
            type: 'four-choice',
            question: '個別生産（MTO：Make to Order）の特徴はどれですか？',
            choices: [
              '在庫から出荷する',
              '需要予測で生産計画を立てる',
              '受注を受けてから製造を開始し、特定受注に紐付ける',
              '繰り返し製造ラインで連続生産する',
            ],
            correctIndex: 2,
            explanation: 'MTOは受注紐付き製造で、製造コストが特定の受注明細に集計されます。',
          },
          {
            type: 'ordering',
            question: 'PPの基本プロセスを正しい順序に並べてください。',
            items: ['製造確認（CO11N）', 'MRP実行（MD01）', '製造指図作成（CO01）', '需要計画（MD61）', '製品原価計算'],
            correctOrder: [3, 1, 2, 0, 4],
            explanation: '需要計画→MRP実行→製造指図作成→製造確認→製品原価計算の順です。',
          },
        ],
      },
      {
        id: 'bom-routing',
        title: '部品表・作業手順',
        content: [
          '部品表（BOM）はCS01で作成し、製品を構成する部品・材料と数量を定義します。',
          '作業手順（Routing）はCA01で作成し、製造工程・作業場所・標準時間を定義します。',
          'BOMと作業手順はMRPや製造指図で参照され、所要量計算・リードタイム計算に使用されます。',
          'BOMタイプには製造BOM・販売BOM・プロジェクトBOM等があります。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '部品表（BOM）の作成トランザクションはどれですか？',
            choices: ['CA01', 'CS01', 'CR01', 'CO01'],
            correctIndex: 1,
            explanation: 'CS01がBOM（Bill of Materials）の作成トランザクションです。CA01は作業手順（Routing）です。',
          },
          {
            type: 'ox',
            question: '作業手順（Routing）には各工程の標準時間が含まれる。',
            correct: true,
            explanation: 'Routingには各工程のセットアップ時間・加工時間・リードタイム等が定義されます。',
          },
          {
            type: 'four-choice',
            question: 'BOMで部品の「有効期限」を設定する目的はどれですか？',
            choices: [
              '部品の在庫管理期間を決める',
              '旧部品から新部品への切り替え（エンジニアリング変更）を管理する',
              '部品の評価期間を設定する',
              '部品の発注タイミングを制御する',
            ],
            correctIndex: 1,
            explanation: 'BOMの有効期限によりエンジニアリング変更（設計変更）を日付管理します。',
          },
          {
            type: 'ox',
            question: 'BOMは多段階構成（Multi-level BOM）をサポートする。',
            correct: true,
            explanation: '多段階BOMにより半製品→部品→原材料の階層構造を定義できます。',
          },
          {
            type: 'four-choice',
            question: '作業手順（Routing）の作成トランザクションはどれですか？',
            choices: ['CS01', 'CA01', 'CR01', 'KP06'],
            correctIndex: 1,
            explanation: 'CA01がRouting（作業手順）の作成トランザクションです。CR01は作業場所の作成です。',
          },
          {
            type: 'ordering',
            question: 'PPマスタデータの作成順序として正しいものを並べてください。',
            items: ['製造指図で参照', '作業手順（CA01）', '品目マスタ（MM01）', 'BOM（CS01）', '作業場所（CR01）'],
            correctOrder: [2, 4, 3, 1, 0],
            explanation: '品目マスタ→作業場所→BOM→作業手順→製造指図で参照の順です。',
          },
        ],
      },
      {
        id: 'mrp-production-order',
        title: 'MRP・製造指図',
        content: [
          'MRP（Material Requirements Planning）はMD01/MD02で実行し、需要に対する部品所要量と生産量を計算します。',
          'MRP実行後に計画指図（Planned Order）が生成され、MD04（在庫/所要量リスト）で確認できます。',
          '計画指図はCO41で製造指図（Production Order）に変換され、材料引き当て・能力確認が行われます。',
          '製造指図の作成はCO01で手動作成することも可能です。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'MRPのシングル品目実行トランザクションはどれですか？',
            choices: ['MD01', 'MD02', 'MD04', 'MD61'],
            correctIndex: 1,
            explanation: 'MD02はシングル品目（単一品目）MRPの実行、MD01は全品目のバッチ実行です。',
          },
          {
            type: 'ox',
            question: 'MRP実行後に生成される計画指図はMD04で確認できる。',
            correct: true,
            explanation: 'MD04（Stock/Requirements List）でMRP結果（計画指図・購買依頼等）を確認できます。',
          },
          {
            type: 'four-choice',
            question: '計画指図を製造指図に変換するトランザクションはどれですか？',
            choices: ['CO01', 'CO41', 'MD02', 'CO11N'],
            correctIndex: 1,
            explanation: 'CO41（Convert Planned Order）で計画指図を製造指図に変換します。',
          },
          {
            type: 'ox',
            question: '製造指図はCO01でも手動作成できる。',
            correct: true,
            explanation: 'CO01で直接製造指図を手動作成することも可能です。計画指図からの変換（CO41）と両方使用されます。',
          },
          {
            type: 'four-choice',
            question: 'MRP計算の入力となる「計画独立所要量」を登録するトランザクションはどれですか？',
            choices: ['MD61', 'MD01', 'CO01', 'MD04'],
            correctIndex: 0,
            explanation: 'MD61（Planned Independent Requirements）で需要予測・販売計画を登録します。',
          },
          {
            type: 'ordering',
            question: 'MRPから製造指図までの流れを正しい順序に並べてください。',
            items: ['製造指図（CO41変換）', 'MRP実行（MD01/MD02）', '計画指図生成', 'MD04で確認', '需要入力（MD61）'],
            correctOrder: [4, 1, 2, 3, 0],
            explanation: '需要入力→MRP実行→計画指図生成→MD04で確認→製造指図変換の順です。',
          },
        ],
      },
      {
        id: 'production-confirmation',
        title: '製造確認・実績原価',
        content: [
          '製造確認はCO11Nで行い、製造指図に対する実際の作業時間・生産数量を報告します。',
          '製造確認により材料実消費量・活動実績が製造指図に集計され、実績原価が計算されます。',
          '入庫確認はMIGOまたはCO11N（同時入庫オプション）で行い、製品の在庫計上を行います。',
          '製造指図の完了確認（TECO）後に差異分析・原価精算（CO88）が実行されます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '製造確認のトランザクションはどれですか？',
            choices: ['CO01', 'CO11N', 'MIGO', 'CO88'],
            correctIndex: 1,
            explanation: 'CO11NがProduction Order Confirmationの標準トランザクションです。',
          },
          {
            type: 'ox',
            question: '製造確認（CO11N）では実際の作業時間と生産数量を報告する。',
            correct: true,
            explanation: 'CO11Nで実績の作業時間・数量を入力することで実績原価が計算されます。',
          },
          {
            type: 'four-choice',
            question: '製造指図の精算（Settlement）に使用するトランザクションはどれですか？',
            choices: ['CO11N', 'CO88', 'KKS2', 'KKAO'],
            correctIndex: 1,
            explanation: 'CO88（Order Settlement）で製造指図の実績原価を製品や原価センタに精算します。',
          },
          {
            type: 'ox',
            question: '製造確認後に製品在庫が自動的に増加する。',
            correct: false,
            explanation: '製造確認（CO11N）は作業実績を報告します。製品入庫にはMIGOまたはCO11Nの入庫同時計上オプションが必要です。',
          },
          {
            type: 'four-choice',
            question: '製造指図の技術的完了（TECO）後の状態はどれですか？',
            choices: [
              'CRTD（作成済）',
              'REL（リリース済）',
              'TECO（技術的完了）',
              'CLSD（クローズ）',
            ],
            correctIndex: 2,
            explanation: 'TECOステータスは技術的完了を示し、その後CLSDでクローズされます。',
          },
          {
            type: 'ordering',
            question: '製造完了から原価精算までの流れを正しい順序に並べてください。',
            items: ['CO88精算', 'CO11N確認', '差異分析（KKS2）', '製品入庫（MIGO）', 'TECO（技術的完了）'],
            correctOrder: [1, 3, 4, 2, 0],
            explanation: 'CO11N確認→製品入庫→TECO→差異分析→CO88精算の順です。',
          },
        ],
      },
      {
        id: 'capacity-planning',
        title: '能力計画',
        content: [
          '能力計画は作業場所の能力（稼働時間・設備数）に対して製造指図の負荷を管理します。',
          '能力カテゴリには機械能力・人員能力・工具能力等があります。',
          '能力評価はCM01/CM04で実行し、作業場所ごとのロードとキャパシティを確認します。',
          '無限能力計画（Infinite）と有限能力計画（Finite）の2種類があります。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '能力評価の照会トランザクションはどれですか？',
            choices: ['CO01', 'CM01', 'CR01', 'CA01'],
            correctIndex: 1,
            explanation: 'CM01（Capacity Planning）で作業場所の負荷状況を確認します。',
          },
          {
            type: 'ox',
            question: '無限能力計画では作業場所のキャパシティ超過を無視して計画を立てる。',
            correct: true,
            explanation: '無限能力計画はキャパシティ制約なしでスケジューリングします。有限計画はキャパシティを考慮します。',
          },
          {
            type: 'four-choice',
            question: '能力カテゴリの例として正しくないものはどれですか？',
            choices: ['機械能力', '人員能力', '工具能力', '財務能力'],
            correctIndex: 3,
            explanation: '財務能力はPPの能力カテゴリには含まれません。機械・人員・工具が主な能力カテゴリです。',
          },
          {
            type: 'ox',
            question: '能力計画の対象は製造指図だけでなく、計画指図（Planned Order）も含まれる。',
            correct: true,
            explanation: '計画指図もCM01等の能力計画に含められ、将来の負荷予測に使用できます。',
          },
          {
            type: 'four-choice',
            question: '作業場所に設定する「能力」の基準となる情報はどれですか？',
            choices: [
              '購買条件と発注書',
              '稼働シフトと機械台数・人員数',
              '品目マスタと評価クラス',
              '製造指図の標準原価',
            ],
            correctIndex: 1,
            explanation: '作業場所の能力は稼働シフト（時間）×機械台数または人員数で定義されます。',
          },
          {
            type: 'ordering',
            question: '能力計画の実行手順を正しい順序に並べてください。',
            items: ['キャパシティ超過品の調整', '能力評価実行（CM01）', '作業場所の能力設定', '製造指図リリース', '負荷分析'],
            correctOrder: [2, 3, 1, 4, 0],
            explanation: '作業場所の能力設定→製造指図リリース→能力評価実行→負荷分析→超過品調整の順です。',
          },
        ],
      },
      {
        id: 'batch-management',
        title: 'バッチ管理',
        content: [
          'バッチ管理は同一品目でもロット（製造バッチ）単位で品質・有効期限・トレーサビリティを管理します。',
          'バッチマスタはMSC1Nで作成し、バッチ固有の属性（製造日・有効期限等）を登録します。',
          'FEFO（First Expiry First Out：先期限切れ先出し）はバッチ検索戦略の一つで、有効期限の短い順に出庫します。',
          'バッチ分類は品目分類の拡張機能で、バッチ固有の品質特性値を管理します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'バッチマスタの作成トランザクションはどれですか？',
            choices: ['MM01', 'MSC1N', 'MI01', 'CS01'],
            correctIndex: 1,
            explanation: 'MSC1NがBatch Master（バッチマスタ）の作成トランザクションです。',
          },
          {
            type: 'ox',
            question: 'FEFO（先期限切れ先出し）ではバッチの有効期限が早いものから優先して出庫される。',
            correct: true,
            explanation: 'FEFOは有効期限（Expiry Date）が近いバッチを優先的に引き当てる戦略です。',
          },
          {
            type: 'four-choice',
            question: 'バッチ管理が必須となる業界の例として最も適切なものはどれですか？',
            choices: [
              '鉄鋼業',
              '食品・医薬品業',
              'ソフトウェア業',
              '金融業',
            ],
            correctIndex: 1,
            explanation: '食品・医薬品業では有効期限・トレーサビリティ管理のためバッチ管理が必須です。',
          },
          {
            type: 'ox',
            question: 'バッチ番号は品目マスタレベルで管理され、プラント間で共有される。',
            correct: false,
            explanation: 'バッチの管理レベル（プラント・会社コード・クライアント）は設定で決まります。デフォルトはプラントレベルです。',
          },
          {
            type: 'four-choice',
            question: 'バッチ検索戦略（FEFO）を有効にするために品目マスタで設定する項目はどれですか？',
            choices: [
              '特殊調達キー',
              'バッチ管理必須フラグと棚卸管理タイプ',
              '評価クラス',
              'MRP方式',
            ],
            correctIndex: 1,
            explanation: 'バッチ管理必須フラグと棚卸管理タイプ（FEFO対応）を品目マスタで設定します。',
          },
          {
            type: 'ordering',
            question: 'バッチ管理の設定から出庫までの流れを正しい順序に並べてください。',
            items: ['FEFO順に出庫', 'バッチ作成（MSC1N）', '有効期限確認', '品目マスタでバッチ管理有効化', 'バッチ検索戦略設定'],
            correctOrder: [3, 4, 1, 2, 0],
            explanation: '品目マスタでバッチ管理有効化→バッチ検索戦略設定→バッチ作成→有効期限確認→FEFO順に出庫の順です。',
          },
        ],
      },
      {
        id: 'work-center',
        title: '作業場所マスタ（Work Center）',
        content: [
          '作業場所（Work Center）はCR01で作成し、製造拠点の機械・設備・人員を表すPPの基本マスタです。',
          '作業場所には能力（稼働時間・台数）・活動タイプ・コスト計算の基準が設定されます。',
          '活動タイプはCO（管理会計）のCO側で定義されたコストドライバーで、作業場所と紐付けられます。',
          '作業場所のコストセンタへのリンクにより製造作業コストがCOに転記されます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '作業場所（Work Center）の作成トランザクションはどれですか？',
            choices: ['CS01', 'CA01', 'CR01', 'CO01'],
            correctIndex: 2,
            explanation: 'CR01がWork Center（作業場所）の作成トランザクションです。',
          },
          {
            type: 'ox',
            question: '作業場所はCO（管理会計）の原価センタとリンクさせることができる。',
            correct: true,
            explanation: '作業場所に原価センタを割り当てることで、製造作業コストがCO原価センタに転記されます。',
          },
          {
            type: 'four-choice',
            question: '作業場所に設定する「活動タイプ」の目的はどれですか？',
            choices: [
              '在庫の評価方法を決める',
              '製造作業コストの計算基準（機械時間・人件費等）を定義する',
              '出荷条件を設定する',
              '購買組織を決定する',
            ],
            correctIndex: 1,
            explanation: '活動タイプは製造コスト計算の基準（機械時間・人件費・電力費等）を定義するCOコンセプトです。',
          },
          {
            type: 'ox',
            question: '一つの作業場所に複数の能力カテゴリ（機械・人員等）を設定できる。',
            correct: true,
            explanation: '1つの作業場所に機械能力・人員能力・工具能力等を複数設定することができます。',
          },
          {
            type: 'four-choice',
            question: '作業場所の「基本データ」に含まれる主な情報はどれですか？',
            choices: [
              'MRP計画パラメータ',
              '作業場所名・責任者・場所（プラント内位置）',
              'バッチ検索戦略',
              '評価クラスと勘定科目',
            ],
            correctIndex: 1,
            explanation: '基本データには作業場所名・カテゴリ・責任者・プラント内の物理的場所が含まれます。',
          },
          {
            type: 'ordering',
            question: '作業場所マスタの設定から製造指図での利用までの流れを並べてください。',
            items: ['製造指図で作業場所を参照', '作業場所に原価センタ割当', 'Routing（CA01）に作業場所登録', '作業場所作成（CR01）', '能力・活動タイプ設定'],
            correctOrder: [3, 4, 1, 2, 0],
            explanation: '作業場所作成→能力・活動タイプ設定→原価センタ割当→Routingに登録→製造指図で参照の順です。',
          },
        ],
      },
      {
        id: 'demand-management',
        title: '需要管理と計画独立所要量（PIR）',
        content: [
          '需要管理はMD61で計画独立所要量（PIR：Planned Independent Requirements）を登録し、MRPの需要入力とします。',
          'PIRには品目・プラント・計画数量・計画日付が含まれ、見込生産（MTS）計画の基礎となります。',
          'MRP方式（MRP Type）はPD（MRP）・VB（再発注点）・ND（計画なし）等から選択します。',
          '受注依存所要量（Customer Independent Requirements）はSDの受注からMRPに直接取り込まれます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '計画独立所要量（PIR）を登録するトランザクションはどれですか？',
            choices: ['MD01', 'MD61', 'MD04', 'CO01'],
            correctIndex: 1,
            explanation: 'MD61（Maintain Planned Independent Requirements）でPIRを登録します。',
          },
          {
            type: 'ox',
            question: 'PIR（計画独立所要量）は見込生産（MTS）の需要入力として使用される。',
            correct: true,
            explanation: 'MTSではPIRをMRPの需要源として使用し、在庫補充計画を立てます。',
          },
          {
            type: 'four-choice',
            question: 'MRP方式「PD」の説明として正しいものはどれですか？',
            choices: [
              '再発注点方式で在庫が基準量を下回ったとき計画を立てる',
              'MRP方式でBOM展開・所要量計算を行う標準的な方式',
              '計画を実行しない',
              'カンバン方式で自動補充する',
            ],
            correctIndex: 1,
            explanation: 'PD（MRP）はBOM展開と正味所要量計算を行う標準的なMRP方式です。',
          },
          {
            type: 'ox',
            question: '個別生産（MTO）ではPIRではなく受注（Sales Order）がMRPの需要源となる。',
            correct: true,
            explanation: 'MTO方式では受注明細が需要源となり、特定受注に紐付いた製造指図が生成されます。',
          },
          {
            type: 'four-choice',
            question: '需要管理でPIRを登録する際に必要な情報として正しくないものはどれですか？',
            choices: ['品目番号', '計画数量', '計画日付（期）', '仕入先番号'],
            correctIndex: 3,
            explanation: 'PIRは社内計画情報のため仕入先番号は不要です。品目・数量・日付・プラントが必要です。',
          },
          {
            type: 'ordering',
            question: '需要管理からMRP実行までの流れを正しい順序に並べてください。',
            items: ['MRP実行（MD01）', '販売計画の収集', 'MD04で結果確認', 'PIR登録（MD61）', '計画指図生成'],
            correctOrder: [1, 3, 0, 4, 2],
            explanation: '販売計画の収集→PIR登録→MRP実行→計画指図生成→MD04で結果確認の順です。',
          },
        ],
      },
      {
        id: 'production-order-lifecycle',
        title: '製造指図のライフサイクル',
        content: [
          '製造指図はCRTD（作成済）→REL（リリース済）→PCNF（部分確認済）→CNF（完全確認済）→TECO（技術的完了）→CLSD（クローズ）のステータスで進みます。',
          'リリース（REL）により材料出庫・能力確認が有効化され、製造作業が開始できます。',
          'CO02で製造指図を変更し、数量・日付・コンポーネントを修正できます。',
          'TECO後は入庫・出庫等の在庫動作は行えなくなりますが、精算（CO88）は可能です。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '製造指図のリリース（REL）操作の効果として正しいものはどれですか？',
            choices: [
              '製造指図が自動精算される',
              '材料出庫や能力確認が有効化され製造作業が開始できる',
              '製造指図がアーカイブされる',
              '製造指図の変更がロックされる',
            ],
            correctIndex: 1,
            explanation: 'RELステータスにより材料出庫・確認処理が可能となり、製造現場で作業を開始できます。',
          },
          {
            type: 'ox',
            question: '製造指図の変更はCO02で行う。',
            correct: true,
            explanation: 'CO02で製造指図の数量・日付・コンポーネント等を変更できます。CO01は作成、CO03は照会です。',
          },
          {
            type: 'four-choice',
            question: 'TECO（技術的完了）後に実行できる操作はどれですか？',
            choices: [
              'MIGO入庫',
              '製造確認（CO11N）',
              'CO88による精算',
              '材料出庫',
            ],
            correctIndex: 2,
            explanation: 'TECO後は在庫操作・確認はできませんが、CO88による原価精算は可能です。',
          },
          {
            type: 'ox',
            question: 'CLSD（クローズ）ステータスになると製造指図は変更も精算もできなくなる。',
            correct: true,
            explanation: 'CLSDは最終ステータスであり、それ以降の変更・精算は一切できません。',
          },
          {
            type: 'four-choice',
            question: '製造指図の初期ステータス（作成直後）はどれですか？',
            choices: ['REL', 'CRTD', 'TECO', 'CLSD'],
            correctIndex: 1,
            explanation: 'CRTD（Created）が製造指図作成直後の初期ステータスです。',
          },
          {
            type: 'ordering',
            question: '製造指図のライフサイクルを正しい順序に並べてください。',
            items: ['TECO（技術的完了）', 'REL（リリース）', 'CLSD（クローズ）', 'CRTD（作成済）', 'CNF（確認済）'],
            correctOrder: [3, 1, 4, 0, 2],
            explanation: 'CRTD→REL→CNF→TECO→CLSDの順です。',
          },
        ],
      },
      {
        id: 'pp-period-end',
        title: 'PP期末処理',
        content: [
          'PP期末処理では製造指図の差異計算（KKS2/KKAO）・仕掛品（WIP）計算・精算（CO88）を行います。',
          'KKAOは製造指図の実績原価・標準原価の差異を一括計算するトランザクションです。',
          'WIP（仕掛品）は月末時点で完了していない製造指図のコストを資産として計上する処理です。',
          'PP期末処理の完了後にCO月次処理（精算・差異分析）と連携してFIへ転記されます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '製造指図の差異計算に使用するトランザクションはどれですか？',
            choices: ['CO88', 'KKAO', 'CO11N', 'MD01'],
            correctIndex: 1,
            explanation: 'KKAOで製造指図の実績vs標準の差異を一括計算します。個別はKKS2です。',
          },
          {
            type: 'ox',
            question: 'WIP（仕掛品）計算は月末時点で未完了の製造指図のコストを資産計上する。',
            correct: true,
            explanation: 'WIP計算により未完了製造指図の投入コストを仕掛品（資産）として貸借対照表に計上します。',
          },
          {
            type: 'four-choice',
            question: '製造指図の精算（Settlement）で原価が最終的に振り替えられる先はどれですか？',
            choices: [
              '購買組織',
              '品目（製品在庫）または原価センタ',
              '販売エリア',
              '利益センタ',
            ],
            correctIndex: 1,
            explanation: 'CO88精算では製造指図の実績原価が製品在庫勘定（MTS）または原価センタ（MTO）に振り替えられます。',
          },
          {
            type: 'ox',
            question: 'PP期末処理の順序は差異計算→WIP計算→精算（CO88）が正しい。',
            correct: false,
            explanation: '正しい順序はWIP計算→差異計算→精算（CO88）です。WIPを先に確定してから差異を計算します。',
          },
          {
            type: 'four-choice',
            question: 'CO88（製造指図精算）を実行するタイミングとして正しいものはどれですか？',
            choices: [
              '製造指図リリース直後',
              '製造確認（CO11N）と同時',
              'TECO後、月次処理の中で',
              '購買発注後',
            ],
            correctIndex: 2,
            explanation: 'CO88はTECO後、月次の期末処理の中でWIP計算・差異計算と合わせて実行します。',
          },
          {
            type: 'ordering',
            question: 'PP期末処理の主要手順を正しい順序に並べてください。',
            items: ['CO88精算', '差異計算（KKAO）', 'FIへの転記確認', 'TECO（技術的完了）', 'WIP計算'],
            correctOrder: [3, 4, 1, 0, 2],
            explanation: 'TECO→WIP計算→差異計算→CO88精算→FIへの転記確認の順です。',
          },
        ],
      },
    ],
  },
  en: {
    id: 'pp',
    title: 'PP (Production Planning)',
    description: 'Learn the production management process from planning to confirmation.',
    sections: [
      {
        id: 'pp-overview',
        title: 'PP Module Overview',
        content: [
          'PP (Production Planning) handles production planning, production orders, and actual cost management.',
          'The core process flows: Demand Planning → MRP Run → Planned Orders → Production Orders → Confirmation → Costing.',
          'PP integrates with MM (component procurement), CO (actual costs), SD (demand pull), and PM (equipment maintenance).',
          'Supported production types include Make-to-Order (MTO), Make-to-Stock (MTS), and Repetitive Manufacturing.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which step follows the MRP Run in the PP process?',
            choices: ['Production Confirmation', 'Demand Planning', 'Planned Order Generation', 'Cost Calculation'],
            correctIndex: 2,
            explanation: 'After the MRP Run, Planned Orders are generated, which are then converted to Production Orders.',
          },
          {
            type: 'ox',
            question: 'The PP module integrates with MM for component procurement.',
            correct: true,
            explanation: 'MRP execution in PP generates Purchase Requisitions that feed into the MM purchasing process.',
          },
          {
            type: 'four-choice',
            question: 'Which best describes Make-to-Stock (MTS) production?',
            choices: [
              'Manufacturing starts after receiving a customer order',
              'Manufacturing in advance to replenish inventory based on demand forecasts',
              'Custom products manufactured for individual customers',
              'Manufacturing outsourced to a subcontractor',
            ],
            correctIndex: 1,
            explanation: 'MTS produces inventory in advance based on demand forecasts.',
          },
          {
            type: 'ox',
            question: 'PP integrates with CO (Controlling) to calculate manufacturing costs.',
            correct: true,
            explanation: 'Production order actual costs are calculated in conjunction with CO internal orders and product costing.',
          },
          {
            type: 'four-choice',
            question: 'Which best describes Make-to-Order (MTO) production?',
            choices: [
              'Ships from stock inventory',
              'Plans production based on demand forecasts',
              'Starts manufacturing after receiving an order, tied to a specific sales order',
              'Continuous production on a repetitive manufacturing line',
            ],
            correctIndex: 2,
            explanation: 'MTO is order-specific manufacturing where costs are collected against a specific sales order.',
          },
          {
            type: 'ordering',
            question: 'Arrange the PP core process steps in the correct order.',
            items: ['Production Confirmation (CO11N)', 'MRP Run (MD01)', 'Production Order Creation (CO01)', 'Demand Planning (MD61)', 'Product Costing'],
            correctOrder: [3, 1, 2, 0, 4],
            explanation: 'Demand Planning → MRP Run → Production Order → Confirmation → Costing.',
          },
        ],
      },
      {
        id: 'bom-routing',
        title: 'Bill of Materials and Routing',
        content: [
          'The Bill of Materials (BOM) is created with CS01 and defines the components and quantities that make up a product.',
          'The Routing is created with CA01 and defines the production operations, work centers, and standard times.',
          'BOMs and Routings are referenced by MRP and production orders for requirements calculation and lead time scheduling.',
          'BOM types include Manufacturing BOM, Sales BOM, and Project BOM.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction creates a Bill of Materials (BOM)?',
            choices: ['CA01', 'CS01', 'CR01', 'CO01'],
            correctIndex: 1,
            explanation: 'CS01 creates the Bill of Materials. CA01 creates the Routing.',
          },
          {
            type: 'ox',
            question: 'A Routing includes the standard time for each operation.',
            correct: true,
            explanation: 'The Routing defines setup time, machine time, and lead time for each production operation.',
          },
          {
            type: 'four-choice',
            question: 'What is the purpose of setting a "Validity Period" on a BOM component?',
            choices: [
              'To set the inventory retention period',
              'To manage engineering changes (switching from old to new component by date)',
              'To set the component valuation period',
              'To control the reorder timing',
            ],
            correctIndex: 1,
            explanation: 'BOM validity dates manage engineering changes so the correct component is used from a specific date.',
          },
          {
            type: 'ox',
            question: 'BOMs support multi-level structures (semi-finished → components → raw materials).',
            correct: true,
            explanation: 'Multi-level BOMs define the full hierarchical structure from finished product down to raw materials.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction creates a Routing?',
            choices: ['CS01', 'CA01', 'CR01', 'KP06'],
            correctIndex: 1,
            explanation: 'CA01 creates the Routing. CR01 creates the Work Center.',
          },
          {
            type: 'ordering',
            question: 'Arrange the PP master data creation sequence in the correct order.',
            items: ['Referenced by Production Order', 'Routing (CA01)', 'Material Master (MM01)', 'BOM (CS01)', 'Work Center (CR01)'],
            correctOrder: [2, 4, 3, 1, 0],
            explanation: 'Material Master → Work Center → BOM → Routing → Referenced by Production Order.',
          },
        ],
      },
      {
        id: 'mrp-production-order',
        title: 'MRP and Production Orders',
        content: [
          'MRP (Material Requirements Planning) is run with MD01/MD02 to calculate component requirements and production quantities.',
          'After the MRP run, Planned Orders are generated and can be reviewed in MD04 (Stock/Requirements List).',
          'Planned Orders are converted to Production Orders using CO41, triggering material reservation and capacity checks.',
          'Production Orders can also be created manually with CO01.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction runs MRP for a single material?',
            choices: ['MD01', 'MD02', 'MD04', 'MD61'],
            correctIndex: 1,
            explanation: 'MD02 runs MRP for a single material. MD01 runs MRP for all materials in batch.',
          },
          {
            type: 'ox',
            question: 'Planned Orders generated by MRP can be reviewed in MD04.',
            correct: true,
            explanation: 'MD04 (Stock/Requirements List) shows MRP results including planned orders and purchase requisitions.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction converts Planned Orders into Production Orders?',
            choices: ['CO01', 'CO41', 'MD02', 'CO11N'],
            correctIndex: 1,
            explanation: 'CO41 (Convert Planned Order) converts planned orders into production orders.',
          },
          {
            type: 'ox',
            question: 'Production Orders can also be created manually with CO01.',
            correct: true,
            explanation: 'CO01 allows direct manual creation of production orders alongside the CO41 conversion route.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction maintains Planned Independent Requirements (PIR) as MRP input?',
            choices: ['MD61', 'MD01', 'CO01', 'MD04'],
            correctIndex: 0,
            explanation: 'MD61 (Planned Independent Requirements) is used to enter demand forecasts and sales plans.',
          },
          {
            type: 'ordering',
            question: 'Arrange the steps from MRP to Production Order in the correct order.',
            items: ['Production Order (CO41 conversion)', 'MRP Run (MD01/MD02)', 'Planned Order Generated', 'Review in MD04', 'Enter Demand (MD61)'],
            correctOrder: [4, 1, 2, 3, 0],
            explanation: 'Enter Demand → MRP Run → Planned Order Generated → Review in MD04 → Convert to Production Order.',
          },
        ],
      },
      {
        id: 'production-confirmation',
        title: 'Production Confirmation and Actual Costs',
        content: [
          'Production confirmations are entered with CO11N to report actual work time and production quantities against a production order.',
          'Confirmations collect actual material consumption and activity quantities on the production order for actual cost calculation.',
          'Goods receipt for finished products is done via MIGO or the simultaneous GR option in CO11N.',
          'After TECO (Technically Complete), variance analysis and settlement (CO88) are executed.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction is used for Production Order Confirmation?',
            choices: ['CO01', 'CO11N', 'MIGO', 'CO88'],
            correctIndex: 1,
            explanation: 'CO11N is the standard transaction for Production Order Confirmation.',
          },
          {
            type: 'ox',
            question: 'CO11N is used to report actual work time and production quantities.',
            correct: true,
            explanation: 'Entering actual times and quantities in CO11N drives actual cost calculation on the production order.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction is used for Production Order Settlement?',
            choices: ['CO11N', 'CO88', 'KKS2', 'KKAO'],
            correctIndex: 1,
            explanation: 'CO88 (Order Settlement) settles actual costs from the production order to finished goods or cost centers.',
          },
          {
            type: 'ox',
            question: 'Finished product stock automatically increases when a production confirmation is entered.',
            correct: false,
            explanation: 'CO11N reports work progress only. A separate GR posting via MIGO (or CO11N simultaneous GR) is needed to increase finished goods stock.',
          },
          {
            type: 'four-choice',
            question: 'What status does a production order have after TECO?',
            choices: ['CRTD (Created)', 'REL (Released)', 'TECO (Technically Complete)', 'CLSD (Closed)'],
            correctIndex: 2,
            explanation: 'TECO (Technically Complete) indicates the order is operationally finished; CLSD follows after settlement.',
          },
          {
            type: 'ordering',
            question: 'Arrange the steps from manufacturing completion to cost settlement in the correct order.',
            items: ['CO88 Settlement', 'CO11N Confirmation', 'Variance Analysis (KKS2)', 'Finished Goods GR (MIGO)', 'TECO (Technically Complete)'],
            correctOrder: [1, 3, 4, 2, 0],
            explanation: 'CO11N Confirmation → Finished GR → TECO → Variance Analysis → CO88 Settlement.',
          },
        ],
      },
      {
        id: 'capacity-planning',
        title: 'Capacity Planning',
        content: [
          'Capacity Planning manages the load on work centers (available hours, number of machines) against production order requirements.',
          'Capacity categories include machine capacity, labor capacity, and tool capacity.',
          'Capacity evaluation is performed with CM01/CM04 to review load vs. available capacity per work center.',
          'Two planning modes are available: Infinite Capacity Planning and Finite Capacity Planning.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction is used for Capacity Evaluation (planning overview)?',
            choices: ['CO01', 'CM01', 'CR01', 'CA01'],
            correctIndex: 1,
            explanation: 'CM01 (Capacity Planning) displays work center load and available capacity.',
          },
          {
            type: 'ox',
            question: 'Infinite Capacity Planning ignores capacity overloads when scheduling.',
            correct: true,
            explanation: 'Infinite planning schedules without capacity constraints. Finite planning respects capacity limits.',
          },
          {
            type: 'four-choice',
            question: 'Which is NOT a standard capacity category in PP?',
            choices: ['Machine Capacity', 'Labor Capacity', 'Tool Capacity', 'Financial Capacity'],
            correctIndex: 3,
            explanation: 'Financial Capacity is not a PP capacity category. Machine, Labor, and Tool are standard categories.',
          },
          {
            type: 'ox',
            question: 'Capacity planning includes Planned Orders in addition to Production Orders.',
            correct: true,
            explanation: 'Planned Orders can also be included in CM01 capacity planning for future load forecasting.',
          },
          {
            type: 'four-choice',
            question: 'What is the basis for defining work center capacity?',
            choices: [
              'Purchasing conditions and purchase orders',
              'Operating shifts and number of machines or personnel',
              'Material master and valuation class',
              'Standard cost of the production order',
            ],
            correctIndex: 1,
            explanation: 'Work center capacity is defined by operating shifts (hours) multiplied by number of machines or personnel.',
          },
          {
            type: 'ordering',
            question: 'Arrange the capacity planning steps in the correct order.',
            items: ['Adjust overloaded items', 'Run Capacity Evaluation (CM01)', 'Configure work center capacity', 'Release Production Order', 'Analyze load'],
            correctOrder: [2, 3, 1, 4, 0],
            explanation: 'Configure Work Center Capacity → Release PO → Run Capacity Evaluation → Analyze Load → Adjust Overloads.',
          },
        ],
      },
      {
        id: 'batch-management',
        title: 'Batch Management',
        content: [
          'Batch Management tracks quality, expiry dates, and traceability at the batch (lot) level for the same material.',
          'Batch Master records are created with MSC1N to store batch-specific attributes (production date, expiry date, etc.).',
          'FEFO (First Expiry First Out) is a batch search strategy that prioritizes batches with the earliest expiry date.',
          'Batch Classification extends the classification system to manage batch-specific quality characteristic values.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction is used to create a Batch Master record?',
            choices: ['MM01', 'MSC1N', 'MI01', 'CS01'],
            correctIndex: 1,
            explanation: 'MSC1N creates Batch Master records.',
          },
          {
            type: 'ox',
            question: 'FEFO (First Expiry First Out) prioritizes batches with the earliest expiry date for issue.',
            correct: true,
            explanation: 'FEFO is a search strategy that ensures the batch closest to expiry is issued first.',
          },
          {
            type: 'four-choice',
            question: 'Which industry most typically requires batch management?',
            choices: ['Steel industry', 'Food and pharmaceutical industry', 'Software industry', 'Financial services'],
            correctIndex: 1,
            explanation: 'Food and pharmaceutical industries require batch management for expiry date tracking and regulatory traceability.',
          },
          {
            type: 'ox',
            question: 'Batch numbers are managed at the Material Master level and shared across plants.',
            correct: false,
            explanation: 'The batch management level (plant, company code, or client) is configurable. The default is plant level.',
          },
          {
            type: 'four-choice',
            question: 'What must be configured in the Material Master to enable FEFO batch search strategy?',
            choices: [
              'Special Procurement Key',
              'Batch Management Required flag and Shelf Life Expiration Date settings',
              'Valuation Class',
              'MRP Type',
            ],
            correctIndex: 1,
            explanation: 'The Batch Management Required flag and SLED (Shelf Life Expiration Date) settings must be enabled in the Material Master.',
          },
          {
            type: 'ordering',
            question: 'Arrange the batch management flow from setup to goods issue in the correct order.',
            items: ['Issue in FEFO order', 'Create Batch (MSC1N)', 'Check Expiry Date', 'Enable Batch Management in Material Master', 'Configure Batch Search Strategy'],
            correctOrder: [3, 4, 1, 2, 0],
            explanation: 'Enable Batch Management → Configure Search Strategy → Create Batch → Check Expiry → Issue in FEFO Order.',
          },
        ],
      },
      {
        id: 'work-center',
        title: 'Work Center Master Data',
        content: [
          'Work Centers are created with CR01 and represent machines, equipment, or personnel in the production facility.',
          'A Work Center stores capacity (shift hours, quantity), activity types, and costing parameters.',
          'Activity Types are CO-side cost drivers linked to work centers for manufacturing cost allocation.',
          'Linking a Work Center to a Cost Center allows manufacturing activity costs to post to CO.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction creates a Work Center?',
            choices: ['CS01', 'CA01', 'CR01', 'CO01'],
            correctIndex: 2,
            explanation: 'CR01 creates Work Centers.',
          },
          {
            type: 'ox',
            question: 'A Work Center can be linked to a CO Cost Center.',
            correct: true,
            explanation: 'Assigning a Cost Center to a Work Center enables manufacturing activity costs to post to CO.',
          },
          {
            type: 'four-choice',
            question: 'What is the purpose of "Activity Types" assigned to a Work Center?',
            choices: [
              'To determine inventory valuation method',
              'To define the basis (machine hours, labor cost, etc.) for manufacturing cost calculation',
              'To set shipping conditions',
              'To determine the purchasing organization',
            ],
            correctIndex: 1,
            explanation: 'Activity Types are CO concepts that define the cost calculation basis (machine hours, labor, power, etc.) for a work center.',
          },
          {
            type: 'ox',
            question: 'Multiple capacity categories (machine, labor, etc.) can be assigned to a single Work Center.',
            correct: true,
            explanation: 'A single work center can have machine capacity, labor capacity, and tool capacity configured simultaneously.',
          },
          {
            type: 'four-choice',
            question: 'Which information is typically found in the Work Center Basic Data?',
            choices: [
              'MRP planning parameters',
              'Work center name, responsible person, and physical location within the plant',
              'Batch search strategy',
              'Valuation class and GL account',
            ],
            correctIndex: 1,
            explanation: 'Basic Data contains the work center name, category, responsible person, and physical location.',
          },
          {
            type: 'ordering',
            question: 'Arrange the Work Center setup to production order usage flow in the correct order.',
            items: ['Production Order references Work Center', 'Assign Cost Center to Work Center', 'Add Work Center to Routing (CA01)', 'Create Work Center (CR01)', 'Set Capacity and Activity Types'],
            correctOrder: [3, 4, 1, 2, 0],
            explanation: 'Create Work Center → Set Capacity & Activity Types → Assign Cost Center → Add to Routing → Production Order References.',
          },
        ],
      },
      {
        id: 'demand-management',
        title: 'Demand Management and Planned Independent Requirements (PIR)',
        content: [
          'Demand Management uses MD61 to enter Planned Independent Requirements (PIR) as the demand input for MRP.',
          'PIR contains material, plant, planned quantity, and planning date, forming the basis for MTS production plans.',
          'MRP Types include PD (MRP), VB (Reorder Point), and ND (No Planning).',
          'Customer Independent Requirements from SD sales orders are directly consumed in MRP for MTO production.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction is used to enter Planned Independent Requirements (PIR)?',
            choices: ['MD01', 'MD61', 'MD04', 'CO01'],
            correctIndex: 1,
            explanation: 'MD61 (Maintain Planned Independent Requirements) is used to enter PIRs.',
          },
          {
            type: 'ox',
            question: 'PIR (Planned Independent Requirements) is used as the demand input for Make-to-Stock (MTS) production.',
            correct: true,
            explanation: 'In MTS, PIRs serve as the demand source for MRP to generate replenishment plans.',
          },
          {
            type: 'four-choice',
            question: 'Which best describes MRP Type "PD"?',
            choices: [
              'Reorder point method — triggers planning when stock falls below a threshold',
              'Standard MRP method — performs BOM explosion and net requirements calculation',
              'No planning is executed',
              'Kanban method — automatic replenishment',
            ],
            correctIndex: 1,
            explanation: 'PD (MRP) is the standard planning method that performs BOM explosion and net requirements calculation.',
          },
          {
            type: 'ox',
            question: 'In Make-to-Order (MTO) production, Sales Orders (not PIRs) serve as the MRP demand source.',
            correct: true,
            explanation: 'MTO uses sales order line items as the demand source, generating production orders tied to specific orders.',
          },
          {
            type: 'four-choice',
            question: 'Which is NOT required information when creating a PIR in demand management?',
            choices: ['Material number', 'Planned quantity', 'Planning date (period)', 'Vendor number'],
            correctIndex: 3,
            explanation: 'PIR is internal planning information; vendor number is not needed. Material, quantity, date, and plant are required.',
          },
          {
            type: 'ordering',
            question: 'Arrange the demand management to MRP execution flow in the correct order.',
            items: ['MRP Run (MD01)', 'Collect Sales Forecast', 'Review Results in MD04', 'Enter PIR (MD61)', 'Planned Orders Generated'],
            correctOrder: [1, 3, 0, 4, 2],
            explanation: 'Collect Sales Forecast → Enter PIR → MRP Run → Planned Orders Generated → Review in MD04.',
          },
        ],
      },
      {
        id: 'production-order-lifecycle',
        title: 'Production Order Lifecycle',
        content: [
          'A Production Order progresses through statuses: CRTD (Created) → REL (Released) → PCNF (Partially Confirmed) → CNF (Confirmed) → TECO (Technically Complete) → CLSD (Closed).',
          'The REL (Release) status enables material issues and capacity confirmations, allowing manufacturing to start.',
          'Production Orders are changed with CO02 to modify quantities, dates, or components.',
          'After TECO, no goods movements are possible, but settlement (CO88) can still be executed.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What is the effect of setting a Production Order to REL (Released)?',
            choices: [
              'The production order is automatically settled',
              'Material issues and confirmations are enabled and manufacturing can begin',
              'The production order is archived',
              'The production order is locked from changes',
            ],
            correctIndex: 1,
            explanation: 'REL status enables material goods issues, production confirmations, and lets manufacturing begin.',
          },
          {
            type: 'ox',
            question: 'Production Orders are changed using CO02.',
            correct: true,
            explanation: 'CO02 changes production orders. CO01 creates, CO03 displays.',
          },
          {
            type: 'four-choice',
            question: 'Which operation can still be performed after TECO?',
            choices: ['MIGO Goods Receipt', 'Production Confirmation (CO11N)', 'CO88 Settlement', 'Material Issue'],
            correctIndex: 2,
            explanation: 'After TECO, goods movements and confirmations are blocked, but CO88 cost settlement is still possible.',
          },
          {
            type: 'ox',
            question: 'Once a production order is CLSD (Closed), no further changes or settlement are possible.',
            correct: true,
            explanation: 'CLSD is the final status; no changes, postings, or settlements can occur after this.',
          },
          {
            type: 'four-choice',
            question: 'What is the initial status of a newly created Production Order?',
            choices: ['REL', 'CRTD', 'TECO', 'CLSD'],
            correctIndex: 1,
            explanation: 'CRTD (Created) is the initial status immediately after a production order is created.',
          },
          {
            type: 'ordering',
            question: 'Arrange the Production Order lifecycle statuses in the correct order.',
            items: ['TECO (Technically Complete)', 'REL (Released)', 'CLSD (Closed)', 'CRTD (Created)', 'CNF (Confirmed)'],
            correctOrder: [3, 1, 4, 0, 2],
            explanation: 'CRTD → REL → CNF → TECO → CLSD.',
          },
        ],
      },
      {
        id: 'pp-period-end',
        title: 'PP Period-End Processing',
        content: [
          'PP period-end processing includes variance calculation (KKS2/KKAO), WIP (Work in Process) calculation, and settlement (CO88).',
          'KKAO performs batch variance calculation across production orders, comparing actual vs. standard costs.',
          'WIP calculation capitalizes the costs of production orders not yet complete at month-end as an asset.',
          'PP period-end results feed into CO month-end processing (settlement, variance analysis) and post to FI.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction is used for batch variance calculation across production orders?',
            choices: ['CO88', 'KKAO', 'CO11N', 'MD01'],
            correctIndex: 1,
            explanation: 'KKAO performs batch variance calculation for production orders. KKS2 does individual orders.',
          },
          {
            type: 'ox',
            question: 'WIP (Work in Process) calculation capitalizes costs of incomplete production orders as assets at month-end.',
            correct: true,
            explanation: 'WIP calculation posts the input costs of incomplete production orders to the balance sheet as a WIP asset.',
          },
          {
            type: 'four-choice',
            question: 'Where are production order costs ultimately transferred during CO88 settlement?',
            choices: [
              'Purchasing Organization',
              'Finished Goods inventory or Cost Center',
              'Sales Area',
              'Profit Center',
            ],
            correctIndex: 1,
            explanation: 'CO88 transfers actual costs to finished goods inventory (MTS) or cost centers (MTO).',
          },
          {
            type: 'ox',
            question: 'The correct PP period-end sequence is: Variance Calculation → WIP Calculation → Settlement (CO88).',
            correct: false,
            explanation: 'The correct sequence is WIP Calculation → Variance Calculation → Settlement (CO88). WIP must be determined first.',
          },
          {
            type: 'four-choice',
            question: 'When should CO88 (Production Order Settlement) be executed?',
            choices: [
              'Immediately after releasing the production order',
              'Simultaneously with production confirmation (CO11N)',
              'After TECO, as part of period-end processing',
              'After creating the purchase order',
            ],
            correctIndex: 2,
            explanation: 'CO88 is executed after TECO as part of period-end closing, together with WIP calculation and variance analysis.',
          },
          {
            type: 'ordering',
            question: 'Arrange the PP period-end processing steps in the correct order.',
            items: ['CO88 Settlement', 'Variance Calculation (KKAO)', 'FI Posting Verification', 'TECO (Technically Complete)', 'WIP Calculation'],
            correctOrder: [3, 4, 1, 0, 2],
            explanation: 'TECO → WIP Calculation → Variance Calculation → CO88 Settlement → FI Posting Verification.',
          },
        ],
      },
    ],
  },
};
