import type { ModuleContent } from '../learning-types';

export const ps: Record<'ja' | 'en', ModuleContent> = {
  ja: {
    id: 'ps',
    title: 'プロジェクト管理（PS）',
    description: 'SAPにおけるプロジェクトの計画・実行・決算を学びます',
    sections: [
      {
        id: 'ps-overview',
        title: 'PSモジュール概要',
        content: [
          'PS（Project System / プロジェクトシステム）は、SAPにおけるプロジェクト管理を担うモジュールです。プロジェクトの計画・予算管理・スケジュール管理・実績管理・決済処理までをカバーします。建設・エンジニアリング・IT・研究開発など、プロジェクトベースの業務を行う企業で広く利用されています。',
          'PSはCO（管理会計）・MM（購買管理）・PP（生産管理）・FI（財務会計）・HR（人事管理）など多くのモジュールと連携します。プロジェクトへの発注はMMと連携し、プロジェクトの原価はCOで管理され、プロジェクト決済はFIに転記されます。このようにPSは他モジュールを横断的に統合する役割を持ちます。',
        ],
        quizzes: [
          {
            type: 'ox',
            question: 'PSモジュールはプロジェクトの計画から決済までを一貫して管理できる。',
            correct: true,
            explanation: '正しいです。PSモジュールはプロジェクトの計画・予算管理・スケジュール管理・実績管理・決済処理までをカバーします。',
          },
          {
            type: 'four-choice',
            question: 'PSモジュールの正式名称はどれか。',
            choices: ['Production System', 'Project System', 'Planning System', 'Process System'],
            correctIndex: 1,
            explanation: 'PSはProject System（プロジェクトシステム）の略です。プロジェクト管理全般を担当します。',
          },
          {
            type: 'four-choice',
            question: 'PSモジュールでプロジェクトに発注処理を行う際に連携するモジュールはどれか。',
            choices: ['FI（財務会計）', 'CO（管理会計）', 'MM（購買管理）', 'HR（人事管理）'],
            correctIndex: 2,
            explanation: 'プロジェクトへの発注処理はMM（購買管理）と連携して行います。購買依頼や発注書をWBS要素やネットワーク活動に割り当てます。',
          },
          {
            type: 'ox',
            question: 'PSモジュールは他のモジュールとは独立して動作し、連携は不要である。',
            correct: false,
            explanation: '不正解です。PSはCO・MM・PP・FI・HRなど多くのモジュールと連携します。プロジェクトの原価管理はCO、購買はMM、決済はFIと連携して機能します。',
          },
          {
            type: 'four-choice',
            question: 'プロジェクト決済（Settlement）により原価が転記されるモジュールはどれか。',
            choices: ['MM（購買管理）', 'PP（生産管理）', 'FI（財務会計）', 'HR（人事管理）'],
            correctIndex: 2,
            explanation: 'プロジェクト決済によりプロジェクトに蓄積された原価が、FI（固定資産・G/L勘定など）やCO（原価センタ・収益性分析など）に転記されます。',
          },
          {
            type: 'four-choice',
            question: 'PSモジュールが最も活用される業種として適切でないものはどれか。',
            choices: ['建設業', 'エンジニアリング', '日用品の小売業', 'IT・研究開発'],
            correctIndex: 2,
            explanation: '日用品の小売業は定常的な業務が中心であり、プロジェクトベースの管理は主要ではありません。建設・エンジニアリング・IT・研究開発はプロジェクト単位の管理が重要です。',
          },
        ],
      },
      {
        id: 'ps-project-definition',
        title: 'プロジェクト定義',
        content: [
          'プロジェクト定義（Project Definition）はPSにおけるプロジェクトの最上位の組織単位です。プロジェクト全体の管理情報（プロジェクト名・責任者・計画開始日/終了日・会社コード・利益センタなど）を保持します。1つのプロジェクト定義の下に複数のWBS要素やネットワークが配置されます。',
          'プロジェクト定義にはプロジェクトプロファイルが割り当てられ、計画・予算・ステータス管理などのデフォルト設定を制御します。また、プロジェクトの種類（投資プロジェクト・顧客プロジェクトなど）に応じて異なるプロジェクトプロファイルを使い分けます。プロジェクト定義のトランザクションコードはCJ20N（プロジェクトビルダ）です。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'PSにおけるプロジェクトの最上位の組織単位は何か。',
            choices: ['WBS要素', 'ネットワーク', 'プロジェクト定義', '活動'],
            correctIndex: 2,
            explanation: 'プロジェクト定義はPSにおけるプロジェクトの最上位の組織単位です。その下にWBS要素やネットワークが配置されます。',
          },
          {
            type: 'four-choice',
            question: 'プロジェクトビルダのトランザクションコードはどれか。',
            choices: ['CJ01', 'CJ20N', 'CN21', 'KO01'],
            correctIndex: 1,
            explanation: 'CJ20Nはプロジェクトビルダで、プロジェクト定義・WBS要素・ネットワークなどを統合的に作成・編集できます。',
          },
          {
            type: 'ox',
            question: 'プロジェクト定義にはプロジェクトプロファイルが割り当てられ、デフォルト設定を制御する。',
            correct: true,
            explanation: '正しいです。プロジェクトプロファイルにより計画・予算・ステータス管理などのデフォルト値や動作が制御されます。',
          },
          {
            type: 'ox',
            question: '1つのプロジェクト定義には1つのWBS要素しか配置できない。',
            correct: false,
            explanation: '不正解です。1つのプロジェクト定義の下に複数のWBS要素を階層的に配置できます。プロジェクトの規模に応じて自由に構造化できます。',
          },
          {
            type: 'four-choice',
            question: 'プロジェクト定義に含まれない情報はどれか。',
            choices: ['プロジェクト名', '計画開始日/終了日', '品目の在庫数量', '会社コード'],
            correctIndex: 2,
            explanation: '品目の在庫数量はMMモジュールで管理される情報であり、プロジェクト定義には含まれません。プロジェクト定義にはプロジェクト名・日程・会社コード・責任者などの管理情報が含まれます。',
          },
          {
            type: 'four-choice',
            question: 'プロジェクトプロファイルの役割として正しいものはどれか。',
            choices: ['ユーザー権限の管理', '計画・予算・ステータス管理のデフォルト設定', 'データベースのパフォーマンス制御', 'プリンタの設定'],
            correctIndex: 1,
            explanation: 'プロジェクトプロファイルはプロジェクトの種類に応じた計画・予算・ステータス管理などのデフォルト設定を提供します。',
          },
        ],
      },
      {
        id: 'ps-wbs',
        title: 'WBS（Work Breakdown Structure）',
        content: [
          'WBS（Work Breakdown Structure / 作業分解構造）はプロジェクトの作業範囲を階層的に分解した構造です。PSではWBS要素（WBS Element）として定義され、プロジェクトの原価管理・予算管理・スケジュール管理の基本単位となります。WBS要素はツリー構造で最大99階層まで定義できます。',
          'WBS要素には「計画要素」と「会計要素」の属性があります。計画要素にはスケジュール（日程）を設定でき、会計要素には原価や予算を計上できます。最下位のWBS要素を会計要素として設定し、そこに実績原価を集計するのが一般的です。WBS要素の階層構造により、上位レベルでは集約された原価を確認し、下位レベルでは詳細な原価を確認できます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'WBSの正式名称は何か。',
            choices: ['Work Base System', 'Work Breakdown Structure', 'Work Budget Structure', 'Work Business System'],
            correctIndex: 1,
            explanation: 'WBSはWork Breakdown Structure（作業分解構造）の略です。プロジェクトの作業範囲を階層的に分解して管理します。',
          },
          {
            type: 'ox',
            question: 'WBS要素は原価管理・予算管理・スケジュール管理の基本単位となる。',
            correct: true,
            explanation: '正しいです。WBS要素はPSにおけるプロジェクト管理の基本単位で、原価・予算・スケジュールの計画と実績を管理します。',
          },
          {
            type: 'four-choice',
            question: 'WBS要素に実績原価を計上するために必要な属性はどれか。',
            choices: ['計画要素', '会計要素', 'ネットワーク要素', 'マイルストーン'],
            correctIndex: 1,
            explanation: '会計要素（Account Assignment Element）の属性を持つWBS要素に原価や予算を計上できます。計画要素はスケジュール管理に使用されます。',
          },
          {
            type: 'ox',
            question: 'WBS要素のツリー構造は最大10階層までに制限されている。',
            correct: false,
            explanation: '不正解です。WBS要素は最大99階層まで定義できます。ただし、実務では3〜5階層程度が一般的です。',
          },
          {
            type: 'four-choice',
            question: 'WBS要素の階層構造のメリットとして正しいものはどれか。',
            choices: ['階層ごとに異なるデータベースを使用できる', '上位で集約・下位で詳細な原価管理が可能', '他のSAPモジュールとの連携が不要になる', '階層が深いほどパフォーマンスが向上する'],
            correctIndex: 1,
            explanation: 'WBS要素の階層構造により、上位レベルではプロジェクト全体やフェーズ単位の集約原価を、下位レベルでは個々の作業パッケージの詳細原価を確認できます。',
          },
          {
            type: 'ordering',
            question: 'WBS要素の一般的な階層構造を上位から並べてください。',
            items: ['プロジェクト全体', 'フェーズ（設計・開発・テスト等）', '作業パッケージ'],
            correctOrder: [0, 1, 2],
            explanation: 'WBSは通常、プロジェクト全体を頂点とし、フェーズ（設計・開発・テスト等）で分割し、さらに具体的な作業パッケージに分解します。',
          },
        ],
      },
      {
        id: 'ps-network',
        title: 'ネットワークと活動',
        content: [
          'ネットワーク（Network）はプロジェクトの詳細な作業工程と依存関係を表現する構造です。ネットワークは活動（Activity）で構成され、活動間の前後関係（リレーションシップ）を定義することで、作業の順序やクリティカルパスを管理できます。ネットワークはWBS要素に割り当てられます。',
          '活動には「内部処理活動」「外部処理活動」「原価活動」の3種類があります。内部処理活動は社内リソースを使用する作業で、作業センタと所要時間を指定します。外部処理活動は外部への発注が伴う作業で、購買依頼や発注書と連携します。原価活動は実作業を伴わず原価のみを計上する活動です。活動にはマイルストーンを設定でき、プロジェクトの重要な節目を管理します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'ネットワークを構成する基本要素は何か。',
            choices: ['WBS要素', '活動（Activity）', 'プロジェクト定義', 'マイルストーン'],
            correctIndex: 1,
            explanation: 'ネットワークは活動（Activity）で構成されます。活動間のリレーションシップにより作業の順序と依存関係を表現します。',
          },
          {
            type: 'four-choice',
            question: '外部への発注が伴う活動の種類はどれか。',
            choices: ['内部処理活動', '外部処理活動', '原価活動', 'マイルストーン活動'],
            correctIndex: 1,
            explanation: '外部処理活動は外部業者への発注が伴う作業です。MM（購買管理）の購買依頼や発注書と連携して外部委託を管理します。',
          },
          {
            type: 'ox',
            question: 'ネットワークのリレーションシップにより、活動間のクリティカルパスを特定できる。',
            correct: true,
            explanation: '正しいです。活動間の前後関係（リレーションシップ）を定義することで、プロジェクト全体の最長経路（クリティカルパス）を自動計算し、遅延リスクのある作業を特定できます。',
          },
          {
            type: 'four-choice',
            question: '社内リソースを使用する作業に該当する活動の種類はどれか。',
            choices: ['外部処理活動', '原価活動', '内部処理活動', 'サービス活動'],
            correctIndex: 2,
            explanation: '内部処理活動は社内リソース（人員・設備）を使用する作業です。作業センタ（Work Center）と所要時間を指定して計画します。',
          },
          {
            type: 'ox',
            question: '原価活動は実際の作業を伴う活動である。',
            correct: false,
            explanation: '不正解です。原価活動は実作業を伴わず、原価のみを計上するための活動です。例えば、間接費の配賦先として使用されます。',
          },
          {
            type: 'four-choice',
            question: 'プロジェクトの重要な節目を管理するために活動に設定するものは何か。',
            choices: ['リレーションシップ', 'マイルストーン', 'プロジェクトプロファイル', 'ネットワークタイプ'],
            correctIndex: 1,
            explanation: 'マイルストーン（Milestone）はプロジェクトの重要な節目を表し、活動に設定して進捗の確認や請求トリガーとして使用できます。',
          },
        ],
      },
      {
        id: 'ps-planning',
        title: 'プロジェクト計画',
        content: [
          'プロジェクト計画には日程計画と原価計画があります。日程計画では、WBS要素や活動に対して計画開始日・計画終了日・所要日数を設定します。ネットワークのスケジューリングでは、フォワードスケジューリング（開始日から終了日を算出）とバックワードスケジューリング（終了日から開始日を逆算）が可能です。',
          '原価計画では、WBS要素やネットワーク活動に対して計画原価を設定します。原価計画の方法には、単位原価計算（Unit Costing）・詳細計画（Detail Planning）・概算計画（Overall Planning）などがあります。計画原価は会計年度と期間（月次など）に分割して登録でき、予実管理に活用します。プロジェクトの計画データはプロジェクト計画ボード（トランザクションCJ2B等）で確認できます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '終了日を起点として開始日を逆算するスケジューリング方法はどれか。',
            choices: ['フォワードスケジューリング', 'バックワードスケジューリング', 'リソースレベリング', 'クリティカルパス法'],
            correctIndex: 1,
            explanation: 'バックワードスケジューリングは、プロジェクトの完了予定日を起点として、各活動の開始日を逆算する方法です。納期厳守のプロジェクトで使用されます。',
          },
          {
            type: 'ox',
            question: 'プロジェクトの原価計画は会計年度と期間に分割して登録できる。',
            correct: true,
            explanation: '正しいです。原価計画は会計年度・期間（月次など）に分割して登録でき、期間ごとの予算管理や予実比較に活用できます。',
          },
          {
            type: 'four-choice',
            question: 'プロジェクト計画に含まれない要素はどれか。',
            choices: ['日程計画', '原価計画', 'ユーザー権限計画', 'リソース計画'],
            correctIndex: 2,
            explanation: 'ユーザー権限計画はBasis（システム管理）の領域であり、プロジェクト計画の要素ではありません。プロジェクト計画には日程・原価・リソースの計画が含まれます。',
          },
          {
            type: 'four-choice',
            question: 'フォワードスケジューリングの説明として正しいものはどれか。',
            choices: ['終了日から開始日を逆算する', '開始日から終了日を算出する', '原価の計画を行う', '予算の承認を行う'],
            correctIndex: 1,
            explanation: 'フォワードスケジューリングは、プロジェクトの開始日を起点として、各活動の所要時間を積み上げて終了日を算出する方法です。',
          },
          {
            type: 'ox',
            question: '概算計画（Overall Planning）はWBS要素レベルで合計原価を一括入力する方法である。',
            correct: true,
            explanation: '正しいです。概算計画はWBS要素に対して合計原価を一括で入力する簡易的な計画方法です。プロジェクト初期段階で詳細な内訳が不明な場合に使用されます。',
          },
          {
            type: 'ordering',
            question: 'プロジェクト計画の一般的な手順を並べてください。',
            items: ['WBS構造を定義', '日程計画を設定', '原価計画を作成', '予算を配分・承認'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'まずWBS構造を定義し、各要素の日程を計画し、原価計画を作成した上で、予算を配分・承認するのが一般的な流れです。',
          },
        ],
      },
      {
        id: 'ps-budget',
        title: '予算管理',
        content: [
          'PSの予算管理は、プロジェクトに割り当てられた資金の管理と支出コントロールを行います。予算はWBS要素に対して設定され、予算配分（トップダウン）と予算積み上げ（ボトムアップ）の方法で管理します。トランザクションCJ30（初期予算設定）・CJ31（予算変更）・CJ32（予算追加）で予算を管理します。',
          'アベイラビリティコントロール（Availability Control）は、実績や発注が予算を超過しないように監視する機能です。予算超過時のアクション（警告・エラー）をしきい値に基づいて設定できます。例えば、実績が予算の90%に達したら警告、100%に達したらエラーとして処理を停止する設定が可能です。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '初期予算設定のトランザクションコードはどれか。',
            choices: ['CJ20N', 'CJ30', 'CJ31', 'CJ32'],
            correctIndex: 1,
            explanation: 'CJ30はWBS要素に初期予算を設定するトランザクションコードです。CJ31は予算変更、CJ32は予算追加に使用します。',
          },
          {
            type: 'four-choice',
            question: '実績や発注が予算を超過しないように監視する機能は何か。',
            choices: ['原価計画', 'アベイラビリティコントロール', 'プロジェクト決済', 'トップダウン予算配分'],
            correctIndex: 1,
            explanation: 'アベイラビリティコントロール（Availability Control）は予算超過を監視し、しきい値に基づいて警告やエラーを発生させる機能です。',
          },
          {
            type: 'ox',
            question: '予算はWBS要素に対して設定される。',
            correct: true,
            explanation: '正しいです。PSの予算はWBS要素に対して設定されます。上位WBS要素に設定した予算を下位要素にトップダウンで配分することも可能です。',
          },
          {
            type: 'four-choice',
            question: '予算を追加するトランザクションコードはどれか。',
            choices: ['CJ30', 'CJ31', 'CJ32', 'CJ20N'],
            correctIndex: 2,
            explanation: 'CJ32はプロジェクトへの追加予算を設定するトランザクションコードです。CJ30は初期予算、CJ31は予算変更（振替）です。',
          },
          {
            type: 'ox',
            question: 'アベイラビリティコントロールで予算超過時にエラーを設定すると、超過する処理は自動的に停止される。',
            correct: true,
            explanation: '正しいです。アベイラビリティコントロールでアクションを「エラー」に設定すると、予算を超過する発注や実績計上は処理がブロックされます。',
          },
          {
            type: 'four-choice',
            question: 'トップダウン予算配分の説明として正しいものはどれか。',
            choices: ['下位WBS要素から予算を積み上げる', '上位WBS要素の予算を下位要素に配分する', '外部から予算を取り込む', '予算を他プロジェクトに振り替える'],
            correctIndex: 1,
            explanation: 'トップダウン予算配分は、上位WBS要素に設定された予算を下位WBS要素に配分する方法です。ボトムアップは逆に下位から積み上げます。',
          },
        ],
      },
      {
        id: 'ps-actual',
        title: '実績管理',
        content: [
          'プロジェクトの実績管理では、WBS要素やネットワーク活動に対して発生した実績原価を記録・追跡します。実績原価は、MM（購買管理）での入庫・請求書照合、FI（財務会計）での費用計上、CO（管理会計）での活動配賦・間接費計算など、さまざまな業務処理から自動的に収集されます。',
          '活動の確認（Confirmation）はトランザクションCN25（個別確認）やCN28（一括確認）で行います。確認では実際の作業時間や使用した資材の数量を入力し、活動の進捗率を更新します。プロジェクトの予実比較はトランザクションCJ45（プロジェクト実績/計画レポート）やS_ALR_87013532等の標準レポートで確認できます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'ネットワーク活動の個別確認を行うトランザクションコードはどれか。',
            choices: ['CN21', 'CN25', 'CN28', 'CJ20N'],
            correctIndex: 1,
            explanation: 'CN25はネットワーク活動の個別確認（Individual Confirmation）を行うトランザクションコードです。CN28は一括確認に使用します。',
          },
          {
            type: 'ox',
            question: 'プロジェクトの実績原価は、購買・会計・管理会計の処理から自動的に収集される。',
            correct: true,
            explanation: '正しいです。MM（入庫・請求照合）、FI（費用計上）、CO（活動配賦・間接費計算）などの処理からプロジェクトに実績原価が自動計上されます。',
          },
          {
            type: 'four-choice',
            question: '活動の確認で入力する情報として含まれないものはどれか。',
            choices: ['実際の作業時間', '使用した資材の数量', 'ユーザーのパスワード', '進捗率'],
            correctIndex: 2,
            explanation: 'ユーザーのパスワードは活動確認の入力項目ではありません。実際の作業時間・資材使用量・進捗率などを入力します。',
          },
          {
            type: 'four-choice',
            question: 'ネットワーク活動の一括確認を行うトランザクションコードはどれか。',
            choices: ['CN25', 'CN28', 'CJ45', 'CJ20N'],
            correctIndex: 1,
            explanation: 'CN28は複数の活動の確認を一括で行うトランザクションコードです。大量の活動確認を効率的に処理する際に使用します。',
          },
          {
            type: 'ox',
            question: '実績原価はすべて手動で入力する必要がある。',
            correct: false,
            explanation: '不正解です。実績原価の多くは他モジュール（MM・FI・CO）での業務処理から自動的にプロジェクトに計上されます。手動入力が必要なのは活動確認（作業時間等）です。',
          },
          {
            type: 'ordering',
            question: '活動確認の流れを正しい順序で並べてください。',
            items: ['作業を実施', '確認データ（時間・数量）を入力', '進捗率を更新', '実績原価が自動計上'],
            correctOrder: [0, 1, 2, 3],
            explanation: '実際の作業を行った後、確認トランザクションで作業時間や数量を入力し、進捗率を更新すると、実績原価が自動計上されます。',
          },
        ],
      },
      {
        id: 'ps-status',
        title: 'ステータス管理',
        content: [
          'PSにはシステムステータスとユーザーステータスの2種類があります。システムステータスはSAPが自動的に管理するステータスで、CRTD（作成済）・REL（リリース済）・TECO（技術的完了）・CLSD（締め済）などがあります。各ステータスによって実行可能な業務処理が制御されます。',
          'ユーザーステータスは企業独自のステータスをステータスプロファイルで定義し、業務プロセスに応じた追加の制御を行います。例えば「承認待ち」「承認済み」「保留」などのステータスを定義できます。リリース（REL）されたWBS要素やネットワークにのみ実績計上が可能になるなど、ステータスは業務処理の制御に重要な役割を果たします。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'SAPが自動管理し、「リリース済み」を意味するシステムステータスはどれか。',
            choices: ['CRTD', 'REL', 'TECO', 'CLSD'],
            correctIndex: 1,
            explanation: 'REL（Released / リリース済み）はプロジェクトやWBS要素が実行可能な状態になったことを示すシステムステータスです。CRTDは作成済み、TECOは技術的完了、CLSDは締め済みです。',
          },
          {
            type: 'ox',
            question: 'ユーザーステータスはステータスプロファイルで定義する企業独自のステータスである。',
            correct: true,
            explanation: '正しいです。ユーザーステータスはステータスプロファイルで定義し、企業固有の業務プロセスに応じた追加の制御（例：承認ワークフロー）を実現します。',
          },
          {
            type: 'four-choice',
            question: 'プロジェクトの技術的完了を意味するステータスはどれか。',
            choices: ['REL', 'TECO', 'CLSD', 'CRTD'],
            correctIndex: 1,
            explanation: 'TECO（Technically Complete / 技術的完了）は、プロジェクトの作業がすべて完了したことを示します。TECO後も決済処理は可能です。CLSDは完全に締め切られた状態です。',
          },
          {
            type: 'ox',
            question: 'CRTD（作成済み）ステータスのWBS要素に実績原価を計上できる。',
            correct: false,
            explanation: '不正解です。実績原価の計上にはWBS要素がREL（リリース済み）ステータスである必要があります。CRTD状態では計画作業のみ可能です。',
          },
          {
            type: 'four-choice',
            question: 'CLSD（締め済み）ステータスの説明として正しいものはどれか。',
            choices: ['計画作業が可能', '実績計上が可能', '決済処理が可能', 'すべての業務処理が完了し締め切られた状態'],
            correctIndex: 3,
            explanation: 'CLSDはプロジェクトが完全に締め切られた状態を示し、実績計上も決済もできません。アーカイブ対象となります。',
          },
          {
            type: 'ordering',
            question: 'プロジェクトの一般的なシステムステータスの遷移を並べてください。',
            items: ['CRTD（作成済み）', 'REL（リリース済み）', 'TECO（技術的完了）', 'CLSD（締め済み）'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'プロジェクトは作成（CRTD）→リリース（REL）→技術的完了（TECO）→締め（CLSD）の順にステータスが遷移します。',
          },
        ],
      },
      {
        id: 'ps-settlement',
        title: 'プロジェクト決済',
        content: [
          'プロジェクト決済（Settlement）は、WBS要素やネットワークに蓄積された原価を決済先（固定資産・原価センタ・G/L勘定・収益性分析セグメントなど）に振り替える処理です。投資プロジェクトでは固定資産への決済が一般的で、完成した資産の取得原価として計上されます。',
          '決済には決済規則（Settlement Rule）の設定が必要で、WBS要素ごとに決済先と配分比率を指定します。月次決済は期間中に発生した原価を決済し、最終決済はプロジェクト完了時に残額をすべて決済します。決済はトランザクションCJ88（個別決済）またはCJB1（一括決済）で実行します。決済を実行すると、プロジェクトの原価がFIやCOの対象先に転記されます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'プロジェクト決済のトランザクションコードはどれか。',
            choices: ['CJ20N', 'CJ30', 'CJ88', 'CJ45'],
            correctIndex: 2,
            explanation: 'CJ88はプロジェクトの個別決済を実行するトランザクションコードです。CJB1は一括決済に使用します。',
          },
          {
            type: 'four-choice',
            question: '投資プロジェクトの一般的な決済先はどれか。',
            choices: ['原価センタ', '固定資産', '内部指図', '利益センタ'],
            correctIndex: 1,
            explanation: '投資プロジェクトでは、完成した資産の取得原価として固定資産に決済するのが一般的です。受注プロジェクトでは原価センタや収益性分析に決済することもあります。',
          },
          {
            type: 'ox',
            question: '決済規則では、WBS要素ごとに決済先と配分比率を指定する。',
            correct: true,
            explanation: '正しいです。決済規則（Settlement Rule）でWBS要素ごとに決済先（固定資産・原価センタ等）と配分比率（例：100%を固定資産に、または70%を原価センタA・30%を原価センタBに）を指定します。',
          },
          {
            type: 'four-choice',
            question: '月次決済と最終決済の違いとして正しいものはどれか。',
            choices: ['月次決済は計画原価を決済し、最終決済は実績原価を決済する', '月次決済は期間原価を決済し、最終決済はプロジェクト完了時に残額を決済する', '月次決済は自動実行され、最終決済は手動でのみ実行できる', '両者に違いはない'],
            correctIndex: 1,
            explanation: '月次決済は当期間に発生した原価を決済し、最終決済はプロジェクト完了時に残っているすべての原価を決済します。最終決済後にTECOやCLSDステータスに設定するのが一般的です。',
          },
          {
            type: 'ox',
            question: '決済規則を設定しなくてもプロジェクト決済を実行できる。',
            correct: false,
            explanation: '不正解です。プロジェクト決済を実行するには、対象のWBS要素に決済規則（決済先と配分比率）が設定されている必要があります。',
          },
          {
            type: 'ordering',
            question: '投資プロジェクトの決済処理の流れを並べてください。',
            items: ['決済規則を設定', '月次決済を実行', 'プロジェクト完了時に最終決済', '固定資産として取得原価が計上'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'まず決済規則を設定し、プロジェクト期間中は月次決済を行い、プロジェクト完了時に最終決済を実行して、固定資産に取得原価として計上します。',
          },
        ],
      },
      {
        id: 'ps-reporting',
        title: 'プロジェクトレポートと分析',
        content: [
          'PSには多くの標準レポートが用意されています。プロジェクト情報システム（トランザクションCN41〜CN49等）では、プロジェクトの構造・日程・原価・予算の状況を階層レポート形式で確認できます。予実比較レポート（CJ45等）では計画原価と実績原価を対比して分析できます。',
          'プロジェクト進捗分析（Progress Analysis）はプロジェクトの出来高（Earned Value）を測定する機能です。計画価値（PV: Planned Value）・出来高（EV: Earned Value）・実績原価（AC: Actual Cost）の3指標を使い、コスト効率（CPI）やスケジュール効率（SPI）を算出します。これらの指標により、プロジェクトが予算内・スケジュール内で進行しているかを客観的に評価できます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'プロジェクト情報システムのトランザクションコードはどれか。',
            choices: ['CJ20N', 'CN41', 'CJ88', 'CJ30'],
            correctIndex: 1,
            explanation: 'CN41〜CN49はプロジェクト情報システムのトランザクションコードで、プロジェクトの構造・日程・原価・予算を階層レポート形式で表示します。CN41は構造概要です。',
          },
          {
            type: 'four-choice',
            question: 'アーンドバリュー分析で使用される3つの指標に含まれないものはどれか。',
            choices: ['計画価値（PV）', '出来高（EV）', '実績原価（AC）', '予算残高（BR）'],
            correctIndex: 3,
            explanation: 'アーンドバリュー分析の3指標はPV（Planned Value / 計画価値）・EV（Earned Value / 出来高）・AC（Actual Cost / 実績原価）です。予算残高は直接の指標ではありません。',
          },
          {
            type: 'ox',
            question: 'CPI（コスト効率指数）が1.0より大きい場合、プロジェクトは予算内で進行している。',
            correct: true,
            explanation: '正しいです。CPI（Cost Performance Index）= EV / ACで算出され、1.0より大きい場合は予算以下の原価で出来高を達成していることを意味します。1.0未満はコスト超過です。',
          },
          {
            type: 'four-choice',
            question: 'SPI（スケジュール効率指数）の算出式として正しいものはどれか。',
            choices: ['AC / PV', 'EV / PV', 'EV / AC', 'PV / AC'],
            correctIndex: 1,
            explanation: 'SPI（Schedule Performance Index）= EV / PVで算出されます。1.0より大きい場合はスケジュール前倒し、1.0未満はスケジュール遅延を示します。',
          },
          {
            type: 'ox',
            question: 'PSの標準レポートでは計画原価と実績原価の対比分析はできない。',
            correct: false,
            explanation: '不正解です。予実比較レポート（CJ45等）で計画原価と実績原価を対比して分析できます。差異分析はプロジェクト管理の基本的な機能です。',
          },
          {
            type: 'ordering',
            question: 'アーンドバリュー分析の手順を並べてください。',
            items: ['計画価値（PV）を設定', '出来高（EV）を測定', '実績原価（AC）を集計', 'CPI・SPIを算出して評価'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'まず計画段階でPV（計画価値）を設定し、実行中にEV（出来高）を測定し、AC（実績原価）を集計した上で、CPI・SPIを算出してプロジェクトの健全性を評価します。',
          },
        ],
      },
    ],
  },
  en: {
    id: 'ps',
    title: 'Project System (PS)',
    description: 'Learn project planning, execution, and settlement in SAP',
    sections: [
      {
        id: 'ps-overview',
        title: 'PS Module Overview',
        content: [
          'PS (Project System) is the SAP module for project management. It covers project planning, budget management, schedule management, actual tracking, and settlement processing. It is widely used in project-based industries such as construction, engineering, IT, and research & development.',
          'PS integrates with many modules including CO (Controlling), MM (Materials Management), PP (Production Planning), FI (Financial Accounting), and HR (Human Resources). Project procurement integrates with MM, project costs are managed in CO, and project settlement posts to FI. PS plays a cross-module integration role.',
        ],
        quizzes: [
          {
            type: 'ox',
            question: 'The PS module can manage a project consistently from planning through settlement.',
            correct: true,
            explanation: 'Correct. The PS module covers project planning, budget management, schedule management, actual tracking, and settlement processing.',
          },
          {
            type: 'four-choice',
            question: 'What does PS stand for?',
            choices: ['Production System', 'Project System', 'Planning System', 'Process System'],
            correctIndex: 1,
            explanation: 'PS stands for Project System, handling all aspects of project management.',
          },
          {
            type: 'four-choice',
            question: 'Which module integrates with PS for project procurement?',
            choices: ['FI (Financial Accounting)', 'CO (Controlling)', 'MM (Materials Management)', 'HR (Human Resources)'],
            correctIndex: 2,
            explanation: 'Project procurement integrates with MM (Materials Management). Purchase requisitions and purchase orders are assigned to WBS elements or network activities.',
          },
          {
            type: 'ox',
            question: 'The PS module operates independently and does not require integration with other modules.',
            correct: false,
            explanation: 'Incorrect. PS integrates with CO, MM, PP, FI, HR, and other modules. Cost management uses CO, procurement uses MM, and settlement posts to FI.',
          },
          {
            type: 'four-choice',
            question: 'To which module are costs posted during project settlement?',
            choices: ['MM (Materials Management)', 'PP (Production Planning)', 'FI (Financial Accounting)', 'HR (Human Resources)'],
            correctIndex: 2,
            explanation: 'Project settlement posts accumulated costs to FI (fixed assets, G/L accounts, etc.) and CO (cost centers, profitability analysis, etc.).',
          },
          {
            type: 'four-choice',
            question: 'Which industry is LEAST suited for PS module usage?',
            choices: ['Construction', 'Engineering', 'Consumer retail', 'IT & R&D'],
            correctIndex: 2,
            explanation: 'Consumer retail focuses on routine operations rather than project-based management. Construction, engineering, and IT/R&D require project-level management.',
          },
        ],
      },
      {
        id: 'ps-project-definition',
        title: 'Project Definition',
        content: [
          'The Project Definition is the top-level organizational unit in PS. It holds project-wide management information (project name, responsible person, planned start/end dates, company code, profit center, etc.). Multiple WBS elements and networks are arranged under one project definition.',
          'A Project Profile is assigned to the project definition, controlling default settings for planning, budgeting, and status management. Different project profiles are used for different project types (investment projects, customer projects, etc.). The transaction code for project management is CJ20N (Project Builder).',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What is the top-level organizational unit in PS?',
            choices: ['WBS Element', 'Network', 'Project Definition', 'Activity'],
            correctIndex: 2,
            explanation: 'The Project Definition is the top-level organizational unit in PS. WBS elements and networks are arranged beneath it.',
          },
          {
            type: 'four-choice',
            question: 'What is the transaction code for the Project Builder?',
            choices: ['CJ01', 'CJ20N', 'CN21', 'KO01'],
            correctIndex: 1,
            explanation: 'CJ20N is the Project Builder, providing integrated creation and editing of project definitions, WBS elements, and networks.',
          },
          {
            type: 'ox',
            question: 'A Project Profile is assigned to the project definition to control default settings.',
            correct: true,
            explanation: 'Correct. Project Profiles control default values and behavior for planning, budgeting, and status management.',
          },
          {
            type: 'ox',
            question: 'Only one WBS element can be placed under a project definition.',
            correct: false,
            explanation: 'Incorrect. Multiple WBS elements can be arranged hierarchically under one project definition, with the structure adapting to project scale.',
          },
          {
            type: 'four-choice',
            question: 'Which information is NOT contained in a project definition?',
            choices: ['Project name', 'Planned start/end dates', 'Material stock quantities', 'Company code'],
            correctIndex: 2,
            explanation: 'Material stock quantities are managed in the MM module, not in the project definition. Project definitions contain project name, dates, company code, responsible person, and similar management information.',
          },
          {
            type: 'four-choice',
            question: 'What is the purpose of a Project Profile?',
            choices: ['User authorization management', 'Default settings for planning, budgeting, and status management', 'Database performance control', 'Printer configuration'],
            correctIndex: 1,
            explanation: 'Project Profiles provide default settings for planning, budgeting, and status management, tailored to the project type.',
          },
        ],
      },
      {
        id: 'ps-wbs',
        title: 'WBS (Work Breakdown Structure)',
        content: [
          'A WBS (Work Breakdown Structure) is a hierarchical decomposition of the project scope. In PS, WBS Elements are the basic units for cost management, budget management, and schedule management. WBS elements can be defined in a tree structure up to 99 levels deep.',
          'WBS elements have "planning element" and "account assignment element" attributes. Planning elements can have schedules, while account assignment elements can receive costs and budgets. Typically, the lowest-level WBS elements are set as account assignment elements to collect actual costs. The hierarchical structure enables viewing aggregated costs at upper levels and detailed costs at lower levels.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What does WBS stand for?',
            choices: ['Work Base System', 'Work Breakdown Structure', 'Work Budget Structure', 'Work Business System'],
            correctIndex: 1,
            explanation: 'WBS stands for Work Breakdown Structure, a hierarchical decomposition of the project scope.',
          },
          {
            type: 'ox',
            question: 'WBS elements serve as the basic unit for cost, budget, and schedule management.',
            correct: true,
            explanation: 'Correct. WBS elements are the fundamental management units in PS for planning and tracking costs, budgets, and schedules.',
          },
          {
            type: 'four-choice',
            question: 'Which attribute must a WBS element have to receive actual costs?',
            choices: ['Planning element', 'Account assignment element', 'Network element', 'Milestone'],
            correctIndex: 1,
            explanation: 'WBS elements with the Account Assignment Element attribute can receive costs and budgets. Planning elements are used for schedule management.',
          },
          {
            type: 'ox',
            question: 'The WBS element tree structure is limited to a maximum of 10 levels.',
            correct: false,
            explanation: 'Incorrect. WBS elements can be defined up to 99 levels deep, though 3-5 levels is typical in practice.',
          },
          {
            type: 'four-choice',
            question: 'What is the benefit of the WBS element hierarchy?',
            choices: ['Different databases per level', 'Aggregated costs at top, detailed costs at bottom', 'No need for integration with other SAP modules', 'Deeper hierarchies improve performance'],
            correctIndex: 1,
            explanation: 'The hierarchy enables viewing aggregated costs at upper levels (project-wide, phase) and detailed costs at lower levels (work packages).',
          },
          {
            type: 'ordering',
            question: 'Arrange the typical WBS hierarchy from top to bottom.',
            items: ['Overall project', 'Phases (Design, Development, Testing, etc.)', 'Work packages'],
            correctOrder: [0, 1, 2],
            explanation: 'WBS typically starts with the overall project, broken into phases (design, development, testing), and further decomposed into work packages.',
          },
        ],
      },
      {
        id: 'ps-network',
        title: 'Networks and Activities',
        content: [
          'A Network represents detailed work processes and dependencies within a project. Networks consist of Activities, and defining relationships between activities enables management of work sequence and critical path. Networks are assigned to WBS elements.',
          'There are three activity types: Internal Processing (using internal resources with work centers and durations), External Processing (involving external procurement linked to purchase requisitions/orders), and Cost Activities (for cost posting only without actual work). Milestones can be set on activities to manage key project checkpoints.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What is the basic component of a network?',
            choices: ['WBS Element', 'Activity', 'Project Definition', 'Milestone'],
            correctIndex: 1,
            explanation: 'Networks consist of Activities. Relationships between activities express work sequences and dependencies.',
          },
          {
            type: 'four-choice',
            question: 'Which activity type involves external procurement?',
            choices: ['Internal Processing', 'External Processing', 'Cost Activity', 'Milestone Activity'],
            correctIndex: 1,
            explanation: 'External Processing activities involve procurement from external vendors, integrating with MM purchase requisitions and purchase orders.',
          },
          {
            type: 'ox',
            question: 'Network relationships can identify the critical path across activities.',
            correct: true,
            explanation: 'Correct. Defining relationships between activities enables automatic calculation of the critical path (longest path), identifying activities at risk of causing delays.',
          },
          {
            type: 'four-choice',
            question: 'Which activity type uses internal company resources?',
            choices: ['External Processing', 'Cost Activity', 'Internal Processing', 'Service Activity'],
            correctIndex: 2,
            explanation: 'Internal Processing activities use internal resources (personnel, equipment), specified with Work Centers and durations.',
          },
          {
            type: 'ox',
            question: 'Cost Activities involve actual physical work.',
            correct: false,
            explanation: 'Incorrect. Cost Activities are for cost posting only without actual work, used for purposes such as overhead allocation targets.',
          },
          {
            type: 'four-choice',
            question: 'What is set on activities to manage key project checkpoints?',
            choices: ['Relationships', 'Milestones', 'Project Profiles', 'Network Types'],
            correctIndex: 1,
            explanation: 'Milestones mark key project checkpoints and can be used for progress tracking or billing triggers.',
          },
        ],
      },
      {
        id: 'ps-planning',
        title: 'Project Planning',
        content: [
          'Project planning includes schedule planning and cost planning. Schedule planning sets planned start dates, end dates, and durations for WBS elements and activities. Network scheduling supports forward scheduling (calculating end date from start date) and backward scheduling (calculating start date from end date).',
          'Cost planning sets planned costs for WBS elements and network activities. Methods include Unit Costing, Detail Planning, and Overall Planning. Planned costs can be distributed across fiscal years and periods (monthly, etc.) for variance analysis. Project planning data can be reviewed in the Project Planning Board (transaction CJ2B, etc.).',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which scheduling method calculates the start date backward from the end date?',
            choices: ['Forward Scheduling', 'Backward Scheduling', 'Resource Leveling', 'Critical Path Method'],
            correctIndex: 1,
            explanation: 'Backward Scheduling calculates each activity\'s start date backward from the project completion date, commonly used for deadline-driven projects.',
          },
          {
            type: 'ox',
            question: 'Project cost plans can be distributed across fiscal years and periods.',
            correct: true,
            explanation: 'Correct. Cost plans can be distributed by fiscal year and period (monthly, etc.) for period-based budget management and variance analysis.',
          },
          {
            type: 'four-choice',
            question: 'Which is NOT an element of project planning?',
            choices: ['Schedule planning', 'Cost planning', 'User authorization planning', 'Resource planning'],
            correctIndex: 2,
            explanation: 'User authorization planning belongs to Basis (system administration), not project planning. Project planning includes schedule, cost, and resource planning.',
          },
          {
            type: 'four-choice',
            question: 'Which statement correctly describes forward scheduling?',
            choices: ['Calculates start date from end date', 'Calculates end date from start date', 'Plans costs', 'Approves budgets'],
            correctIndex: 1,
            explanation: 'Forward Scheduling calculates the end date by adding activity durations starting from the project start date.',
          },
          {
            type: 'ox',
            question: 'Overall Planning is a method for entering total costs at the WBS element level in one step.',
            correct: true,
            explanation: 'Correct. Overall Planning is a simplified planning method where total costs are entered at the WBS element level, useful in early project stages when detailed breakdowns are not yet available.',
          },
          {
            type: 'ordering',
            question: 'Arrange the typical project planning steps in order.',
            items: ['Define WBS structure', 'Set schedule plan', 'Create cost plan', 'Distribute and approve budget'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'First define the WBS structure, plan schedules for each element, create cost plans, then distribute and approve the budget.',
          },
        ],
      },
      {
        id: 'ps-budget',
        title: 'Budget Management',
        content: [
          'PS budget management controls project funding and spending. Budgets are set on WBS elements, managed via top-down distribution or bottom-up rollup. Transactions CJ30 (initial budget), CJ31 (budget change), and CJ32 (budget supplement) are used for budget management.',
          'Availability Control monitors whether actuals and commitments exceed the budget. Actions (warning, error) can be configured based on thresholds. For example, a warning at 90% budget utilization and an error blocking processing at 100% can be configured.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What is the transaction code for initial budget setting?',
            choices: ['CJ20N', 'CJ30', 'CJ31', 'CJ32'],
            correctIndex: 1,
            explanation: 'CJ30 is used for setting initial budgets on WBS elements. CJ31 is for budget changes, and CJ32 is for budget supplements.',
          },
          {
            type: 'four-choice',
            question: 'What feature monitors whether actuals and commitments exceed the budget?',
            choices: ['Cost Planning', 'Availability Control', 'Project Settlement', 'Top-Down Budget Distribution'],
            correctIndex: 1,
            explanation: 'Availability Control monitors budget exceedance and triggers warnings or errors based on configured thresholds.',
          },
          {
            type: 'ox',
            question: 'Budgets are set on WBS elements.',
            correct: true,
            explanation: 'Correct. PS budgets are set on WBS elements. Top-down distribution from upper WBS elements to lower elements is also possible.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used for budget supplements?',
            choices: ['CJ30', 'CJ31', 'CJ32', 'CJ20N'],
            correctIndex: 2,
            explanation: 'CJ32 is used for budget supplements. CJ30 is for initial budgets, and CJ31 is for budget changes (transfers).',
          },
          {
            type: 'ox',
            question: 'When Availability Control is set to error on budget exceedance, processing that would exceed the budget is automatically blocked.',
            correct: true,
            explanation: 'Correct. When the action is set to "error," purchase orders or actual postings that would exceed the budget are blocked.',
          },
          {
            type: 'four-choice',
            question: 'Which statement correctly describes top-down budget distribution?',
            choices: ['Rolls up budgets from lower WBS elements', 'Distributes upper WBS element budget to lower elements', 'Imports budgets from external sources', 'Transfers budget to other projects'],
            correctIndex: 1,
            explanation: 'Top-down distribution allocates the budget set on upper WBS elements to lower WBS elements. Bottom-up does the reverse.',
          },
        ],
      },
      {
        id: 'ps-actual',
        title: 'Actual Tracking',
        content: [
          'Project actual tracking records and monitors actual costs incurred against WBS elements and network activities. Actual costs are automatically collected from various business processes: goods receipt and invoice verification in MM, expense postings in FI, and activity allocation and overhead calculation in CO.',
          'Activity Confirmations are entered via transaction CN25 (individual) or CN28 (collective). Confirmations record actual work hours and material quantities, updating activity progress. Project plan/actual comparison reports include CJ45 and standard reports like S_ALR_87013532.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction code is used for individual activity confirmation?',
            choices: ['CN21', 'CN25', 'CN28', 'CJ20N'],
            correctIndex: 1,
            explanation: 'CN25 is used for individual activity confirmation. CN28 is used for collective confirmation.',
          },
          {
            type: 'ox',
            question: 'Project actual costs are automatically collected from procurement, accounting, and controlling processes.',
            correct: true,
            explanation: 'Correct. Actual costs are automatically posted from MM (goods receipt, invoice verification), FI (expense posting), and CO (activity allocation, overhead calculation).',
          },
          {
            type: 'four-choice',
            question: 'Which is NOT entered during activity confirmation?',
            choices: ['Actual work hours', 'Material quantities used', 'User password', 'Progress percentage'],
            correctIndex: 2,
            explanation: 'User password is not an activity confirmation input. Actual work hours, material quantities, and progress percentage are entered.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used for collective activity confirmation?',
            choices: ['CN25', 'CN28', 'CJ45', 'CJ20N'],
            correctIndex: 1,
            explanation: 'CN28 is used for confirming multiple activities collectively, enabling efficient processing of large volumes.',
          },
          {
            type: 'ox',
            question: 'All actual costs must be entered manually.',
            correct: false,
            explanation: 'Incorrect. Most actual costs are automatically posted from other modules (MM, FI, CO). Manual entry is mainly needed for activity confirmations (work hours, etc.).',
          },
          {
            type: 'ordering',
            question: 'Arrange the activity confirmation flow in order.',
            items: ['Perform work', 'Enter confirmation data (hours, quantities)', 'Update progress percentage', 'Actual costs are automatically posted'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'After performing work, enter confirmation data (hours, quantities), update the progress percentage, and actual costs are automatically posted.',
          },
        ],
      },
      {
        id: 'ps-status',
        title: 'Status Management',
        content: [
          'PS has two types of statuses: System Status and User Status. System Status is automatically managed by SAP, including CRTD (Created), REL (Released), TECO (Technically Complete), and CLSD (Closed). Each status controls which business operations are permitted.',
          'User Status is defined in Status Profiles for company-specific statuses, adding custom control to business processes. For example, "Pending Approval," "Approved," and "On Hold" statuses can be defined. Only REL (Released) WBS elements and networks can receive actual postings, demonstrating how status controls business processing.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which system status means "Released"?',
            choices: ['CRTD', 'REL', 'TECO', 'CLSD'],
            correctIndex: 1,
            explanation: 'REL (Released) indicates the project or WBS element is ready for execution. CRTD is Created, TECO is Technically Complete, and CLSD is Closed.',
          },
          {
            type: 'ox',
            question: 'User Status is a company-specific status defined in Status Profiles.',
            correct: true,
            explanation: 'Correct. User Status is defined in Status Profiles for company-specific business process controls (e.g., approval workflows).',
          },
          {
            type: 'four-choice',
            question: 'Which status means the project is technically complete?',
            choices: ['REL', 'TECO', 'CLSD', 'CRTD'],
            correctIndex: 1,
            explanation: 'TECO (Technically Complete) indicates all project work is done. Settlement processing is still possible after TECO. CLSD means fully closed.',
          },
          {
            type: 'ox',
            question: 'Actual costs can be posted to a WBS element with CRTD (Created) status.',
            correct: false,
            explanation: 'Incorrect. WBS elements must be REL (Released) to receive actual costs. In CRTD status, only planning activities are allowed.',
          },
          {
            type: 'four-choice',
            question: 'Which statement correctly describes CLSD (Closed) status?',
            choices: ['Planning is possible', 'Actual posting is possible', 'Settlement is possible', 'All business processing is complete and closed'],
            correctIndex: 3,
            explanation: 'CLSD indicates the project is fully closed, with no actual postings or settlement possible. It becomes eligible for archiving.',
          },
          {
            type: 'ordering',
            question: 'Arrange the typical system status progression for a project.',
            items: ['CRTD (Created)', 'REL (Released)', 'TECO (Technically Complete)', 'CLSD (Closed)'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'Projects progress through Created (CRTD) → Released (REL) → Technically Complete (TECO) → Closed (CLSD).',
          },
        ],
      },
      {
        id: 'ps-settlement',
        title: 'Project Settlement',
        content: [
          'Project Settlement transfers accumulated costs from WBS elements and networks to settlement receivers (fixed assets, cost centers, G/L accounts, profitability analysis segments, etc.). For investment projects, settlement to fixed assets is common, recording asset acquisition costs.',
          'Settlement requires Settlement Rules specifying receivers and distribution percentages per WBS element. Periodic settlement settles costs incurred during the period, while final settlement settles all remaining costs at project completion. Settlement is executed via transaction CJ88 (individual) or CJB1 (collective), posting project costs to FI and CO receivers.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What is the transaction code for project settlement?',
            choices: ['CJ20N', 'CJ30', 'CJ88', 'CJ45'],
            correctIndex: 2,
            explanation: 'CJ88 executes individual project settlement. CJB1 is used for collective settlement.',
          },
          {
            type: 'four-choice',
            question: 'What is the typical settlement receiver for investment projects?',
            choices: ['Cost center', 'Fixed asset', 'Internal order', 'Profit center'],
            correctIndex: 1,
            explanation: 'Investment projects typically settle to fixed assets, recording the completed asset\'s acquisition cost. Customer projects may settle to cost centers or profitability analysis.',
          },
          {
            type: 'ox',
            question: 'Settlement Rules specify receivers and distribution percentages per WBS element.',
            correct: true,
            explanation: 'Correct. Settlement Rules define the receiver (fixed asset, cost center, etc.) and distribution percentage (e.g., 100% to a fixed asset, or 70/30 split between cost centers) per WBS element.',
          },
          {
            type: 'four-choice',
            question: 'What is the difference between periodic and final settlement?',
            choices: ['Periodic settles planned costs; final settles actual costs', 'Periodic settles period costs; final settles all remaining costs at project completion', 'Periodic runs automatically; final can only run manually', 'There is no difference'],
            correctIndex: 1,
            explanation: 'Periodic settlement settles costs incurred during the current period, while final settlement settles all remaining costs at project completion. TECO or CLSD status is typically set after final settlement.',
          },
          {
            type: 'ox',
            question: 'Project settlement can be executed without setting up settlement rules.',
            correct: false,
            explanation: 'Incorrect. Settlement rules (specifying receivers and percentages) must be configured on the WBS elements before settlement can be executed.',
          },
          {
            type: 'ordering',
            question: 'Arrange the investment project settlement process flow in order.',
            items: ['Configure settlement rules', 'Execute periodic settlement', 'Execute final settlement at project completion', 'Acquisition costs posted to fixed asset'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'First configure settlement rules, execute periodic settlements during the project, perform final settlement at completion, and acquisition costs are posted to the fixed asset.',
          },
        ],
      },
      {
        id: 'ps-reporting',
        title: 'Project Reporting and Analysis',
        content: [
          'PS provides many standard reports. The Project Information System (transactions CN41-CN49, etc.) displays project structure, schedule, cost, and budget status in hierarchical report format. Plan/actual comparison reports (CJ45, etc.) analyze planned vs. actual costs.',
          'Progress Analysis measures project Earned Value. Using three metrics — PV (Planned Value), EV (Earned Value), and AC (Actual Cost) — it calculates CPI (Cost Performance Index) and SPI (Schedule Performance Index). These indicators objectively evaluate whether a project is on budget and on schedule.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What is the transaction code for the Project Information System?',
            choices: ['CJ20N', 'CN41', 'CJ88', 'CJ30'],
            correctIndex: 1,
            explanation: 'CN41-CN49 are Project Information System transactions displaying project structure, schedule, costs, and budget in hierarchical reports. CN41 shows the structure overview.',
          },
          {
            type: 'four-choice',
            question: 'Which is NOT one of the three Earned Value Analysis metrics?',
            choices: ['Planned Value (PV)', 'Earned Value (EV)', 'Actual Cost (AC)', 'Budget Remaining (BR)'],
            correctIndex: 3,
            explanation: 'The three EVM metrics are PV (Planned Value), EV (Earned Value), and AC (Actual Cost). Budget Remaining is not a direct EVM metric.',
          },
          {
            type: 'ox',
            question: 'A CPI (Cost Performance Index) greater than 1.0 indicates the project is within budget.',
            correct: true,
            explanation: 'Correct. CPI = EV / AC. Greater than 1.0 means earned value exceeds actual cost, indicating cost efficiency. Below 1.0 indicates cost overrun.',
          },
          {
            type: 'four-choice',
            question: 'What is the correct formula for SPI (Schedule Performance Index)?',
            choices: ['AC / PV', 'EV / PV', 'EV / AC', 'PV / AC'],
            correctIndex: 1,
            explanation: 'SPI = EV / PV. Greater than 1.0 indicates ahead of schedule, while less than 1.0 indicates schedule delay.',
          },
          {
            type: 'ox',
            question: 'PS standard reports cannot compare planned and actual costs.',
            correct: false,
            explanation: 'Incorrect. Plan/actual comparison reports (CJ45, etc.) enable analysis of planned versus actual costs. Variance analysis is a fundamental PS feature.',
          },
          {
            type: 'ordering',
            question: 'Arrange the Earned Value Analysis steps in order.',
            items: ['Set Planned Value (PV)', 'Measure Earned Value (EV)', 'Collect Actual Cost (AC)', 'Calculate CPI/SPI and evaluate'],
            correctOrder: [0, 1, 2, 3],
            explanation: 'First set PV during planning, measure EV during execution, collect AC, then calculate CPI/SPI to evaluate project health.',
          },
        ],
      },
    ],
  },
};
