import type { Quiz } from '../learning-types';
import type { Language } from '../i18n';

/** Additional SD practice questions, appended after each section's originals. */
export const sdQuizzes: Record<Language, Record<string, Quiz[]>> = {
  ja: {
    'sd-overview': [
      {
        type: 'four-choice',
        question: '照会・見積・受注・出荷・請求の各伝票が、前後の伝票とリンクして記録される仕組みを何と呼ぶか。',
        choices: ['伝票フロー', 'コピー管理', '条件テクニック', '出力管理'],
        correctIndex: 0,
        explanation: '伝票フローです。どの受注から出荷・請求が作られたかをたどれるため、処理がどこで止まっているかを確認できます。',
      },
      {
        type: 'four-choice',
        question: 'SDの伝票（受注など）の3階層構造として正しいものはどれか。',
        choices: ['ヘッダ・明細・納入日程行', '会社コード・プラント・保管場所', '販売組織・流通チャネル・製品部門', '得意先・品目・条件レコード'],
        correctIndex: 0,
        explanation: '受注伝票はヘッダ（得意先や伝票全体の情報）、明細（品目ごとの情報）、納入日程行（いつ・いくつ納入するか）の3階層です。',
      },
      {
        type: 'four-choice',
        question: '請求伝票を会計に転記したときに、FIに計上される代表的な仕訳はどれか。',
        choices: ['（借）売掛金 ／（貸）売上', '（借）売上原価 ／（貸）在庫', '（借）在庫 ／（貸）GR/IR', '（借）現金 ／（貸）売掛金'],
        correctIndex: 0,
        explanation: '請求時には売掛金と売上が計上されます。売上原価と在庫の仕訳は出庫転記の時点で、現金と売掛金の仕訳は入金時に計上されます。',
      },
      {
        type: 'ox',
        question: '伝票フローを見ると、ある受注から作成された出荷伝票や請求伝票、会計伝票までをたどることができる。',
        correct: true,
        explanation: '正しいです。受注・出荷・請求の各画面から伝票フローを表示でき、どの伝票まで処理が進んでいるかを一目で確認できます。',
      },
    ],
    'customer-master': [
      {
        type: 'four-choice',
        question: '受注先・出荷先・請求先・支払人のように、取引の中で得意先が果たす役割を何と呼ぶか。',
        choices: ['パートナ機能', '得意先勘定グループ', '販売エリア', '得意先グループ'],
        correctIndex: 0,
        explanation: 'パートナ機能です。本社が注文し、工場に届け、経理部に請求するといった取引を、役割ごとに別の得意先を指定して表現できます。',
      },
      {
        type: 'ox',
        question: '1つの得意先が、受注先・出荷先・請求先・支払人のすべての役割を兼ねることができる。',
        correct: true,
        explanation: '正しいです。小規模な取引先では4つの役割を同じ得意先が兼ねるのが一般的です。役割ごとに別の得意先を指定することもできます。',
      },
      {
        type: 'four-choice',
        question: '得意先勘定グループが制御するものとして正しいものはどれか。',
        choices: ['得意先番号の番号範囲と、マスタ画面の項目の入力制御', '得意先に適用する価格', '与信限度額', '出荷ポイントの決定'],
        correctIndex: 0,
        explanation: '得意先勘定グループは、番号範囲や、どの項目を必須・任意・非表示にするかを制御します。出荷先専用などの用途別にグループを分けます。',
      },
      {
        type: 'four-choice',
        question: '得意先が使っている独自の品目番号や、得意先・品目の組み合わせ固有の納入条件を登録するマスタはどれか。',
        choices: ['得意先・品目情報レコード', '購買情報レコード', '条件レコード', 'バッチマスタ'],
        correctIndex: 0,
        explanation: '得意先・品目情報レコードです。得意先の品目番号で受注を入力したり、得意先ごとの納入許容範囲などを設定したりできます。',
      },
    ],
    'sales-order': [
      {
        type: 'four-choice',
        question: '受注登録時にシステムが自動で決定しないものはどれか。',
        choices: ['価格', '明細カテゴリ', '出荷ポイント', '実際にピッキングされた数量'],
        correctIndex: 3,
        explanation: 'ピッキング数量は出荷伝票の段階で決まります。価格、明細カテゴリ、出荷ポイント、確認納期などは受注登録時に自動決定されます。',
      },
      {
        type: 'four-choice',
        question: '標準受注の通常の品目で使われる標準の明細カテゴリはどれか。',
        choices: ['TAN', 'TAS', 'TANN', 'REN'],
        correctIndex: 0,
        explanation: 'TANが標準明細です。TASは第三者取引、TANNは無償明細、RENは返品の明細カテゴリです。',
      },
      {
        type: 'ox',
        question: '受注伝票は全体のステータスのほかに、出荷・請求・与信などの個別のステータスを持つ。',
        correct: true,
        explanation: '正しいです。個別のステータスを見ると、出荷が一部済みで請求は未処理、といった状態を把握できます。',
      },
      {
        type: 'ox',
        question: 'ATPチェックで受注数量の一部しか確保できない場合、確保できなかった数量は受注に登録できず自動的に削除される。',
        correct: false,
        explanation: '誤りです。確保できた分とできなかった分は、日付の異なる納入日程行に分けて登録されます。不足分は後の日付で確認されるか、未確認のまま残ります。',
      },
    ],
    'shipping-billing': [
      {
        type: 'four-choice',
        question: '受注を参照して出荷伝票を作成するトランザクションコードはどれか。',
        choices: ['VL01N', 'VF01', 'VA01', 'VL02N'],
        correctIndex: 0,
        explanation: 'VL01Nが出荷伝票の作成です。VF01は請求伝票の作成、VA01は受注の作成、VL02Nは出荷伝票の変更（出庫転記もここから実行）です。',
      },
      {
        type: 'four-choice',
        question: '複数の出荷伝票を1枚の請求伝票にまとめられる条件として正しいものはどれか。',
        choices: ['支払人・請求日・支払条件など、請求伝票ヘッダの分割基準が同じである', '出荷した品目が同じである', '出荷ポイントが異なる', '出荷伝票の作成者が同じである'],
        correctIndex: 0,
        explanation: '請求伝票のヘッダに入る項目（支払人、請求日、支払条件など）が一致していれば1枚にまとめられます。どれかが異なると請求伝票が分割されます。',
      },
      {
        type: 'ox',
        question: '1つの出荷伝票から、複数の請求伝票を作成することはできない。',
        correct: false,
        explanation: '誤りです。明細ごとに支払条件が異なるなど、請求伝票の分割基準が異なる場合は、1つの出荷伝票から複数の請求伝票が作成されます。',
      },
      {
        type: 'four-choice',
        question: '請求リスト（Invoice List）の説明として正しいものはどれか。',
        choices: [
          '一定期間の複数の請求伝票を、請求先ごとにまとめて送付するための伝票',
          '出荷前にピッキング対象の品目をまとめた一覧',
          '与信ブロックされた受注の一覧',
          '条件レコードの一覧',
        ],
        correctIndex: 0,
        explanation: '請求リストは、請求伝票を1件ずつではなく月単位などでまとめて送付したい得意先向けに、複数の請求伝票を1つにまとめるものです。',
      },
    ],
    'sales-org': [
      {
        type: 'four-choice',
        question: '出荷処理を担当する組織単位で、出荷伝票の作成単位となるものはどれか。',
        choices: ['出荷ポイント', '販売オフィス', '流通チャネル', '販売グループ'],
        correctIndex: 0,
        explanation: '出荷ポイントです。出荷伝票は出荷ポイントごとに作成され、倉庫の出荷場や出荷方法（トラック、宅配など）の単位で設定します。',
      },
      {
        type: 'ox',
        question: '出荷ポイントはプラントに割り当てられ、1つのプラントに複数の出荷ポイントを設定できる。',
        correct: true,
        explanation: '正しいです。同じ工場でもトラック用と宅配用で出荷場が分かれている場合など、1つのプラントに複数の出荷ポイントを持てます。',
      },
      {
        type: 'four-choice',
        question: '販売オフィスと販売グループの関係として正しいものはどれか。',
        choices: [
          '販売オフィスは支店などの地域拠点で、販売グループはその中の営業担当チームを表す',
          '販売グループは会社コードに、販売オフィスはプラントに割り当てる',
          '販売オフィスと販売グループは同じものを別の名前で呼んでいる',
          '販売グループは出荷ポイントの下位の単位である',
        ],
        correctIndex: 0,
        explanation: '販売オフィスは支店や営業所などの地域拠点、販売グループはその中で営業を担当するチームを表します。どちらも社内の営業組織を表す任意の単位です。',
      },
      {
        type: 'four-choice',
        question: '販売地区（Sales District）の主な用途として正しいものはどれか。',
        choices: ['得意先を地域別に分類し、分析や価格決定に使う', '在庫を保管する場所を表す', '会計上の独立した単位を表す', '出荷伝票を作成する単位を表す'],
        correctIndex: 0,
        explanation: '販売地区は得意先マスタに設定する地域の区分で、地域別の売上分析や、地域ごとの価格の条件レコードに使えます。',
      },
    ],
    pricing: [
      {
        type: 'four-choice',
        question: '条件テクニックを構成する4つの要素に含まれないものはどれか。',
        choices: ['条件タイプ', 'アクセスシーケンス', '条件テーブル', '転記キー'],
        correctIndex: 3,
        explanation: '条件テクニックは条件タイプ・アクセスシーケンス・条件テーブル・条件レコードの4要素です。転記キーはFIで借方・貸方を決めるコードです。',
      },
      {
        type: 'ox',
        question: '条件タイプでは、金額・率・数量単位の値といった計算タイプや、受注で手入力による上書きを許可するかを設定する。',
        correct: true,
        explanation: '正しいです。PR00のような価格は金額、値引きは率、というように条件タイプごとに計算方法や変更可否を定義します。',
      },
      {
        type: 'four-choice',
        question: '条件レコードに有効期間を設定する主な理由はどれか。',
        choices: ['価格改定を事前に登録し、指定日から自動で新価格を適用するため', '条件レコードを削除できないようにするため', '条件タイプを変更するため', '受注の保存を禁止するため'],
        correctIndex: 0,
        explanation: '有効期間を設定しておくと、4月1日から新価格を適用するといった価格改定を事前に登録でき、受注の価格決定日に応じて自動的に使い分けられます。',
      },
      {
        type: 'four-choice',
        question: 'アクセスシーケンスの検索順で「排他」フラグを設定した場合の動作として正しいものはどれか。',
        choices: ['条件レコードが見つかった時点で、それ以降の検索を行わない', 'すべての条件テーブルを検索し、最も安い価格を採用する', '条件レコードが見つかっても無視する', '手入力の価格しか受け付けない'],
        correctIndex: 0,
        explanation: '排他を設定すると、最初に見つかった条件レコードを採用して検索を終了します。詳細な組み合わせから順に並べることで、最も具体的な価格が優先されます。',
      },
    ],
    'inquiry-quotation': [
      {
        type: 'four-choice',
        question: '見積が受注に至らなかった理由を明細ごとに記録する項目はどれか。',
        choices: ['拒否理由', '受注理由', '請求ブロック', '出荷ブロック'],
        correctIndex: 0,
        explanation: '拒否理由です。「価格で他社に負けた」などの理由を記録しておくと、失注の分析に使えます。',
      },
      {
        type: 'ox',
        question: '見積の明細に拒否理由を設定すると、その明細は受注への引継ぎの対象外となり、未処理の見積としても扱われなくなる。',
        correct: true,
        explanation: '正しいです。拒否理由を付けた明細は完了扱いとなり、未決の見積の一覧からも外れます。',
      },
      {
        type: 'four-choice',
        question: '得意先が承諾した見積から受注を作成する一般的な方法はどれか。',
        choices: ['VA01で見積を参照して受注を作成する', 'VA22で見積を変更すると受注に変わる', 'VF01で見積から請求伝票を作成する', 'VL01Nで見積から出荷伝票を作成する'],
        correctIndex: 0,
        explanation: 'VA01で受注を作成する際に見積を参照すると、コピー管理の設定に従って品目や価格が引き継がれ、伝票フローも記録されます。',
      },
      {
        type: 'ox',
        question: '照会（Inquiry）は、得意先からの問い合わせを記録し、価格や納期を回答するために使う伝票である。',
        correct: true,
        explanation: '正しいです。照会は法的な拘束力のない問い合わせの記録で、見積は条件を提示する伝票です。どちらも受注前の営業活動を記録して分析に使えます。',
      },
    ],
    'credit-management': [
      {
        type: 'four-choice',
        question: '与信限度額と比較される与信エクスポージャ（与信残高）に通常含まれないものはどれか。',
        choices: ['未決済の売掛金', '出荷済みで未請求の金額', '未出荷の受注金額', '有効期限内の見積金額'],
        correctIndex: 3,
        explanation: '見積は受注に至っていないため、与信残高には含めません。売掛金、未請求の出荷、未出荷の受注を合わせたものが与信限度額と比較されます。',
      },
      {
        type: 'ox',
        question: '与信チェックには、限度額との比較のほか、一定日数を超えて支払が遅れている明細があるかを確認するチェックもある。',
        correct: true,
        explanation: '正しいです。限度額に余裕があっても、延滞している得意先への出荷を止めたい場合に使います。',
      },
      {
        type: 'four-choice',
        question: '動的与信チェックの説明として正しいものはどれか。',
        choices: [
          '将来の一定期間内に出荷予定の受注だけを与信残高に含めて判定する',
          'すべての未出荷受注を期間に関係なく含めて判定する',
          '売掛金は含めず受注金額だけで判定する',
          '得意先ごとの与信限度額を毎日自動で変更する',
        ],
        correctIndex: 0,
        explanation: '動的チェックは、期間の範囲を超えた先の受注を与信残高から除きます。数か月先の受注まで含めると与信枠が不必要に埋まってしまうためです。',
      },
      {
        type: 'ox',
        question: '与信ブロックが解除されるまで、その受注から出荷伝票を作成することはできない。',
        correct: true,
        explanation: '正しいです。与信ブロックは後続の出荷を止めるための仕組みで、与信担当者が確認して解除すると出荷に進めます。',
      },
    ],
    'returns-credit': [
      {
        type: 'four-choice',
        question: '返品やクレジットメモ依頼の原因（品質不良、数量違いなど）を記録し、分析や統制に使う項目はどれか。',
        choices: ['受注理由', '拒否理由', '出荷条件', '得意先グループ'],
        correctIndex: 0,
        explanation: '受注理由（Order Reason）です。返品やクレジットメモの理由を記録しておくと、原因の傾向を分析したり、理由によって必須入力を制御したりできます。',
      },
      {
        type: 'ox',
        question: '請求伝票をVF11で取り消すと取消伝票が作成され、元の請求伝票は削除されずに残る。',
        correct: true,
        explanation: '正しいです。取消は元の伝票を消すのではなく、反対の取消伝票を作成します。会計伝票も逆仕訳され、監査証跡が残ります。',
      },
      {
        type: 'four-choice',
        question: 'クレジットメモ依頼に既定で請求ブロックを付ける目的として最も適切なものはどれか。',
        choices: ['内容を承認する前に返金の伝票が発行されるのを防ぐため', '在庫を自動で返品保留にするため', '得意先の与信限度額を上げるため', '価格決定をやり直すため'],
        correctIndex: 0,
        explanation: '返金は会社のお金が出ていく取引なので、承認者が内容を確認してブロックを解除するまでクレジットメモを発行できないようにします。',
      },
      {
        type: 'ox',
        question: '請求伝票を取り消した後は、元の出荷伝票を参照して、あらためて請求伝票を作成できる。',
        correct: true,
        explanation: '正しいです。取消によって出荷伝票の請求ステータスが未請求に戻るため、誤りを直したうえで再度請求できます。',
      },
    ],
    'billing-period-end': [
      {
        type: 'four-choice',
        question: '売上の期間帰属を確認するために、月末に特に注意して確認すべき伝票の状態はどれか。',
        choices: ['出庫転記済みで未請求の出荷伝票', '有効期限切れの見積', '拒否理由が設定された照会', '作成済みの条件レコード'],
        correctIndex: 0,
        explanation: '出庫転記済みで未請求の出荷は、売上を計上すべき期間に請求が漏れている可能性があります。月末に洗い出して、請求の漏れや期ずれを防ぎます。',
      },
      {
        type: 'four-choice',
        question: '会計への転記でエラーになった請求伝票を一覧し、再度会計に引き渡すトランザクションコードはどれか。',
        choices: ['VFX3', 'VF04', 'VF11', 'VKM1'],
        correctIndex: 0,
        explanation: 'VFX3は、会計転記がブロックされた請求伝票の一覧と再引き渡しに使います。VF04は請求対象の一覧、VF11は請求伝票の取消、VKM1は与信ブロックの解除です。',
      },
      {
        type: 'ox',
        question: '必須項目が未入力の不完全な受注は、設定によって出荷や請求に進めないようにできる。',
        correct: true,
        explanation: '正しいです。不完全ログの設定で、どの項目が欠けていると出荷や請求を止めるかを決められます。',
      },
      {
        type: 'ox',
        question: 'V.02は、不完全な受注伝票を一覧表示して確認するために使えるトランザクションである。',
        correct: true,
        explanation: '正しいです。不完全な伝票を定期的に確認しないと、出荷や請求が止まったまま気づかれない原因になります。',
      },
    ],
  },
  en: {
    'sd-overview': [
      {
        type: 'four-choice',
        question: 'What is the mechanism that links inquiries, quotations, orders, deliveries and billing documents to the documents before and after them?',
        choices: ['Document flow', 'Copy control', 'Condition technique', 'Output determination'],
        correctIndex: 0,
        explanation: 'Document flow. It shows which deliveries and invoices came from which order, so you can see where processing has stopped.',
      },
      {
        type: 'four-choice',
        question: 'What are the three levels of an SD document such as a sales order?',
        choices: ['Header, item and schedule line', 'Company code, plant and storage location', 'Sales organisation, distribution channel and division', 'Customer, material and condition record'],
        correctIndex: 0,
        explanation: 'A sales order has a header (customer and document-wide data), items (per material) and schedule lines (how much is delivered when).',
      },
      {
        type: 'four-choice',
        question: 'Which entry is typically posted in FI when a billing document is released to accounting?',
        choices: ['Debit receivables / credit revenue', 'Debit cost of goods sold / credit inventory', 'Debit inventory / credit GR/IR', 'Debit cash / credit receivables'],
        correctIndex: 0,
        explanation: 'Billing posts receivables and revenue. Cost of goods sold against inventory is posted at goods issue, and cash against receivables at payment.',
      },
      {
        type: 'ox',
        question: 'Document flow lets you trace from a sales order to the deliveries, billing documents and accounting documents created from it.',
        correct: true,
        explanation: 'Correct. Document flow can be displayed from orders, deliveries and invoices, showing at a glance how far processing has gone.',
      },
    ],
    'customer-master': [
      {
        type: 'four-choice',
        question: 'What are roles such as sold-to party, ship-to party, bill-to party and payer called?',
        choices: ['Partner functions', 'Customer account groups', 'Sales areas', 'Customer groups'],
        correctIndex: 0,
        explanation: 'Partner functions. A head office ordering, a factory receiving and an accounts department being billed can each be a different customer.',
      },
      {
        type: 'ox',
        question: 'One customer can act as sold-to, ship-to, bill-to and payer all at once.',
        correct: true,
        explanation: 'Correct. For smaller customers the same account usually takes all four roles, though separate customers can be assigned per role.',
      },
      {
        type: 'four-choice',
        question: 'What does a customer account group control?',
        choices: ['The customer number range and field control on the master screen', 'The prices applied to the customer', 'The credit limit', 'Shipping point determination'],
        correctIndex: 0,
        explanation: 'The account group controls the number range and which fields are required, optional or hidden, and groups are often split by use such as ship-to only.',
      },
      {
        type: 'four-choice',
        question: 'Which master record holds a customer’s own material number and delivery terms specific to a customer and material?',
        choices: ['Customer-material info record', 'Purchasing info record', 'Condition record', 'Batch master'],
        correctIndex: 0,
        explanation: 'The customer-material info record, which lets orders be entered with the customer’s material number and holds settings such as delivery tolerances.',
      },
    ],
    'sales-order': [
      {
        type: 'four-choice',
        question: 'Which of these is not determined automatically when a sales order is created?',
        choices: ['Price', 'Item category', 'Shipping point', 'Quantity actually picked'],
        correctIndex: 3,
        explanation: 'Picked quantity is recorded later on the delivery. Price, item category, shipping point and confirmed dates are determined at order entry.',
      },
      {
        type: 'four-choice',
        question: 'Which is the standard item category for a normal item on a standard order?',
        choices: ['TAN', 'TAS', 'TANN', 'REN'],
        correctIndex: 0,
        explanation: 'TAN is the standard item. TAS is a third-party item, TANN a free-of-charge item and REN a returns item.',
      },
      {
        type: 'ox',
        question: 'Besides an overall status, a sales order carries separate statuses for delivery, billing, credit and so on.',
        correct: true,
        explanation: 'Correct. The individual statuses reveal situations such as partially delivered but not yet billed.',
      },
      {
        type: 'ox',
        question: 'If the ATP check can confirm only part of the quantity, the unconfirmed part cannot be entered and is deleted automatically.',
        correct: false,
        explanation: 'Incorrect. Confirmed and unconfirmed quantities are split across schedule lines with different dates; the shortfall is confirmed later or stays unconfirmed.',
      },
    ],
    'shipping-billing': [
      {
        type: 'four-choice',
        question: 'Which transaction creates an outbound delivery with reference to a sales order?',
        choices: ['VL01N', 'VF01', 'VA01', 'VL02N'],
        correctIndex: 0,
        explanation: 'VL01N creates deliveries. VF01 creates billing documents, VA01 creates sales orders and VL02N changes deliveries, including posting goods issue.',
      },
      {
        type: 'four-choice',
        question: 'When can several deliveries be combined into one billing document?',
        choices: ['When the billing header split criteria, such as payer, billing date and payment terms, are the same', 'When the materials delivered are the same', 'When the shipping points differ', 'When the same user created the deliveries'],
        correctIndex: 0,
        explanation: 'If the fields that go into the billing header, such as payer, billing date and payment terms, match, the deliveries are combined; any difference splits the invoice.',
      },
      {
        type: 'ox',
        question: 'One delivery can never result in more than one billing document.',
        correct: false,
        explanation: 'Incorrect. If split criteria differ, for example items with different payment terms, one delivery produces several billing documents.',
      },
      {
        type: 'four-choice',
        question: 'What is an invoice list?',
        choices: [
          'A document that combines a period’s billing documents for a bill-to party so they can be sent together',
          'A list of materials to pick before shipping',
          'A list of credit-blocked orders',
          'A list of condition records',
        ],
        correctIndex: 0,
        explanation: 'An invoice list bundles several billing documents, for example monthly, for customers who want them sent together rather than one by one.',
      },
    ],
    'sales-org': [
      {
        type: 'four-choice',
        question: 'Which organisational unit handles shipping and is the unit in which deliveries are created?',
        choices: ['Shipping point', 'Sales office', 'Distribution channel', 'Sales group'],
        correctIndex: 0,
        explanation: 'The shipping point. Deliveries are created per shipping point, which is set up per loading area or shipping method such as truck or parcel.',
      },
      {
        type: 'ox',
        question: 'Shipping points are assigned to plants, and one plant can have several shipping points.',
        correct: true,
        explanation: 'Correct. A single factory may have separate loading areas for trucks and parcels, each its own shipping point.',
      },
      {
        type: 'four-choice',
        question: 'How are the sales office and sales group related?',
        choices: [
          'A sales office is a regional base such as a branch, and a sales group is a sales team within it',
          'A sales group is assigned to a company code and a sales office to a plant',
          'They are two names for the same thing',
          'A sales group sits below a shipping point',
        ],
        correctIndex: 0,
        explanation: 'A sales office represents a branch or regional office and a sales group the team selling within it. Both are optional units describing the internal sales organisation.',
      },
      {
        type: 'four-choice',
        question: 'What is a sales district mainly used for?',
        choices: ['Classifying customers by region for analysis and pricing', 'Representing where stock is stored', 'Representing an independent accounting unit', 'Representing the unit that creates deliveries'],
        correctIndex: 0,
        explanation: 'A sales district is a regional grouping set on the customer master, used for regional sales analysis and region-specific price condition records.',
      },
    ],
    pricing: [
      {
        type: 'four-choice',
        question: 'Which of these is not one of the four elements of the condition technique?',
        choices: ['Condition type', 'Access sequence', 'Condition table', 'Posting key'],
        correctIndex: 3,
        explanation: 'The condition technique consists of condition types, access sequences, condition tables and condition records. A posting key is FI’s debit/credit code.',
      },
      {
        type: 'ox',
        question: 'A condition type defines the calculation type, such as fixed amount, percentage or per-unit value, and whether the value may be overwritten manually on the order.',
        correct: true,
        explanation: 'Correct. A price such as PR00 is an amount and a discount a percentage, with calculation and changeability defined per condition type.',
      },
      {
        type: 'four-choice',
        question: 'Why do condition records have validity periods?',
        choices: ['So price changes can be entered in advance and apply automatically from a given date', 'So condition records cannot be deleted', 'So the condition type can be changed', 'So orders cannot be saved'],
        correctIndex: 0,
        explanation: 'Validity periods let a new price be entered ahead of, say, 1 April, and the right record is picked according to the order’s pricing date.',
      },
      {
        type: 'four-choice',
        question: 'What happens when the exclusive indicator is set in an access sequence?',
        choices: ['Once a condition record is found, the search stops', 'All tables are searched and the lowest price wins', 'Records found are ignored', 'Only manual prices are accepted'],
        correctIndex: 0,
        explanation: 'With the exclusive indicator the first record found is used and the search ends. Ordering accesses from most to least specific gives the most specific price priority.',
      },
    ],
    'inquiry-quotation': [
      {
        type: 'four-choice',
        question: 'Which field records, per item, why a quotation did not become an order?',
        choices: ['Reason for rejection', 'Order reason', 'Billing block', 'Delivery block'],
        correctIndex: 0,
        explanation: 'The reason for rejection. Recording reasons such as losing on price supports analysis of lost business.',
      },
      {
        type: 'ox',
        question: 'Setting a reason for rejection on a quotation item excludes it from copying to orders and stops it being treated as open.',
        correct: true,
        explanation: 'Correct. Rejected items count as completed and drop out of open quotation lists.',
      },
      {
        type: 'four-choice',
        question: 'How is a sales order normally created from a quotation the customer accepted?',
        choices: ['Create the order in VA01 with reference to the quotation', 'Change the quotation in VA22 and it becomes an order', 'Create a billing document from the quotation in VF01', 'Create a delivery from the quotation in VL01N'],
        correctIndex: 0,
        explanation: 'Creating the order in VA01 with reference to the quotation copies materials and prices according to copy control and records the document flow.',
      },
      {
        type: 'ox',
        question: 'An inquiry records a customer’s question so that prices and delivery dates can be given in reply.',
        correct: true,
        explanation: 'Correct. An inquiry is a non-binding record of interest, while a quotation offers terms. Both record pre-sales activity for later analysis.',
      },
    ],
    'credit-management': [
      {
        type: 'four-choice',
        question: 'Which of these is not normally part of the credit exposure compared with the credit limit?',
        choices: ['Open receivables', 'Delivered but unbilled value', 'Undelivered order value', 'Valid quotation value'],
        correctIndex: 3,
        explanation: 'Quotations are not orders yet, so they are excluded. Receivables, unbilled deliveries and undelivered orders together make up the exposure.',
      },
      {
        type: 'ox',
        question: 'Besides comparing against the limit, credit checks can also look for items overdue beyond a set number of days.',
        correct: true,
        explanation: 'Correct. This stops deliveries to customers who are paying late even when their limit still has room.',
      },
      {
        type: 'four-choice',
        question: 'Which statement describes a dynamic credit check correctly?',
        choices: [
          'Only orders due for delivery within a set future horizon count towards the exposure',
          'All undelivered orders count regardless of date',
          'Receivables are ignored and only order values count',
          'Credit limits are changed automatically every day',
        ],
        correctIndex: 0,
        explanation: 'A dynamic check leaves out orders beyond the horizon, since counting orders months ahead would use up the limit unnecessarily.',
      },
      {
        type: 'ox',
        question: 'No delivery can be created from a sales order until its credit block is released.',
        correct: true,
        explanation: 'Correct. A credit block exists to stop delivery; once the credit controller reviews and releases it, shipping can proceed.',
      },
    ],
    'returns-credit': [
      {
        type: 'four-choice',
        question: 'Which field records the cause of a return or credit memo request, such as a defect or wrong quantity, for analysis and control?',
        choices: ['Order reason', 'Reason for rejection', 'Shipping conditions', 'Customer group'],
        correctIndex: 0,
        explanation: 'The order reason. Recording it shows patterns in causes and can drive which fields are required.',
      },
      {
        type: 'ox',
        question: 'Cancelling a billing document in VF11 creates a cancellation document, and the original billing document remains rather than being deleted.',
        correct: true,
        explanation: 'Correct. Cancellation creates an opposite document rather than removing the original; the accounting document is reversed too, preserving the audit trail.',
      },
      {
        type: 'four-choice',
        question: 'Why does a credit memo request carry a billing block by default?',
        choices: ['To stop a refund being issued before it is approved', 'To move stock into blocked returns automatically', 'To raise the customer’s credit limit', 'To redo pricing'],
        correctIndex: 0,
        explanation: 'A refund means money leaving the company, so the credit memo cannot be issued until an approver reviews it and removes the block.',
      },
      {
        type: 'ox',
        question: 'After a billing document is cancelled, a new billing document can be created with reference to the original delivery.',
        correct: true,
        explanation: 'Correct. Cancellation resets the delivery’s billing status to not billed, so it can be billed again once the error is fixed.',
      },
    ],
    'billing-period-end': [
      {
        type: 'four-choice',
        question: 'To check that revenue falls in the right period, which documents need particular attention at month end?',
        choices: ['Deliveries with goods issue posted but not yet billed', 'Expired quotations', 'Inquiries with a reason for rejection', 'Newly created condition records'],
        correctIndex: 0,
        explanation: 'Goods issued but not billed may mean revenue is missing from the period it belongs to. Finding them at month end prevents missed or late billing.',
      },
      {
        type: 'four-choice',
        question: 'Which transaction lists billing documents that failed to post to accounting and releases them again?',
        choices: ['VFX3', 'VF04', 'VF11', 'VKM1'],
        correctIndex: 0,
        explanation: 'VFX3 lists billing documents blocked from accounting and passes them on again. VF04 is the billing due list, VF11 cancels billing documents and VKM1 releases credit blocks.',
      },
      {
        type: 'ox',
        question: 'Configuration can stop an incomplete sales order, one missing required data, from going on to delivery or billing.',
        correct: true,
        explanation: 'Correct. The incompletion procedure defines which missing fields block delivery or billing.',
      },
      {
        type: 'ox',
        question: 'V.02 can be used to list and review incomplete sales documents.',
        correct: true,
        explanation: 'Correct. Without regular review, incomplete documents can quietly hold up delivery and billing.',
      },
    ],
  },
};
