import type { ModuleContent } from '../learning-types';

export const sd: Record<'ja' | 'en', ModuleContent> = {
  ja: {
    id: 'sd',
    title: 'SD（販売管理）',
    description: '受注から請求までの販売プロセスを学習します。',
    sections: [
      {
        id: 'sd-overview',
        title: 'SDモジュール概要',
        content: [
          'SD（Sales and Distribution）は受注・出荷・請求の一連の販売プロセスを管理するモジュールです。',
          '主要プロセスはOTC（Order to Cash）と呼ばれ、照会→見積→受注→出荷→請求→入金の流れで構成されます。',
          'SDはFI（売掛金）・MM（在庫）・PP（生産計画）と密接に連携します。',
          '組織構造として販売組織・流通チャネル・製品部門の組み合わせが販売エリアを形成します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'OTC（Order to Cash）プロセスの正しい順序はどれですか？',
            choices: [
              '受注→照会→見積→出荷→請求',
              '照会→見積→受注→出荷→請求',
              '見積→照会→受注→請求→出荷',
              '受注→見積→照会→出荷→請求',
            ],
            correctIndex: 1,
            explanation: 'OTCプロセスは照会→見積→受注→出荷→請求の順に進みます。',
          },
          {
            type: 'ox',
            question: 'SDモジュールは財務会計（FI）と連携しない。',
            correct: false,
            explanation: 'SDの請求処理はFIの売掛金に自動転記されます。',
          },
          {
            type: 'four-choice',
            question: '販売エリアを構成する3つの組織要素はどれですか？',
            choices: [
              '会社コード・プラント・保管場所',
              '販売組織・流通チャネル・製品部門',
              '購買組織・購買グループ・会社コード',
              '原価センタ・利益センタ・事業部',
            ],
            correctIndex: 1,
            explanation: '販売エリア＝販売組織＋流通チャネル＋製品部門の組み合わせです。',
          },
          {
            type: 'ox',
            question: '一つの販売組織は複数の会社コードに割り当てることができる。',
            correct: false,
            explanation: '販売組織は必ず1つの会社コードに割り当てられます。',
          },
          {
            type: 'four-choice',
            question: 'SDモジュールで受注を作成するトランザクションコードはどれですか？',
            choices: ['ME21N', 'VA01', 'VF01', 'VL01N'],
            correctIndex: 1,
            explanation: 'VA01が受注（Sales Order）の作成に使用されます。',
          },
          {
            type: 'ordering',
            question: 'SDのOTCプロセスを正しい順序に並べてください。',
            items: ['請求', '受注', '出荷', '入金', '照会・見積'],
            correctOrder: [4, 1, 2, 0, 3],
            explanation: '照会・見積→受注→出荷→請求→入金の順です。',
          },
        ],
      },
      {
        id: 'customer-master',
        title: '得意先マスタ',
        content: [
          '得意先マスタは販売取引の相手先情報を管理し、一般データ・会社コードデータ・販売エリアデータの3階層で構成されます。',
          '一般データには名称・住所など、会社コードデータには与信・照合勘定など、販売エリアデータには価格グループ・出荷条件などが含まれます。',
          'トランザクションVD01（販売エリアのみ）またはXD01（全データ）で作成します。',
          '得意先グループは得意先を分類し、勘定決定や統計に利用されます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '得意先マスタを全データ（一般・会社コード・販売エリア）で作成するトランザクションはどれですか？',
            choices: ['VD01', 'XD01', 'FD01', 'VA01'],
            correctIndex: 1,
            explanation: 'XD01は全レベルのデータを一括作成します。VD01は販売エリアデータのみです。',
          },
          {
            type: 'ox',
            question: '得意先マスタの一般データは複数の会社コード・販売エリアで共有される。',
            correct: true,
            explanation: '一般データ（名称・住所等）は会社コードや販売エリアをまたいで共有されます。',
          },
          {
            type: 'four-choice',
            question: '得意先マスタの販売エリアデータに含まれる項目はどれですか？',
            choices: [
              '照合勘定',
              '支払条件（財務用）',
              '出荷条件',
              '銀行口座',
            ],
            correctIndex: 2,
            explanation: '出荷条件は販売エリアデータに属します。照合勘定・支払条件（財務）・銀行口座は会社コードデータです。',
          },
          {
            type: 'ox',
            question: '得意先グループは与信管理の与信限度額を直接決定する。',
            correct: false,
            explanation: '得意先グループは分類目的で使用されます。与信限度額はFD32で個別に設定します。',
          },
          {
            type: 'four-choice',
            question: '得意先マスタで設定する「照合勘定」はどのデータレベルですか？',
            choices: ['SDデータ', '一般データ', '会社コードデータ', '販売エリアデータ'],
            correctIndex: 2,
            explanation: '照合勘定（売掛金勘定）は会社コードデータに含まれます。',
          },
          {
            type: 'ordering',
            question: '得意先マスタの階層を上位から正しい順序に並べてください。',
            items: ['販売エリアデータ', '会社コードデータ', '一般データ'],
            correctOrder: [2, 1, 0],
            explanation: '一般データ→会社コードデータ→販売エリアデータの階層構造です。',
          },
        ],
      },
      {
        id: 'sales-order',
        title: '受注処理',
        content: [
          '受注（Sales Order）はVA01で作成し、得意先マスタ・品目マスタ・価格条件から自動的にデータが引き継がれます。',
          '受注タイプ（OR：標準受注、RE：返品など）によって後続の処理フローが決まります。',
          'アベイラビリティチェック（ATP）は受注登録時に在庫確認を行い、確認納期を設定します。',
          '受注には明細カテゴリが割り当てられ、出荷・請求の動作を制御します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '標準受注の受注タイプはどれですか？',
            choices: ['RE', 'CR', 'OR', 'DR'],
            correctIndex: 2,
            explanation: 'OR（Order）が標準受注タイプです。REは返品、CRはクレジットメモ依頼です。',
          },
          {
            type: 'ox',
            question: 'ATPチェック（アベイラビリティチェック）は受注時に在庫の引き当てを行う。',
            correct: true,
            explanation: 'ATPチェックにより在庫・生産計画を考慮した確認納期が受注明細に設定されます。',
          },
          {
            type: 'four-choice',
            question: '受注の不完全ログ（Incompletion Log）の目的は何ですか？',
            choices: [
              '在庫不足を警告する',
              '後続処理（出荷・請求）に必要なデータが不足している場合に通知する',
              '与信限度超過を通知する',
              '価格エラーを検出する',
            ],
            correctIndex: 1,
            explanation: '不完全ログは必須フィールドが未入力の場合に警告し、後続処理のブロックを防ぎます。',
          },
          {
            type: 'ox',
            question: '受注明細カテゴリは受注タイプと品目カテゴリグループから自動決定される。',
            correct: true,
            explanation: '明細カテゴリは受注タイプと品目カテゴリグループの組み合わせテーブルから自動決定されます。',
          },
          {
            type: 'four-choice',
            question: 'VA02は何のトランザクションですか？',
            choices: ['受注の作成', '受注の照会', '受注の変更', '受注の削除'],
            correctIndex: 2,
            explanation: 'VA02は受注の変更、VA01は作成、VA03は照会です。',
          },
          {
            type: 'ordering',
            question: '受注処理の流れを正しい順序に並べてください。',
            items: ['ATPチェック', '受注保存', '得意先・品目入力', '価格決定', '出荷スケジュール'],
            correctOrder: [2, 3, 0, 4, 1],
            explanation: '得意先・品目入力→価格決定→ATPチェック→出荷スケジュール→受注保存の順です。',
          },
        ],
      },
      {
        id: 'shipping-billing',
        title: '出荷・請求処理',
        content: [
          '出荷処理はVL01Nで出荷伝票を作成し、ピッキング・梱包・貨物実行（PGI）の手順で進みます。',
          'PGI（Post Goods Issue：出荷確定）により在庫が減少しMMと連携、売上原価が計上されます。',
          '請求処理はVF01で請求書を作成し、FIへの売掛金転記が自動実行されます。',
          'VF04は請求保留リストから一括請求を処理するトランザクションです。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'PGI（出荷確定）が実行されると何が発生しますか？',
            choices: [
              '売掛金が計上される',
              '在庫が減少し売上原価が計上される',
              '与信チェックが実行される',
              '請求書が作成される',
            ],
            correctIndex: 1,
            explanation: 'PGIにより在庫（MM）が減少し、CO側に売上原価が計上されます。',
          },
          {
            type: 'ox',
            question: '出荷伝票の作成トランザクションはVF01である。',
            correct: false,
            explanation: 'VF01は請求書の作成です。出荷伝票の作成はVL01Nです。',
          },
          {
            type: 'four-choice',
            question: '請求書の一括作成に使用するトランザクションはどれですか？',
            choices: ['VF01', 'VF02', 'VF04', 'VL01N'],
            correctIndex: 2,
            explanation: 'VF04（Billing Due List）から複数の出荷をまとめて請求書に変換できます。',
          },
          {
            type: 'ox',
            question: 'ピッキングは出荷伝票作成後、PGI前に行われる。',
            correct: true,
            explanation: '出荷プロセスは出荷伝票作成→ピッキング→梱包→PGIの順です。',
          },
          {
            type: 'four-choice',
            question: '請求書をFIに転記する際に使用される標準請求タイプはどれですか？',
            choices: ['F1（標準請求）', 'OR（標準受注）', 'RE（返品）', 'LF（出荷）'],
            correctIndex: 0,
            explanation: 'F1が標準請求書タイプです。FIへの転記はこの請求タイプ設定に基づきます。',
          },
          {
            type: 'ordering',
            question: '出荷から請求までの流れを正しい順序に並べてください。',
            items: ['PGI（出荷確定）', '請求書作成', 'ピッキング', 'FI転記', '出荷伝票作成'],
            correctOrder: [4, 2, 0, 1, 3],
            explanation: '出荷伝票作成→ピッキング→PGI→請求書作成→FI転記の順です。',
          },
        ],
      },
      {
        id: 'sales-org',
        title: '組織構造と販売エリア',
        content: [
          '販売組織は製品・サービスの販売責任を持つ組織単位で、必ず1つの会社コードに割り当てられます。',
          '流通チャネルは販売ルート（直販・代理店・小売等）を区別し、製品部門は製品ラインを分類します。',
          'プラントは出荷元として販売組織に割り当てられ、在庫管理・出荷処理に使用されます。',
          '販売オフィス・販売グループは任意の組織要素で、担当者レベルの管理に使用します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '販売組織の説明として正しいものはどれですか？',
            choices: [
              '複数の会社コードに割り当てられる',
              '製品・サービスの販売責任を持ち、1つの会社コードに割り当てられる',
              '流通チャネルと製品部門の組み合わせで定義される',
              '任意の組織要素でレポート目的にのみ使用される',
            ],
            correctIndex: 1,
            explanation: '販売組織は1つの会社コードにのみ割り当て可能です。',
          },
          {
            type: 'ox',
            question: '同じプラントを複数の販売組織に割り当てることができる。',
            correct: true,
            explanation: '1つのプラントは複数の販売組織に割り当てることが可能です。',
          },
          {
            type: 'four-choice',
            question: '流通チャネルの主な目的はどれですか？',
            choices: [
              '製品ラインを分類する',
              '販売ルート（直販・代理店等）を区別する',
              '出荷元の在庫場所を特定する',
              '担当営業員を管理する',
            ],
            correctIndex: 1,
            explanation: '流通チャネルは販売ルートを区別し、価格・得意先マスタの共有設定に使用します。',
          },
          {
            type: 'ox',
            question: '販売オフィスと販売グループはSAPシステムで必須の組織要素である。',
            correct: false,
            explanation: '販売オフィスと販売グループは任意要素です。販売エリア（販売組織・流通チャネル・製品部門）が必須です。',
          },
          {
            type: 'four-choice',
            question: '販売エリアの正しい定義はどれですか？',
            choices: [
              '会社コード＋プラント＋保管場所',
              '販売組織＋流通チャネル＋製品部門',
              '販売組織＋販売オフィス＋販売グループ',
              '得意先＋販売組織＋流通チャネル',
            ],
            correctIndex: 1,
            explanation: '販売エリア＝販売組織＋流通チャネル＋製品部門の3要素の組み合わせです。',
          },
          {
            type: 'ordering',
            question: 'SD組織階層を上位から正しい順序に並べてください。',
            items: ['製品部門', '流通チャネル', '販売グループ', '販売組織', '販売オフィス'],
            correctOrder: [3, 1, 0, 4, 2],
            explanation: '販売組織→流通チャネル→製品部門→販売オフィス→販売グループの順です。',
          },
        ],
      },
      {
        id: 'pricing',
        title: '価格条件と価格設定手順',
        content: [
          '価格設定手順（Pricing Procedure）は価格・割引・割増・税金の計算順序を定義します。',
          '条件タイプ（PR00：標準価格、K004：品目割引等）ごとにアクセスシーケンスが設定されます。',
          'アクセスシーケンスは条件テーブルを検索する順序を定義し、最初にヒットした条件レコードが使用されます。',
          'VK11で条件レコードを登録し、受注時に自動的に価格が決定されます。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '価格設定手順の目的はどれですか？',
            choices: [
              '得意先の与信限度を決定する',
              '価格・割引・税金の計算順序を定義する',
              '出荷条件を決定する',
              '請求タイプを決定する',
            ],
            correctIndex: 1,
            explanation: '価格設定手順は各条件タイプの計算順序・加減算・必須/オプションを定義します。',
          },
          {
            type: 'ox',
            question: '条件レコードの登録トランザクションはVK11である。',
            correct: true,
            explanation: 'VK11で価格・割引等の条件レコードを登録します。VK12が変更、VK13が照会です。',
          },
          {
            type: 'four-choice',
            question: '標準価格の条件タイプはどれですか？',
            choices: ['K004', 'PR00', 'MWST', 'RA01'],
            correctIndex: 1,
            explanation: 'PR00が標準品目価格の条件タイプです。K004は品目割引、MWSTは税金です。',
          },
          {
            type: 'ox',
            question: 'アクセスシーケンスは条件テーブルを下位から上位へ検索する。',
            correct: false,
            explanation: 'アクセスシーケンスは定義された順序（通常は詳細→汎用）で条件テーブルを検索し、最初のヒットで停止します。',
          },
          {
            type: 'four-choice',
            question: '価格設定手順はどの組み合わせで決定されますか？',
            choices: [
              '販売組織＋流通チャネル＋得意先価格設定手順指示子＋伝票価格設定手順指示子',
              '会社コード＋販売組織',
              '品目カテゴリ＋得意先グループ',
              '受注タイプ＋請求タイプ',
            ],
            correctIndex: 0,
            explanation: '価格設定手順は販売エリア（販売組織・流通チャネル）＋得意先側と伝票側の価格設定手順指示子の組み合わせで決定されます。',
          },
          {
            type: 'ordering',
            question: '価格決定のロジックを正しい順序に並べてください。',
            items: ['条件レコードから金額取得', '条件タイプ確認', 'アクセスシーケンスで検索', '価格設定手順の適用', '最終価格の算出'],
            correctOrder: [3, 1, 2, 0, 4],
            explanation: '価格設定手順の適用→条件タイプ確認→アクセスシーケンスで検索→条件レコードから金額取得→最終価格算出の順です。',
          },
        ],
      },
      {
        id: 'inquiry-quotation',
        title: '照会・見積処理',
        content: [
          '照会（Inquiry）はVA11で作成し、得意先からの情報収集段階の伝票です。受注には影響しません。',
          '見積（Quotation）はVA21で作成し、価格・納期を確約する伝票で有効期限が設定できます。',
          '照会・見積から受注へのコピー機能により、データの再入力を省略できます。',
          'コピー管理（Copy Control）はVOVAで設定し、元伝票タイプから後続伝票タイプへのデータ引継ぎルールを定義します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '見積（Quotation）を作成するトランザクションはどれですか？',
            choices: ['VA11', 'VA21', 'VA01', 'VK11'],
            correctIndex: 1,
            explanation: 'VA21が見積の作成です。VA11は照会、VA01は受注の作成です。',
          },
          {
            type: 'ox',
            question: '照会（Inquiry）は在庫のATPチェックに影響を与える。',
            correct: false,
            explanation: '照会は情報収集段階の伝票であり、在庫引当・ATPチェックには影響しません。',
          },
          {
            type: 'four-choice',
            question: '見積に設定できる「有効期限」の目的はどれですか？',
            choices: [
              '在庫の引当期間を決める',
              '提示した価格・条件が有効な期間を定める',
              '与信チェックの期間を設定する',
              '支払期限を設定する',
            ],
            correctIndex: 1,
            explanation: '有効期限内のみ見積条件（価格・納期等）が有効であることを得意先に示します。',
          },
          {
            type: 'ox',
            question: 'コピー管理（Copy Control）によって、見積から受注へデータを引き継ぐことができる。',
            correct: true,
            explanation: 'コピー管理を設定することで、見積の品目・価格等を受注に自動引継ぎできます。',
          },
          {
            type: 'four-choice',
            question: '照会の伝票タイプはどれですか？',
            choices: ['OR', 'QT', 'IN', 'RE'],
            correctIndex: 2,
            explanation: 'INが照会（Inquiry）の伝票タイプです。QTは見積（Quotation）、ORは受注です。',
          },
          {
            type: 'ordering',
            question: 'プリセールスから受注までの流れを正しい順序に並べてください。',
            items: ['見積（VA21）', '受注（VA01）', '照会（VA11）', '出荷処理', '得意先へ提案'],
            correctOrder: [2, 4, 0, 1, 3],
            explanation: '照会→得意先へ提案→見積→受注→出荷処理の順です。',
          },
        ],
      },
      {
        id: 'credit-management',
        title: '与信管理',
        content: [
          '与信管理は得意先の信用リスクを管理し、与信限度超過時に受注・出荷をブロックします。',
          'FD32で与信限度額を設定し、与信管理グループ・与信エリアを使用して管理します。',
          'VKM1は与信ブロックされた受注を一覧表示し、担当者が手動で解除します。',
          'リスクカテゴリと与信管理グループの組み合わせで与信チェックの動作を制御します。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '与信限度額を設定するトランザクションはどれですか？',
            choices: ['XD01', 'FD32', 'VKM1', 'VA01'],
            correctIndex: 1,
            explanation: 'FD32（Customer Credit Management）で与信限度額と与信エリアを設定します。',
          },
          {
            type: 'ox',
            question: 'VKM1は与信ブロックされた受注を一覧表示するトランザクションである。',
            correct: true,
            explanation: 'VKM1でブロックされた受注を確認し、与信担当者が解除または拒否できます。',
          },
          {
            type: 'four-choice',
            question: '与信チェックが実行されるタイミングとして正しくないものはどれですか？',
            choices: ['受注保存時', '出荷伝票作成時', 'ピッキング完了時', '与信エリアの超過検知時'],
            correctIndex: 2,
            explanation: 'ピッキング完了時には与信チェックは通常実行されません。受注・出荷作成時が主なタイミングです。',
          },
          {
            type: 'ox',
            question: '与信エリアは会社コードと常に一致する。',
            correct: false,
            explanation: '与信エリアは会社コードと独立して設定でき、複数会社コードをまたいだ与信管理も可能です。',
          },
          {
            type: 'four-choice',
            question: '与信ブロックが設定された受注の状態はどうなりますか？',
            choices: [
              '受注が自動キャンセルされる',
              '出荷処理がブロックされる',
              '請求処理のみブロックされる',
              '受注が自動分割される',
            ],
            correctIndex: 1,
            explanation: '与信ブロック時は後続の出荷処理が停止されます。VKM1で解除するまで出荷できません。',
          },
          {
            type: 'ordering',
            question: '与信超過時の処理フローを正しい順序に並べてください。',
            items: ['VKM1で解除', '与信ブロック設定', '受注作成', '出荷再開', '与信チェック実行'],
            correctOrder: [2, 4, 1, 0, 3],
            explanation: '受注作成→与信チェック実行→与信ブロック設定→VKM1で解除→出荷再開の順です。',
          },
        ],
      },
      {
        id: 'returns-credit',
        title: '返品・クレジットメモ処理',
        content: [
          '返品受注はタイプRE（Returns）でVA01作成し、元受注または請求書を参照して処理します。',
          '返品入庫はVL01Nで返品出荷伝票を作成し、PGR（Post Goods Receipt）で在庫を戻します。',
          'クレジットメモ依頼（CR）は金額調整のみ行い、在庫の物理的な返却は伴いません。',
          'デビットメモ依頼（DR）は追加請求に使用し、クレジットメモの逆処理です。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: '返品受注の伝票タイプはどれですか？',
            choices: ['OR', 'CR', 'RE', 'DR'],
            correctIndex: 2,
            explanation: 'RE（Returns）が返品受注タイプです。CRはクレジットメモ依頼、DRはデビットメモ依頼です。',
          },
          {
            type: 'ox',
            question: 'クレジットメモ依頼（CR）では物理的な在庫返却が発生する。',
            correct: false,
            explanation: 'CRは金額調整のみです。物理的な在庫返却が必要な場合は返品受注（RE）を使用します。',
          },
          {
            type: 'four-choice',
            question: '返品入庫（PGR）が実行されると在庫はどうなりますか？',
            choices: [
              '在庫が減少する',
              '在庫が増加する',
              '在庫に変動はない',
              '在庫がブロックされる',
            ],
            correctIndex: 1,
            explanation: 'PGR（Post Goods Receipt）により返品品が在庫に戻り、在庫が増加します。',
          },
          {
            type: 'ox',
            question: 'デビットメモ依頼（DR）は得意先への追加請求に使用する。',
            correct: true,
            explanation: 'DRは売値の訂正増額や追加費用請求に使用します。クレジットメモの逆方向の処理です。',
          },
          {
            type: 'four-choice',
            question: 'クレジットメモの承認前処理としてブロックをかける設定はどこで行いますか？',
            choices: [
              '得意先マスタ',
              '受注タイプの設定（VOV8）',
              '価格条件',
              '請求タイプ',
            ],
            correctIndex: 1,
            explanation: 'VOV8（受注タイプ設定）でクレジット/デビットメモ依頼の承認ブロックを設定します。',
          },
          {
            type: 'ordering',
            question: '返品プロセスを正しい順序に並べてください。',
            items: ['クレジットメモ発行', '返品出荷（VL01N）', '返品受注作成（RE）', '元伝票参照', 'PGR実行'],
            correctOrder: [3, 2, 1, 4, 0],
            explanation: '元伝票参照→返品受注作成→返品出荷→PGR実行→クレジットメモ発行の順です。',
          },
        ],
      },
      {
        id: 'billing-period-end',
        title: '請求一括処理・SD月次処理',
        content: [
          'VF04（Billing Due List）は出荷済みで未請求の伝票を一覧表示し、一括で請求書を作成します。',
          'VF11は請求書のキャンセルに使用し、逆仕訳がFIに自動転記されます。',
          '勘定決定（Account Determination）はコンディション技術を使用し、請求時のGL勘定を自動決定します。',
          'SD月次処理では未処理の出荷・請求の確認、売上レポートの確認、次期への繰越設定などを行います。',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'VF04の目的はどれですか？',
            choices: [
              '受注の一覧照会',
              '出荷済み未請求伝票の一括請求処理',
              '与信ブロックの解除',
              '価格条件の一括変更',
            ],
            correctIndex: 1,
            explanation: 'VF04（Billing Due List）で未請求の出荷をまとめて請求書に変換できます。',
          },
          {
            type: 'ox',
            question: 'VF11で請求書をキャンセルするとFIへの逆仕訳が自動的に行われる。',
            correct: true,
            explanation: 'VF11による請求キャンセルで、FIの売掛金転記が自動的に逆仕訳されます。',
          },
          {
            type: 'four-choice',
            question: '請求時にGL勘定を自動決定する仕組みはどれですか？',
            choices: [
              '勘定設定（Account Assignment）',
              '勘定決定（Account Determination）',
              '価格設定手順',
              '出荷条件',
            ],
            correctIndex: 1,
            explanation: '勘定決定はコンディション技術を使用し、売上・税金等のGL勘定を自動決定します。',
          },
          {
            type: 'ox',
            question: 'SDの月次処理では未処理の出荷・請求伝票を次月に繰り越すことが推奨される。',
            correct: false,
            explanation: '月次クローズ前に未処理の出荷・請求を完了させることが推奨されます。繰越は例外的な処置です。',
          },
          {
            type: 'four-choice',
            question: '勘定決定の条件タイプ「KOFI」は何を決定しますか？',
            choices: [
              '価格条件',
              '売上勘定',
              '与信限度',
              '出荷条件',
            ],
            correctIndex: 1,
            explanation: 'KOFIは売上（Revenue）勘定の決定に使用される勘定決定条件タイプです。',
          },
          {
            type: 'ordering',
            question: 'SD月次クローズの主要手順を正しい順序に並べてください。',
            items: ['売上レポート確認', '未処理請求の完了', '翌月設定の確認', '未処理出荷の完了', 'FI担当者へ引継ぎ'],
            correctOrder: [3, 1, 0, 4, 2],
            explanation: '未処理出荷の完了→未処理請求の完了→売上レポート確認→FI担当者へ引継ぎ→翌月設定の確認の順です。',
          },
        ],
      },
    ],
  },
  en: {
    id: 'sd',
    title: 'SD (Sales and Distribution)',
    description: 'Learn the sales process from order to billing.',
    sections: [
      {
        id: 'sd-overview',
        title: 'SD Module Overview',
        content: [
          'SD (Sales and Distribution) manages the end-to-end sales process: order receipt, shipping, and billing.',
          'The core process is called OTC (Order to Cash): Inquiry → Quotation → Sales Order → Delivery → Billing → Payment.',
          'SD integrates closely with FI (accounts receivable), MM (inventory), and PP (production planning).',
          'The organizational structure uses Sales Organization, Distribution Channel, and Division to form a Sales Area.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What is the correct order of the OTC (Order to Cash) process?',
            choices: [
              'Sales Order → Inquiry → Quotation → Delivery → Billing',
              'Inquiry → Quotation → Sales Order → Delivery → Billing',
              'Quotation → Inquiry → Sales Order → Billing → Delivery',
              'Sales Order → Quotation → Inquiry → Delivery → Billing',
            ],
            correctIndex: 1,
            explanation: 'The OTC process flows: Inquiry → Quotation → Sales Order → Delivery → Billing.',
          },
          {
            type: 'ox',
            question: 'The SD module does not integrate with Financial Accounting (FI).',
            correct: false,
            explanation: 'SD billing automatically posts to FI accounts receivable.',
          },
          {
            type: 'four-choice',
            question: 'Which three organizational elements form a Sales Area?',
            choices: [
              'Company Code, Plant, Storage Location',
              'Sales Organization, Distribution Channel, Division',
              'Purchasing Organization, Purchasing Group, Company Code',
              'Cost Center, Profit Center, Business Area',
            ],
            correctIndex: 1,
            explanation: 'Sales Area = Sales Organization + Distribution Channel + Division.',
          },
          {
            type: 'ox',
            question: 'One Sales Organization can be assigned to multiple Company Codes.',
            correct: false,
            explanation: 'A Sales Organization is assigned to exactly one Company Code.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction code is used to create a Sales Order in SD?',
            choices: ['ME21N', 'VA01', 'VF01', 'VL01N'],
            correctIndex: 1,
            explanation: 'VA01 is used to create Sales Orders.',
          },
          {
            type: 'ordering',
            question: 'Arrange the OTC process steps in the correct order.',
            items: ['Billing', 'Sales Order', 'Delivery', 'Payment', 'Inquiry/Quotation'],
            correctOrder: [4, 1, 2, 0, 3],
            explanation: 'Inquiry/Quotation → Sales Order → Delivery → Billing → Payment.',
          },
        ],
      },
      {
        id: 'customer-master',
        title: 'Customer Master',
        content: [
          'The Customer Master stores trading partner information in three levels: General Data, Company Code Data, and Sales Area Data.',
          'General Data holds name and address; Company Code Data holds reconciliation account; Sales Area Data holds pricing group and shipping conditions.',
          'Use VD01 (Sales Area only) or XD01 (all data) to create customer master records.',
          'The Customer Group classifies customers and is used in account determination and reporting.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction creates a customer master with all data (General, Company Code, and Sales Area)?',
            choices: ['VD01', 'XD01', 'FD01', 'VA01'],
            correctIndex: 1,
            explanation: 'XD01 creates all levels at once. VD01 creates only Sales Area data.',
          },
          {
            type: 'ox',
            question: 'General Data in the Customer Master is shared across multiple Company Codes and Sales Areas.',
            correct: true,
            explanation: 'General Data (name, address, etc.) is shared across all Company Codes and Sales Areas.',
          },
          {
            type: 'four-choice',
            question: 'Which field belongs to the Sales Area Data of the Customer Master?',
            choices: [
              'Reconciliation Account',
              'Payment Terms (Financial)',
              'Shipping Conditions',
              'Bank Account',
            ],
            correctIndex: 2,
            explanation: 'Shipping Conditions belong to Sales Area Data. Reconciliation Account and payment terms belong to Company Code Data.',
          },
          {
            type: 'ox',
            question: 'The Customer Group directly determines the credit limit for a customer.',
            correct: false,
            explanation: 'Customer Group is used for classification. Credit limits are set individually in FD32.',
          },
          {
            type: 'four-choice',
            question: 'The "Reconciliation Account" in the Customer Master belongs to which data level?',
            choices: ['SD Data', 'General Data', 'Company Code Data', 'Sales Area Data'],
            correctIndex: 2,
            explanation: 'The reconciliation account (accounts receivable GL account) is part of Company Code Data.',
          },
          {
            type: 'ordering',
            question: 'Arrange the Customer Master hierarchy from top to bottom.',
            items: ['Sales Area Data', 'Company Code Data', 'General Data'],
            correctOrder: [2, 1, 0],
            explanation: 'General Data → Company Code Data → Sales Area Data (top to bottom).',
          },
        ],
      },
      {
        id: 'sales-order',
        title: 'Sales Order Processing',
        content: [
          'Sales Orders are created with VA01 and automatically inherit data from Customer Master, Material Master, and pricing conditions.',
          'The Order Type (OR: standard, RE: returns, etc.) determines the subsequent processing flow.',
          'Availability Check (ATP) runs at order entry to confirm stock and set confirmed delivery dates.',
          'Item Categories are assigned to order lines and control shipping and billing behavior.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What is the Order Type for a standard Sales Order?',
            choices: ['RE', 'CR', 'OR', 'DR'],
            correctIndex: 2,
            explanation: 'OR (Order) is the standard Sales Order type. RE is Returns, CR is Credit Memo Request.',
          },
          {
            type: 'ox',
            question: 'The ATP (Availability to Promise) check reserves stock against a sales order.',
            correct: true,
            explanation: 'The ATP check confirms delivery dates based on available stock and production plans.',
          },
          {
            type: 'four-choice',
            question: 'What is the purpose of the Incompletion Log in a sales order?',
            choices: [
              'To warn about insufficient stock',
              'To notify when required data for downstream processing is missing',
              'To notify about credit limit exceeded',
              'To detect pricing errors',
            ],
            correctIndex: 1,
            explanation: 'The Incompletion Log alerts when mandatory fields are missing, preventing downstream processing blocks.',
          },
          {
            type: 'ox',
            question: 'The Item Category is automatically determined from the Order Type and the Item Category Group.',
            correct: true,
            explanation: 'Item Category is auto-determined from the combination of Order Type and Item Category Group.',
          },
          {
            type: 'four-choice',
            question: 'What does transaction VA02 do?',
            choices: ['Create a Sales Order', 'Display a Sales Order', 'Change a Sales Order', 'Delete a Sales Order'],
            correctIndex: 2,
            explanation: 'VA02 changes a Sales Order. VA01 creates, VA03 displays.',
          },
          {
            type: 'ordering',
            question: 'Arrange the sales order processing steps in the correct order.',
            items: ['ATP Check', 'Save Order', 'Enter Customer & Material', 'Pricing', 'Delivery Scheduling'],
            correctOrder: [2, 3, 0, 4, 1],
            explanation: 'Enter Customer & Material → Pricing → ATP Check → Delivery Scheduling → Save Order.',
          },
        ],
      },
      {
        id: 'shipping-billing',
        title: 'Shipping and Billing',
        content: [
          'Shipping is processed with VL01N to create a Delivery document, followed by picking, packing, and PGI.',
          'PGI (Post Goods Issue) reduces inventory (MM integration) and posts cost of goods sold.',
          'Billing is processed with VF01 to create an invoice, which automatically posts to FI accounts receivable.',
          'VF04 (Billing Due List) allows batch processing of multiple deliveries into invoices.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What happens when PGI (Post Goods Issue) is executed?',
            choices: [
              'Accounts receivable is posted',
              'Inventory is reduced and cost of goods sold is posted',
              'A credit check is performed',
              'An invoice is created',
            ],
            correctIndex: 1,
            explanation: 'PGI reduces MM inventory and triggers cost of goods sold posting in CO.',
          },
          {
            type: 'ox',
            question: 'The transaction for creating a delivery document is VF01.',
            correct: false,
            explanation: 'VF01 creates invoices (billing). VL01N creates delivery documents.',
          },
          {
            type: 'four-choice',
            question: 'Which transaction is used for batch invoice creation?',
            choices: ['VF01', 'VF02', 'VF04', 'VL01N'],
            correctIndex: 2,
            explanation: 'VF04 (Billing Due List) converts multiple deliveries into invoices in one step.',
          },
          {
            type: 'ox',
            question: 'Picking occurs after delivery document creation but before PGI.',
            correct: true,
            explanation: 'The shipping process is: Create Delivery → Picking → Packing → PGI.',
          },
          {
            type: 'four-choice',
            question: 'Which billing type is used for standard invoice posting to FI?',
            choices: ['F1 (Standard Invoice)', 'OR (Standard Order)', 'RE (Returns)', 'LF (Delivery)'],
            correctIndex: 0,
            explanation: 'F1 is the standard billing type for invoices. FI posting is based on this billing type configuration.',
          },
          {
            type: 'ordering',
            question: 'Arrange the steps from shipping to billing in the correct order.',
            items: ['PGI (Post Goods Issue)', 'Invoice Creation', 'Picking', 'FI Posting', 'Delivery Document Creation'],
            correctOrder: [4, 2, 0, 1, 3],
            explanation: 'Delivery Creation → Picking → PGI → Invoice Creation → FI Posting.',
          },
        ],
      },
      {
        id: 'sales-org',
        title: 'Organizational Structure and Sales Area',
        content: [
          'The Sales Organization is responsible for selling products/services and is assigned to exactly one Company Code.',
          'Distribution Channel distinguishes sales routes (direct, wholesale, retail, etc.); Division classifies product lines.',
          'Plants are assigned to Sales Organizations as shipping points and are used for inventory management and delivery.',
          'Sales Office and Sales Group are optional organizational elements used for sales rep-level management.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which statement correctly describes a Sales Organization?',
            choices: [
              'It can be assigned to multiple Company Codes',
              'It is responsible for selling and is assigned to one Company Code',
              'It is defined by the combination of Distribution Channel and Division',
              'It is an optional element used only for reporting',
            ],
            correctIndex: 1,
            explanation: 'A Sales Organization is assigned to exactly one Company Code.',
          },
          {
            type: 'ox',
            question: 'The same plant can be assigned to multiple Sales Organizations.',
            correct: true,
            explanation: 'One plant can be assigned to multiple Sales Organizations.',
          },
          {
            type: 'four-choice',
            question: 'What is the main purpose of the Distribution Channel?',
            choices: [
              'To classify product lines',
              'To distinguish sales routes (direct, distributor, etc.)',
              'To identify the shipping source location',
              'To manage sales representatives',
            ],
            correctIndex: 1,
            explanation: 'Distribution Channel distinguishes sales routes and is used in pricing and customer master sharing.',
          },
          {
            type: 'ox',
            question: 'Sales Office and Sales Group are mandatory organizational elements in SAP SD.',
            correct: false,
            explanation: 'Sales Office and Sales Group are optional. The mandatory elements are Sales Organization, Distribution Channel, and Division.',
          },
          {
            type: 'four-choice',
            question: 'What is the correct definition of a Sales Area?',
            choices: [
              'Company Code + Plant + Storage Location',
              'Sales Organization + Distribution Channel + Division',
              'Sales Organization + Sales Office + Sales Group',
              'Customer + Sales Organization + Distribution Channel',
            ],
            correctIndex: 1,
            explanation: 'Sales Area = Sales Organization + Distribution Channel + Division.',
          },
          {
            type: 'ordering',
            question: 'Arrange the SD organizational hierarchy from top to bottom.',
            items: ['Division', 'Distribution Channel', 'Sales Group', 'Sales Organization', 'Sales Office'],
            correctOrder: [3, 1, 0, 4, 2],
            explanation: 'Sales Organization → Distribution Channel → Division → Sales Office → Sales Group.',
          },
        ],
      },
      {
        id: 'pricing',
        title: 'Pricing Conditions and Pricing Procedure',
        content: [
          'The Pricing Procedure defines the calculation sequence for prices, discounts, surcharges, and taxes.',
          'Each Condition Type (PR00: list price, K004: material discount, etc.) has an Access Sequence.',
          'The Access Sequence defines the order in which condition tables are searched; the first match is used.',
          'Condition Records are maintained in VK11 and are automatically retrieved during order entry.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What is the purpose of the Pricing Procedure?',
            choices: [
              'To determine the credit limit for a customer',
              'To define the calculation sequence for prices, discounts, and taxes',
              'To determine shipping conditions',
              'To determine the billing type',
            ],
            correctIndex: 1,
            explanation: 'The Pricing Procedure defines the step-by-step calculation order, including whether each condition is mandatory or optional.',
          },
          {
            type: 'ox',
            question: 'VK11 is the transaction for maintaining condition records.',
            correct: true,
            explanation: 'VK11 creates condition records. VK12 changes them, and VK13 displays them.',
          },
          {
            type: 'four-choice',
            question: 'Which condition type represents the standard material price?',
            choices: ['K004', 'PR00', 'MWST', 'RA01'],
            correctIndex: 1,
            explanation: 'PR00 is the standard list price condition type. K004 is material discount, MWST is tax.',
          },
          {
            type: 'ox',
            question: 'The Access Sequence searches condition tables from the lowest to highest priority.',
            correct: false,
            explanation: 'The Access Sequence searches in the defined order (typically most specific first) and stops at the first match.',
          },
          {
            type: 'four-choice',
            question: 'How is the Pricing Procedure determined for a sales order?',
            choices: [
              'Sales Organization + Distribution Channel + Customer Pricing Procedure + Document Pricing Procedure',
              'Company Code + Sales Organization',
              'Item Category Group + Customer Group',
              'Order Type + Billing Type',
            ],
            correctIndex: 0,
            explanation: 'The Pricing Procedure is determined by Sales Area (Sales Org + Dist. Channel) + Customer Pricing Procedure + Document Pricing Procedure indicators.',
          },
          {
            type: 'ordering',
            question: 'Arrange the pricing determination logic in the correct order.',
            items: ['Retrieve amount from condition record', 'Check condition type', 'Search via access sequence', 'Apply pricing procedure', 'Calculate final price'],
            correctOrder: [3, 1, 2, 0, 4],
            explanation: 'Apply Pricing Procedure → Check Condition Type → Search via Access Sequence → Retrieve Amount → Calculate Final Price.',
          },
        ],
      },
      {
        id: 'inquiry-quotation',
        title: 'Inquiry and Quotation Processing',
        content: [
          'An Inquiry is created with VA11 and represents the information-gathering stage; it does not affect stock.',
          'A Quotation is created with VA21 and commits a price and delivery date to the customer, with an optional validity period.',
          'The copy function from Inquiry/Quotation to Sales Order eliminates the need to re-enter data.',
          'Copy Control (VOVA) defines rules for transferring data from source document types to target document types.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction is used to create a Quotation?',
            choices: ['VA11', 'VA21', 'VA01', 'VK11'],
            correctIndex: 1,
            explanation: 'VA21 creates a Quotation. VA11 creates an Inquiry, VA01 creates a Sales Order.',
          },
          {
            type: 'ox',
            question: 'An Inquiry (VA11) triggers an ATP stock availability check.',
            correct: false,
            explanation: 'An Inquiry is an information-gathering document and does not trigger ATP checks or stock reservations.',
          },
          {
            type: 'four-choice',
            question: 'What is the purpose of the "Validity Period" on a Quotation?',
            choices: [
              'To define the stock reservation period',
              'To indicate the period during which the quoted price and terms are valid',
              'To set the credit check period',
              'To set the payment due date',
            ],
            correctIndex: 1,
            explanation: 'The Validity Period tells the customer how long the quoted conditions (price, delivery) remain valid.',
          },
          {
            type: 'ox',
            question: 'Copy Control allows data to be transferred from a Quotation to a Sales Order.',
            correct: true,
            explanation: 'With Copy Control configured, items and pricing from a Quotation are automatically copied to the Sales Order.',
          },
          {
            type: 'four-choice',
            question: 'What is the document type for an Inquiry?',
            choices: ['OR', 'QT', 'IN', 'RE'],
            correctIndex: 2,
            explanation: 'IN is the document type for Inquiry. QT is Quotation, OR is Sales Order.',
          },
          {
            type: 'ordering',
            question: 'Arrange the pre-sales to order process in the correct order.',
            items: ['Quotation (VA21)', 'Sales Order (VA01)', 'Inquiry (VA11)', 'Delivery Processing', 'Proposal to Customer'],
            correctOrder: [2, 4, 0, 1, 3],
            explanation: 'Inquiry → Proposal to Customer → Quotation → Sales Order → Delivery Processing.',
          },
        ],
      },
      {
        id: 'credit-management',
        title: 'Credit Management',
        content: [
          'Credit Management controls customer credit risk and blocks sales orders or deliveries when credit limits are exceeded.',
          'Credit limits are set in FD32 using Credit Management Groups and Credit Control Areas.',
          'VKM1 displays credit-blocked orders for the credit manager to release or reject.',
          'The combination of Risk Category and Credit Management Group controls the credit check behavior.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'Which transaction is used to set a customer credit limit?',
            choices: ['XD01', 'FD32', 'VKM1', 'VA01'],
            correctIndex: 1,
            explanation: 'FD32 (Customer Credit Management) is used to set credit limits and credit control areas.',
          },
          {
            type: 'ox',
            question: 'VKM1 is used to display and release credit-blocked sales orders.',
            correct: true,
            explanation: 'VKM1 lists blocked orders so the credit manager can release or reject them.',
          },
          {
            type: 'four-choice',
            question: 'Which is NOT a typical point where a credit check is performed?',
            choices: ['When saving a sales order', 'When creating a delivery document', 'When picking is completed', 'When the credit area exposure is exceeded'],
            correctIndex: 2,
            explanation: 'Credit checks are not typically triggered at picking completion. They occur at order save and delivery creation.',
          },
          {
            type: 'ox',
            question: 'A Credit Control Area always corresponds to exactly one Company Code.',
            correct: false,
            explanation: 'A Credit Control Area can span multiple Company Codes, enabling cross-company credit management.',
          },
          {
            type: 'four-choice',
            question: 'What happens to a sales order with a credit block?',
            choices: [
              'The order is automatically cancelled',
              'Delivery processing is blocked',
              'Only billing is blocked',
              'The order is automatically split',
            ],
            correctIndex: 1,
            explanation: 'A credit block stops the downstream delivery process. The order remains open until released in VKM1.',
          },
          {
            type: 'ordering',
            question: 'Arrange the credit limit exceeded process in the correct order.',
            items: ['Release in VKM1', 'Credit Block Set', 'Sales Order Created', 'Delivery Resumed', 'Credit Check Executed'],
            correctOrder: [2, 4, 1, 0, 3],
            explanation: 'Sales Order Created → Credit Check Executed → Credit Block Set → Release in VKM1 → Delivery Resumed.',
          },
        ],
      },
      {
        id: 'returns-credit',
        title: 'Returns and Credit Memo Processing',
        content: [
          'Returns are processed with Order Type RE (Returns) in VA01, referencing the original order or invoice.',
          'Return delivery is created in VL01N and a PGR (Post Goods Receipt) is executed to return stock to inventory.',
          'A Credit Memo Request (CR) adjusts value only; no physical stock return is involved.',
          'A Debit Memo Request (DR) is used for additional billing and is the reverse of a Credit Memo Request.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What is the Order Type for a Returns order?',
            choices: ['OR', 'CR', 'RE', 'DR'],
            correctIndex: 2,
            explanation: 'RE (Returns) is the returns order type. CR is Credit Memo Request, DR is Debit Memo Request.',
          },
          {
            type: 'ox',
            question: 'A Credit Memo Request (CR) triggers a physical stock return.',
            correct: false,
            explanation: 'CR is a value-only adjustment. Use Returns Order (RE) when physical stock return is required.',
          },
          {
            type: 'four-choice',
            question: 'What happens to stock when a PGR (Post Goods Receipt) is executed for a return?',
            choices: [
              'Stock is reduced',
              'Stock is increased',
              'Stock is unchanged',
              'Stock is blocked',
            ],
            correctIndex: 1,
            explanation: 'PGR for a return adds the returned goods back to inventory, increasing stock.',
          },
          {
            type: 'ox',
            question: 'A Debit Memo Request (DR) is used for additional billing to the customer.',
            correct: true,
            explanation: 'DR is used when additional charges need to be billed, such as price corrections or extra fees.',
          },
          {
            type: 'four-choice',
            question: 'Where is the approval block for Credit/Debit Memo Requests configured?',
            choices: [
              'Customer Master',
              'Order Type configuration (VOV8)',
              'Pricing Conditions',
              'Billing Type',
            ],
            correctIndex: 1,
            explanation: 'VOV8 (Order Type configuration) controls the billing block for Credit/Debit Memo Requests requiring approval.',
          },
          {
            type: 'ordering',
            question: 'Arrange the returns process in the correct order.',
            items: ['Issue Credit Memo', 'Return Delivery (VL01N)', 'Create Returns Order (RE)', 'Reference Original Document', 'Execute PGR'],
            correctOrder: [3, 2, 1, 4, 0],
            explanation: 'Reference Original Document → Create Returns Order → Return Delivery → PGR → Issue Credit Memo.',
          },
        ],
      },
      {
        id: 'billing-period-end',
        title: 'Batch Billing and SD Period-End Processing',
        content: [
          'VF04 (Billing Due List) displays delivered-but-not-yet-billed documents and allows batch invoice creation.',
          'VF11 cancels an invoice and automatically posts the reversal to FI.',
          'Account Determination uses condition technique to automatically assign GL accounts during billing.',
          'SD month-end closing includes verifying open deliveries and invoices, reviewing revenue reports, and confirming next-period settings.',
        ],
        quizzes: [
          {
            type: 'four-choice',
            question: 'What is the purpose of VF04?',
            choices: [
              'To list all sales orders',
              'To batch-process open deliveries into invoices',
              'To release credit blocks',
              'To mass-update pricing conditions',
            ],
            correctIndex: 1,
            explanation: 'VF04 (Billing Due List) converts multiple outstanding deliveries into invoices in one step.',
          },
          {
            type: 'ox',
            question: 'Cancelling an invoice with VF11 automatically posts a reversal entry to FI.',
            correct: true,
            explanation: 'VF11 invoice cancellation triggers an automatic reversal of the FI accounts receivable posting.',
          },
          {
            type: 'four-choice',
            question: 'Which mechanism automatically assigns GL accounts during SD billing?',
            choices: [
              'Account Assignment',
              'Account Determination',
              'Pricing Procedure',
              'Shipping Conditions',
            ],
            correctIndex: 1,
            explanation: 'Account Determination uses condition technique to assign revenue, tax, and other GL accounts automatically.',
          },
          {
            type: 'ox',
            question: 'It is recommended to carry over unprocessed deliveries and invoices to the next month during SD month-end closing.',
            correct: false,
            explanation: 'Best practice is to complete all open deliveries and invoices before month-end close. Carry-forward is an exception.',
          },
          {
            type: 'four-choice',
            question: 'What does the Account Determination condition type "KOFI" determine?',
            choices: [
              'Price condition',
              'Revenue account',
              'Credit limit',
              'Shipping condition',
            ],
            correctIndex: 1,
            explanation: 'KOFI is the account determination condition type used to determine the revenue (sales) GL account.',
          },
          {
            type: 'ordering',
            question: 'Arrange the SD month-end closing steps in the correct order.',
            items: ['Review revenue reports', 'Complete open invoices', 'Confirm next-period settings', 'Complete open deliveries', 'Hand off to FI team'],
            correctOrder: [3, 1, 0, 4, 2],
            explanation: 'Complete open deliveries → Complete open invoices → Review revenue reports → Hand off to FI → Confirm next-period settings.',
          },
        ],
      },
    ],
  },
};
